### ISSUE TITLE
C-2

### ISSUE THREAD

**Issue by jimmy-tudeski** [AstarNetwork/growth-program#1675]
Community Management

We are constantly growing our local Astar Poland Community - at today's we have 337 active members. Stakenode had 2 live videos about parachains where we spoke about Astar crowdloan. 
We deducted our community about the necessity of lockdrop tokens vesting and we received consensus and approval from the community for 30% unlock and vesting rest. 
We produced several articles about Astar:
https://stakenode.medium.com/astar-network-crowdloan-guide-stake-dot-to-get-astr-bd30c3ee5f19
https://stakenode.medium.com/how-to-send-shiden-network-sdn-tokens-from-kucoin-or-other-cex-to-metamask-evm-tutorial-de1bba4e92a2
https://stakenode.medium.com/shiden-network-evm-tutorial-819da3798f45

We also promoted Astar parachains crowdloan on Twitter:

https://twitter.com/stakenode_dev/status/1457273622024933379?s=20
https://twitter.com/stakenode_dev/status/1456689002464137220?s=20
https://twitter.com/stakenode_dev/status/1456267167146471424?s=20
https://twitter.com/stakenode_dev/status/1456183206408069123?s=20
https://twitter.com/stakenode_dev/status/1453996085240901639?s=20

We are going to launch some educational campaigns for Shiden / Astar community in November and going to have live meetings with Astart Poland community to educate them about Shiden / Astar

**Comment by fiexer** [comment]
Can you share the stats of those articles?
Only the latest one is older than 2 weeks so I can add that one.

Tweets are for next month rewards (A5)

Community management is added!
I have added you to the list and will automatically add you every month.

**Comment by jimmy-tudeski** [comment]
https://stakenode.medium.com/astar-network-crowdloan-guide-stake-dot-to-get-astr-bd30c3ee5f19
![image](https://user-images.githubusercontent.com/68714636/141446382-4f33a946-5d00-4592-bedb-546a2f778725.png)

https://stakenode.medium.com/how-to-send-shiden-network-sdn-tokens-from-kucoin-or-other-cex-to-metamask-evm-tutorial-de1bba4e92a2
![image](https://user-images.githubusercontent.com/68714636/141446548-e5c907d5-5559-44e3-9830-ee48d761586c.png)

https://stakenode.medium.com/shiden-network-evm-tutorial-819da3798f45
![image](https://user-images.githubusercontent.com/68714636/141446687-9ae21e18-13a4-4ccf-a1cc-fba3efb3e29b.png)

**Comment by fiexer** [comment]
Added!
