### ISSUE TITLE
C2_ Persian community management 

### ISSUE THREAD

**Issue by Persianboy1382** [AstarNetwork/growth-program#1685]
Persian community management in November
Telegram group: https://t.me/Astarnetwork_Persian
Telegram channel: https://t.me/astar_persianANN
Twitter: https://twitter.com/AstarPersian?s=09

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
![image](https://user-images.githubusercontent.com/36227274/145218368-4dcbe345-1827-43e0-96c0-221c9b108239.png)

This is not organic growth! 
No points added for this month.
