### ISSUE TITLE
C2 - Community Management - Ukrainian Community 

### ISSUE THREAD

**Issue by ArtemCrypto6083** [AstarNetwork/growth-program#1705]
Hi,

The Ukrainian Community Telegram Chat was created on October 22. Since then, it has gained 92 members.

It is moderated by me only. I have promoted it in personal CIS crypto chats, asked my colleague to write an article about Astar & Shiden Network to the private CIS crypto blog he works at. 

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by togamamora** [comment]
Please share the TG statistics.

**Comment by ArtemCrypto6083** [comment]
95 subscribers since October 22
<10 messages per day

**Comment by ArtemCrypto6083** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/83471580/144818908-ab90ee7f-b8a0-4bfb-9700-de5acb8bca43.png">

**Comment by fiexer** [comment]
Added!
