### ISSUE TITLE
A1 - Translate "Astar Community program" by Maarten to Japanese

### ISSUE THREAD

**Issue by TaigaTigerKobayashi** [AstarNetwork/growth-program#1710]
Discord: Thomas5884
Twitter: @thomaspotlatch
DOT wallet: 16RHayVsB33dP7MN2iYKrDNvEQ28jUKsQ1y5DwkX231hMww

Medium: https://medium.com/@thomas5884/astar%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%83%86%E3%82%A3%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%82%92%E5%BF%9C%E6%8F%B4%E3%81%97%E3%82%88%E3%81%86-%E7%BF%BB%E8%A8%B3-25ca62ffd47e

Twitter:
https://twitter.com/taigak5884/status/1461056763860439042?s=20

**Comment by Gunit2481** [comment]
Please can you provide your Shiden address ? 

And share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !

**Comment by Gunit2481** [comment]
Please can you provide your Shiden address ?

**Comment by fiexer** [comment]
Please add Shiden address by the end of this week or rewards will not be distributed for this task.

**Comment by fiexer** [comment]
Invalid
