### ISSUE TITLE
C1 - Unofficial telegram / Decentraland Events 

### ISSUE THREAD

**Issue by ERC20s** [AstarNetwork/growth-program#1712]
https://play.decentraland.org/?position=30,10

https://t.me/UNOFFICIALastar

Discord handle: butter#4840
Telegram handle: https://t.me/BUTTERBUY
SDN address: XX9ePXLTJBxkQanKkYB3zq249vyif2ZwcGPT8npJ3MvXLVH

**Comment by fiexer** [comment]
Unofficial community added!
Please add Decentraland Events when MVP is ready.
