### ISSUE TITLE
Table for crowdloan contributors | Tokenomics | Calculating profits

### ISSUE THREAD

**Issue by donatello345** [AstarNetwork/growth-program#1716]
Hi, Maarten, I did something, namely a table with all the separations in the first 24 months, since it's too early to look further.

✓ Marketing - your documents did not specify the blocking of these tokens, so I assumed that money for marking is always needed, so I distributed them by 10% for the first 10 months (but I think they will be used much less often).

✓ Crowdloan - in your documents it was indicated that 20% will be allocated for crowdloan in 2021, and only 15% will be allocated, so I put 5% in reserve for the next crowdlowns (they are not in the table, since the table is designed for the first 24 months).

✓ Tokens from Protocol Development, On-Chain DAO, Team (Employee Incentives) and Foundation will not be used in the first 2 years, or not in such a large amount, so there are 0 in the table of locks. (If something needs to be fixed, write to me and I will do it)

👍  What is my table for:

✓ It is convenient to consider all the separations of tokens from different groups and see what circulation in the market will be in a certain period.

✓ In the "Capitalization" field (any user) can enter the desired capitalization and will be able to see the cost of ASTA in a certain month.

✓ In the "Your DOT deposit" fields, you can enter the number of DOT you threw into the Astar crowdlloan, and in the "DOT Contributions" the number of DOT tokens was collected by Astar Network. Thus, a person will be able to see how many ASTA tokens he will receive and how the token unlock will look like.

✓ Also, he will be able to see the approximate cost of all his ASTA tokens for all 24 months (with one capitalization that he will enter), taking into account all the unlocks.

**If you do not need Profit calculations, then you can also write to me and I will delete it, I will leave only the table of unlocks**

Table - https://docs.google.com/spreadsheets/d/1onH0yLFmv9S1BXMmG4O_pbg3ktsGecwtwuj7XP5mjNg/edit?usp=sharing

**Comment by fiexer** [comment]
Hi donatello

Sorry about having not responded to this topic.
Is this sheet shared with the community or was the meaning for us to use it?
