### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by abk400** [AstarNetwork/growth-program#1724]
Discord ID: KArt#3451
Node name on Telemetry: StableNode📈
Subscan link of my account: https://shibuya.subscan.io/account/bhDzaudC9jCZgd5e1tuYx7mNyLqWhFuQW28vHBkx5yLuyn1
Email address: abk400@gmail.com
SDN address is bRUdLdK7grFt65Kj6Xtz6zECttJ485UKFXG1ipDARFp6Xj2

**Comment by fiexer** [comment]
Please update your node to the latest stable version.
Reply to this thread and I can send you the funds and add you to the list.

**Comment by abk400** [comment]
Done, my current version is 3.1.4

**Comment by fiexer** [comment]
Added to the list and send the funds.
Please onboard.
