### ISSUE TITLE
A1 - Astar Network on Subsocial Network

### ISSUE THREAD

**Issue by donatello345** [AstarNetwork/growth-program#1726]
Subsocial Network - a decentralized social network in the Kusama and Polkadot ecosystem. 
I found it necessary to create a blog there for Astar Network.

Space - https://app.subsocial.network/5598

I moved the most important articles there (crowdloan)

- Astar Crowdloan Event — Part I - https://app.subsocial.network/5598/astar-crowdloan-event-part-i-23930
- Astar Crowdloan Event II - https://app.subsocial.network/5598/astar-crowdloan-event-part-ii-23936
- Last call for starting Astar Crowdloan Event — Part III - https://app.subsocial.network/5598/last-call-for-starting-astar-crowdloan-event-part-iii-23940
- The Astar Crowdloan Event is LIVE! - https://app.subsocial.network/5598/the-astar-crowdloan-event-is-live-23941
- Astar Crowdloan Event — Part IV - https://app.subsocial.network/5598/astar-crowdloan-event-part-iv-23943

I can continue to publish news there, but if something needs to be changed, write.

**Comment by fiexer** [comment]
Thanks!
I will also add myself as an admin to the space. Thanks for creating this.
