### ISSUE TITLE
A4 - Astar meetups 

### ISSUE THREAD

**Issue by ahimbisibwebrian** [AstarNetwork/growth-program#1737]
Links to 2 Astar meetups in November 
We discussed on topics about Polkadot Parachain Auctions and Crowdloans ie Astar Crowdloan event, Astar use cases 

https://drive.google.com/drive/folders/11wcyP8TFxQ-uHV1miHyiDaus6az0N0Dc

https://drive.google.com/drive/folders/11wQJtKU7ISXHDs7Q_5KYRSm7raLMo6Nq

**Comment by fiexer** [comment]
Already rewarded

**Comment by fiexer** [comment]
Added!
