### ISSUE TITLE
Informing about Astar and Shiden Projects / Translating articles into Russian / November / 2021

### ISSUE THREAD

**Issue by Celsiu** [AstarNetwork/growth-program#1743]
Astar crowdloan event summary / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/%D0%BF%D0%BE%D0%B4%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D1%8F-astar-95a4a0b9ccc4

Astar Crowdloan Event — Part IV / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3%D1%83-%D0%B0%D1%81%D1%82%D0%B0%D1%80-%D1%87%D0%B0%D1%81%D1%82%D1%8C-iv-15be2e70738

The Astar Crowdloan Event is LIVE! / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-astar-crowdloan-%D1%83%D0%B6%D0%B5-%D0%B2-%D0%BF%D1%80%D1%8F%D0%BC%D0%BE%D0%BC-%D1%8D%D1%84%D0%B8%D1%80%D0%B5-e92aaeb3007b

Last call for starting Astar Crowdloan Event — Part III / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D0%B9-%D0%B7%D0%B2%D0%BE%D0%BD%D0%BE%D0%BA-%D0%B4%D0%BE-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%B0-%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3%D0%B0-astar-%D1%87%D0%B0%D1%81%D1%82%D1%8C-iii-64955680cfb2

Astar Community program / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B0-astar-72c3783a0b7b

Shiden Integrates with Covalent, Bringing Data Accessibility to the Platform / Translation of the article into Russian -
https://medium.com/@sir_Celsiu_s/shiden-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F-%D1%81-covalent-%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B8%D0%B2%D0%B0%D1%8F-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%BD%D0%B0-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B5-4b9b5b93a4c3

**Comment by Gunit2481** [comment]
Please can you provide your SDN Address ?

Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by fiexer** [comment]
Please share stats today, tomorrow so we can give you the points.

**Comment by Celsiu** [comment]
![stats](https://user-images.githubusercontent.com/93481015/145784745-fdbccb4b-e5a8-4563-999b-f37bfeebde74.png)

**Comment by Gunit2481** [comment]
Added !

**Comment by Gunit2481** [comment]
Please, could you share your Shiden address today !
