### ISSUE TITLE
A4 - Organize meetup about Astar/Shiden. e.g., Zoom meeting, AMA.

### ISSUE THREAD

**Issue by theojamiller** [AstarNetwork/growth-program#1750]
Hosted an hour-long talk as an introduction to Polkadot Auctions and professed the benefits of Astar and how to participate. 

Will edit and post the video when it's on Youtube.

https://www.meetup.com/en-AU/all-things-blockchain/events/282299422/

My Wallet:
a7697urR1bFwkdu4979x9nP549ZbFUUrUDzu6JZuVEQAZVF

**Comment by fiexer** [comment]
Great!
Thanks a lot. Let us know when the video is online.

**Comment by fiexer** [comment]
Any stats available?

**Comment by theojamiller** [comment]
https://youtu.be/TkEZzVbUJL8

**Comment by fiexer** [comment]
Great! Thanks
Very informative AMA
