### ISSUE TITLE
A1 - Write blog posts about Astar/Shiden.

### ISSUE THREAD

**Issue by theojamiller** [AstarNetwork/growth-program#1751]
Arranged to have a blog post written to time the Sunday Evening (busyiest time) for Reddits Subreddit r/CryptoCurrency with 4 million members and plenty more lurkers.

Anaelle did the lion's share of work by writing the article, however, I spend quite a bit of time promoting it. 

https://www.reddit.com/r/CryptoCurrency/comments/r3yete/the_polkadot_standard_where_does_polkadot_fit_in/
https://app.subsocial.network/4323/the-polkadot-standard-25082

Anaelle: 
Z1fHUw3G38sDiuJ8mGBGoiCJwyV5Qg2zdrNxzV49Drhf2ft

Theo:
Gk7N9HeG8y5UaRWLYU5pSz78bigRhavHeZc43NfWvSwKhBr

**Comment by fiexer** [comment]
We need more activity on Reddit channels like this!
Thanks a lot!
