### ISSUE TITLE
A3 - tutorial on the dApp staking in English

### ISSUE THREAD

**Issue by pmensik** [AstarNetwork/growth-program#1753]
We have created a video about dApp staking along with a Twitter post

https://twitter.com/Polkadotters1/status/1465668460562759681

https://www.youtube.com/watch?v=Yu8IlKIu6DU

Discord - pmensik#3434
Telegram - @pmensik
Shiden address - XoPmK9TagQEAFusNy1DYAEgLuft4Ly5wGwM66bvAYLhC3km

**Comment by Gunit2481** [comment]
To have representative stats, the contribution will be added after 2 weeks.

**Comment by fiexer** [comment]
Added
