### ISSUE TITLE
A3 - tutorial on the dApp staking in Czech

### ISSUE THREAD

**Issue by pmensik** [AstarNetwork/growth-program#1754]
We have created a video about dApp staking for the Czech and Slovak community :-)

https://www.youtube.com/watch?v=uyjnixxvx9I

Discord - pmensik#3434
Telegram - @pmensik
Shiden address - XoPmK9TagQEAFusNy1DYAEgLuft4Ly5wGwM66bvAYLhC3km

**Comment by Gunit2481** [comment]
To have representative stats, the contribution will be added after 2 weeks.

**Comment by fiexer** [comment]
Added
