### ISSUE TITLE
C2 - Russian Community Support and Development | November

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#1755]
C2 - Russian Community Support and Development | November

Russian community Astar / Shiden
https://t.me/astar_rus 1600+

- Prevention of attacks on community and spam attacks
- Installing bots
- Community development
- Translation of core team messages
- 4 Admins covering all timezones (5 timezones) 7 days a week  

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by fiexer** [comment]
Added!
