### ISSUE TITLE
A3 - Russian Video | How to transfer tokens | Shiden Wallet and Metamask

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#1759]
A3 - Russian Video | How to transfer tokens | Shiden Wallet and Metamask

https://www.youtube.com/watch?v=bYirt4lsw0I

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by Gunit2481** [comment]
To have representative stats, the contribution will be added after 2 weeks.

**Comment by fiexer** [comment]
Added
