### ISSUE TITLE
A4 - Astar Offline Meetup

### ISSUE THREAD

**Issue by cryptosats** [AstarNetwork/growth-program#1761]
Organized an offline meetup for Astar at Lekki, Lagos, Nigeria (18th November 2021)
https://www.linkedin.com/posts/cmalize_astar-shiden-meetup-activity-6867573982795829248-pu7C
https://twitter.com/ChrisMalize3/status/1461814613176197124?s=20

Represented Astar at Olabisi Onabanjo University, Ogun State, Nigeria during their blockchain submit (16th November 2021)
https://twitter.com/ChrisMalize3/status/1460722209052246018?s=20
https://www.linkedin.com/posts/cmalize_blockchain-summit-oou-activity-6866505964338606080-Txho

**Comment by fiexer** [comment]
Added!
