### ISSUE TITLE
A1 - Subsocial space & articles

### ISSUE THREAD

**Issue by Gunit2481** [AstarNetwork/growth-program#1770]
Recently, I created a Subsocial account for Astar FR and a space to publish articles. The initiative was made to move from a centralized social network to a decentralized one part of the Polkadot ecosystem and in the mean time to support another project of the ecosystem. The Astar FR space allow anyone to post articles and share their thoughts about Astar & Shiden. 

I moved and rewrote all the articles (18) I made during the last months on Subsocial and from now, all the new articles will be posted on Subsocial.

Astar FR Subsocial : https://app.subsocial.network/accounts/3pMb7VG1sUy9vJEEGzCBfJgnyuxFXiWcTAFHAe8MZayB5ehk
Astar FR Space : https://app.subsocial.network/5572

Article : https://app.subsocial.network/5572/astar-network-la-porte-d-acces-a-un-reseau-multi-chaines-23131
Translation : https://app.subsocial.network/5572/weekly-update-21-23257
Translation : https://app.subsocial.network/5572/programme-d-initiative-communautaire-d-astar-23259
Translation : https://app.subsocial.network/5572/debloquer-vos-tokens-de-crowdloans-sur-shiden-23260
Translation : https://app.subsocial.network/5572/lancement-officiel-de-shiden-network-23261
FAQ Article :https://app.subsocial.network/5572/faq-sur-astar-and-shiden-23273
Translation : https://app.subsocial.network/5572/growth-fund-1-30-m-pour-l-ecosysteme-astar-shiden-23549
Translation : https://app.subsocial.network/5572/microsoft-japon-annonce-son-soutien-dans-le-developpement-de-23551
Translation : https://app.subsocial.network/5572/standard-protocol-rejoint-le-programme-des-batisseurs-23553
Translation : https://app.subsocial.network/5572/kucoin-ama-avec-shiden-network-plateforme-multi-chaine-de-23555
Tutorial : https://app.subsocial.network/5572/tutoriel-se-connecter-au-reseau-shiden-sur-metamask-23556
Translation : https://app.subsocial.network/5572/astar-and-shiden-builders-et-grants-program-23558 
Tutorial : https://app.subsocial.network/5572/tutoriel-d-apps-staking-sur-shiden-network-23560 
Tutorial : https://app.subsocial.network/5572/tutoriel-transfert-de-tokens-sdn-23561 
Translation : https://app.subsocial.network/5572/astar-crowdloans-event-partie-i-23563 
Translation : https://app.subsocial.network/5572/astar-crowdloans-event-partie-ii-23565 
Translation : https://app.subsocial.network/5572/astar-crowdloan-event-partie-iii-23572 
Translation : https://app.subsocial.network/5572/resume-astar-crowdloan-event-23584

**Comment by fiexer** [comment]
Please add your contributions in the sheet.

**Comment by Gunit2481** [comment]
Added !
