### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by web3-space** [AstarNetwork/growth-program#1771]
Discord ID: Ivanderkach#8278
Telemetry: WEB3-SPACE
Subscan: https://shibuya.subscan.io/account/5Ck5YyFsLBnkx3BzKYG6QzGir4KC6twmW5q7SMKXiiqERUxD
Email: info@web3-space.com
Shiden Account: WcfzGDx7RRsAsDpoqiDSeRzw72K57eWXHLFg4XPb5qC1UHE

Hi Maarten, I started the node on 11/17/2021, 14 days uptime have already passed. Please fund me so that I can start the collation. Thank you!

**Comment by fiexer** [comment]
I only see 8 days on Telemetry and on-chain identity 2 days.
I cant verify 14 days uptime currently. Sorry

**Comment by web3-space** [comment]
Yes, I passed the verification just 2 days ago. But it's strange that you see only 8 days in telemetry. Ok I'll wait another 6 days. Should I create a new ticket or update this one?

**Comment by fiexer** [comment]
Just reply here :-)

**Comment by igoodvvin** [comment]
Have a nice day Maarten, is it time to onboard?

**Comment by web3-space** [comment]
Have a nice day Maarten, is it time to onboard?

**Comment by fiexer** [comment]
Send & Added!
