### ISSUE TITLE
A3 - Video about how to use dappstore in Shiden network (French)

### ISSUE THREAD

**Issue by GreatTeacherKez** [AstarNetwork/growth-program#1774]
I made a video about how to use dappstore in Shiden network for help french community.
Posted in twitter: https://twitter.com/greatteacherkez/status/1464931147272622085
Relayed by Astar network FR the november 28th : https://twitter.com/AstarNetwork_FR
Posted in discord and telegram too.
Youtube Link: https://www.youtube.com/watch?v=8VtTRoSdhVA&feature=youtu.be

**Comment by Gunit2481** [comment]
To have representative stats, the contribution will be added after 2 weeks.

**Comment by fiexer** [comment]
Added
