### ISSUE TITLE
A6 - Tutorial on How to Dappstaking + Upgrade Runtime in Thai

### ISSUE THREAD

**Issue by pnpdude** [AstarNetwork/growth-program#1775]
https://panupongpnp.medium.com/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-dappstaking-%E0%B8%9A%E0%B8%99-shiden-astar-network-2-32319d202975

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by fiexer** [comment]
Please add stats today or tomorrow!

**Comment by pnpdude** [comment]
Here 🌟

![Screenshot_20211212-181956_Medium.jpg](https://user-images.githubusercontent.com/90048622/145710226-98f25c88-5685-4ae6-bebc-901fb2889dd5.jpg)

**Comment by Gunit2481** [comment]
Added !
