### ISSUE TITLE
A8 - Astar_CryptoNapa Sub reddit

### ISSUE THREAD

**Issue by Totestek** [AstarNetwork/growth-program#1778]
r/Astar_CryptoNapa
https://www.reddit.com/r/Astar_CryptoNapa/
Twitter: @Totestek1
Telegram: @Bigbagger
Discord: Totestek#1283
Shiden Wallet: ZhcYfD7UniFudA9GS4a2E35LHPqqvok1ZrHRLbeSKgn7ahW

**Comment by fiexer** [comment]
Please contact me on Telegram for further discussion @fiexer
