### ISSUE TITLE
C2 - Shiden subreddit growth

### ISSUE THREAD

**Issue by stakepile** [AstarNetwork/growth-program#1779]
Discord: stakepile#7999
Shiden address: WGxS9u98ZDmwFdX6tVYGr2fL4NEK2BVYsvcNokgJ8p78rVX

I continue to grow the Shiden Reddit group. Membership in the community has grown from 297 by the end of October to 686 by Dec 10th. The community can be found here: https://www.reddit.com/r/ShidenNetwork/

The following are stats for November
Members: 686
Pageviews: 24,455
Unique user sessions: 2,173

![image](https://user-images.githubusercontent.com/90024770/145667201-93e567bf-2f7d-49d6-86f0-c1475834c8b3.png)
![image](https://user-images.githubusercontent.com/90024770/145667242-227aca3b-5dd4-42a3-8d8e-6b125157acba.png)
![image](https://user-images.githubusercontent.com/90024770/145667255-4eebb74f-a20a-42f6-88cf-d868a54b4d57.png)

**Comment by fiexer** [comment]
Please provide me full control over the reddits please.
