### ISSUE TITLE
C2 - Astar reddit community growth

### ISSUE THREAD

**Issue by stakepile** [AstarNetwork/growth-program#1780]
Discord: stakepile#7999
Shiden address: WGxS9u98ZDmwFdX6tVYGr2fL4NEK2BVYsvcNokgJ8p78rVX

I continue to grow the Astar Reddit group which was set up recently to support Astar Polkadot crowdloan. Membership in the community has grown from 44 in Oct to 402 by Dec 10. The community can be found here: https://www.reddit.com/r/AstarNetwork/

The following are stats for November
Members: 402
Pageviews: 9485
Unique sessions: 1228

![image](https://user-images.githubusercontent.com/90024770/145667627-7a6c430e-6f09-4330-bd9f-45bbee3d8a43.png)
![image](https://user-images.githubusercontent.com/90024770/145667598-83b57b85-40df-469a-a933-2ee21b24b725.png)
![image](https://user-images.githubusercontent.com/90024770/145667613-6a0f86cb-e9b6-4782-9804-50862b80b5b1.png)

**Comment by fiexer** [comment]
Please provide me full control of the reddits please.
