### ISSUE TITLE
A8 _ an article about ASTR rewards for DOT contributers

### ISSUE THREAD

**Issue by Persianboy1382** [AstarNetwork/growth-program#1782]
https://twitter.com/AstarPersian/status/1469589380633350151?t=9omE_-nKM137ItjkXbJZQA&s=19

Discord: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address: bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Created after November.
Community rewards program stopped end November. New program will be launched in January
