### ISSUE TITLE
 A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by DeYure2U** [AstarNetwork/growth-program#1783]
Discord ID: DeYure#1628
Telemetry: DeYure
Subscan: https://shibuya.subscan.io/account/ZPkQov12wwG2qjT8TRa79oNTwssPYucqCSodXaxoEAjpqsC
Email: deyure.prime@gmail.com
Shiden Account: ZjpiHnHcjrUPsvbY32tz73EnZGsyzzsN6bcQPcN3mBNwQM8

Hello!Node uptime 14 days. Ready to become an active collator. Thank you!

**Comment by fiexer** [comment]
Send & Added!
Please onboard
