### ISSUE TITLE
A1－Create an introductory blog for AstarNetwork

### ISSUE THREAD

**Issue by tatsuzou12** [AstarNetwork/growth-program#1784]
Create an introductory blog for AstarNetwork

Bloglink

https://blog.hatena.ne.jp/tatsuzou12/tatsuzou12.hatenablog.com/edit?entry=13574176438040650962
https://blog.hatena.ne.jp/tatsuzou12/tatsuzou12.hatenablog.com/edit?entry=13574176438029224176
https://blog.hatena.ne.jp/tatsuzou12/tatsuzou12.hatenablog.com/edit?entry=13574176438029069018
https://blog.hatena.ne.jp/tatsuzou12/tatsuzou12.hatenablog.com/edit?entry=13574176438029096130

Discord:たつぞう#3920
Telegram:@tatsuzou
ShidenAdress:16Luu1rFWQbSzUyU34mYDSvSV16BNuCqYh1MTRYuoXC1zNhD

**Comment by togamamora** [comment]
The community program is only valid until November. Any contribution made on December will not be counted.
