### ISSUE TITLE
A4 Astar Network meetup

### ISSUE THREAD

**Issue by ahimbisibwebrian** [AstarNetwork/growth-program#1787]
We hosted our meetup this December with over 37 members from the Polkadot Community and other communities we discussed on topics about Dapp staking , EVM , Building on Polkadot, Contracts among others 
Link to the photos 

https://drive.google.com/drive/folders/12h8W2UT-jXqLIn5sQ_DgmyqZYJg8MUEL

**Comment by togamamora** [comment]
Meetup: 20 points
