### ISSUE TITLE
A4 Astar workshop

### ISSUE THREAD

**Issue by Mucunguzi256** [AstarNetwork/growth-program#1788]
We convened an Astar Workshop at Kabale University Students Center. The workshop was a day long event where we discussed majorly on involving software students on building on Astar and learning deploying Smart contracts on Polkadot Network. We also discussed the DapStaking and how early developers can be incentivized.
The workshop was attended by 230 members, who were predominantly students from Kabale University in South Western Uganda.
We also had members from other blockchain communities such as Near, Avalanch, Celo and Umbrella Network.
https://drive.google.com/drive/folders/10s2HBABk52XZDpG-YmOM88WdClCF91GE

Address
Wr3L92YY3fcyCWAPFEKxbwLKHwo7mtf5ShNWJfn9xizzQjT

Discord
Mucu256#3205

**Comment by togamamora** [comment]
The community reward program ended in November. Any contribution made after that is not recognized.

This program now is only opened for official amabassadors.
