### ISSUE TITLE
A8 - Freestyle creatives and BI-related design works for Astar Network

### ISSUE THREAD

**Issue by aarkwhr** [AstarNetwork/growth-program#1789]
Hi, I'm from Astar Korean Telegram Group. I have been contributing as a sticker/NFT designer for past few months for Astar Network:

1) AstarSisters NFT x 8: https://singular.rmrk.app/collections/f4f5911143c9a1fd5d-ASTRS
2) Astar Sticker-set x 1: https://t.me/addstickers/AstarSisters_v1
3) Astar x Quantstamp Announcement banner: https://medium.com/astar-network/quantstamp-conducted-a-security-audit-of-astar-network-7fa96fa12d13

- My Telegram Handler: @Dragonue
- My Shiden Address: ZXUb5ReaswA7NRyPySNFFNDRRvHMTyEymiMcwAasB2cbN3N

I am looking forward to promoting my Astarsister NFT with Astar officially in the near future, @Maarten hopefully...
If you need any further design assistance, you may contact me anytime =]

Thank you!
From. OpenBeta

**Comment by RHEEUNION** [comment]
High quality art creator from Korean Community.
Wanna see more works/contributions from you in 2022 =]
Thank you, Openbeta!
