### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by kyle1214** [AstarNetwork/growth-program#1791]
Discord ID : KyleYoon#3912
Node name on Telemetry : SubStake✨ | Kyle
Subscan link : https://shibuya.subscan.io/account/XfReD4tr5HFy7uPN6UaRV8RYyZPR1JS1NuT7uFAMnS65UDu
Email address : lkyoon@gmail.com
Shiden wallet addr : W2y9sPAG46soMNKZMFSaNcHzDN2m1NUFqVPtz3pZLjZyboo

**Comment by fiexer** [comment]
Approved!
Funds send to onboard collator.

**Comment by kyle1214** [comment]
Thanks !!
