### ISSUE TITLE
A5 - Informational support in social networks (twitter/telegram/medium) for Shiden and Astar / December 2021 

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#1792]
A5 - Informational support in social networks (twitter/telegram) for Shiden and Astar / December 2021
Providing the info about the Astar/Shiden , in telegram, twitter, medium and other platforms
 																					
Telegram  																				
PromoTeam RU	Astar Crowdloan announcement	https://t.me/promoteam_ann/599																						
PromoTeam RU	Shiden Build2Earn	https://t.me/promoteam_ann/616																						
PromoTeam RU	Astar launch updates	https://t.me/promoteam_ann/660																						
Parachain News EN	Crowdloan support	https://t.me/ParachainNews/1215																						
Parachain News EN	Social media mentions	https://t.me/ParachainNews/1218																						
Parachain News EN	Social media mentions	https://t.me/ParachainNews/1251																						
Parachain News EN	Social media mentions	https://t.me/ParachainNews/1255																						
Parachain News EN	Shiden Build2Earn	https://t.me/ParachainNews/1261																						
Parachain News EN	Social media mentions	https://t.me/ParachainNews/1307																						
Parachain News EN	Social media mentions	https://t.me/ParachainNews/1314																						
																								
Medium 																			
PromoTeam Polkadot Ecosystem EN	
Astar updates Community call recap	https://medium.com/polkadot-ecosystem-promoteam/astar-network-parachain-launch-on-polkadot-and-roadmap-for-2022-6ff82ae508f2																						

Astar Network RU	Astar updates Community call recap RU	https://medium.com/plasm-network-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D1%8F/astar-network-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D0%B0%D1%80%D0%B0%D1%87%D0%B5%D0%B9%D0%BD%D0%B0-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-polkadot-%D0%B8-%D0%BF%D0%BB%D0%B0%D0%BD%D1%8B-%D0%BD%D0%B0-2022-fcde56961b4b																						

Astar Network RU	How to transfer SDN RU	https://medium.com/plasm-network-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D1%8F/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-shiden-%D0%BA%D0%B0%D0%BA-%D0%B1%D1%8B%D1%81%D1%82%D1%80%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%8C-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D1%8B-sdn-369f31bb0bcb																						

Twitter
DotParachains	Social Media Mentions	https://twitter.com/DotParachains/status/1466438428527058961?s=20																						
DotParachains	Social Media Mentions	https://twitter.com/DotParachains/status/1472128206006280192?s=20																						
DotParachains	Crowdloan support	https://twitter.com/dotparachains/status/1465641183410016260?s=21																						

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
Social Engagement: 150 points
Article: 20 points
Tutorial: 15 points
