### ISSUE TITLE
Contributions of December 2021 - Gunit

### ISSUE THREAD

**Issue by Gunit2481** [AstarNetwork/growth-program#1795]
Hi,

**A1 & A6 - Articles & Tutorials into French:**

During the month of December 2021, I translated 5 articles into french and created 2 tutorials. Since I'm using Subsocial for decentralization and to support a dotsama project, I can't provide stats for those articles. 

Translations : 
- Ambassador program : https://app.subsocial.network/5572/programme-des-ambassadeurs-26772
- What we've learned from Shiden : https://app.subsocial.network/5572/ce-que-nous-avons-appris-du-lancement-de-shiden-27939
- Astar onboarding Polkadot Relay Chain : https://app.subsocial.network/5572/astar-onboarding-polkadot-relay-chain-strategie-de-27942
- Quantstamp Audit : https://app.subsocial.network/5572/quantstamp-a-realise-un-audit-de-securite-d-astar-network-29924
- Introduction to X-VM : https://app.subsocial.network/5572/presentation-du-x-vm-sur-astar-network-30108

Tutorials : 
- Transfering from Ethereum to Shiden : https://app.subsocial.network/5572/tutoriel-transferer-des-tokens-entre-ethereum-et-shiden-30147
- Minting & listing NFT on Shiden  :https://app.subsocial.network/5572/tutoriel-miner-un-nft-sur-shiden-network-3015

**C2 Community management December 2021 :** 

With bld and GTZ, we manage the twitter of @AstarNetworkFR (585 followers) and the telegram group of Astar Network France (485 members). I also created the Subsocial of AstarFR with 10 followers.

Telegram : @Gunit31
Discord : @g'ₑₓₚₑcₜ cₕₐₒₛ#3121
Twitter : @gunit3124 https://twitter.com/gunit3124
Wallet : Z5VAv3wwBuH15d1gAgjztz8CQPG6rwekFYxavgjhggJicsk

**Comment by togamamora** [comment]
Community Support: 30
Translations: 30
Tutorials: 30
Twitter: 30
