### ISSUE TITLE
Contributions of December 2021 - MSPY

### ISSUE THREAD

**Issue by thanhmycm** [AstarNetwork/growth-program#1796]
**C2 Community management December 2021 :**

I'm Le Thanh My (MS-PY), manager of vietnamese community and vietnam news channel.
Group : https://t.me/PlasmOfficialVietnam
Channel : https://t.me/astarshidenvietnam

Discord : MS-PY#0410
Telegram : @ThanhCayMoney

My address SDN : **ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd**

**Comment by togamamora** [comment]
Do you have the combot statistics for your local community?

**Comment by thanhmycm** [comment]
Not yet.

**Comment by togamamora** [comment]
Commmunity Support Vietnam: 50 points
Community Support Main: 50 points
Translations: 20 points
