### ISSUE TITLE
A3 - Several YouTube videos dedicated to Astar/Shiden Network

### ISSUE THREAD

**Issue by Fernglenburnaby** [AstarNetwork/growth-program#1797]
Hello,

I have created several videos about Astar and Shiden Networks on my YouTube Channel - "Cryptozilla".
Videos 1-4 are fully dedicated to Astar/Shiden, while only a part of the videos 4-6 is focused on Astar/Shiden.

SDN Address:
XkxrBnVjcwwD8Buo7U66s2tvDMrsXrJsFkbhfmqWi9TxK5L

TG: **@MaxTheo**
Discord: Cap#3465
Twitter: **@Cryptozilla_mg**

**1) Astar Network Crowdloan for Polkadot Auctions ! Details & Rewards and Bonuses**
https://www.youtube.com/watch?v=9GFaaV48C1k&ab_channel=Cryptozilla
**_3560 views_**

**2) Shiden dApp Staking Tutorial ! Stake Your SDN Tokens !**
https://www.youtube.com/watch?v=b9r4VlXJkh0&ab_channel=Cryptozilla
**_1709 views_**

**3) Astar Allocation For Polkadot Auctions ! 20% of ASTR supply, but Will It Be Enough ?**
https://www.youtube.com/watch?v=IoOZDr5Vypk&ab_channel=Cryptozilla
**_6835 views_**

**4) Astar Network Update ! ASTR Trading & Staking Festival With High APY is Coming !**
https://www.youtube.com/watch?v=tkAHLPBmHqw
**_1539 views_**

**5) Astar and Manta Network the Most Profitable Crowdloans on Polkadot Auctions ?**
https://www.youtube.com/watch?v=X4r8WKgLw9g&ab_channel=Cryptozilla
**_7080 views_**

**6) Astar Winning the 3rd Polkadot Auction & Why Are All Kusama Parachains Down ?**
https://www.youtube.com/watch?v=XoM5GKu1ApE&ab_channel=Cryptozilla
**_3123 views_**

Thank you!
Max (Cryptozilla)

**Comment by togamamora** [comment]
The community reward program ended in November. Any contribution made after that is not recognized.

This program now is only opened for official ambassadors. You can apply to join our ambassador program. Please kindly fill in the form.
