### ISSUE TITLE
C2 - Community Management - Korean Community

### ISSUE THREAD

**Issue by RHEEUNION** [AstarNetwork/growth-program#1798]
Hello everyone,
I'm `RHEE` from South Korea and I'm an Official Ambassador of Astar Network.

**[Background]**
- Astar Korean Community Telegram group : https://t.me/astar_kr
Current Community Size: 487 members (Around 30% are active in interactions, reached my prev kpi=500 members last month)
- Prevention of attacks on community and spam attacks (Installing bots)
- Translation of core team messages in pinned messages
- Helped Yakub to prepare Astar x Quantstamp Announcement banner: https://medium.com/astar-network/quantstamp-conducted-a-security-audit-of-astar-network-7fa96fa12d13
- Cooperating with @dragonue and illustrated Astarsisters and sticker-set: https://t.me/addstickers/AstarSisters_v1 + https://singular.rmrk.app/collections/f4f5911143c9a1fd5d-ASTRS

**[Personal Info]**
Telegram Username: @rheeunion
Discord Username: rheeunion#605
Shiden Address: bUUve83HysJPyXGfbAPcGdV2YujGPVMqZgM61fio4WTrQSs

**Comment by togamamora** [comment]
Community Support: 50 points
Stickers: 50 points
Banner + Translation: 50 points
