### ISSUE TITLE
C2: Community Management Africa

### ISSUE THREAD

**Issue by cryptosats** [AstarNetwork/growth-program#1799]
I managed the African community, answered questions asked by community members, educated the community about the ecosystem and use case of Astar and Shiden Network.

I also represented Astar within my region in a professional and ethical manner during the month of December.

**Comment by togamamora** [comment]
1. On which channel?
2. Do you have any stats?

All contribution have to be verifiable.

**Comment by cryptosats** [comment]
> 1. On which channel?
> 2. Do you have any stats?
> 
> All contribution have to be verifiable.

Astar Africa Community group (Telegram)
We grew the community to 113 engaged and interactive members

**Comment by togamamora** [comment]
Community Support: 30 points
