### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by radiumb** [AstarNetwork/growth-program#1800]
Discord ID : radiumblock#9567 
Node name on Telemetry : RadiumBlock-ShibuyaCollator
Subscan link : https://shibuya.subscan.io/account/Y2KRRkaAuNhg48tuw8XRNynGAtrB36YMn4tjcK94kz3zyrH
Email address : info@radiumblock.com 
Shiden wallet addr : a58QztZ7M6jrpq5Gf4t7yM5y2syBA17HBKHXNMgGojRLx2x

**Comment by radiumb** [comment]
Our node uptime is 15 days. Ready to become an active collator. Thank you!

**Comment by fiexer** [comment]
All tokens sent! Please onboard your collator.
