### ISSUE TITLE
C2 - Community Management Japan

### ISSUE THREAD

**Issue by Kahonnohak** [AstarNetwork/growth-program#1802]
Helping Japan Communities 
Discord Japan channel : https://discord.gg/jVxBxURm
Telegram Japan (not much) :https://t.me/PlasmJapan

Translate highlights of Twitter Space event, conference

Twitter: https://twitter.com/kaori_ruku 
Telegram: @kaoriatcrypto
Shiden address: Zbqi66JFjpBc62WbkwUKgrgKwFKNYvtW5jdDLKz714Aq3nH

**Comment by togamamora** [comment]
Community Support: 30
Translation: 10
