### ISSUE TITLE
C2 - Community Management Spanish

### ISSUE THREAD

**Issue by ercab2408** [AstarNetwork/growth-program#1803]
Hi 
My nickname is ercab and I have been managing the Spanish community for more than 2 years and since then I have been contributing not only in TG but also as a channel administrator in Discord in Spanish.
- I have collaborated with nodes in the Dusty tesnet and now in Shibuya
- I do translations of all the official announcements to keep the community updated.
- Our Spanish community is the second largest in our project. With a monthly growth of over 10%.

Telegram :https://t.me/PlasmESP
User:@ercab24
![Statdic2021](https://user-images.githubusercontent.com/76635320/148670069-1db256b9-4514-4853-a8ae-ee7abbaa92a2.jpg)
NameNode:AMRCSTAKE

**Comment by togamamora** [comment]
Community Support: 50 points
Translations: 30 points
