### ISSUE TITLE
A1 & A5 : Infographic : ASTR TOKEN

### ISSUE THREAD

**Issue by boomblb** [AstarNetwork/growth-program#1804]
🟨 Sun 9 Jan'22

✔️ Telegram : @boomblb124

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Shiden Address : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Infographic : ASTR TOKEN
-	Link : https://link.medium.com/ceE9aqY2Fmb

🟩 Social Engagement : CoinRuay (FB Page)
-	Link : https://www.facebook.com/101755535144405/posts/335760548410568/

**Comment by togamamora** [comment]
The infographic and facebook posts were only done in Jan 2022. They don't count into December.
