### ISSUE TITLE
A3 - Video instructions on how to receive and send ASTR tokens

### ISSUE THREAD

**Issue by AntonProfiT** [AstarNetwork/growth-program#1810]
I created a very detailed instruction on how to get my tokens and send them to the exchange, and also answered most of the questions that the community has at the moment, and also invited viewers to join the official Astar channels https://youtu.be/czjmw3gQFqU

My Astar address: apqKtEov3SUcyYjUEPv12bz6wiEyoQ8dFhsAjZC9X1mzaQ1
My Telegram: @Anton_ProfiT
My Discord: AntonProfiT#2497

**Comment by togamamora** [comment]
The community reward program ended in November. Any contribution made after that is not recognized.

This program now is only opened for official ambassadors. You can apply to be an ambassador if you want. Please fill in the form.
