### ISSUE TITLE
A5- A message in the telegram about the start of the token distribution

### ISSUE THREAD

**Issue by AntonProfiT** [AstarNetwork/growth-program#1811]
Community of 5000 users 
Post - https://t.me/ProfiT_Mafia/403

My Astar address: apqKtEov3SUcyYjUEPv12bz6wiEyoQ8dFhsAjZC9X1mzaQ1
My Telegram: @Anton_ProfiT
My Discord: AntonProfiT#2497

**Comment by togamamora** [comment]
The community reward program ended in November. Any contribution made after that is not recognized.

This program now is only opened for official ambassadors. You can apply to be an ambassador if you want. Please fill in the form.
