### ISSUE TITLE
Informing about Astar and Shiden Projects / Translating articles into Russian / December / 2021

### ISSUE THREAD

**Issue by Celsiu** [AstarNetwork/growth-program#1814]
Astar onboarding Polkadot Relay Chain — Launch strategy - 
https://medium.com/@sir_Celsiu_s/%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-astar-%D0%B2-%D1%8D%D1%81%D1%82%D0%B0%D1%84%D0%B5%D1%82%D0%BD%D1%83%D1%8E-%D1%86%D0%B5%D0%BF%D0%BE%D1%87%D0%BA%D1%83-polkadot-%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0-442a82016391

What we’ve learned from launching Shiden -
https://medium.com/@sir_Celsiu_s/%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D0%BD%D0%B0%D1%83%D1%87%D0%B8%D0%BB%D0%B8%D1%81%D1%8C-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0-shiden-6c053ae14e5c

tofuNFT launches on Shiden Network -
https://medium.com/@sir_Celsiu_s/tofunft-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-shiden-network-cdfee1658cdc

**Comment by togamamora** [comment]
Community reward program ended in Nov 2021. This will not be counted.

**Comment by Celsiu** [comment]
Thanks
