### ISSUE TITLE
Added!

### ISSUE THREAD

**Issue by DHK-krm** [AstarNetwork/growth-program#1817]
Added!
I don't know how else to find out. On January 17, I was kicked out of the Astar discord group. I wrote the question "is it possible to stake locked coins" in the dapp-staking chat. At the moment when I pressed Enter to send a message, the Astar group disappeared from the list. As I found out, I was blocked (most likely a bot, because it happened instantly while sending a message). Maybe the fact that the message contained the words blocking. Wanted to know why? DHK_krm#2422
_Originally posted by @fiexer in https://github.com/AstarNetwork/growth-program/issues/1686#issuecomment-986781315_

**Comment by DHK-krm** [comment]
Again, sorry for posting in the work thread.

**Comment by togamamora** [comment]
I have unbanned you. Welcome back!!
