### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by openbitlab2** [AstarNetwork/growth-program#1818]
Discord ID: openbitlab#9650
Node name: openbitlab
Subscan link: https://shibuya.subscan.io/account/WymSUSGLYezVHN3LA5h3qUcYpwiGQMmynXbnzDRVtk5m2B6
Email: openbitlab@gmail.com
Shiden wallet: WymSUSGLYezVHN3LA5h3qUcYpwiGQMmynXbnzDRVtk5m2B6

**Comment by fiexer** [comment]
Funds send! Please onboard
