### ISSUE TITLE
CC/ Cohabitaiton between Shiden and Astar: why continue to use Shiden

### ISSUE THREAD

**Issue by GreatTeacherKez** [AstarNetwork/growth-program#1822]
Article published in Subsocial, in FR and English:
fr link: https://app.subsocial.network/5572/cohabitation-entre-astar-et-shiden-pourquoi-continuer-30839
English link: https://app.subsocial.network/5521/cohabitation-between-astar-and-shiden-why-continue-to-use-30813

link and Stats tweet announcing the article: https://twitter.com/greatteacherkez/status/1483167467820175365
![Stats 5](https://user-images.githubusercontent.com/93451322/150698092-cf0507d6-36ec-4fa4-bfdf-feb2a99a024d.png)

**Comment by togamamora** [comment]
@GreatTeacherKez 
I noticed that you have submitted a few issues.

Please deleted all of them abd submit only 1 issue per months.  

Example:
Title: January Contribution

1. CM: Community Management
- list the statistics

2. VSM
- share all the links

etc.. etc.
