### ISSUE TITLE
January 2022 Contribution

### ISSUE THREAD

**Issue by GreatTeacherKez** [AstarNetwork/growth-program#1824]
telegram --> @GTKez
discord --> Great Teacher Kez#1422
SDN adress: 
WAyw2mtxkRk9vjmwBdGivFduhVmGEeCH8JAXVmREzku92a8

Contributions:
CC/ Article published in Subsocial, in FR and English:
fr link: https://app.subsocial.network/5572/cohabitation-entre-astar-et-shiden-pourquoi-continuer-30839
English link: https://app.subsocial.network/5521/cohabitation-between-astar-and-shiden-why-continue-to-use-30813

link and Stats tweet announcing the article: https://twitter.com/greatteacherkez/status/1483167467820175365
![Stats 5](https://user-images.githubusercontent.com/93451322/151054807-93e0eb0f-81ee-4f9d-80f3-3d07485ac67d.png)

VSM/
Twitter thread about Shiden Datas: https://twitter.com/greatteacherkez/status/1481186034666901507
![stats tweet thread shiden](https://user-images.githubusercontent.com/93451322/151054971-a2c89f84-4c92-490d-9162-783394725798.png)

others tweets about Astar: https://twitter.com/greatteacherkez/status/1482689144837001216
![stats 2 astar](https://user-images.githubusercontent.com/93451322/151055168-9ad841a4-b2eb-4458-91c6-7b1b7d4e8484.png)

https://twitter.com/greatteacherkez/status/1484227984911384577
![stats 3](https://user-images.githubusercontent.com/93451322/151055213-09c859db-dc32-40a1-9f7e-e963f8e153bc.png)

And how to consult rewards (translate the Mamora help on discord and I thanks him): https://twitter.com/greatteacherkez/status/1484422162350063617
![stats 4](https://user-images.githubusercontent.com/93451322/151055286-732ee34c-e1e4-4263-be81-df5922fc17a7.png)

CM/
Telegram managment, combot stats
![stats combot tg jan](https://user-images.githubusercontent.com/93451322/151056823-06e7da02-882a-4081-b71b-1dab3e1bf502.png)

EM/
AMA/live 01h30 with Astar FR community with BLD and Gunit
https://twitter.com/i/spaces/1zqJVBkqZwmJB

**Comment by togamamora** [comment]
CM: 40 
VSM: 25
CC: 7
EM: 7
