### ISSUE TITLE
A3_video about Astar 

### ISSUE THREAD

**Issue by Persianboy1382** [AstarNetwork/growth-program#1826]
Link:
https://twitter.com/AstarPersian/status/1487073974425165825?t=hi3e5Aw8XEz-RS9qVH62Rg&s=19

Discord handle: Pooya #0847 
Telegram handle: @Persian_ambassador

SDN address: bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by togamamora** [comment]
FYI, the community reward program is closed since Dec 2021.  This program is now open only for official ambassadors.
