### ISSUE TITLE
Contribution January 2022

### ISSUE THREAD

**Issue by thanhmycm** [AstarNetwork/growth-program#1827]
I'm Lê Thành Mỹ
My username Telegram : @ThanhCayMoney
My username Discord : MS-PY#0410

Currently working as an ambassador and community manager for Telegram and Discord Vietnam.
https://t.me/PlasmOfficialVietnam
https://t.me/astarshidenvietnam

In January 2022, there are videos to guide users on:

1. Instructions  claim ASTR on Poladkot.js : https://youtu.be/mse40MNxdJw
2. Instructions  transfer ASTR from portal.astar.network to CEX : https://youtu.be/pha_r0wizyc
3. Instructions for betting ASTR on portal.astar.network : https://youtu.be/itPXou6zskU
4. Instructions  transfer ASTR from Astar network to Metamask and vice versa: https://youtu.be/7Sg3JGQDxWE
5. Instructions to withdraw ASTR from CEX and swap, add liquidity on ArthSwap

My address Astar/Shiden : **ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd**

**Comment by togamamora** [comment]
Where is the VSM tweet task?

**Comment by thanhmycm** [comment]
I will create again tomorrow because I made an Astar/Shiden Vietnameses before but it got suspended.

**Comment by togamamora** [comment]
CM: 50
TT: 7
