### ISSUE TITLE
January 2022 Contribution

### ISSUE THREAD

**Issue by pnpdude** [AstarNetwork/growth-program#1828]
Telegram Username: @pnp_404

Discord Username: @PnP#3971

SDN Wallet Address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

Contributions:

CM - Manage and support Thai telegram/Discord , Unofficial Astar Discord, and Official Astar Discord community chat.
- install shieldly bot on telegram to prevent scammer and spamming

![image](https://user-images.githubusercontent.com/90048622/151704036-7126a8e8-dede-4dad-afcc-0ae00732fc1b.png)

![image](https://user-images.githubusercontent.com/90048622/151704052-93daaf72-7b2f-491e-ad99-7e66cbaf9d4e.png)

Translated short news to the Thai Local Community, and Article as follow

1.) Astar Roadmap
https://medium.com/astar-network-thai-community/astar-roadmap-2022-astar-shiden-network-802b7da3b287
![image](https://user-images.githubusercontent.com/90048622/151704499-aa968203-ea8e-4ddc-a28d-bc3c453bfafb.png)

2.) How to buy ASTR from DEX (Tiger's)
https://medium.com/astar-network-thai-community/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%8B%E0%B8%B7%E0%B9%89%E0%B8%AD-astr-%E0%B8%9C%E0%B9%88%E0%B8%B2%E0%B8%99-dex-151d7bca8706
![image](https://user-images.githubusercontent.com/90048622/151704461-24f1d792-201f-4fca-8d85-63db1179880b.png)

Lastly, this is 30 days stat from Astar Thai Community Medium which is included my own article and translated from Official
https://medium.com/astar-network-thai-community
![image](https://user-images.githubusercontent.com/90048622/151704537-25c5d4ae-d775-4004-9d36-aad7afd70252.png)
 

VSM - Twitted 4 tweets
1.) What's Astar and what Astar solve in Thai
https://twitter.com/xpnp404/status/1482266208460484611?s=20&t=wwh2EdAQ-SqrVALVfKAfxg
![image](https://user-images.githubusercontent.com/90048622/151704160-559c8ecf-7cb0-46fa-b6ef-fd05603fafae.png)

2.) Summary of Astar Crowdcast- English and Thai
https://twitter.com/xpnp404/status/1482395902228963329?s=20&t=el2SQ46JHkri8hG9vJ29yw
![image](https://user-images.githubusercontent.com/90048622/151704176-63d93f06-a386-4468-b6bd-1e67bde1f2ab.png)

3.) Short Thread of dAppstaking
https://twitter.com/xpnp404/status/1485300696262254592?s=20&t=Oklm70xlwXJAR9321AykbA
![image](https://user-images.githubusercontent.com/90048622/151704231-58af2404-7154-4280-9ea9-74984bd6aeb4.png)

4.) Update Shiden bridge to Astar
https://twitter.com/xpnp404/status/1487482224870309888?s=20&t=obGhDsEH4hKVVqWtBIDrIA
![image](https://user-images.githubusercontent.com/90048622/151704293-13201257-efac-4da5-b704-0810e693fd51.png)

CC- This is an article writing to summarize Astar in a nutshell including What's Astar, Crowdloan Reward, How to Transfer either from Exchange to Polkadot.js and Polkadot.js to MetaMAsk, and summarize Roadmap
https://medium.com/astar-network-thai-community/astar-network-%E0%B9%80%E0%B8%A3%E0%B8%B4%E0%B9%88%E0%B8%A1%E0%B9%80%E0%B8%94%E0%B8%B4%E0%B8%99%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2-7e5315004172
![image](https://user-images.githubusercontent.com/90048622/151704710-b0159971-1831-458c-8367-9b4b1334d193.png)

TT - Write a tutorial Article, Get to Know and How to use Portal for new User
https://medium.com/astar-network-thai-community/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-astar-portal-101-85858bb7e31e
![image](https://user-images.githubusercontent.com/90048622/151704755-a6ee3aae-c695-41cf-ae83-9aec599de1d4.png)

If you have any questions, please feel free to ask.
Thank you.

**Comment by togamamora** [comment]
CM: 50
VSM: 25
CC: 7
TT: 7
