### ISSUE TITLE
Contribution : January 2022

### ISSUE THREAD

**Issue by boomblb** [AstarNetwork/growth-program#1830]
🟨 January 2022

✔️ Telegram : @boomblb124

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Shiden Address : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Contributions

1. CM :  Manage and support Thai Telegram

![151704036-7126a8e8-dede-4dad-afcc-0ae00732fc1b](https://user-images.githubusercontent.com/84943107/151800191-e6ecc561-670b-413a-848f-17fcd17da04c.png)

![151704052-93daaf72-7b2f-491e-ad99-7e66cbaf9d4e](https://user-images.githubusercontent.com/84943107/151800344-9c371241-8b4c-4357-b576-5af62c9bf832.png)

2. VSM : Promote & Sharing posts for engage new comers to Telegram group

2.1 Astar 101

✔️ Link : https://www.facebook.com/101755535144405/posts/335760548410568/

✔️ Stats : 

![S__147423354](https://user-images.githubusercontent.com/84943107/151804368-2b67cb49-916b-4cfd-a257-140f9cf94251.jpg)

![S__147423356](https://user-images.githubusercontent.com/84943107/151804394-12ee1b5d-e14e-4e51-a43f-12dab28bf1ee.jpg)

2.2 Astar Roadmap

✔️ Link : https://www.facebook.com/101755535144405/posts/337162508270372/

✔️ Stats : 

![S__147423358](https://user-images.githubusercontent.com/84943107/151804789-dfaf144c-e6db-45f9-ab9c-14f2896fa019.jpg)

![S__147423360](https://user-images.githubusercontent.com/84943107/151804819-b504ccb2-3926-455e-9e57-812d744deeb7.jpg)

2.3 Astar Crowdcast Event

✔️ Link : https://fb.watch/aTE5y1iYrQ/

✔️ Stats : 

![S__147423361](https://user-images.githubusercontent.com/84943107/151805327-9ddfb71c-2717-4db2-97e9-f5c044333612.jpg)

![S__147423363](https://user-images.githubusercontent.com/84943107/151805364-efeb92ff-3e3d-4c08-a972-366aab4bac75.jpg)

2.4 Stake2Earn Festival

✔️ Link : https://www.facebook.com/101755535144405/posts/342155921104364/

✔️ Stats : 

![S__147423364](https://user-images.githubusercontent.com/84943107/151805632-c18ded44-eaf1-4bf5-9d71-8d6047451508.jpg)

![S__147423366](https://user-images.githubusercontent.com/84943107/151805648-716f8cab-051a-4f37-b96e-f5dfbdfc5fcc.jpg)

2.5 Infographic : ASTR TOKEN

✔️ Link : https://link.medium.com/TTpbEsMBgnb

✔️ Stats : 

![Infographic_ASTR TOKEN (Medium)](https://user-images.githubusercontent.com/84943107/151802112-644945b2-6dd8-43f0-8c32-c231deeac4d8.jpg)

2.6 Infographic : Astar Parachain Launch

✔️ Link : https://link.medium.com/TTpbEsMBgnb

✔️ Stats : 

![Infographic_Astar parachain launch (Medium)](https://user-images.githubusercontent.com/84943107/151802244-ae36d852-e5f7-45a1-a284-3d016e0094eb.jpg)

If you have any inquiries, please don't hesitate to tell me. Thanks

Best Regards,
BooM

**Comment by togamamora** [comment]
CM: 35
VSM: 25
ART: 7
