### ISSUE TITLE
Contribution January 2022 - @greatbond007

### ISSUE THREAD

**Issue by Greatbond-007** [AstarNetwork/growth-program#1831]
1. TG management- Astar Indian group - 30-40% followers growth. Currently at 199 followers. 
https://t.me/AstarandShidenNetworkIndia

2. Twitter Management Polkastars - https://twitter.com/Polkastarss 
-Followers growth 49 to 144,  
- Impressions - 87.25k, 
- Average engagement per tweet 150 
<<stats sheets attached.>>
[daily_tweet_activity_metrics_Polkastarss_20220101_20220201_en.csv](https://github.com/AstarNetwork/growth-program/files/7972843/daily_tweet_activity_metrics_Polkastarss_20220101_20220201_en.csv)

3. Creation of Astar Hub logo:
<<attached>>
![WhatsApp Image 2022-01-17 at 12 03 36 PM (1)](https://user-images.githubusercontent.com/89275535/151843191-0e69611d-781e-4d63-a83d-c87c54a39821.jpeg)
![WhatsApp Image 2022-01-17 at 12 42 38 PM](https://user-images.githubusercontent.com/89275535/151843202-14e81600-9f75-4a0d-9955-19c0f06fa832.jpeg)
![WhatsApp Image 2022-01-17 at 12 03 36 PM](https://user-images.githubusercontent.com/89275535/151843207-e95b81f0-e3ec-441f-a3d4-93b9a76fd786.jpeg)

4. Creation of PolkaStar Logo:
https://twitter.com/Polkastarss

5. Crowdcast announcement: 
https://twitter.com/Polkastarss/status/1482334441834172416?s=20&t=wMjwsakVoJk5yNCG1RDeNQ
impression - 59k

**6. Creatives for improving brand image:**

a. https://twitter.com/Polkastarss/status/1487905156184231936
impressions - 6k, engagement - 332

b. https://twitter.com/Polkastarss/status/1485599420549046281
Impression - 6.6k, engagement - 213

7.  Cosmos partnership announcement 
https://twitter.com/Polkastarss/status/1486000904050741251?s=20&t=wMjwsakVoJk5yNCG1RDeNQ

8. Kraken listing announcement: 
https://twitter.com/Polkastarss/status/1483712831401099266?s=20&t=wMjwsakVoJk5yNCG1RDeNQ
impression - 2.9k

9. Gateio, Huobi, and Okex listing:
https://twitter.com/Polkastarss/status/1483020731403280385

With my every contribution, I have tried to bring in the best of social media presence from graphical and communication perspective with a focus on engagement.

**Comment by togamamora** [comment]
CM: 40
VSM: 28
ART: 8

**Comment by togamamora** [comment]
Can I have the SDN wallet address?

**Comment by Greatbond-007** [comment]
Here you go!
