### ISSUE TITLE
Contribution January 2022 - @marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#1832]
Telegram ID : @marveLet
Discord ID : marvelet#8647
SDN Wallet : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

TG :
Astar Shiden Indonesia :
@astarshiden_id 
https://t.me/astarshiden_id
Users : 121
Combot Link : https://combot.org/c/-1001288040165/a
Screenshots : 
![Screenshot (105)](https://user-images.githubusercontent.com/87793956/151910052-44b4129d-5678-4a1c-afb7-5da46ff390e9.png)
![Screenshot (106)](https://user-images.githubusercontent.com/87793956/151910082-d2fd1eef-d678-46ca-9ee0-6715a249ae8a.png)

TT :
How To Transfer ASTR To Metamask
Tweet Link :
https://twitter.com/rudayruday/status/1484726472237805572?s=20&t=VErc95hJvV92asLjPtq42g
Screenshots :
![Screenshot (107)](https://user-images.githubusercontent.com/87793956/151910291-70af9490-1bf9-40be-b146-bbea0d895627.png)

**Comment by togamamora** [comment]
CM: 50
VSM: 18
TT: 8
