### ISSUE TITLE
January 2022 Contribution - @Gunit

### ISSUE THREAD

**Issue by Gunit2481** [AstarNetwork/growth-program#1833]
### January 2022 Contribution - @Gunit

Telegram Username: @Gunit31
Discord Username: @G'ₑₓₚₑcₜ cₕₐₒₛ#3121
SDN Wallet Address: Z5VAv3wwBuH15d1gAgjztz8CQPG6rwekFYxavgjhggJicsk

**Contributions:**

1/ CM - Manage and support of Astar Fr and Astar Main community chat.
Discord : Polkadot francophonie - Astar channel (626 members)
Telegram : https://t.me/PlasmNetwork_FR - 586 followers

Combot stats :
<img width="665" alt="image" src="https://user-images.githubusercontent.com/85451570/151922265-0806bc67-2afd-42dd-b1b1-99602d7f8b02.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/85451570/151922325-4ba75f03-bb23-49eb-9252-4d609d12da4e.png">

2/ VSM Twitter : 
- @gunit3124 : 1071 followers 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/85451570/151921038-6272adaf-1785-4297-bd3e-98f22c0f62da.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/85451570/151921430-c3d981ac-c587-4e62-89ce-c8e3bef3aab3.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/85451570/151921209-cce2f991-c044-4bc9-8192-d6f87e70cd13.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/85451570/151921294-8f513c5d-a2cd-4c20-9f05-f5e1f9a28357.png">

- @AstarNetwork_FR : 772 followers

<img width="608" alt="image" src="https://user-images.githubusercontent.com/85451570/151921543-047aa3a3-1029-4af8-aef4-fa16c4b38b81.png">
<img width="222" alt="image" src="https://user-images.githubusercontent.com/85451570/151921594-b5bfffa3-d186-4edf-af10-5e70a0949eb1.png">
<img width="223" alt="image" src="https://user-images.githubusercontent.com/85451570/151921629-7efae276-2e12-46a9-aa98-1961c31e1538.png">
<img width="227" alt="image" src="https://user-images.githubusercontent.com/85451570/151921653-8b810c52-648b-46d5-b5f6-744ef2dbf4e6.png">

3/ CC - Write 1 article
Launch of Astar Network
https://app.subsocial.network/5572/lancement-d-astar-network-30808 (Subsocial doesn't provide statistics but I have some stats from twitter)
<img width="565" alt="image" src="https://user-images.githubusercontent.com/85451570/151924879-f4af65fa-edc5-48a4-a5b6-558d64bb2fab.png">
The article has also been shared by the biggest French influencer in crypto (214k followers)
![image](https://user-images.githubusercontent.com/85451570/151925293-6b5a0fb3-4a0c-4415-b7cb-30738429765d.png)

4/ TT - Wrote 2 tutorials
Math Wallet :
https://app.subsocial.network/5572/tutoriel-math-wallet-astar-network-sur-mobile-31101
<img width="548" alt="image" src="https://user-images.githubusercontent.com/85451570/151924631-9b030100-289e-49d0-bee5-cca4863e480d.png">

dApp staking :
https://app.subsocial.network/5572/staking-festival-sur-astar-30873
<img width="551" alt="image" src="https://user-images.githubusercontent.com/85451570/151924729-ef441f53-149c-4b63-9821-c4f1c772b426.png">

5/ EM - Organized 1 AMA
With Great teacher and Bld, we hosted a Twitter space AMA during 1h30 on Sunday 23rd of January, we had around 290 people. Subjects were dApps staking, Astar portal, the roadmap and Q&A.
Replay : https://twitter.com/i/spaces/1zqJVBkqZwmJB

Stats : 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/85451570/151922419-59c49284-4a8e-4408-8a8b-5b9436f271e5.png">

7/ DEV - Added French language to Astar Portal.
- https://github.com/AstarNetwork/astar-apps/pull/208
<img width="238" alt="image" src="https://user-images.githubusercontent.com/85451570/151923102-6bd487d5-0deb-4ca0-b054-b446d8da8e9a.png">

That's all for my contributions, thank you !

**Comment by togamamora** [comment]
CM: 50
VSM: 30
CC: 10
EM: 7
