### ISSUE TITLE
Contribution January 2022 - @rhee

### ISSUE THREAD

**Issue by RHEEUNION** [AstarNetwork/growth-program#1834]
Hello everyone,
I'm `RHEE` from South Korea and I'm an Official Ambassador of Astar Network.

**[Personal Info]**
Telegram Username: rheeunion
Discord Username: rheeunion#605
Astar/Shiden Address: bUUve83HysJPyXGfbAPcGdV2YujGPVMqZgM61fio4WTrQSs

**[Background]**
1. Astar Korean Community Telegram group : https://t.me/astar_kr
- Last Month Community Size: 487 members
- Current Community Size: 723 members _(KPI Achieved)_
![image](https://user-images.githubusercontent.com/39883171/152264548-5c4222b3-2d3f-48e4-8c55-e0f2afa80d88.png)
![image](https://user-images.githubusercontent.com/39883171/152264565-0b47b63c-6bac-44e8-92c8-29ccb19e2c1a.png)
![image](https://user-images.githubusercontent.com/39883171/152264571-7c98d35d-2d46-479f-a7be-6992f2aa947f.png)
![image](https://user-images.githubusercontent.com/39883171/152264584-86fd44cb-a519-4c57-a09a-c409f09e790c.png)
- Q1 community size goal: 1,000 members
- Prevention of attacks on community and spam/fudding attacks

2. Translation of core team messages in pinned messages and Astarhub document:
- Astarhub: https://docs.google.com/document/d/1xakmdLQ7R9IV5fJVAU6k8mu0oM05lXo8J0K4JMBsW6c/edit?usp=sharing

3. DApp-staking community support on Discord.

4. Joint Arthswap ACP program.
![image](https://user-images.githubusercontent.com/39883171/152264754-7903e2be-cd6b-41b7-a165-db641d844de3.png)

**Comment by togamamora** [comment]
Did you make any tweets in January? From Jan 2022 onwards, need to follow the new format.

**Comment by RHEEUNION** [comment]
> Did you make any tweets in January? From Jan 2022 onwards, need to follow the new format.
> 
> 

@togamamora oops, no tweets on January. Will do it in Febuary for sure👍

**Comment by togamamora** [comment]
CM: 50

For February, please follow the new reward program. Basic tasks are mandatory and you can choose up to 2 supplementary tasks.
