### ISSUE TITLE
January 2022 Contribution - kahonnohak

### ISSUE THREAD

**Issue by Kahonnohak** [AstarNetwork/growth-program#1835]
### January 2022 Contribution - kahonnohak

Telegram Username: @kaoriatcrypto

Discord Username: @kaori#1166

Twitter User name: @kaori_ruku

SDN Wallet Address: Zbqi66JFjpBc62WbkwUKgrgKwFKNYvtW5jdDLKz714Aq3nH

### Contributions:

CM - Manage and support local channels

Astar Telegram; https://t.me/PlasmJapan

Astar Discord: https://discord.gg/zARxg4ZR

Closed Community Discord (Polkadot) :https://discord.gg/uH6b8nzr

### TT - Wrote a tutorial

How to send ASTR tokens
https://note.com/kahon_design/n/n6013c354f29e

What is dApp Staking 
https://note.com/kahon_design/n/n798d912385fb

### Translation of official articles

Fundraising 
https://medium.com/@kaori_ruku/polkadot%E4%B8%8A%E3%81%AE%E3%83%9E%E3%83%AB%E3%83%81%E3%83%81%E3%82%A7%E3%83%BC%E3%83%B3%E3%82%B9%E3%83%9E%E3%83%BC%E3%83%88%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%AF%E3%83%88%E3%83%97%E3%83%A9%E3%83%83%E3%83%88%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A0astar-network-polychain%E7%8E%87%E3%81%84%E3%82%8B%E6%88%A6%E7%95%A5%E7%9A%84%E3%83%A9%E3%82%A6%E3%83%B3%E3%83%89%E3%81%A72200%E4%B8%87%E3%83%89%E3%83%AB%E3%82%92%E8%AA%BF%E9%81%94-c6f786a5f3a2

Roadmap2022
https://medium.com/@kaori_ruku/astar-roadmap-2022-astar-shiden-network-b8a61b6d64c2

<img width="569" alt="スクリーンショット 2022-02-01 19 34 26" src="https://user-images.githubusercontent.com/77480847/151953433-7fc7fea6-7ec6-4d6e-85fa-b4b70e6c624d.png">

### Twitter stats
<img width="1236" alt="スクリーンショット 2022-02-01 19 17 01" src="https://user-images.githubusercontent.com/77480847/151953591-15de71e6-7a83-449d-aa72-ea5a34432a60.png">
<img width="884" alt="スクリーンショット 2022-02-01 19 42 14" src="https://user-images.githubusercontent.com/77480847/151954262-77c34208-8a9d-4478-b87b-d3bb8fd4dee9.png">

**Comment by togamamora** [comment]
CM: 50
VSM: 30
TT: 7
