### ISSUE TITLE
C2 - Russian Community Support and Development | January 2022

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#1836]
C2 - Russian Community Support and Development | January 2022

Russian community Astar / Shiden
https://t.me/astar_rus 2100+

Prevention of attacks on community and spam attacks
Installing bots
Community development
Translation of core team messages
4 Admins covering all timezones (5 timezones) 7 days a week
Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
Please take note on the changes of the Ambasaador reward program.

Maybe you are not aware, but this has been announced. Please read the program again.
