### ISSUE TITLE
Activity Report / January 2022 - PromoTeam 

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#1837]
Informational support in social networks (twitter/telegram) for Shiden and Astar / January 2022 Providing the info about the Astar/Shiden , in telegram, twitter, medium and other platforms

Telegram activity
https://t.me/ParachainNews/1423
https://t.me/ParachainNews/1438
https://t.me/ParachainNews/1455
https://t.me/ParachainNews/1465
https://t.me/ParachainNews/1466
https://t.me/ParachainNews/1474
https://t.me/ParachainNews/1493
https://t.me/ParachainNews/1496
https://t.me/promoteam_ann/699
https://t.me/promoteam_ann/711
https://t.me/promoteam_ann/744
https://t.me/promoteam_ann/746
https://t.me/promoteam_ann/749
https://t.me/promoteam_ann/755
https://t.me/promoteam_ann/756
https://t.me/promoteam_ann/764
https://t.me/promoteam_ann/782
https://t.me/promoteam_ann/796
https://t.me/promoteam_ann/797
https://t.me/promoteam_ann/800

Translation into Russian
https://link.medium.com/5WK5LYkchnb

YouTube , news mentioning and translations
https://www.youtube.com/watch?v=nY_LzKTLd0A
https://www.youtube.com/watch?v=ILZSxFsxgFc&t
https://www.youtube.com/watch?v=TLpVlKIb_9g
https://www.youtube.com/watch?v=yvygiWJVX88

Twitter activity
https://twitter.com/PromoTeamPD/status/1484178298154323973?s=20
https://twitter.com/DotParachains/status/1481637723521753092?s=20
https://twitter.com/DotParachains/status/1483374910609240064?s=20
https://twitter.com/DotParachains/status/1483762195016077316?s=20
https://twitter.com/DotParachains/status/1484141103255281667?s=20
https://twitter.com/DotParachains/status/1485558955577327619?s=20

Russian Community Support and Development | January 2022

Russian community Astar / Shiden
https://t.me/astar_rus 2100+

Prevention of attacks on community and spam attacks
Installing bots
Community development
Translation of core team messages
4 Admins covering all timezones (5 timezones) 7 days a week

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
Please compile all the contribution in one single post.

Follow the new format.

**Comment by togamamora** [comment]
CM: 50
VSM: 25
CC: 8

Please install combot on the Telegram channel so that it is easy to view the statistics.
