### ISSUE TITLE
feat(Activity_Report): January 2022 Contributions

### ISSUE THREAD

**Issue by TomaszWaszczyk** [AstarNetwork/growth-program#1838]
**Telegram:**  pantarheipl 
**Discord:** Tomasz Waszczyk#2111
**SDN Wallet:** Y4xFYxA6rKQKB284UVeiGGeFMt4djg9LDQKn4stprGsDAcN

# Contributions

1. Translation of AstarHub to Polish language.
2. Initial blog post about Astar Network and dApp Staking: https://waszczyk.com/dapp-staking-jak-moze-wygladac-praca-programista-w-niedalekiej-przyszlosci - I will work and improve the post futher

# Social media activities
## Twitter
https://twitter.com/pantarheipl/status/1484253586448162818

## LinkedIn
![image](https://user-images.githubusercontent.com/1605705/152227158-6eac72fc-a409-46c5-afcb-749f81506cc1.png)
![image](https://user-images.githubusercontent.com/1605705/152227275-e242af93-fc52-45a8-8605-41f274d3aeff.png)
![image](https://user-images.githubusercontent.com/1605705/152227367-ebfe7ed0-4082-4fb7-a988-2ce7bce5cf79.png)

**Comment by togamamora** [comment]
Where is the CM community management submission? Please provide the Polish Telegram statistics.

**Comment by TomaszWaszczyk** [comment]
I have the group https://www.meetup.com/Silesia-Blockchain-Meetup/ I do not have any Telegram group.

**Comment by togamamora** [comment]
> I have the group https://www.meetup.com/Silesia-Blockchain-Meetup/ I do not have any Telegram group.

You can start joining the Astar Polish telegram group and provide community support. Same goes to the Polish channel on Discord.

This is a requirement for this ambassador program.

**Comment by togamamora** [comment]
VSM: 25
CC: 6

**Comment by TomaszWaszczyk** [comment]
I did not know, in the next month I will show my statistics.
