### ISSUE TITLE
A3 - Created a Video about Astar

### ISSUE THREAD

**Issue by snars2018** [AstarNetwork/growth-program#1839]
I have created a step by step video tutorial on how to Withdraw Astar coin from Astar Dashboard to Kucoin Exchange. Here's the link below.

https://youtu.be/Ny8-F9udMOI

https://twitter.com/snars11
SDN wallet address:
Xg1oajKXxYDMQh6RPSWTX3ScAmdcAA41gVpHmJw5TuhmhFJ

Astar wallet address:
Xg1oajKXxYDMQh6RPSWTX3ScAmdcAA41gVpHmJw5TuhmhFJ

**Comment by togamamora** [comment]
FYI, the community reward program is no longer active since Dec 2021. This program is now only for the official ambassadors.
