### ISSUE TITLE
EM Astar launch community meetup

### ISSUE THREAD

**Issue by ahimbisibwebrian** [AstarNetwork/growth-program#1840]

**Comment by ahimbisibwebrian** [comment]
We successfully hosted our Astar launch meetup 

Link to the meetup photos 

https://drive.google.com/drive/folders/13ZE5zwXCw3lxeLr63DFiicT6ZWrpZ2nU

**Comment by togamamora** [comment]
Please read the ambassador program.

To qualify for the rewards, you need to complete the mandatory tasks.

EM is only supplementary.

**Comment by togamamora** [comment]
CM: 20
EM: 7

From now onwards, please also do the other mandatory tasks, VSM. We want the ambassador to actively participate in making our social media presence viral.
