### ISSUE TITLE
Contribution January 2022 - @s.takahashi

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/growth-program#1841]
I'm Shin Takahashi.
My job is software developer of traditional security group in japan.
I want to change financial system by blockchain and I want to use blockchain to strengthen the power of the community that exists on a daily basis.

My contributions as following...
- I wrote a article that introduce dApp staking. https://realtakahashi-work.medium.com/astar-network%E3%81%AEdapp-staking%E3%81%AE%E5%87%84%E3%81%95-48e81f7acedb
- Translate Astar Hub to Japanese.

<img width="347" alt="202201_result" src="https://user-images.githubusercontent.com/38233656/152313804-ab4d2830-0766-4eff-b93c-806bf8438bb0.png">

**Comment by togamamora** [comment]
Please also provide your stats on supporting the local community.

**Comment by togamamora** [comment]
CM: 30
CC: 7

**Comment by togamamora** [comment]
Can I have your SDN wallet address?
