### ISSUE TITLE
EM

### ISSUE THREAD

**Issue by KAMALAIMMACULATE** [AstarNetwork/growth-program#1842]
Community Online Meetup for Astar Aftrica
https://twitter.com/ChrisMalize3/status/1486472939688103945?s=20

Telegram handle: @kamalaimmaculate
Discord: Kamala Immaculate#5476 

SDN Address: aUkGV7BjjbhBHEum67r9Jk2fPawfUPwyDTPY6qxnajVRBGF

**Comment by togamamora** [comment]
EM: 7

From now onwards, please also do the CM & VSM. 

We want the ambassador to actively participate in supporting the local community channels  and making our social media presence viral.

Otherwise, your contribution will not be considered.
