### ISSUE TITLE
CM-Community Management_Spanish 

### ISSUE THREAD

**Issue by ercab2408** [AstarNetwork/growth-program#1843]
In the month of January our work in the Spanish community in Discord and Telegram mainly focused on the following:
- Share information about the progress of the Launch
- Assistance in the configuration of the wallet and connection to the portal.astar
- Communication about the alliances and inclusion of Astar in Polkaex and Arthswap
- Creation of our AMA calendar and Q1 events which started last February 02 with a Polkadot event. We will upload this event next month in the corresponding category.
- We continue to contribute to the Shibuya testnet (AMRCSTAKE NODE)

This is the statistics of the main account. We hope in the coming months to be able to reach a major number of users by this way.
Link-1: https://analytics.twitter.com/user/ercab24/tweets

Link-2: https://analytics.twitter.com/user/ercab24/home

Data
Email:ercab24@protonmail.com
Twitter: @ercab24 @AstarNetwork_ES
Discord:Ercab24#2125
Telegram: @ercab24 / https://t.me/PlasmESP
Account Shidenr ewards#: aJMU3fdQVv98WmcdCXpb6jcYeWkwjCGwQycefP8at1HQefu
Account ASTAR rewards: XFMioWrpg5X7f5VzUHDKK1dsNcUMyHYM3oM7Naja99DfL1D

**Comment by togamamora** [comment]
Please compile all contribution into one post.

**Comment by togamamora** [comment]
CM: 45

From now onwards, please install combot on the telegram channel so that it is easy for you to display the statistics. Also, please participate in the mandatory task, VSM. We want to make our social media presence viral.

**Comment by ercab2408** [comment]
I don't understand, create a case also in the VSM activity then you sent me to compile in a single case.
Please tell me how much you think my community contribution to the project is because I don't understand what you are saying about contributing to the mandatory VSM activity.

**Comment by togamamora** [comment]
Please check the main page on the VSM tasks.
