### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by Validatrium** [AstarNetwork/growth-program#1845]
[validatrium] Igor#8102
Validatrium
https://shibuya.subscan.io/account/bNotgV13gBVJyDaYqQhmCyyPLJtbSx3w4Ng5X8byx78ov4n
info@validatrium.com
Shiden rewards: Z21yN7SuztYCu5MtJ9Wc3QHB9cCArNZwWrTxhNCWapw7zmh

**Comment by fiexer** [comment]
Funds send! Please onboard
