### ISSUE TITLE
Establish Chinese area of Astar telegram

### ISSUE THREAD

**Issue by Gravesyou** [AstarNetwork/growth-program#1847]
https://t.me/Astarnetworkchinese

**Comment by togamamora** [comment]
This will go into January. I have checked your Telegram statistics. For February

1. Please install combot on the Telegram chat and the statistics
2. Participate in other tasks. VSM, and other supplementary tasks.

**Comment by Gravesyou** [comment]
OK，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AstarNetwork/growth-program"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AstarNetwork/growth-program] Establish Chinese area of Astar telegram (Issue #1847)





 
This will go into January. I have checked your Telegram statistics. For February
  
Please install combot on the Telegram chat and the statistics
 
Participate in other tasks. VSM, and other supplementary tasks.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
