### ISSUE TITLE
Create AstarNetwork Chinese WeChat official account

### ISSUE THREAD

**Issue by Gravesyou** [AstarNetwork/growth-program#1848]
Publish hundreds of articles.
1、November 7：Astar Network announced the launch of the $30 million ecosystem growth fund.--https://mp.weixin.qq.com/s/eYa9U4Q48Ar9GIx0Uk3vEQ
2、October 9th：Shiden Network opened Staking dApp, and Shibuya test network went online. --https://mp.weixin.qq.com/s/B5_L5DAv1_xF36JnsEwreA
3、October 14th：Shiden Network has launched the # Build2ern of DApp Staking--https://mp.weixin.qq.com/s/Ut7h_lXrhodR-jXgsJnHmQ
4、October 19th：Astar Crowdloan Event — Part I--https://mp.weixin.qq.com/s/R0tBepTNNKf8bj4IPW_9Ew
5、November 1(st)：Astar welcomes Commonwealth Labs and Webb Technologies as the core companies behind the Protocol. --https://mp.weixin.qq.com/s/0yxYKS9fVm402VXpJUPxEg
6、November 2(nd)：Astar Crowdloan Event — Part II--https://mp.weixin.qq.com/s/cDgIspF1_ESUgOxknwrd6A
7、November 4(th)：Astar Crowdloan Event—PartⅢ--https://mp.weixin.qq.com/s/mSytFufpx0bbX_BlP74Ecw
8、November 9(th)：Astar Network Crowdloan Event Begins--https://mp.weixin.qq.com/s/lmGsP6C_n6zrIuUzynTG9w
9、November 12(th):Polkadot parallel chain slot Auction officially started!--https://mp.weixin.qq.com/s/3GKZK79lJvG2EV-Z8Z7cgA
10、November 15(th)：Astar Crowdloan Event — Part IV--https://mp.weixin.qq.com/s/ATIyGEyh-a2ElbYe25MiDQ
11、November 15(th)：Astar Network Crowdloan Event Summary--https://mp.weixin.qq.com/s/cW-Jp-wY8kb_Dv3ISt4a3A
12、November 16(th）：Astar Network Polkadot Crowdloan is supported by Bifrost SALP--https://mp.weixin.qq.com/s/FOPYWoRhTPeBPIfjeaUohQ
13、December 21(st):Shiden Network issue tofuNFT--https://mp.weixin.qq.com/s/UJ-BH0xYF_9OQAW2O7XiQg
14、December 21(st)：Enlightenment of Shiden Network project--https://mp.weixin.qq.com/s/IXnDtH-eLSL2z12d6d6iKA
15、January 28(th)：Astar Network completed a strategic round of financing of US$ 22 million, with Polychain leading the investment.--https://mp.weixin.qq.com/s/VOsv__TcKxp-XPhZbNwVww

**Comment by togamamora** [comment]
Please also do the same report every month. One report per month for all the contribution.

**Comment by Gravesyou** [comment]
Is it submitted in it every month?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AstarNetwork/growth-program"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AstarNetwork/growth-program] Create AstarNetwork Chinese WeChat official account (Issue #1848)





 
Closed #1848.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by togamamora** [comment]
Yes.

**Comment by Gravesyou** [comment]
OK，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AstarNetwork/growth-program"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AstarNetwork/growth-program] Create AstarNetwork Chinese WeChat official account (Issue #1848)





 
Yes.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
