### ISSUE TITLE
 A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by ioannist** [AstarNetwork/growth-program#1850]
Your Discord ID:
ioannis | DVN#3081

Node name on Telemetry:
StakeBaby

[Subscan](https://shibuya.subscan.io/) link of your account.
https://shibuya.subscan.io/account/W8gprYCd3n8oLrD44d44Rpq8yXbwTe2zTcrnmUG6JRFSZ1u

Email address to send important updates for your node.
contact@stakebaby.com

Shiden wallet address to payout your rewards.
ZWf4VNwx47nekGanr2B7TQQtmqjXxQT2Cfu2NVvEf5b63Wa

**Comment by bLd75** [comment]
Funds are sent, please register and comment here when your collator is producing blocks.

**Comment by diversified-validator-network** [comment]
Hi, the last transfer on the account was 29 days ago. Doesn't look like the funds were sent. Can you send me the tx hash?

**Comment by diversified-validator-network** [comment]
Oh, it seems the test tokens were sent to the rewards address. I guess we mixed up the role of each address.

Will get the node running asap.

**Comment by bLd75** [comment]
Sorry my bad, I used the 2nd address. You can transfer to 1st one if you prefer.
There is no payout in SDN for Shibuya collators, no need for 2 addresses.

**Comment by diversified-validator-network** [comment]
Yeap, np. We already run an active collator on Shiden but we want to be active in the testnets for all the networks we operate in. Will post here as soon as the node is up.
