### ISSUE TITLE
February 2022 contribution

### ISSUE THREAD

**Issue by GreatTeacherKez** [AstarNetwork/growth-program#1851]
telegram --> @GTKez
discord --> Great Teacher Kez#1422
Native adress:
WAyw2mtxkRk9vjmwBdGivFduhVmGEeCH8JAXVmREzku92a8

Contributions
CM/
telegram stats astar FR
![combot feb](https://user-images.githubusercontent.com/93451322/155874434-eeaf3e27-bb1e-4749-8499-5fcf216c3d1d.png)

+ I have now Director Role at Wag media discord, for Astar/Shiden publications.
I read articles of last months, see videos too, and already distribute the first rewards (excluding official ambassador for double rewards reasons)
Rewards are:
- 20 astr https://youtu.be/sEE9dAFJOqA
-200 ASTR https://www.youtube.com/watch?v=91LO_A8m7K4
-100 ASTR https://medium.com/@Onepiece_SubWallet/d%E1%BB%B1-%C3%A1n-astar-l%C3%A0-g%C3%AC-ai-%C4%91ang-x%C3%A2y-d%E1%BB%B1ng-n%C3%B3-v%C3%A0-t%E1%BA%A1i-sao-n%C3%AAn-ch%E1%BB%8Dn-astar-ph%E1%BA%A7n-2-100f66dd1afb
-20 ASTR https://medium.com/@Onepiece_SubWallet/d%E1%BB%B1-%C3%A1n-astar-l%C3%A0-g%C3%AC-ai-%C4%91ang-x%C3%A2y-d%E1%BB%B1ng-n%C3%B3-v%C3%A0-t%E1%BA%A1i-sao-n%C3%AAn-ch%E1%BB%8Dn-astar-ph%E1%BA%A7n-1-41d2b749e570
-100 ASTR https://app.subsocial.network/5549/what-is-astar-who-is-behind-it-and-why-astr-part-2-31327
-100 ASTR https://app.subsocial.network/5549/what-is-astar-who-is-behind-it-and-why-astr-part-1-31240
-10 ASTR https://app.subsocial.network/6119/astar-degen-an-ape-s-vision-31203

CC/ Article presenting ALL DAPP and contract in Shiden 
link: https://app.subsocial.network/5521/shiden-dappstore-review-edition-speciale-2022-31448
![stat articles dapp shiden](https://user-images.githubusercontent.com/93451322/155873558-ad4bab08-1efc-43ef-b5c2-369ad1198de5.png)

2 videos, in French and English to explain using of bridges from SDN to Astar, using CBridge, go arthswap etc...
Fr video link: https://www.youtube.com/watch?v=W3r0bC0T2Ao&t=21s
English video link: https://www.youtube.com/watch?v=qVIIqA4e0ys
Tweet announcing and presenting videos
fr: https://twitter.com/greatteacherkez/status/1491728695467417604
![twit feb 4](https://user-images.githubusercontent.com/93451322/155873988-4679954f-ef37-4199-83ff-2df2b8eb7cc2.png)

eng: https://twitter.com/greatteacherkez/status/1491819951744765954
![twit feb 5](https://user-images.githubusercontent.com/93451322/155874021-b8c48f14-f92e-411c-9231-d9ef548cafd2.png)

VSM/
https://twitter.com/greatteacherkez/status/1488408397779197956
![twit feb 1](https://user-images.githubusercontent.com/93451322/155873629-0b25f030-369c-40fe-939a-feef8375b347.png)

https://twitter.com/greatteacherkez/status/1489560353725952001
![twit feb 2](https://user-images.githubusercontent.com/93451322/155873685-0f41395c-b93c-4026-824b-05f902c52162.png)

https://twitter.com/greatteacherkez/status/1489948424044699649
![twit feb 3](https://user-images.githubusercontent.com/93451322/155873743-ed52337c-0942-44ad-ac98-8f838bc36100.png)

https://twitter.com/greatteacherkez/status/1496183671023407104
![twit feb 6](https://user-images.githubusercontent.com/93451322/155874144-a712356b-c4d1-4efa-b2bb-2e9177e3cd4a.png)

ART
![twit feb 7](https://user-images.githubusercontent.com/93451322/155874284-08ab6003-993c-45af-a6d5-b4e5cb419189.png)
/ I used Toga Model to make a prettiest info for interactions in Astar (french, i'll do it in eng)
https://twitter.com/greatteacherkez/status/1496438486278324236

**Comment by togamamora** [comment]
CM: 45
VSM: 25
CC: 8
AT: 6
