### ISSUE TITLE
February 2022 Contribution

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#1852]
Telegram Username: pitcoin777
Discord Username: Pit Coin #3857
SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

Contributions

1) CM - Manage and support of Astar PT (Telegram) and Astar Main community chat (Discord)

Telegram: https://t.me/astarnetworkPT - 145 followers
![Screen Shot 2022-02-27 at 10 21 46](https://user-images.githubusercontent.com/99457582/155884328-67f0d7d8-5374-47ab-b4ce-d6f02b9fbd8d.png)

![Screen Shot 2022-02-27 at 10 28 35](https://user-images.githubusercontent.com/99457582/155884375-9f70f39f-c994-425c-98e1-7a4e3dbd87b2.png)

![Screen Shot 2022-02-27 at 10 28 44](https://user-images.githubusercontent.com/99457582/155884381-e0a83e2d-2b01-4a3b-8b61-b53af1cc05b5.png)

![Screen Shot 2022-02-27 at 10 28 56](https://user-images.githubusercontent.com/99457582/155884383-34b1d762-f060-4481-ad2f-cc9f5664a828.png)

Also, I translated the Astarhub.io portal into Portuguese
![Screen Shot 2022-02-26 at 23 31 39](https://user-images.githubusercontent.com/99457582/155884823-b3ea0c24-0a7b-446f-a615-64837f9fe1d1.png)

2) VSM Twitter

@AstarNetworkPT - 137 followers
![Screen Shot 2022-02-27 at 10 32 02](https://user-images.githubusercontent.com/99457582/155884509-8cea86fb-aa24-4c42-b0f2-4f485c1f0241.png)

![Screen Shot 2022-02-27 at 10 31 11](https://user-images.githubusercontent.com/99457582/155884521-30ae9e54-627f-401c-88fc-51d5569d2fef.png)

![Screen Shot 2022-02-27 at 10 32 30](https://user-images.githubusercontent.com/99457582/155884529-6740abd1-6ac8-473d-bef5-80bdc1839d66.png)

![Screen Shot 2022-02-27 at 10 32 18](https://user-images.githubusercontent.com/99457582/155884533-fa93933f-7710-4a71-9aa0-222134d87802.png)

3) CC - Wrote 3 articles

-What’s is dApps Staking
https://pitcoin.medium.com/o-que-%C3%A9-dapp-staking-e53bfe13b8b4

-What’s is Astar Network
https://pitcoin.medium.com/o-que-%C3%A9-astar-network-40d1616de517

-Starlay – Lending on Astar
https://app.subsocial.network/6283/starlay-ferramentas-cronograma-e-tokenomics-31509

4) TT - Wrote/Recorded 5 tutorials

-Transfer ASTR to Metamask/Polkadot.js (video + article)
https://app.subsocial.network/6283/transferir-astr-da-polkadot-js-para-a-metamask-e-vice-versa-31489
https://www.youtube.com/watch?v=hlHI9QrUfug

-Bridge between Astar and ETH/BSC (video + article)
https://app.subsocial.network/6283/bridge-como-transferir-tokens-da-rede-eth-bsc-para-astar-31558
https://www.youtube.com/watch?v=_LwUtkD8cYg

-Mint Astar Degens NFT (video)
https://youtu.be/qzRTn4L-_AA

That's all for my contributions. Thanks.

**Comment by togamamora** [comment]
CM: 50
VSM: 25
CC: 8
TT: 8
