### ISSUE TITLE
February 2022 Contribution

### ISSUE THREAD

**Issue by pnpdude** [AstarNetwork/growth-program#1853]
Telegram Username: @pnp_404

Discord Username: @PnP#3971

SDN Wallet Address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

Contributions:

CM - Manage and support both Local and Main community chat.
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/90048622/155890741-15fe565d-0105-4057-bf60-9f425d27f54f.png">
VSM - Tweet
https://twitter.com/xpnp404
<img width="917" alt="image" src="https://user-images.githubusercontent.com/90048622/155890204-1c721c5d-dcb9-431d-8288-227ff2026f81.png">

1. https://twitter.com/xpnp404/status/1489619351951253504?s=20&t=lIg0cRMnjSujuK3PrRexiA
<img width="742" alt="image" src="https://user-images.githubusercontent.com/90048622/155890275-ff997f0d-1e23-4875-88e1-925d5d717680.png">

2. https://twitter.com/xpnp404/status/1492171573062955009
<img width="734" alt="image" src="https://user-images.githubusercontent.com/90048622/155890313-ba56768a-d2dc-4f23-9678-712b8fdc1a1e.png">

3. https://twitter.com/xpnp404/status/1493642232771280897?s=20&t=AMetuAhKF7hHs74yrMAFuw
<img width="734" alt="image" src="https://user-images.githubusercontent.com/90048622/155890340-935de483-401e-4133-89a5-71e12f4319cb.png">

4. https://twitter.com/xpnp404/status/1494351779404054528?s=20&t=V6YJDzVcn1ePE9u3AWdhYQ
<img width="673" alt="image" src="https://user-images.githubusercontent.com/90048622/155890364-13edd742-33b9-49ad-a97c-f5a73e56b33f.png">

5. https://twitter.com/xpnp404/status/1494746769359765505
<img width="732" alt="image" src="https://user-images.githubusercontent.com/90048622/155890388-809d514e-2112-4e17-ba09-204cd1b7ef54.png">

6. https://twitter.com/xpnp404/status/1495722377497706500?s=20&t=kmVD1bVZEeskWFnOhnZwUA
<img width="740" alt="image" src="https://user-images.githubusercontent.com/90048622/155890424-1875540d-e57b-4437-97b2-4bcd23e3209a.png">

TT - Publish 3 Short Videoes mainly for Apes and quick respond = keep it short, move it fast (concept)
Talisman extension will be available next month, the extension trying to solve Polkadot.js extension that is not user friendly.
This could be great opportunity for mass adoption for Astar 

No sound -> international purpose 
https://www.youtube.com/channel/UCRbpF5f4MaKJWgP7RqunI9Q
<img width="549" alt="image" src="https://user-images.githubusercontent.com/90048622/155890634-ac5ff0c1-feda-46fb-8e80-6107e5591273.png">

**Comment by togamamora** [comment]
CM: 50
VSM: 27
TT: 8
