### ISSUE TITLE
February 2022 - Contribution

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#1854]
Telegram Username: @ marveLet (Soul Eater)
Discord Username: marvelet#8647
SDN Wallet: YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

1. CM
Astar Shiden Indonesia - Telegram : [https://t.me/astarshiden_id](https://t.me/astarshiden_id)

![astarshidenid feb22](https://user-images.githubusercontent.com/87793956/156012043-ee365634-619b-45d9-b602-d089f5eda6e5.jpg)
![astarshidenid feb22_2](https://user-images.githubusercontent.com/87793956/156012078-14179d20-2dbd-4d76-8638-e5625954464d.jpg)

2. VSM
Twitter : [https://twitter.com/rudayruday](https://twitter.com/rudayruday)

My personal twitter mostly are talking about Astar, but I will report only 3 of them who pretty much got good engagements
- [https://twitter.com/rudayruday/status/1489426571815690240?s=20&t=7iI6mv1dAuEuvVfsWPHdgw](https://twitter.com/rudayruday/status/1489426571815690240?s=20&t=7iI6mv1dAuEuvVfsWPHdgw)

![1](https://user-images.githubusercontent.com/87793956/156013568-688a9672-a8ad-4998-8a41-de874ad58053.jpg)

- [https://twitter.com/rudayruday/status/1494569674658684930?s=20&t=7iI6mv1dAuEuvVfsWPHdgw](https://twitter.com/rudayruday/status/1494569674658684930?s=20&t=7iI6mv1dAuEuvVfsWPHdgw)

![2](https://user-images.githubusercontent.com/87793956/156013966-ed3a9329-0b25-4d4c-a461-05b96fa7dc5a.jpg)

- [https://twitter.com/rudayruday/status/1498133713787703296?s=20&t=7iI6mv1dAuEuvVfsWPHdgw](https://twitter.com/rudayruday/status/1498133713787703296?s=20&t=7iI6mv1dAuEuvVfsWPHdgw)

![3](https://user-images.githubusercontent.com/87793956/156014606-5c372444-92ad-4286-b2aa-3876c1583daf.jpg)

================
That's all my contribution for February 2022

**Comment by togamamora** [comment]
CM: 50
VSM: 25
