### ISSUE TITLE
February 2022 Contribution - kahonnohak

### ISSUE THREAD

**Issue by Kahonnohak** [AstarNetwork/growth-program#1855]
### **January 2022 Contribution - kahonnohak**

Telegram Username: @kaoriatcrypto

Discord Username: @Kaorihttps://github.com/AstarNetwork/growth-program/issues/1166

Twitter User name: @kaori_ruku

SDN Wallet Address: Zbqi66JFjpBc62WbkwUKgrgKwFKNYvtW5jdDLKz714Aq3nH

### **Contributions:**

CM - Manage and support local channels

Astar Telegram; https://t.me/PlasmJapan

Astar Discord: https://discord.gg/zARxg4ZR

Closed Community Discord (Polkadot) :https://discord.gg/uH6b8nzr

### **TT - Wrote a tutorial**

How to use Nova Wallet
https://note.com/kahon_design/n/n662c770ba882
<img width="1188" alt="スクリーンショット 2022-03-01 23 20 15" src="https://user-images.githubusercontent.com/77480847/156186159-c7ad46f7-25e8-40e5-8427-449bf66800e6.png">

**Comment by togamamora** [comment]
CM: 50
VSM: 28
TT: 8
