### ISSUE TITLE
Contribution : February 2022

### ISSUE THREAD

**Issue by boomblb** [AstarNetwork/growth-program#1856]
🟨 February 2022

✔️ Telegram : @boomblb124

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Shiden Address : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Contributions

1. CM : Manage and support Thai Telegram

<img width="1052" alt="155890741-15fe565d-0105-4057-bf60-9f425d27f54f" src="https://user-images.githubusercontent.com/84943107/156188583-e8d68043-a4a9-4719-bc89-fc8ed2f0ae81.png">

2. VSM : Promote & Sharing posts for engage new comers to Telegram group

2.1 Astar Network February Recap

✔️ Link : https://www.facebook.com/101755535144405/posts/364173245569298/

✔️ Stats :

![1646146059250](https://user-images.githubusercontent.com/84943107/156194050-b946a1a0-983d-4f81-8d93-7ec3f66fe2e9.jpg)

If you have any inquiries, please don't hesitate to tell me. Thanks

Best Regards,
BooM

**Comment by togamamora** [comment]
CM: 45
VSM: 15
