### ISSUE TITLE
February 2022 Contribution (Korean Community)

### ISSUE THREAD

**Issue by RHEEUNION** [AstarNetwork/growth-program#1858]
Hello everyone,
I'm `RHEE` from South Korea and I'm an Official Ambassador of Astar Network.

**[Personal Info]**
Telegram Username: @RHEEUNION
Discord Username: rheeunion#605
Astar/Shiden Address: bUUve83HysJPyXGfbAPcGdV2YujGPVMqZgM61fio4WTrQSs

**Contributions:**
**1. CM - Manage and support both Local and Main community chat.**
![image](https://user-images.githubusercontent.com/39883171/156229854-dc1bdc6f-43a9-457e-9766-b022ddfefa4e.png)

**2. VSM - Tweet & Announcements (https://twitter.com/AstarNetwork_KR + [Polkadot Korea Official](https://t.me/polkadot_korea_official))** 
- https://twitter.com/AstarNetwork_KR/status/1489575814035550208?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1491839483817254913?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1491841581170626560?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1493427081895878656?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1495785255160381442?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1496889423128309760?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://twitter.com/AstarNetwork_KR/status/1497161513018093570?s=20&t=ikp0XdL9ld3y1sJNxCGicw
- https://t.me/polkadot_korea_info/430
- https://t.me/polkadot_korea_info/433
- https://t.me/polkadot_korea_info/434
- https://t.me/polkadot_korea_info/435
- https://t.me/polkadot_korea_info/439
- https://t.me/polkadot_korea_info/440

**Comment by togamamora** [comment]
CM: 50
VSM: 27
