### ISSUE TITLE
February 2022 - Contribution

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/growth-program#1859]
I wrote two tutorials for Japanese Community.

1. How to use hardhat (https://realtakahashi-work.medium.com/hardhat%E3%82%92%E4%BD%BF%E3%81%86-astar-network-ee2b27563a3f)
2. How to deploy NFT (https://realtakahashi-work.medium.com/nft%E3%82%92%E7%99%BA%E8%A1%8C%E3%81%99%E3%82%8B-astar-network-67618941b3cf)

<img width="353" alt="astar_202202_1" src="https://user-images.githubusercontent.com/38233656/156261710-9ac33eee-6b9d-4eee-b6b9-29b0eabfa6bc.png">
<img width="464" alt="astar_202202_2" src="https://user-images.githubusercontent.com/38233656/156261719-dc83ec84-fb3d-4952-a290-7ba6f97572fa.png">

**Comment by togamamora** [comment]
How about your involvement in.community support and social media engagement?

**Comment by togamamora** [comment]
You are a technical guy. I think I need to create a different Ambassador program.  The current one does not suit you.

**Comment by realtakahashi** [comment]
I think your point is correct. The current ambassador program doesn't suit me.
I work full time as an engineer. And I have a restriction that I can't make a contract with other companies.
Therefore, I presume that it cannot directly contribute to the development of the core team.
I'm looking for a community contribution that I can feel free to do every month.
Do you have any ideas?
