### ISSUE TITLE
VSM

### ISSUE THREAD

**Issue by ahimbisibwebrian** [AstarNetwork/growth-program#1868]
Created and posted infographics on twitter, retweeted most of the Astar network tweets 
https://twitter.com/brianahimbisib6/status/1496411191727558665?s=21

https://twitter.com/brianahimbisib6/status/1496200799243980807?s=21

**Comment by togamamora** [comment]
Did you do any community support stuff? If you do, please submit the statistics.

**Comment by ahimbisibwebrian** [comment]
Thats in the African Channel, posting relevant links to the group,
Planning for our big Astar Event as well this month with an expected of non
blockchain joining , in additional to inviting all them join the channel

**Comment by togamamora** [comment]
I know. But please submit all tasks in only 1 report.

CM, VSM, etc etc, in one report. Do not split it into many.

**Comment by togamamora** [comment]
Please see how the other guys are making their report.

**Comment by ahimbisibwebrian** [comment]
Thanks so much for the correction , can i redo this now?
Am sorry for the inconvinieces if any

**Comment by togamamora** [comment]
Yeah. Put this report into the previous one that you submitted.

**Comment by ahimbisibwebrian** [comment]
Did so 
Thanks
