### ISSUE TITLE
Persian ambassador Cooperation

### ISSUE THREAD

**Issue by mohammadtaghian** [AstarNetwork/growth-program#1872]
Hi 

I'm Iranian ambassador with a team that working with me.

We can:

✓Managing Iran community

✓make it more knowable between Iranian traders and investors

✓helping them and answering their questions

✓making YouTube videos for you're project monthly in Persian language

 ✓translating all articles to Persian

My portfolio website:
https://mohammadtaghian.github.io

One sample video from our YouTube channel:

✓ https://youtu.be/aGzW8rufUk4

We making video monthly or weekly for the projects which we are ambassador there.we have studio with professional materials of recording video

Some samples from Iranian community that our team managing:

✓ https://t.me/coinexiranian

✓ https://t.me/waykichainirann

✓ https://t.me/coinexpersiann

✓ https://t.me/TokenPocketIR

Hope that accept us as irainian ambassador, also we can make call for more trust and understanding better.

Tnks ❤️

**Comment by togamamora** [comment]
1. Are you currently a community member of Astar?
2. Have you ever contributed anything to Astar ecosystem?

If your answer to both of these questions is NO, then you won't be selected.

**Comment by mohammadtaghian** [comment]
Yes we are in their telegram group also when I asking to be ambassador of
astar meant we love to helping to grow this project

**Comment by togamamora** [comment]
which telegram group?

**Comment by mohammadtaghian** [comment]
This one: https://t.me/PlasmOfficial

**Comment by togamamora** [comment]
PlasmOfficial telegram has been on read only mode since Jan 2022.

My question was, have you been an active community member of Astar? Have you done any contribution in the past?

**Comment by mohammadtaghian** [comment]
Mate I'm officiall ambassador of Iran , I have worked 6 years in this
field, only our studio price for recording video is 8k$.
I'm not one small ambassador who just asking over and over and wanna to
join for a job.
We are professional and if you don't have trust you can make call with me
to see

**Comment by togamamora** [comment]
I was asking if have you have previously contributed anything for Astar.

**Comment by togamamora** [comment]
And if you want to apply, please use the form.

**Comment by togamamora** [comment]
Yes. That was my question and thanks for answering. 

You can apply using the form on the front page. 

But, I prefer someone who have been an active community member and have contributed something to the ecosystem.

**Comment by mohammadtaghian** [comment]
Mate we making community from zero and start building it
Like these communities:
https://t.me/coinexiranian
https://t.me/waykichainirann
https://t.me/TokenPocketIR

So no worries we can do our job complete, also we can make call to talk
about it for more trust and planning too

**Comment by mohammadtaghian** [comment]
So please help me, what would I do to become as astar ambassador?
