### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by 2019jack** [AstarNetwork/growth-program#1873]
My Discord ID:

john xie#8674
Node name on Telemetry:
HashQuark
[Subscan](https://shibuya.subscan.io/) link of your account.
https://shibuya.subscan.io/account/W8uKv7LGKbgMhxqZv3sLdWdQ4y28Qdc4AgpVQ1hTJaTajgz
Email address to send important updates for your node.
xiexiaodong@hashquark.io
Shiden wallet address to payout your rewards.
ZZySuRwRuw6DvDUppQHz2HQuhML15ywn7H8Pi9SYRchQN9X

**Comment by bLd75** [comment]
You already have SBY and collating

**Comment by 2019jack** [comment]
yes, waiting for the shiden wallet address to be added to the whitelist and run shiden network collator

**Comment by bLd75** [comment]
This is Shibuya funds requests, mainnet whitelist is not managed on Github.

**Comment by 2019jack** [comment]
Hey bLd759, is it possible to add our HashQuark to the whitelist of the hidden collator node until now? Any advice to give?

Best,
Thanks
