### ISSUE TITLE
April 2022 Contribution - marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#1899]
April 2022 CONTRIBUTION

Telegram : Soul Eater / @marvelet
Discord : marvelet#8647
SDN Address : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

1. CM
TELEGRAM
Astar Shiden Indonesia
Link : https://t.me/astarshiden_id
Combot Link : [https://combot.org/c/-1001288040165/a?start=2022-04-01&end=2022-04-30](https://combot.org/c/-1001288040165/a?start=2022-04-01&end=2022-04-30)

Comment :
- Total Members  190 members (exclude Rose Bot) , raised around 50+ members on April alone, as Astar price reaching peak USD0.3+
- Interaction between members are very high, indicating some of them already attached to Astar Ecosystem, notably Starlay and Arthswap, few members becoming ambassador for few dApp projects on Astar like AstridDAO and Alnair, 
- dApps that were often mentioned on Indonesia community based on my observations are : Starlay, Arthswap, NIKA (Alnair), Sirius and AstridDAO
- Few of them are talking regarding getting rekt because buying ASTR on its peak, but majority didn't too much care regarding the price now, and busy on trying new dApps and token, indicating they are already hold ASTR before it was ATH. APY / APR and IDO oppurtunity are always the subject. 

Screenshots taken from Combot Analytics :
![ss april 1](https://user-images.githubusercontent.com/87793956/166097543-58b70615-2eb0-49f5-8ee0-c4b71ad69a56.png)
![ss april 2](https://user-images.githubusercontent.com/87793956/166097549-5e8cdf16-78b6-425a-b028-d293b162bc9d.png)

DISCORD
Channel Indonesian on Astar official Discord
Link : same as Astar official Discord

Comment :
- Not too much interaction as last month, several asking when ARSW airdrop landed or when ARSW get listed
- I tried to giving interaction by giving up hot dApp or hot oppurtunity aping on meme / IDO

==================

2. VSM

Twitter as Official Ambassador :https://twitter.com/rudayruday
Analytic : https://analytics.twitter.com/user/rudayruday/home
Comment :
- Continuing to promote Astar, added with WASM and Polkadot ecosystem

Screenshots :
![ss april 3](https://user-images.githubusercontent.com/87793956/166097667-38c6b0b5-6ae8-4e6b-90fc-05b47e5a4f19.png)

Twitter as Astar Network Indonesia : https://twitter.com/AstarNetwork_ID
Analytic : https://analytics.twitter.com/user/astarshiden_id/home
Comment :
- Continuing to tweet more news and information, achievement, milestones regarding Astar Network, in Bahasa Indonesia.

Screenshots :
![ss april 4](https://user-images.githubusercontent.com/87793956/166097892-9bd6a40a-581d-484a-b8ee-638a4102030e.png)

==================

3.  EM

Conducting first time online meetup for Astar Shiden Indonesia on Telegram and Discord on GMeet
When : April, 11 2022 / 20:00 GMT+7
Topics : Astar and Shiden Network Introduction (EVM + WASM feature) , How to move ASTR from Exchange -> Metamask -> Exchange
Attendants : ~10 participants
Proof : https://drive.google.com/file/d/1gLiQ3-lhuw8NlIHwGXKvtdUd1NABDnTS/view?usp=sharing

Comment : 
- all members, even small of them showed up, are very excited, all learn how to move ASTR from exchange to portal to metamask to portal and back to exchange again, and all attendants now understand that Astar Native Address is for interacting with WASM-based dApp later, and could knew the different between EVM and WASM. 
- will be conducted every month, for May topic are dApp Staking, Stable dApp, and summary of ASTR achievements on AmsterDOT

===================

4. CC

Writing an article on Asteroid, regarding basic FAQs of Astar Network
Link : https://asteroid.ac/articles/KnHVVGqOU
Comment : 
- This article are supplementary reading for Online Meetup participant and to introduce if a new member came up in telegram or discord to read that article first.
- Will be writing another article every month regarding Astar dApp, with more engaging content to audience (will be more specific to Astar Incubator and Builder Participants)

===================

5. BH

Portal v2 Betatest
- Beta Testing participant for  Math Wallet and Nova Wallet for Portal v2
When : Conducted on Astar Ambassador Telegram Channel (early April 2022)
Status : Finish

Minor Bug on Portal v2 after deployed 
- Issue can be seen here https://github.com/AstarNetwork/astar-apps/issues/350
Status : Fixed (but seems on GitHub, admin forget to close)

===================

That's all for my April contribution.

**Comment by togamamora** [comment]
Only 2 supplementary tasks are accepted into points calculation.
