### ISSUE TITLE
CC - Overview of DeFi applications deployed to Astar

### ISSUE THREAD

**Issue by pmensik** [AstarNetwork/growth-program#1918]
We have created the most comprehensive overview of DeFi applications that our currently deployed to Astar network. Unfortunately the read ratio is not that high but I suspect this due to the current state of the markets that causes peoples interest in crypto to drop. 

Twitter - https://twitter.com/Polkadotters1/status/1513511667451277317

https://polkadotters.medium.com/astar-network-multichain-polkadot-dapp-hub-e2c64c8f1e2c

![image](https://user-images.githubusercontent.com/3175660/167508361-051f103f-a876-4983-b90d-8c3b380b9779.png)

Discord - pmensik#3434
Telegram - @pmensik
Astar address - Z7c8uESo3BPPChURHLCwSQ2ZpX4ftpKTHYdrVL7RE47JLus

**Comment by pmensik** [comment]
@togamamora Thanks for pointing it out. So as far as I understand I just need to change the title to `CC`? Is there anything else I need to adjust?

**Comment by togamamora** [comment]
Do you have your own community that your are managing? This is part of the task.

**Comment by pmensik** [comment]
@togamamora So in other words, you don't deserve any reward for writing articles or promoting Astar unless you manage a community? 
Well, we have an international Polkadotters community and I also manage the whole Czech/Slovak Polkadot community where I post updates about Astar and other projects.

**Comment by togamamora** [comment]
This is the new program. It is designed to encourage the growth of the community as we are heading towards DAO.

**Comment by togamamora** [comment]
In the case that you have been managing the Polkadotters community, you need to include that in the report.

Also, whatever social media posts that you have made regarding Astar, need to be included.

See the example of the report format.
