### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by wojciechos** [AstarNetwork/growth-program#1922]
Discord ID: beatroot#6098
Node name on Telemetry: POLSKADOT_Wojo
Subscan link of account: https://shibuya.subscan.io/account/5Dc1ERfangFfo2kKPjK74p8aQyJ1LBQ2BPSpXMCRvwu126QA

**Comment by bLd75** [comment]
Funds have been sent: https://shibuya.subscan.io/extrinsic/0x0998f6c7d0a5356b515f59c3d40ce595fba32c499eacb0c5e5adf4338f3f656c
