### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by remi-3Tekos** [AstarNetwork/growth-program#1923]
Discord ID: Remi | 3Tekos#3616
Node name on Telemetry: 3Tekos
Subscan link of account: https://shibuya.subscan.io/account/aqpMcr7zFX3vhw9KzgpwBNwzk9sAAAtzGSFFoSg7pe5bwr5

**Comment by bLd75** [comment]
Funds have been sent: https://shibuya.subscan.io/extrinsic/0xa69444e68f1a82a7dd1cc19e76e7899f222029224492bf47a96062249a26662d
