### ISSUE TITLE
Kamala Immaculate- MAY Contributions 2022

### ISSUE THREAD

**Issue by KAMALAIMMACULATE** [AstarNetwork/growth-program#1943]
Name: Kamala Immaculate

Email: ([kamalaimmaculate@gmail.com](mailto:kamalaimmaculate@gmail.com))

Discord: kamala immaculate#5476

Telegram: Kamala Immaculate

Shiden Address: aUkGV7BjjbhBHEum67r9Jk2fPawfUPwyDTPY6qxnajVRBGF

1.Contribution.
I hosted a meetup, below is the link
https://drive.google.com/drive/folders/1IoooHXotEBDhfmwfm27E3bXN5AaiUhEN

2. Contribution
 designed three infographics
https://twitter.com/KamalaImmac/status/1533769993585819649?t=jzXU3M63x6p4TztTzVTN5A&s=19

https://twitter.com/KamalaImmac/status/1530211566322335745?t=wtqL9MeE7oTqw3TrveIJug&s=19

https://twitter.com/KamalaImmac/status/1534181913103147008?t=zkO4yRKyEBSUdMkplF7Umw&s=19

3.Contribution
engagement on twitter, retweeting and liking
Thank you

**Comment by togamamora** [comment]
late submission
