### ISSUE TITLE
July 2022 Contribution- Chris

### ISSUE THREAD

**Issue by cryptosats** [AstarNetwork/growth-program#1970]
Telegram Username: @christopedia

Discord Username: @cmalize#8352

SDN Wallet Address: Y5iCr5tyia5UwQnjVjSE9nDWJoFtowywG3BSfmsqLzNgy6W

Contributions:

CM - Managed and supported  Local  community chat (Africa)
![TG 1](https://user-images.githubusercontent.com/69989414/182597490-342c5ae0-a766-4b97-90bb-4f0dda0292e1.jpg)
![TG 2](https://user-images.githubusercontent.com/69989414/182597496-5f772da9-3b08-4fb8-b2b6-9c3fec6b3118.jpg)
![TG 3](https://user-images.githubusercontent.com/69989414/182597501-3edfd434-08b5-4930-816c-460729b3955f.jpg)

VSM - I Made 8 Tweets In July About Astar Network
https://twitter.com/ChrisMalize3/status/1545886534410305537?t=P_dR_bfBXEtV4YO6O7kQRw&s=19
https://twitter.com/ChrisMalize3/status/1546981386606841860?t=deLP6BCrcNgsc2T0VW4ERg&s=19
https://twitter.com/ChrisMalize3/status/1546989377951260673?t=uCD2E0d3x3Js-iuk95tb5g&s=19
https://twitter.com/ChrisMalize3/status/1547212932710375425?t=wlvYtfCPp5G4kX8BTKmVjQ&s=19
https://twitter.com/ChrisMalize3/status/1548046662089641984?t=aZjBh3Iz4Vrohp53Ex4Jqg&s=19
https://twitter.com/ChrisMalize3/status/1548994619836452867?t=D0OkExm1ufR2n4Lyj-T51Q&s=19
https://twitter.com/ChrisMalize3/status/1551666845924614152?t=N6j9oI_lVD0BBrxTEK2xRg&s=19
https://twitter.com/ChrisMalize3/status/1552319562850377734?t=ggblq5QmZGeTiCEfZ_gN1g&s=19

![photo_2022-08-03_12-45-50](https://user-images.githubusercontent.com/69989414/182601213-12f942a9-b789-46f7-bd9e-74e8e2a6f5d7.jpg)
![photo_2022-08-03_12-45-50 (2)](https://user-images.githubusercontent.com/69989414/182601300-3868e49b-37d0-40d9-8ecd-3710ad985dea.jpg)
![photo_2022-08-03_12-45-49](https://user-images.githubusercontent.com/69989414/182601368-b74c76ae-df9e-4c34-b3b0-50a88ef61a10.jpg)
![photo_2022-08-03_12-45-50 (3)](https://user-images.githubusercontent.com/69989414/182601375-056c7858-49ee-444b-b865-62d50a4689ac.jpg)
![photo_2022-08-03_12-45-50 (4)](https://user-images.githubusercontent.com/69989414/182601378-d8bafbb2-f01d-43ac-bde0-6c261f9cdd86.jpg)
![photo_2022-08-03_12-45-51 (2)](https://user-images.githubusercontent.com/69989414/182601380-8f050f20-809f-461a-844e-264299cf2bcd.jpg)
![photo_2022-08-03_12-45-51 (3)](https://user-images.githubusercontent.com/69989414/182601382-567ec0f5-be65-48ae-8f4f-3cfdb34af0df.jpg)
![photo_2022-08-03_12-45-51](https://user-images.githubusercontent.com/69989414/182601388-591ea48b-934f-4ad8-81ed-72214f17d966.jpg)

CC- I wrote one (1) article about Astar Network
https://twitter.com/ChrisMalize3/status/1545886534410305537?t=P_dR_bfBXEtV4YO6O7kQRw&s=19

**Comment by togamamora** [comment]
For article, please use other format e.g. Medium, Linkedin, Subsocial..  Don't use Tweet storm.

**Comment by cryptosats** [comment]
Got you. Thank you.
