### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by MaculataDao** [AstarNetwork/growth-program#2014]
GM I would like to participate in the collator program on shibuya. Here is the requested information

discord: subscanneur
Node name on Telemetry: cbo
Subscan link of my account: https://shibuya.subscan.io/account/asRjUH8MyDTB4r9RPQSziY8ssduLdMMeeWhvwaDPTXj3hHY

I have Set on-chain Identity and request jugement

thanks for all astar team.

**Comment by togamamora** [comment]
@fiexer
Is this something you want to take a look at?
