### ISSUE TITLE
October 2022 Contribution - s.takahashi

### ISSUE THREAD

**Issue by realtakahashi** [AstarNetwork/growth-program#2022]
**- Twitter Activities**
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/38233656/198906020-8e5b2609-4285-43e0-b22a-841bd2906199.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/38233656/198906046-03d36f36-018b-4dc7-82c7-d9b5c8a266ea.png">
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/38233656/198906075-41799e51-5796-4a69-a936-8342c51402d3.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/38233656/198906091-c2658b60-5a9d-4737-86e1-b03728eb50f7.png">

**- My own Articles of Astar Network**
I worte an article in this month.
https://realtakahashi-work.medium.com/a-guide-to-wasm-ink-implementation-for-beginners-b90f0beec8a6
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/38233656/198906197-2fa54e83-e48e-47be-8227-d190628b2461.png">
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/38233656/198906223-c6c3ce2b-c46e-4540-9b33-b2f9fb4f6016.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/38233656/198906255-c47de2ae-4bad-4a7c-9f0c-679c322bf5e1.png">

**- At the hackathon officially sponsored by Astar Network, I was in charge of the study group lecturer.**
hackathon URL: https://tokyo.akindo.io/
youtube: https://www.youtube.com/watch?v=OZk8bsTy51E&t=21s

**Comment by togamamora** [comment]
From November onwards, you can start following this program:
https://github.com/AstarNetwork/growth-program/blob/main/Technical%20Ambassador%20Program.md

It is basically the same things that you have been doing:
1. Sharing what you learn about ink! & WASM on social media.
2. Writing tutorials
3. Doing a developer/technical meetup
4. Helping other developers on Discord.
