### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by chaerulchas** [AstarNetwork/growth-program#2044]
GM I would like to participate in the collator program on shibuya. Here is the requested information

discord: tigerfishguy#0067
Node name on Telemetry: Kommunitas.net
Subscan link of my account: https://shibuya.subscan.io/account/5DhDDhL5PAtnhvNUxNx68c9dcmdwoiSRgmDb12j32hBkAWsa

I have Set on-chain Identity and request jugement

thanks for all astar team.

**Comment by bLd75** [comment]
@chaerulchas 
- your node is not visible on Telemetry
- you have 20 SBY, please set your identity on-chain as indicated in documentation
