### ISSUE TITLE
Activity Report / December 2022 - PromoTeam

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#2077]
Informational support in social networks (twitter/telegram) for Shiden and Astar / December 2022

Providing the info about the Astar/Shiden , in telegram, twitter, medium and other platforms

Here is the link to the list of social network contributions in Google Doc

https://docs.google.com/spreadsheets/d/1qJ2zFDyiRQ-k1av3epT3RPTF5QMRCijwcuUvlpEWLhQ/edit?usp=sharing

Russian Community Support and Development |  December 2022

Russian community Astar / Shiden
https://t.me/astar_rus

Prevention of attacks on community and spam attacks
Community development
Translation of core team messages
3 Admins covering all timezones (5 timezones) 7 days a week

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Astar/Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
In the next report, please include the links to each tweet or videos that you made and screenshot the statistics too.

![image](https://user-images.githubusercontent.com/37278708/212835959-2987e9de-0238-46b6-ac1f-fab7233cc586.png)
