### ISSUE TITLE
Ink! recruit contribution. (Nov 2022-Jan 2023) - kota

### ISSUE THREAD

**Issue by Kotakageyama** [AstarNetwork/growth-program#2086]
Discord Username: kota3kota3#2984

Dev Community Support:
1. did you help any other devs on Astar discord? screenshots of messages will do.
![Screenshot from 2023-01-15 13-27-01](https://user-images.githubusercontent.com/27982108/212522918-9d3f4970-9522-4c5b-8174-7a0c003a4702.png)
2. Did you start a local dev community? Please share your telegram group stats if any.
No, I didn't.

Social media activities (sharing what you learn):
1. twitter
![image](https://user-images.githubusercontent.com/27982108/212523257-24c1059e-750b-48fa-b1d6-c31eeedad241.png)

Content Creation:
1. my blog article 
lerning ink!
https://zenn.dev/kota13/scraps/2bb169a1fe1fd2
learning Rust
https://zenn.dev/kota13/scraps/60dd5acf1f5409
2. Dapps on Astar using UNCHAIN's program
https://github.com/Kotakageyama/astar_sns_frontend
https://github.com/Kotakageyama/astar_sns_contract

**Comment by togamamora** [comment]
From March onwards, please also submit your report to earn points based on these activities

![image](https://user-images.githubusercontent.com/37278708/224224514-4e639188-ec0b-4053-ae59-3bac6cf5cf2a.png)
