### ISSUE TITLE
January Contributions 2023: Ahimbisibwe Brian

### ISSUE THREAD

**Issue by ahimbisibwebrian** [AstarNetwork/growth-program#2099]
![IMG_7854](https://user-images.githubusercontent.com/91603452/216832086-2490c2c1-8ba1-45d8-8489-bf3a574e513e.PNG)
Name: Ahimbisibwe Brian
Telegram: brayoahimbisibwe
Discord:brian#4181
Twitter: bricrypto256
Wallet address: WYQL12buyFK93DgyLHE6tefVLmTynHzQJJQwxAsXL4rZEQy

Task 1
Engangement in the African Telegram channel 
![IMG_7852](https://user-images.githubusercontent.com/91603452/216832038-fc082d52-a557-4fe6-ae81-95ab85651b43.PNG)
![IMG_7853](https://user-images.githubusercontent.com/91603452/216832060-edbd683c-b2a1-43f3-a3c5-998172878598.PNG)
Task 2
Created content memes for posting on twitter
![IMG_7856](https://user-images.githubusercontent.com/91603452/216832162-6381c244-b0a0-4fa4-a69b-22072ccb1490.PNG)
![IMG_7855](https://user-images.githubusercontent.com/91603452/216832160-bdf616ed-f8e5-4650-aeef-b4b282ac6421.PNG)

![IMG_7857](https://user-images.githubusercontent.com/91603452/216832179-b3414f73-665a-4c91-9ae0-3d984e1c7205.PNG)
Link to the tweets 
https://twitter.com/bricrypto256/status/1619038348882112512?s=20&t=WnTBWuXvdVr32ELJ5MaLDA
https://twitter.com/bricrypto256/status/1616049671000002562?s=20&t=WnTBWuXvdVr32ELJ5MaLDA
https://twitter.com/bricrypto256/status/1615098717115416576?s=20&t=WnTBWuXvdVr32ELJ5MaLDA

I posted and retweeted most of the tweets from the main Aster official twitter account

**Comment by togamamora** [comment]
This submission is rejected. You have been missing for a long time and I did not see any participation. You are removed from the Ambassador program.
