### ISSUE TITLE
Alphaday Grant Proposal

### ISSUE THREAD

**Issue by deparisfi** [AstarNetwork/growth-program#2101]
### Project: Alphaday
Alphaday builds crypto experience dashboards for enthusiasts, developers, and projects. Users can drag and drop from hundreds of services, news and social feeds, charts, and dapp functionality to create their daily workflows inside a single dashboard. This eliminates the need to have multiple browser tabs open to get different bits of information. i.e. imagine having token prices, gas prices, twitter feed, latest news headlines, TVL, borrowing rates and any other information any user could possibly want all within one single dashboard. 
### Team
Team members
[Deniz Omer](mailto:deniz@alphaday.com)
I’ve been involved in the Ethereum space since early 2016 and joined Kyber Network in 2017 as Head of Ecosystem Growth before quitting to start Alphaday full-time in 2021. Previously I worked at Thomson Reuters for a decade building financial products that rivaled the Bloomberg Terminal. I am currently also a Venture Partner at IOSG.VC

My co-founder Felipe has also been involved in Ethereum since 2016 and was a Developer Advocate at Pegasys and Consensys before quitting to work full time on Alphaday.

Alphaday’s third co-founder is DeFiDude who used to be a community manager at both Aave and Kyber Network before co-founding Alphaday.
We have assembled a team of 9 individuals.
Team Website
https://www.linkedin.com/in/denizomer/ 
https://www.linkedin.com/in/faraggi/ 
https://twitter.com/defidude 

Team Code Repos
https://github.com/faraggi
https://github.com/ppalomo
https://github.com/v-almonacid
https://github.com/elcharitas
https://github.com/Xavier-Charles
https://github.com/getgiddy

### Project Details
We would like to create a Shiden Network ecosystem dashboard that aggregates the following information into a single community dashboard:

- The latest Shiden Network official announcements and blog post content
- A feed of all news mentions of Shiden Network from coindesk, cointelegraph and 20+ other news sources aggregated from across the internet
- A calendar containing all Shiden Network events including Shiden Network meetups, hackathons with Shiden Network bounties, AMAs
- Podcast feed containing the latest appearances and interviews given by Shiden Network team members
- Youtube stream containing educational Shiden Network content.
- Astar (Plasm) Documentation
- Integration with Shiden Network Forum to show the latest and trending discussion topics
- Discord & Telegram Integration to show a feed of latest discussions
- FAQ, Whitepaper, SDN tokenomics information
- Shiden Network Careers integration to show the latest open jobs listed on Shiden Network 
- Shiden Network Backers and Supporters

### Ecosystem
We’ve done market research on this and currently people’s regular crypto workflows consist of jumping from one browser tab to another to check prices, read news, follow twitter, participate in discussions. A typical crypto user will have 6 to 10 open tabs at any given time and people have referred to Alphaday as the ‘tab killer’ because all the information you’d need across all your different tabs is available in Alphaday. In this sense, we do not have any direct competitor that can provide 50 different types of services and functionality within one dashboard. 
We have received pre-seed money from Anthony Sassano, Mariano Conti, Signum, IOSG and a few other Ethereum-focused angel investors.
A month ago we started reaching out to a select group of projects to pitch our Ecosystem Board idea and within this first month we’ve had buy-in from Aave, Dfinity (ICP), Zcash, Aztec, theGraph, Sia, Impossible Finance and a few other projects and we’ll be releasing dashboards for their communities throughout February, and March.

### Development Roadmap and Budget Breakdown
1,200 USD upfront costs for development including integrating the discussion forums, blog post, social feed, jobs listing and documentations.

120 USD per month for 12 months for maintenance including having an Alphaday content analyst quality-checking the dashboard every day and ensuring the Calendar widget is up-to-date with latest Shiden Network events, all news mentions across the internet are captured by the dashboard, any updates not automatically captured by the Alphaday aggregator engine is manually added to the board, and other maintenance tasks.

For a total of 2,640 USD.

### Future Plans
Once we’ve launched the board, we will do user interviews and feedback sessions to tune the dashboard. We will continue this process of iterating, deploying, and collecting feedback continuously to build a dashboard that Shiden Network stakeholders truly love to use.
Additional Information
How did you hear about the Builders Program? 
Through your website.
Here you can also add any additional information that you think is relevant to this application but isn't part of it already, such as:

### Relevant Links
Live Product: https://app.alphaday.com/
Landing Page: https://alphaday.com/
Twitter: https://twitter.com/AlphadayHQ  
Discord: https://discord.com/invite/8KSmPyT5k8

Email Address: [deniz@alphaday.com](mailto:deniz@alphaday.com)
Telegram handle: @Denizined
Discord name: Deniz | Alphaday#0697
Twitter handle: @DenizOmer

**Comment by Poggi-Luca** [comment]
Hey Deniz!
The proposal is very interesting.....but please post it in the forum (just copy-paste it): forum.astar.network
So we can discuss further with all team members, ambassadors and community members!
This is not the right place to post it!
Thank you :)

**Comment by togamamora** [comment]
Hi @deparisfi 

Please propose this idea on Shiden DAO discord. https://discord.gg/Y7HRtvgpfG
