### ISSUE TITLE
January 2023 contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2106]
Telegram Username: @actlee
Discord Username: @Pithecus#9288
SDN Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

**Mandatory task**
**CM**
- Communicate with the Korean TG channel
- Share the announcements
![image](https://user-images.githubusercontent.com/90181025/217978267-7332f71b-46fe-4ffd-b47b-a8b70e14b63f.png)
![image](https://user-images.githubusercontent.com/90181025/217978307-368de55a-0e59-465f-ad24-926d302f8546.png)
 
![image](https://user-images.githubusercontent.com/90181025/217978537-89a10a76-3ca4-4ab8-869f-ff497c92393b.png)

**VSM**
- Personal account, @spmlaihm
![image](https://user-images.githubusercontent.com/90181025/217978808-a3cfad5e-3d53-42a3-8ab0-46f423ca42ec.png)
![image](https://user-images.githubusercontent.com/90181025/217978981-6dedff83-11b1-4b36-9355-e7aa9fc792fc.png)
https://twitter.com/spmlaihm/status/1619231570933710848
https://twitter.com/spmlaihm/status/1619231573257375744
https://twitter.com/spmlaihm/status/1619231575455207429
https://twitter.com/spmlaihm/status/1619231578202451968
https://twitter.com/spmlaihm/status/1619231580278624256
https://twitter.com/spmlaihm/status/1618182408276422656
https://twitter.com/spmlaihm/status/1616113794085707777
https://twitter.com/spmlaihm/status/1616111973904564227
https://twitter.com/spmlaihm/status/1614745046405750784
https://twitter.com/spmlaihm/status/1614745049232719874
https://twitter.com/spmlaihm/status/1614745051267043332
https://twitter.com/spmlaihm/status/1614745053418725379
https://twitter.com/spmlaihm/status/1614745055536861185
https://twitter.com/spmlaihm/status/1614745057688420355
https://twitter.com/spmlaihm/status/1614619595108765698
https://twitter.com/spmlaihm/status/1614619597252034561
https://twitter.com/spmlaihm/status/1612221997664337921
https://twitter.com/spmlaihm/status/1610635940292182018

- Local account, @AstarNetwork_KR
![image](https://user-images.githubusercontent.com/90181025/217979153-a55348c5-4f57-4067-b1cc-12b29fe3e944.png)
![image](https://user-images.githubusercontent.com/90181025/217979236-1b46a104-c4c7-41fc-adec-715e883e20ef.png)

**Supplementary tasks**
**TT**
https://cryptolifebalance.tistory.com/39
![image](https://user-images.githubusercontent.com/90181025/217985505-7b4572d7-123c-4e7f-a21c-482470209c92.png)

https://cryptolifebalance.tistory.com/40
![image](https://user-images.githubusercontent.com/90181025/217989373-32349ac6-237c-4dfd-a4ed-2576c37c702e.png)

https://cryptolifebalance.tistory.com/41
![image](https://user-images.githubusercontent.com/90181025/217990221-1edafb86-8ff7-4289-bc6b-ab1990ca758d.png)

https://cryptolifebalance.tistory.com/42
![image](https://user-images.githubusercontent.com/90181025/217990635-7675300d-e7a5-4e22-b28f-40d049f6f6ab.png)

https://cryptolifebalance.tistory.com/43
![image](https://user-images.githubusercontent.com/90181025/217990802-c826f4da-bd0e-459e-9f5d-f0e3d5466b6d.png)

**BH**
Translate the frontend texts into Korean
![image](https://user-images.githubusercontent.com/90181025/218056786-aca04d35-3755-4307-a9fe-ae3b13a204e1.png)

**Comment by togamamora** [comment]
Translation is not BH or TT.

BH is when you found a bug, able to replicate and report the issue.
TT is tutorial.

**Comment by togamamora** [comment]
Article and announcement translation is part of CM.
