### ISSUE TITLE
Content creation, Mod and rust learning - Dr CAO's Astar Specific Contributions (Feb/2023)

### ISSUE THREAD

**Issue by ahjxcrz** [AstarNetwork/growth-program#2111]
Feb 2023

Telegram Username: 
@ahjxcrz

Discord Username:
DrCAO#1508

SDN Wallet Address:
akBsuDRUzk9hRxiLRdQTcFsgsHoa5PvWQuPVjrEK6zkLU3X

Contributions:

1. CM - Manage and support both Local and Main community chat.

I am mainly on the main discord and also Chinese Wechat. 
12 in the question channel and 64 in chat (Not that much for two reasons: (1. I want to make more but it is hard to compete with Toga, he answers most of the questions. (2. I didn't know that I need to take care of the discord until almost mid of Feb.).  
60+ in Wechat, answer questions about the AD NFT, promote the Astar and also the dApp staking questions, reward, etc. 
In addition, I am also proposing to organize event in Chinese community that will encourage more users to use Astar, still discuss with Graves. 

2. VSM 

Tweet analytics:
Tweets: 104, Tweet impressions: 32.9K, Profile visits: 3907, Mentions: 117, Followers: 874

Representative tweet and videos: 
Promote the Astar Degens: https://twitter.com/AstarDegens/status/1626330634338635778

Voted for the Astar Degens: https://twitter.com/cao_lab/status/1622820190710030336

Promote the Astar's ink and hackthon: https://twitter.com/cao_lab/status/1618304452762697729

Promote the PSP22 contract using Astar docs!	https://twitter.com/cao_lab/status/1618732887163179009

Tutorial on deploy PSP22 contract - tweet	https://twitter.com/cao_lab/status/1618868380949438465

Polkadot eco update: https://twitter.com/cao_lab/status/1629618199816974337

Astar Degens NFT holder or dApp stakers: https://twitter.com/cao_lab/status/1628652001985990656

Promote Astarpass: https://twitter.com/cao_lab/status/1621635863817093120

3. CC:
Youtube video and mention the CandyGirl NFT update and also the PhatContract DEX for Astar and Moonbeam	https://www.youtube.com/watch?v=ocrUdoael88

Chinese video to promote PSP22 contract:  https://www.youtube.com/watch?v=GOtN4_KTvVU

Chinese tutorial on deploy PSP22 contract - video: https://www.youtube.com/watch?v=J2C9mJ99q3M

Polkadot eco update 2/25 | Centrifuge| Moonbeam| Bifrost| Parallel Finance| Astar| BrainDEX: https://www.youtube.com/watch?v=KxnbRqWj4iQ

Astar Degens related videos: https://www.youtube.com/watch?v=wLNbJQUZ5CI
https://www.youtube.com/watch?v=4re4swLxiFk

Polkadot NFT videos: https://www.youtube.com/watch?v=zNQsahqd6b0

Rust and WASM: https://www.youtube.com/watch?v=yqXrmet4GqM

4. TT:

Tutorial on compiling PSP22 contract	: https://www.youtube.com/watch?v=Aa5ZbPRmtA8

Tutorial on deploy PSP22 contract : https://www.youtube.com/watch?v=cLwVQW0nzjQ

**Comment by ahjxcrz** [comment]
Another meme tweet for the AD NFT and Astar: https://twitter.com/cao_lab/status/1630366066890383361

**Comment by togamamora** [comment]
You joined on the mid of Feb 2023. Please start submitting the contribution starting from March.
