### ISSUE TITLE
February 2023 Contribution - GuiGou

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/growth-program#2115]
Telegram Username: @GuiGou12358
Discord Username: GuiGou#1021
Twitter Username: @GuiGou12358
Native Wallet Address: 5DaCixaPPaYrdGdSxP6Mwptn7dPNp3DTeJCQKuCUQe5jp6fL

CM: Manage and Support Astar Network FR (Telegram)
![image](https://user-images.githubusercontent.com/92046056/222084576-8da0340a-f7ac-4a4a-8b62-87afe2444bdb.png)

DS: Support the builders and developers on #wasm-smart-contract channel on Astar Discord
I try to answer to all questions/issues posted in this channel 
![image](https://user-images.githubusercontent.com/92046056/222085543-7e0b39c5-7dc3-4e4c-9d22-10866faeeb80.png)

CC: Explaining in french what is ink!
https://polkaverse.com/9768/qu-est-ce-ink-de-parity-37602

And promote it via twitter
https://twitter.com/GuiGou12358/status/1630128732840009729
https://twitter.com/AstarNetwork_FR/status/1630856592605233152

EM: Every Wednesday we are talking about ink! and the wasm smart contracts with a group of developers in the discord PhalaFr 
https://twitter.com/GuiGou12358/status/1630665450592845824

I would like to gather some developers to write some games on Shiden
https://discord.com/channels/1008714014483816518/1078227456789598229/1078227456789598229
![image](https://user-images.githubusercontent.com/92046056/222094969-ea661f81-7d7c-4d11-882e-39814a3fb051.png)
https://forum.astar.network/t/shiden-community-management/4386/4?u=guigou
![image](https://user-images.githubusercontent.com/92046056/222095702-b1055a23-f217-414c-8777-ffb0900a8150.png)

Extra task:
In the meantime I continue to build with ink! and rust:
gitHub: https://github.com/GuiGou12358/lucky-contracts
Teasing: https://youtu.be/hW4OcKYC3YM

**Comment by togamamora** [comment]
In the future, please add the statistics for the EM. e,g, how many members participated in the talk. You can screenshot the event.

 That will help to justify the points.
