### ISSUE TITLE
February 2023 Contribution - Leo (Neurolauncher)

### ISSUE THREAD

**Issue by LeoNeurolanche** [AstarNetwork/growth-program#2118]
Leo February 2023

**Telegram : @neurolauncher

Twitter: [https://twitter.com/neurolauncher](https://twitter.com/neurolauncher?s=21&t=1BQFwGrkFN94j4clXAU1Ow)
Twitter Astar Turkey: https://twitter.com/astarnetworktr?s=21&t=dcYv_JgsxzkSULikeHAeIQ
Medium Astar Turkey: https://medium.com/@astarnetworktr
Medium (Personal): https://medium.com/@enesfaruksahin
**Telegram Astar Turkish Channel: https://t.me/AstarTurkiye

**Discord: neurolanche#9226
Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4
Contributions:

CM - Manage and support both Local and Main community chat.

This month we made some attempts to revive the Turkish community. We tried to make the Telegram channel more active. We set up Turkey Twitter account.

![image](https://user-images.githubusercontent.com/126774982/222411874-f57505de-5a78-4904-ae54-5289f1802db4.png)![image](https://user-images.githubusercontent.com/126774982/222411911-b81a4dbf-769a-4170-ac8d-44fa62a4f67c.png)![image](https://user-images.githubusercontent.com/126774982/222411932-1cf1a5b2-a6c5-491f-9a52-ad98b14dd38d.png)![image](https://user-images.githubusercontent.com/126774982/222411965-fd83d769-0409-4fd0-be89-e951dbba55f8.jpeg)![image](https://user-images.githubusercontent.com/126774982/222411982-32aba948-4b98-4466-85f2-bd47d16b770d.png)![image](https://user-images.githubusercontent.com/126774982/222412007-147e0a66-9ad7-4ad7-8ff6-9c7ec73c8938.jpeg)![image](https://user-images.githubusercontent.com/126774982/222412037-7493acfd-cc1e-42e0-87cb-3dd260117c59.jpeg)![image](https://user-images.githubusercontent.com/126774982/222412046-2573ec8a-3eab-4eb9-a0a9-c0de7e8dbf24.jpeg)![image](https://user-images.githubusercontent.com/126774982/222412059-87e524d2-0777-46a9-ba0e-842af6cc84b9.jpeg)![image](https://user-images.githubusercontent.com/126774982/222412069-571e495e-b698-4d03-a872-666ac1eed7cc.jpeg)

**VM Viral Social Media Engagement**
Twitter : I am managing my profile for Astar and now we have created public Astar Network TR twitter account. We ll manage together this profile with another AMB Floki. Translating all posts these shared by Astar Network.

Twitter monthly statistics.
![image](https://user-images.githubusercontent.com/126774982/222413205-b0095eb8-e6c0-418d-b34f-f1dd5a1dcc67.jpeg)
![image](https://user-images.githubusercontent.com/126774982/222413231-acc2302f-0f60-4d88-94a3-733b306eb896.jpeg)
1-)https://twitter.com/neurolauncher
2-)https://twitter.com/AstarNetworkTr
![image](https://user-images.githubusercontent.com/126774982/222967128-564884a5-6526-4c3a-9fbd-83e9978fb549.jpeg)
![image](https://user-images.githubusercontent.com/126774982/222967157-9276940c-efa6-4a93-8fb2-36ad391c90a4.jpeg)
Good comrades bring success;  Astar Network has signed with Sony Network Communication:
![image](https://user-images.githubusercontent.com/126774982/222412211-2f7d896f-705b-4cab-b0e8-8c92ffae86b3.jpeg)

https://twitter.com/neurolauncher/status/1628752420305076226?s=46&t=ndr6UaH0xtPdaZeZGWK9fA

Will Japanese hospitality bring success?  The key to Astar Network's success is;
![image](https://user-images.githubusercontent.com/126774982/222412364-484b5397-1052-4b32-8e03-2c0348fd9a02.jpeg)

https://twitter.com/neurolauncher/status/1626601091352924161?s=46&t=ndr6UaH0xtPdaZeZGWK9fA

To create an ecosystem, it is necessary to nurture it;  What is AstarPass?
![image](https://user-images.githubusercontent.com/126774982/222412506-94863d34-3d32-4244-a3f4-80e59aca16aa.jpeg)

https://twitter.com/neurolauncher/status/1625455428829081600?s=46&t=ndr6UaH0xtPdaZeZGWK9fA

I invited the famous basketball player Birkan Batuk to the Astar Network ecosystem. Now owns a Astar Degens.
![image](https://user-images.githubusercontent.com/126774982/222412607-1ac6a4b7-03b2-480a-ba3f-62bd2e7a8ebd.jpeg)

https://twitter.com/neurolauncher/status/1626685011146559504?s=46&t=o8kS8rEjXRsccPK5P7rrgw

https://twitter.com/astardegens/status/1627399228187377664?s=46&t=o8kS8rEjXRsccPK5P7rrgw

**CC The Content Creator** 

Article for Astar Bulletin 

https://theastarbulletin.news/a-paradise-for-users-astar-pass-e9e1896a89c
![image](https://user-images.githubusercontent.com/126774982/222412763-685f90ff-89d6-4675-af47-6a735a7f198b.png)

Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4

**Comment by togamamora** [comment]
As discussed on Telegram, you can start this from March 2023.
![image](https://user-images.githubusercontent.com/37278708/224209869-b47f8666-8954-43e5-a426-ecba5f9fdad2.png)
