### ISSUE TITLE
February 2023 Contribution - Gunit 

### ISSUE THREAD

**Issue by Gunit2481** [AstarNetwork/growth-program#2123]
Telegram Username: @Gunit31
Discord Username: G'ₑₓₚₑcₜ cₕₐₒₛ#3121

New ASTR Wallet Address: W861TbgiVofe4cM8FJi2u8tWTfmfUXDLB2uqqHcHeHeSYtK

**CM**
TELEGRAM/DISCORD
Astar France
Link : https://t.me/PlasmNetwork_FR
Combot Link : https://combot.org/c/-1001138925620/a

![image](https://user-images.githubusercontent.com/85451570/222731150-baceac9a-eec6-4993-b0a4-e2a426c11a0e.png)
![image](https://user-images.githubusercontent.com/85451570/222731241-83f096c4-b849-4f76-9693-b2f2662c0b37.png)
Comment:

For Telegram, the number of members increased to 538 members.
February was quite and the main topics were Toyota, Sony, SDN delisting, RMRK, dApp Staking and ink!.

**VSM**

Twitter as Official Ambassador: https://twitter.com/gunit3124
Screenshots :
![image](https://user-images.githubusercontent.com/85451570/222732043-35bb41f3-b18e-4c33-99f5-a65feaf8db30.png)Twitter as 

Astar Network FR: https://twitter.com/AstarNetwork_FR
![image](https://user-images.githubusercontent.com/85451570/222732606-75a4441e-529d-498f-8f8b-6d1a8833b022.png)
![image](https://user-images.githubusercontent.com/85451570/222732723-f5587527-12f9-47f4-a49b-1429bbf0052d.png)

**TT**
One Guide step-by-step to withdraw ASTR from a CEX and stake them in dApp Staking

Guide url : https://polkaverse.com/5572/transferer-des-astr-depuis-un-cex-vers-astar-network-et-37651

![image](https://user-images.githubusercontent.com/85451570/222743228-26b82376-2f8a-422b-9b34-e8974c02900c.png)

**Linguistar**

I have worked with @GuiGou12358  on the French version of the Astar portal. PR #694 was merged on February 20th.

End of my contributions for February. Thank you. :)

**Comment by togamamora** [comment]
@0xRamz 
Are the Liguistars incentivized already?
