### ISSUE TITLE
February 2023 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2132]
Telegram Username: @actlee
Discord Username: @Pithecus#9288
SDN Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

**Mandatory task**
**CM**
- Communicate with the Korean TG channel
- Share the announcements
![image](https://user-images.githubusercontent.com/90181025/223095239-13b46739-e288-496a-b594-5bd6561f46a6.png)
![image](https://user-images.githubusercontent.com/90181025/223095314-ae33415a-55b0-4b65-a69b-9be2bbe5905f.png)
![image](https://user-images.githubusercontent.com/90181025/223095370-9cecb519-39b0-4b5f-92bd-3ebf959b88a8.png)

- Translate Medium/Twitter article(s)
[Web3 Incubation Program by Sony Network Communications and Astar](https://medium.com/astar-network/web3-incubation-program-by-sony-network-communications-and-astar-4d5766ba3ea6) into Korean
https://cryptolifebalance.tistory.com/45
![image](https://user-images.githubusercontent.com/90181025/223095537-39d32c80-f15f-40d5-b93d-7a7ab77cf489.png)

[Upbit listing ASTR/BTC pair] into Korean
https://cryptolifebalance.tistory.com/47
![image](https://user-images.githubusercontent.com/90181025/223097343-11368767-37f3-469c-a8f2-2be6bbc6cb34.png)

**VSM**
- Analytics on the private account
![image](https://user-images.githubusercontent.com/90181025/223095750-1e5d1bea-598c-4c6b-95fa-470bca049dc3.png)
![image](https://user-images.githubusercontent.com/90181025/223096189-f217b540-6c09-4b0f-bab2-db719f072720.png)
https://twitter.com/spmlaihm/status/1625307052154228737
https://twitter.com/spmlaihm/status/1625307054427582464
https://twitter.com/spmlaihm/status/1625307056080142337
https://twitter.com/spmlaihm/status/1625337520945856514
https://twitter.com/spmlaihm/status/1625337523261022211
https://twitter.com/spmlaihm/status/1625338902335655938
https://twitter.com/spmlaihm/status/1625338905045131264
https://twitter.com/spmlaihm/status/1625971255164784640
https://twitter.com/spmlaihm/status/1625971411163414528
https://twitter.com/spmlaihm/status/1626416007387422724
https://twitter.com/spmlaihm/status/1626416009702785026
https://twitter.com/spmlaihm/status/1626416011397287936
https://twitter.com/spmlaihm/status/1626416012944896001
https://twitter.com/spmlaihm/status/1626426166771957761
https://twitter.com/spmlaihm/status/1627149541525913601
https://twitter.com/spmlaihm/status/1627149947555528705
https://twitter.com/spmlaihm/status/1627611716954488835

- Analytics on the Astar KR account (co-manage this account with Rhee)
![image](https://user-images.githubusercontent.com/90181025/223096369-ed391eb9-7530-4fed-ae89-ea30f9ab6bfc.png)
![image](https://user-images.githubusercontent.com/90181025/223096460-ff75aa90-bf4d-470f-b725-43ba5804e8b3.png)

**Supplementary task**
**TT**
- Tutorial: how to use the NFT marketplace on Shibuya Testnet 
https://cryptolifebalance.tistory.com/44
![image](https://user-images.githubusercontent.com/90181025/223096630-afa3212d-3df2-4b8d-a30b-fe794241fbc9.png)

- Tutorial: dApp staking for beginners, from withdrawal to dApp staking
https://cryptolifebalance.tistory.com/46
![image](https://user-images.githubusercontent.com/90181025/223097482-33e20ee0-0eaf-49d7-a92e-fd5bf362ec98.png)

- Tutorial: how to create wallet addresses on Astar native with Ledger
https://cryptolifebalance.tistory.com/48
![image](https://user-images.githubusercontent.com/90181025/223097632-15660ff1-35ca-4773-9eee-7cb309792ec0.png)

**Others**
- Translate Astar Portal into Korean
https://twitter.com/AstarNetwork/status/1628590498188500993
https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/kr/index.ts
![image](https://user-images.githubusercontent.com/90181025/223098316-a772b201-bbd9-4937-bfc2-5c75ccb66b46.png)

**Comment by togamamora** [comment]
One 1 tutorial is ok in a month. You don't have to make up to 3 tutorials lol. Save the others for other months to earn points.
