### ISSUE TITLE
March 2023 Contribution - GuiGou

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/growth-program#2153]
Telegram Username: @GuiGou12358
Discord Username: GuiGou#1021
Twitter Username: @GuiGou12358
Native Wallet Address: 5DaCixaPPaYrdGdSxP6Mwptn7dPNp3DTeJCQKuCUQe5jp6fL

### CM: 
Manage and Support Astar Network FR (Telegram)
![image](https://user-images.githubusercontent.com/92046056/230008233-971b4f35-c5bd-4f84-a080-9b7ef2066953.png)

### DS: 
Support the builders and developers on #wasm-smart-contract channel on Astar Discord
I try to answer to all questions/issues posted in this channel
![image](https://user-images.githubusercontent.com/92046056/230009051-bb8ed6af-3f76-451d-9d9b-0231adb01ea0.png)

### CC: 
French translation of "We just released ink! 4.0!"
https://polkaverse.com/9768/nous-venons-de-sortir-ink-4-0-37857

And promote it via twitter
https://twitter.com/GuiGou12358/status/1638602885482029056
https://twitter.com/AstarNetwork_FR/status/1640379795950141440

### TT: 
I start tutorials to write Smart Contracts in Rust and Ink! 
https://polkaverse.com/11143
First tutorial:
https://polkaverse.com/11143/technical-guide-install-cargo-contract-37738
Second tutorial
https://polkaverse.com/11143/1-an-introduction-to-write-smart-contracts-in-rust-and-ink-37782

And promote it via twitter
https://twitter.com/GuiGou12358/status/1640293032162471937

### EM 1: 
Participate to the weekly call to build smart contract in rust and ink! with french team  
https://twitter.com/GuiGou12358/status/1638596377864282122
![AMA-1](https://user-images.githubusercontent.com/92046056/230013403-96285299-135c-45b7-833b-700c7fb8aaa9.png)
![AMA-2](https://user-images.githubusercontent.com/92046056/230013458-3d738a6b-ff06-4ed8-9a5a-aacdfb2d3f39.png)
![AMA-3](https://user-images.githubusercontent.com/92046056/230013512-fffef653-c310-4fbe-a32b-29e4725b5b12.png)
![AMA-4](https://user-images.githubusercontent.com/92046056/230013606-343ac4b4-e628-4a5a-be48-eb9145d7e5ce.png)

### EM 2: 
Co-organization of an AMA event with the French ambassadors of PhalaNetwork accompanied by @Gunit and @GreatTeacherKez.

During 1h30 of live streaming, we talked about :
Presentation and news of Astar network
Presentation and news of Phala Network
Current collaborations between Astar and Phala (XCM, HRMP, Defi, Phatcontract, dApps, ink!)
Potential new cross-chain dApps between Astar and Phala
Replay: https://www.youtube.com/watch?v=YuZX9xvPB-c

https://twitter.com/GuiGou12358/status/1640476672527925248
https://twitter.com/AstarNetwork_FR/status/1640469179659845633

### DEV:
Continue to build the dApp Lucky - I plan to deploy the dApp on Shiden in April.

**Comment by togamamora** [comment]
Translation is not content creation. So, I am not giving any points. Content creation and creating your own content.
