### ISSUE TITLE
March 2023 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2156]
Telegram Username: @actlee
Discord Username: @Pithecus#9288
SDN Wallet Address: b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM

**Mandatory task**
**CM**

- Communicate with the Korean TG channel
- Share the announcements
![image](https://user-images.githubusercontent.com/90181025/230809438-e8180d51-72e9-4120-8bc5-e290a9a18491.png)

![image](https://user-images.githubusercontent.com/90181025/230809203-20ecea72-7df4-4f4e-9125-8f62e893e6a9.png)
![image](https://user-images.githubusercontent.com/90181025/230809349-7c6e3d56-1ed3-455d-a5dd-d9b2540b8841.png)

- Translate articles into Korean
https://cryptolifebalance.tistory.com/52
![image](https://user-images.githubusercontent.com/90181025/230815197-73cdae75-fc3e-451a-9301-63ae2073c605.png)

https://cryptolifebalance.tistory.com/53
![image](https://user-images.githubusercontent.com/90181025/230817449-011cdcd5-a643-4f38-b148-6cef9b9e35b0.png)

**VSM**
- Monthly impression increased by roughly 11%
![image](https://user-images.githubusercontent.com/90181025/230809995-26a49bfb-5093-4a07-a403-9e5d313eab93.png)
![image](https://user-images.githubusercontent.com/90181025/230810211-e13363f4-023b-4c99-95e7-4be06a99e577.png)
![image](https://user-images.githubusercontent.com/90181025/230810249-88fa160c-ba39-4f54-acbd-64ef920e6436.png)

https://twitter.com/spmlaihm/status/1638828679139565571
https://twitter.com/spmlaihm/status/1638828945842872321
https://twitter.com/spmlaihm/status/1638829645960208385
https://twitter.com/spmlaihm/status/1638830768347664389
https://twitter.com/spmlaihm/status/1638937827714142208
https://twitter.com/spmlaihm/status/1635031767538335745
https://twitter.com/spmlaihm/status/1635031770516324353
https://twitter.com/spmlaihm/status/1635031772923842561
https://twitter.com/spmlaihm/status/1635031775671111680
https://twitter.com/spmlaihm/status/1635031777436917761
https://twitter.com/spmlaihm/status/1634355312764280833
https://twitter.com/spmlaihm/status/1634352685854892033
https://twitter.com/spmlaihm/status/1634131820219359235
https://twitter.com/spmlaihm/status/1632850077738778625
https://twitter.com/spmlaihm/status/1630750067882704896

**TT**
https://cryptolifebalance.tistory.com/48
[아스타] 나노 렛져에서 아스타 지갑 주소 만들기
![image](https://user-images.githubusercontent.com/90181025/230809929-f347cd29-65fd-4b65-8c0b-f5d26e7b5cc0.png)

**Comment by togamamora** [comment]
It would be great to also make pinned announcement translations in your telegram group.
