### ISSUE TITLE
Query regarding Reward for Successful Pull Request Contribution

### ISSUE THREAD

**Issue by MarcoB95-lab** [AstarNetwork/growth-program#2181]
Hey

I am writing to you today regarding a recent contribution I made to the Astar Network project.

Specifically, I made a pull request that has since been successfully merged. However, I noticed that this contribution wasn't included in the UI DAO list. Here is the link to the specific pull request: https://github.com/AstarNetwork/astar-token-api/pull/70

The pull request involved the refactoring of endpoint tags. I implemented Swagger tags within the controller file to enhance our API documentation. This step has resulted in improved categorization and organization of our API endpoints, which should enhance the user experience for developers interacting with our documentation.

Given the successful implementation and the value it adds to our project, I was wondering if I might be eligible for a reward for this contribution? 

Thank you in advance for your consideration.

Kind regards,

Marco

**Comment by togamamora** [comment]
For my own record.

https://github.com/AstarNetwork/astar-token-api/pull/70#issuecomment-1557325952
