### ISSUE TITLE
Activity Report / March - June 2023 - PromoTeam

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#2212]
**Informational support in social networks (twitter/telegram) for Shiden and Astar / March - June 2023**
Providing the info about the Astar/Shiden , in telegram, twitter, medium and other platforms
Here is the link to the list of social network contributions in Google Doc
https://docs.google.com/spreadsheets/d/1XM5hDfW1Gt-KwW20kmZV5pbS_pw9MbwSohWFrZ7LdIs/edit?usp=sharing

**Russian Community Support and Development | March - June 2023**
Russian community Astar / Shiden
Translation of main messages and texts. Translation of core team messages.
https://t.me/astar_rus
Prevention of attacks on community and spam attacks
Community development, invitations.
Translation of core team messages
2 Admins covering all timezones (5 timezones) 7 days a week

**Representing Astar on ETH Belgrade conference May 2023
Representing Astar on Polkadot Day Belgrade June 2023
Representing Astar in Decoded Viewing Party Belgrade 2023** 

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
Do you have any photos & videos of the event in Belgrade?
