### ISSUE TITLE
June 2023 Contribution

### ISSUE THREAD

**Issue by cryptosats** [AstarNetwork/growth-program#2214]
Telegram Username: @christopedia

Discord Username: @cmalize#8352

SDN Wallet Address: Y5iCr5tyia5UwQnjVjSE9nDWJoFtowywG3BSfmsqLzNgy6W

Contributions:

1. **CM - Managed and supported both Local and Main community chat.**
[
![photo_2023-07-03_12-56-32 (2)](https://github.com/AstarNetwork/growth-program/assets/69989414/bf52b986-bb13-4e05-b238-a5a36a67cd94)
![photo_2023-07-03_12-56-32 (3)](https://github.com/AstarNetwork/growth-program/assets/69989414/1428471d-6611-4f63-ac1b-51ce36b72ae7)
![photo_2023-07-03_12-56-32](https://github.com/AstarNetwork/growth-program/assets/69989414/735cbb72-1293-4622-9b5a-1f13c5eaec71)
]

2. **VSM - I Twitted 10 Content About Astar network.**

[https://twitter.com/ChrisMalize3/status/1665834890607075328?t=XmGC4BZEzkuaK3ay7-WDGQ&s=19
https://twitter.com/ChrisMalize3/status/1666400321134788613?t=yJE5IWsOyX-oO1Oxi9tkJA&s=19
https://twitter.com/ChrisMalize3/status/1667057383669989376?t=-S5PsXOCdBqxiNAaLt8ZiQ&s=19
https://twitter.com/ChrisMalize3/status/1668720841012461573?t=Dm-CeNToLHv1-u0Vzj_Z3w&s=19
https://twitter.com/ChrisMalize3/status/1668923515020406785?t=tYxMvVk3klFgMPDEfnZKoQ&s=19
https://twitter.com/ChrisMalize3/status/1669279085527289856?t=dTdw7xLW3TQVMV2kg5rFiA&s=19
https://twitter.com/ChrisMalize3/status/1670004444308680705?t=1hJfbmaGkcxfyd0ZQL9m6g&s=19
https://twitter.com/ChrisMalize3/status/1671035360590045187?t=UPM2Ot0_KkDkIuyCgNn_eg&s=19
https://twitter.com/ChrisMalize3/status/1671457251914137601?t=HamgUlaIWNuYpao9kfLxwA&s=19
https://twitter.com/ChrisMalize3/status/1673290082583822336?t=ZCHbR90SXk1Z0vP63rQ0xA&s=19

]
[
![photo_2023-07-03_13-15-23 (2)](https://github.com/AstarNetwork/growth-program/assets/69989414/a88aa2e0-d71b-4404-bf60-cc18fcdaf0d3)
![photo_2023-07-03_13-15-23 (3)](https://github.com/AstarNetwork/growth-program/assets/69989414/f81d68b8-0a76-4536-9bab-4813ee7df7a1)
![photo_2023-07-03_13-15-23 (4)](https://github.com/AstarNetwork/growth-program/assets/69989414/a434cbb7-b543-43f3-b4cc-ceca77986fdb)
![photo_2023-07-03_13-15-23](https://github.com/AstarNetwork/growth-program/assets/69989414/7282b7bc-6b37-489e-bffd-d4c7a77155bd)
![photo_2023-07-03_13-15-24 (2)](https://github.com/AstarNetwork/growth-program/assets/69989414/01c70ef6-71df-442c-8843-6c375d80962a)
![photo_2023-07-03_13-15-24 (3)](https://github.com/AstarNetwork/growth-program/assets/69989414/4a3bbbfc-0712-4b50-a7d1-dd90c6c305e1)
![photo_2023-07-03_13-15-24](https://github.com/AstarNetwork/growth-program/assets/69989414/25c7580e-6488-4eac-a38e-6d8b89d80dd2)
![photo_2023-07-03_13-15-25 (2)](https://github.com/AstarNetwork/growth-program/assets/69989414/da4a0f1b-11ea-4d84-8582-c34993677171)
![photo_2023-07-03_13-15-25 (3)](https://github.com/AstarNetwork/growth-program/assets/69989414/485df9ff-5eeb-4209-8021-390fe4d51ea1)
![photo_2023-07-03_13-15-25](https://github.com/AstarNetwork/growth-program/assets/69989414/44d8a37d-220b-4349-9f93-83b338c80904)
] 

3. **CC- I wrote three (3) Articles About Astar Network**

https://www.linkedin.com/posts/cmalize_astar-activity-7074715454635749378-usCf?utm_source=share&utm_medium=member_desktop
https://twitter.com/ChrisMalize3/status/1669279085527289856?t=dTdw7xLW3TQVMV2kg5rFiA&s=19
https://www.linkedin.com/posts/cmalize_blockchain-astar-polkadot-activity-7077209407817682944-IImG?utm_source=share&utm_medium=member_desktop
https://twitter.com/ChrisMalize3/status/1673290082583822336?t=ZCHbR90SXk1Z0vP63rQ0xA&s=19
 https://www.linkedin.com/posts/cmalize_astar-defi-blockchain-activity-7079072968357593088-Tekq?utm_source=share&utm_medium=member_desktop

**Comment by togamamora** [comment]
![image](https://github.com/AstarNetwork/growth-program/assets/37278708/12bb3959-cd90-49ab-a42b-5004bed3c6d9)
Is Astar really using this consensus? Please double check.
