### ISSUE TITLE
August 2023 Contribution - Disruptor

### ISSUE THREAD

**Issue by franzeh** [AstarNetwork/growth-program#2261]
Discord Username: Disruptor#3881
Twitter Username: @matosfranze
Telegram Username: @Disruptoor
Medium: https://medium.com/@disruptor.astr
ASTR Wallet: avW1zAw1KyCq2PxDPmxSNSWBNu3Sbw8t716qTmEqCzY85q2

CM - Community Management

CM - Manage and Support Astar Network PT (Telegram) and Astar Network (Discord)

Telegram: https://t.me/astarnetworkPT - 451 members (+7 members) +3%
![b8da16cf-6cc6-485b-a0bb-c3fedf6d563e](https://github.com/AstarNetwork/growth-program/assets/91338802/8a99f582-dc33-4a27-9f56-b429ac28a834)
![b17941a0-11bb-42cc-8034-03876bc567aa](https://github.com/AstarNetwork/growth-program/assets/91338802/09208af9-be03-48f8-bede-91d383a4dfd4)

GOV - Governance & Project Engagement

Gov - https://forum.astar.network/u/disruptor1
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/046a478f-ca0a-4369-b0e3-2780e4bbe2fa)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/3c839e73-ff4a-4e63-8883-c78c4895314b)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/a540ddb3-4fb8-4af0-bea7-a683bccbddc1)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/58a84206-18d8-4905-9767-1071c662dee2)

SM - Social Media Engagement

SM - Twitter @matosfranze – 1031 followers (+157 new members) +15%

![image](https://github.com/AstarNetwork/growth-program/assets/91338802/858fb2f0-81ff-4106-81b5-a3927b17d3f4)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/47ccb590-2d4c-44db-9489-ff21493ef119)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/83ba31bd-7704-4ff3-94d7-9ed9f3d80ee1)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/875feb91-66b6-444b-aeb3-682087f47315)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/cbb4fd4a-eb80-4d44-9d90-1e00aaa2af44)

SM - Twitter @astar_vision – 92 followers (+44 new members) +85% - My newly created profile dedicated to publishing content in Portuguese

![image](https://github.com/AstarNetwork/growth-program/assets/91338802/eb2a1834-cea3-4c71-90aa-3e672f1efd34)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/ef9d3642-68e9-4667-9ff3-ccf2b20ee7cd)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/e652830c-07dc-4783-9191-fe17d81217d1)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/500a0884-efdd-4168-8f01-5fadbcb6befa)
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/a7ea9e8a-c4bb-4887-8125-766137e09243)

SM - https://medium.com/@disruptor.astr

![image](https://github.com/AstarNetwork/growth-program/assets/91338802/384adc1a-155b-4bd0-9d71-dbfb099a70ee)

SM - https://www.linkedin.com/in/franz%C3%A9-matos-29b604261/recent-activity/all/
![image](https://github.com/AstarNetwork/growth-program/assets/91338802/850d45d2-77ec-4c1a-96f5-0366bfc06d9b)

CC - The Content Creator

CC - Medium - Article for The Astar Bulletin- Astar’s Kaizen Spirit: A Journey of Innovation, Discipline and Growth
fusion-of-kaizen-philosophy-and-astar-networks-blockchain-innovation-48ee62b1d30d

CC - Medium - Article for The Astar Bulletin - Astar Network: A Sinfonia do Progresso Impulsionada pela filosofia Kaizen
https://theastarbulletin.news/astar-network-a-sinfonia-do-progresso-impulsionada-pela-filosofia-kaizen-67a24ae4fbd1

**Comment by togamamora** [comment]
In the future, please add the statistic screenshot of the article/content. Like this:
![image](https://github.com/AstarNetwork/growth-program/assets/37278708/845c9472-7ad9-4156-a13d-7187066290f3)
