### ISSUE TITLE
VasaKing Monthly (August 2023) Contribution

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2272]
Telegram Username: @VasaKing
Discord Username: @VasaKing

SDN Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

Contributions:

CM - Manage and support the italian community

VSM - Twitter threads

SuperNova Announcement | https://twitter.com/AstarShidenIta/status/1689185115912470528?s=20 | 09/08/2023 

Astar Games | https://twitter.com/AstarShidenIta/status/1689225599183671296?s=20 | 09/08/2023 

SuperNova | https://twitter.com/AstarShidenIta/status/1689554678076284928?s=20 | 10/08/2023 |   |  

Community call 4 | https://twitter.com/AstarShidenIta/status/1689909525871288320 | 11/08/2023 |   |  

Candy Girl | https://twitter.com/AstarShidenIta/status/1689939719344254976 | 11/08/2023 |   |  

Astar Tokenomics 2.0 | https://twitter.com/AstarShidenIta/status/1690432133238525953 | 12/08/2023 |   |  

Skylabs | https://twitter.com/AstarShidenIta/status/1690708705099034624 | 13/08/2023 |   |  

Interchain Spaces | https://twitter.com/AstarShidenIta/status/1691760576299426036 | 16/08/2023 |   |  

Arthswap V3 | https://twitter.com/AstarShidenIta/status/1691766723794333935 | 16/08/2023 |   |  

Alchemy Astar | https://twitter.com/AstarShidenIta/status/1691814819085631922 | 16/08/2023 |   |  

Astar EVM staking | https://twitter.com/AstarShidenIta/status/1692194289994870923 | 17/08/2023 |   |  

ThirdWeb x Astar | https://twitter.com/AstarShidenIta/status/1692496698600202386 | 18/08/2023 |   |  

Polkasafe | https://twitter.com/AstarShidenIta/status/1692929995079913581 | 19/08/2023 |   |  

Token2049 | https://twitter.com/AstarShidenIta/status/1693192397625139363 | 20/08/2023 |   |  

Sota x Arisa ZKproof | https://twitter.com/AstarShidenIta/status/1693593239251542360 | 21/08/2023 |   |  

Crosschain/multichain | https://twitter.com/AstarShidenIta/status/1693617430868677059 | 21/08/2023 |   |  

Coinfest | https://twitter.com/AstarShidenIta/status/1693639094214226275 | 21/08/2023 |   |  

Polkapals | https://twitter.com/AstarShidenIta/status/1693895789532397845 | 22/08/2023 |   |  

Interoperabilty | https://twitter.com/AstarShidenIta/status/1696821188452811030 | 30/08/2023 |   |  

![Astar August 1](https://github.com/AstarNetwork/growth-program/assets/63927981/1e993ed5-f2df-4192-a3d9-926bbddad83c)

![Astar August 2 ](https://github.com/AstarNetwork/growth-program/assets/63927981/dcfaaa8c-0eed-4771-82a0-3bd54a8d5cdd)

**Comment by togamamora** [comment]
The program has been changed since Aug 2023. Please participate in the GOV task.
https://github.com/AstarNetwork/growth-program/blob/main/Ambassador%20Program.md
