### ISSUE TITLE
Activity Report / August 2023 - Alex PromoTeam

### ISSUE THREAD

**Issue by GlobalSG** [AstarNetwork/growth-program#2273]
Informational support in social networks (twitter/telegram) for Shiden and Astar August 2023

Here is the links to some social network contributions:

https://t.me/ParachainNews/2171- Astar mentioned
https://t.me/ParachainNews/2170 - Astar mentioned
https://t.me/ParachainNews/2167 - Astar Tokenomics 2.0
https://t.me/ParachainNews/2165 - Astar mentioned
https://t.me/ParachainNews/2164 - Astar mentioned

Twitter support retweets from 3 accounts
DotParachains Social Media mentions Retweets - https://twitter.com/DotParachains
PromoTeamPD Social Media mentions Retweets - https://twitter.com/PromoTeamPD
Alex PromoTeam Social Media mentions Retweets - https://twitter.com/Alex_PromoTeam

Russian Community Support and Development | August 2023
Russian community Astar / Shiden
Translation of main messages and texts. Translation of core team messages.
https://t.me/astar_rus
Prevention of attacks on community and spam attacks
Community development, invitations.
Translation of core team messages
2 Admins covering all timezones (5 timezones) 7 days a week

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by togamamora** [comment]
The program has been changed since Aug 2023. Please participate in the GOV task.
https://github.com/AstarNetwork/growth-program/blob/main/Ambassador%20Program.md
