### ISSUE TITLE
August 2022 contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2274]
Telegram Username: @actlee
Discord Username: @Pithecus#9288
SDN Wallet Address: b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM

Mandatory task
**CM**
- Manage the Korean TG and Discord channel
    - some users experienced not able to access the portal , soon fixed, thanks Team! 
    - excited about the new tokenomics and low inflation rate
- Share the announcement into Korean, e.g.,
https://t.me/astar_kr/71906
https://t.me/astar_kr/71959
https://t.me/astar_kr/72111
https://t.me/astar_kr/72354
https://t.me/astar_kr/72435
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ef5b9c91-0e97-4be6-9d4e-af6db3976a7a)
- Telegram channel summary
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/3804400a-4975-4771-8d01-15480cacf4fa)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/3239766a-761f-48bd-b4a3-44e586e4818f)

**VSM**
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/e90554e6-183a-446f-bf21-0a4be8e6c632)

**UI Tester**
- Participated in August with three other all-star members
- Shared two feedback forms
https://docs.google.com/spreadsheets/d/1wVtQ5zMVJYgQaXrQE88lm6zfIqZRu-S-e4fRRGWDGws/edit#gid=1299336498

**Comment by togamamora** [comment]
The program has been changed since Aug 2023. Please participate in the GOV task.
https://github.com/AstarNetwork/growth-program/blob/main/Ambassador%20Program.md

**Comment by crypto-pithecus** [comment]
Forgot to attach it. From the next time, for sure! Thanks.

![image](https://github.com/AstarNetwork/growth-program/assets/90181025/f014ea57-8ee9-4c9c-84fc-36170666d284)
