### ISSUE TITLE
Contribution : Feb 2024

### ISSUE THREAD

**Issue by boomblb** [AstarNetwork/growth-program#2402]
🟩 Feb’24

✔️ Telegram : @boomblb124

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Astar Wallet : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Contributions

1.CM : Manage and support Thai Telegram

✔️ Stats :

![1709306930800](https://github.com/AstarNetwork/growth-program/assets/84943107/03017be2-6768-4128-878e-b67d17eb2ce1)

![1709307002991](https://github.com/AstarNetwork/growth-program/assets/84943107/28308ed8-5213-4341-8ab7-68b0553b14c2)

2.Gov : Governance & Project Management

✔️ Stats :

![1709307099438](https://github.com/AstarNetwork/growth-program/assets/84943107/51c871e9-dd90-4cf0-b9b5-4e20a7a44534)

![1709307149654](https://github.com/AstarNetwork/growth-program/assets/84943107/029f4175-8ea1-46bf-a0e0-6f3f14b8152b)

![1709307197487](https://github.com/AstarNetwork/growth-program/assets/84943107/7f5a9242-0733-46c9-a017-eb5250f2a14f)

![1709307276278](https://github.com/AstarNetwork/growth-program/assets/84943107/8c46baae-2b2f-47c5-b03b-10ce646a6460)

3.SM : Social Media Engagement

3.1 Kokyo NFT : Japan Airlines x beyondClub (How to participate) [Week 2]

🪄 Link : https://facebook.com/story.php?story_fbid=pfbid0gqY9ovg1xBQ9Kw5QAVusMPqwTfwixSjDbBmURfZwfN2FzdX179W4R1jBBHbZsf4cl&id=100028559902371

![1709307365429](https://github.com/AstarNetwork/growth-program/assets/84943107/0d81ca4f-3fbd-402a-b131-20fb2de2e862)

🪄 Link : https://x.com/coinruay124/status/1757551531434627289?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709307610772](https://github.com/AstarNetwork/growth-program/assets/84943107/489b1a31-391f-422c-98fd-b0f6eeaa50d9)

3.2 Kokyo NFT : Japan Airlines x beyondClub (How to participate) [Week 3]

🪄 Link : https://facebook.com/story.php?story_fbid=pfbid0KA6LCQexhp12CenPGA9hsgykn511wkGkwSUiDv7Dzu5nxo1qthP1D85qbAcKYsnJl&id=100028559902371

![1709307664761](https://github.com/AstarNetwork/growth-program/assets/84943107/6b8aac9d-e4df-4733-9103-92f7438c29b2)

🪄 Link : https://x.com/coinruay124/status/1758294673494597865?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709307729140](https://github.com/AstarNetwork/growth-program/assets/84943107/72f7ca4a-60e4-448a-9ad8-f561976b19d9)

3.3 Baseball-themed NFT game app : Deloitte Tohmatsu Group x Astar zkEVM

🪄 Link : https://x.com/coinruay124/status/1759076298088157366?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709307933811](https://github.com/AstarNetwork/growth-program/assets/84943107/af5efc9c-43cf-40cc-ac4c-8c8f4d19356e)

3.4 Partnership : Astar Network x DeSpread

🪄 Link : https://www.facebook.com/100028559902371/posts/pfbid02BhJ4ifDf27wQdL6qPo6AC2vp48gHnUjgEMd75Sc87NiK8ABtrSHLEjM13Pc71u5ol/

![1709307986248](https://github.com/AstarNetwork/growth-program/assets/84943107/915cd794-82c2-4441-9f1f-07dc3e94e2f9)

🪄 Link : https://x.com/coinruay124/status/1760259225354407949?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709308053180](https://github.com/AstarNetwork/growth-program/assets/84943107/aad3aca8-5228-46c3-8686-bf77029e39f1)

3.5 Kokyo NFT : Japan Airlines x beyondClub (How to participate) [Week 4]

🪄 Link : https://www.facebook.com/100028559902371/posts/pfbid037Py5jyu7xh9Knnvkvpj9nozbi7Mp3hVsB1NwhSQG58m43uPKM6Mr4PA3xQ6hDG5el/?

![1709308105334](https://github.com/AstarNetwork/growth-program/assets/84943107/19e1fe3d-b812-463a-ba44-d2b710fd56e1)

🪄 Link : https://x.com/coinruay124/status/1760830236118405394?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709308160755](https://github.com/AstarNetwork/growth-program/assets/84943107/de07744e-5cfb-4436-8a22-aa5f03fbb2ef)

3.6 Startale Labs : Raises $3.5m from UOB Venture Management and Samsung Next 

🪄 Link : https://www.facebook.com/100028559902371/posts/pfbid07pm7SuJVF3VnBQUKHTBbxtBmy2E12LvaUN3buq9nZU2kqKmtwUvqGffprozw9Teil/?

![1709308210489](https://github.com/AstarNetwork/growth-program/assets/84943107/8096b03d-cb01-4511-9de0-4425f5c7cb29)

 🪄 Link : https://x.com/coinruay124/status/1760978069932876227?s=46&t=CvPxBenhP4BATdtUPfmRmw
 
![1709308285494](https://github.com/AstarNetwork/growth-program/assets/84943107/a83df2de-9c3c-4c35-9035-cdf8afff7cf6)

3.7 Astar Network : Others

🪄 Link : https://x.com/coinruay124/status/1761970591421354351?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709308399476](https://github.com/AstarNetwork/growth-program/assets/84943107/b172382a-03ad-4939-b8dc-2ac9faafdb94)

3.8 Astar Network : Protocols

🪄 Link : https://www.facebook.com/100028559902371/posts/pfbid02RwoMq6Xjo9navrHzgYJum4e1i4wrEUxvzMGFxTsdBS5mL5A45sQuHZGB5s5K8uuFl/?

![1709308445287](https://github.com/AstarNetwork/growth-program/assets/84943107/9fb47498-fed9-4947-95ed-17011b25016c)

🪄 Link : https://x.com/coinruay124/status/1762269691136098641?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709308522497](https://github.com/AstarNetwork/growth-program/assets/84943107/4fbc973a-4d91-4155-90b6-353b2649e92f)

4.Content Creation

4.1 Astar Network : Infrastructures

🪄 Link : https://facebook.com/story.php?story_fbid=pfbid02JXAvNvRN3of8umug9mSaZmBqbbsa8tCiBb3AgCBbqdrRuFMj8KoNg7W9Nvk1ZEYQl&id=100028559902371

![1709308633810](https://github.com/AstarNetwork/growth-program/assets/84943107/532fdeee-81bc-4615-84b6-d6f62b3a736d)

🪄 Link : https://x.com/coinruay124/status/1754007545365283264?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709308889728](https://github.com/AstarNetwork/growth-program/assets/84943107/1dc2b9f2-1bbd-4d0e-8629-c9988352047c)

4.2 Kokyo NFT : Japan Airlines x beyondClub (How to participate) [Week 1]

🪄 Link : https://facebook.com/story.php?story_fbid=pfbid0C6zCRdP6o4eyrkgfvZe2wvQSB6AFBKXshzuVfbeKtxcd94BNp2efw7XcF3esS6RHl&id=100028559902371

![1709309150607](https://github.com/AstarNetwork/growth-program/assets/84943107/8a806237-0285-471f-a10e-5814dcf4984b)

🪄 Link : https://x.com/coinruay124/status/1755182959857181016?s=46&t=CvPxBenhP4BATdtUPfmRmw

![1709309219341](https://github.com/AstarNetwork/growth-program/assets/84943107/2d28e035-f5ca-410d-9cea-84fec5122f8e)

If you have any inquiries, please don't hesitate to tell me.

Thanks

Best Regards, 
BooM

**Comment by Gunit2481** [comment]
Thank you for your work Boom!

**Comment by boomblb** [comment]
Thanks Gaius =)
