### ISSUE TITLE
February 2024 Contibution - Leo

### ISSUE THREAD

**Issue by LeoNeurolanche** [AstarNetwork/growth-program#2403]
Hello, I'm Leo. In February, as the Astar Network Turkey team, we were involved in many activities and projects.

First, I will share the content I created from my own account with you, and then I will inform you about the posts we made on the Turkey account. Let's take a look together.

Personal Twitter: https://twitter.com/neurolauncher?s=21&t=ISh07fvjMqpmUg40w5HqBg  Discord: neurolauncher.
 Astar Network Turkey Twitter: https://twitter.com/astarnetworktr_?s=21&t=ISh07fvjMqpmUg40w5HqBg  Astar Network Turkey Telegram: https://t.me/AstarTurkiye  Personal medium: https://medium.com/@enesfaruksahin?source=linkShare-7dc743decc41-1683244333  Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4

First, I will share the Twitter analytics of my own account and the Astar Turkey account with you.

My personal Twitter montly views: 255k view

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/2767075d-02d9-4c57-8285-ac083a0331b9)

**Cm: Community Support**

This month, in addition to actively providing support to the Turkish communityx In addition, I became the active person in the community by sending 164 messages.And also new 252 member.

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/b7f66263-5ce8-4082-85d2-bd65558a76d2)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/e7bd6385-50ae-4ff5-922c-2997ffc682e6)

**GOV - Governance & Project Engagement**

Gov- https://forum.astar.network/u/leo/activity

I participated in all active forum activities in governance this month. Additionally, I made efforts for the Astar ecosystem to be more decentralized.

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/598d6956-b420-43bc-ad69-d4dad1563b95)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/c05dd4f6-be01-4893-9e03-b401130cf41a)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/5377409b-58e2-42a5-ac7d-a89bac466756)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/c2a8adc1-3b13-451e-82cb-e9b9f878b2db)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/7802f784-f738-4ae5-88ec-8e522d619749)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/d56560f5-2e4c-4b84-b2e1-6d3ad9d5e022)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/92b6a521-12f6-413e-9b3f-ea62d43859d8)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/bcd63ff1-4f1f-4e60-8583-efd9e4a3f040)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/5841c2b3-d409-4281-b76a-0f554aeada3e)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/8e0ac0ae-0988-4c4b-8fa1-c449341b3de6)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/4995cf1e-f5b0-4ef3-95e8-f77ea7acd3c1)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/268f3151-a87d-4e5c-a6d2-62022f4c56b5)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/ba585147-b0fa-4726-b77d-35a859ee2668)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/25253915-efd5-4a8f-81c6-c056cfb06dac)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/0d860abd-8778-4148-8a6b-31199078677f)

**SM - SOCIAL MEDIA ENGAGEMENT**

I will share my social media activities on my personal account, and unfortunately I can't share what I posted on the Astar Turkey account because it suspended from twitter.

Tweets about Astar (around 20k views)
Note: I didnt add any related about Neurolanche tweet.

**Personal tweets:**

---------------------
Tweet 1: A Vision Mechanism: Astar Network ZkEvm

After a successful 3-year parachain process on Polkadot, Astar Network plans to announce the Astar ZkEvm soon through collaboration with Polygon.

With the ZkEvm, a significant burning mechanism will be introduced for the ASTR.

(18,395 View, 135 Like, 40 Rt, 11 Comment)

https://x.com/neurolauncher/status/1754854531089756543?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/7b05fae7-3575-4782-844a-d168f7d91d34)

---------------------

Tweet 2: A hybrid infrastructure: Astar Network

When we look at most #Web3 projects, they have various features. These infrastructures is so important for developers.

Today, we will examine why ASTR is valuable by looking at the 3 different infrastructures that 
Astar Network has.

(9904 View, 154 Like, 41 Rt, 22 Comment)

https://x.com/neurolauncher/status/1755188908470489472?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/7c7ab48a-c99d-47c7-a51c-8fb19702a7d7)

---------------------

Tweet 3: Unique use cases of ASTR ~ dApp staking

As blockchain users, many of us have heard of the concept of staking. We have also witnessed the challenges developers face in the Web3 

We will take a closer look at one of Astar Network's most significant strengths, dApp staking!

(20,388 View, 117 Like, 38 Rt, 14 Comment)

https://x.com/neurolauncher/status/1755936655519674808?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/9d98ca31-16bd-4494-945b-fc7e04d64662)

---------------------

Tweet 4: dApp Staking V3 ~ Build & Earn

What innovations are awaiting us with the Astar Network dapp staking version 3 mechanism? A fairer earnings program? 

Higher APY for stakers? A higher burn mechanism for ASTR Token? We will discuss these in the most transparent environment.

(9579 View, 127 Like, 34 Rt, 10 Comment)

https://x.com/neurolauncher/status/1758508429172174956?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/b697f589-585f-47f9-be0d-cdd74218576b)

---------------------

Tweet 5: Astar Network ZkEvm with millions of web3 users! 

Many projects today aim to introduce web2 users to Blockchain technology. 

Today, we will discuss how, with the upcoming Account Abstraction extension on Astar Network, millions of users will start using our ecosystem.

(12,952 View, 140 Like, 42 Rt, 16 Comment)

https://x.com/neurolauncher/status/1759587114289660094?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/e53b4427-84e3-4ecb-899d-bc467b94dec0)

---------------------

Tweet 6: Hi Astar Network family from Italy!

I am starting an educational series with the aim of increasing web3 awareness among users in Turkey and reaching out to a young and significant developer audience for Astar Network.

We will build the future together

(6240 View, 86 Like, 27 Rt, 5 Comment)

**CC- CONTENT CREATION**

Article 1: Published at TAB

The Rise of ASTR to the Top 20 ~ A deflationary infrastructure!

https://theastarbulletin.news/the-rise-of-astr-to-the-top-20-a-deflationary-infrastructure-b06be96c8311

Article 2: Published at TAB

Revolution from Japan ~ Astar Network

https://theastarbulletin.news/revolution-from-japan-astar-network-06b772827778

Video 1: New Dapp Staking Mechanism how affect burning mechanism

https://youtu.be/gYmDLA_XUZM?si=M8WXBfZOo8pwZU1U

Video 2: With Astar ZkEvm, What we will see in Astar Network. 

https://youtu.be/WW5wXT9Jxwo?si=SiTNgVcK8w7wkHyZ

**Comment by Gunit2481** [comment]
Good work Leo!
