### ISSUE TITLE
February 2024 Contribution - VasaKing

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2404]
Telegram : @VasaKing

Discord Username: @VasaKing

ASTR Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

----- CM - Community Support & Management -----

 Support on the Italian Astar Community Telegram 

----- GOV - Forum partecipation -----

https://forum.astar.network/u/vasaking/activity

----- VSM - Astar Italia Twitter -----

Shun at TeamZ https://x.com/Astar_Italia/status/1753008687768068303?s=20

Yoki promo #1 https://x.com/Astar_Italia/status/1753023423666700438?s=20

Italian Youtuber promo https://x.com/Astar_Italia/status/1753024381473661098?s=20

Yoki promo #2 https://x.com/Astar_Italia/status/1753028660003578293?s=20

ETH Cinco De Mayo https://x.com/Astar_Italia/status/1753387281186947522?s=20

dApp Staking v3 Giude https://x.com/Astar_Italia/status/1753761731350806543?s=20

Shiden https://x.com/Astar_Italia/status/1753788007558115576?s=20

Kokyo NFT https://x.com/Astar_Italia/status/1754481545996321200?s=20

Astar Audits https://x.com/Astar_Italia/status/1754510361263325226?s=20

AggLayer https://x.com/Astar_Italia/status/1754542582686785599?s=20

Metasky https://x.com/Astar_Italia/status/1755597006620500294?s=20

Astar dApp v3 https://x.com/Astar_Italia/status/1757353801965507056?s=20

Sota on Chosun Biz https://x.com/Astar_Italia/status/1757776772404293936?s=20

Yoki promo #3 https://x.com/Astar_Italia/status/1758495834625159602?s=20

Yoki promo #4 https://x.com/Astar_Italia/status/1758860369731178945?s=20

Arthswap zkEVM https://x.com/Astar_Italia/status/1759557469091578055?s=20

Aggregation Day https://x.com/Astar_Italia/status/1759559546299666713?s=20

Web3TravelAlliance https://x.com/Astar_Italia/status/1759589467617124387?s=20

zkEVM testnet tutorial https://x.com/Astar_Italia/status/1759607479195869583?s=20

700k ASTR Holders https://x.com/Astar_Italia/status/1760209969297739805?s=20

KokyoNFT twitter space https://x.com/Astar_Italia/status/1760218642447274277?s=20

DEW premint https://x.com/Astar_Italia/status/1760232313428804008?s=20

Rarible on Astar https://x.com/Astar_Italia/status/1760303362031988867?s=20

Bitget Japan https://x.com/Astar_Italia/status/1760575160036245744?s=20

Sota on Build Asia https://x.com/Astar_Italia/status/1762076261415866797?s=20

Grow x Astar https://x.com/Astar_Italia/status/1762439412447621510?s=20

Hikiko x Astar https://x.com/Astar_Italia/status/1762496089679450231?s=20

Yoki promo #5 https://x.com/Astar_Italia/status/1763244921958367510?s=20

Sota on Denver https://x.com/Astar_Italia/status/1763262865027236106?s=20

![Astar February](https://github.com/AstarNetwork/growth-program/assets/63927981/c2f6f5c4-d90d-4ae5-950c-8e90b6826d30)

![Astar February 2](https://github.com/AstarNetwork/growth-program/assets/63927981/20ec28b0-fb67-4846-ac0c-10919763c57b)

----- CC - Medium -----

Astar Dapp staking https://medium.com/@AstarItalia/guida-al-dapp-staking-v3-888a66307c70

AggLayer https://medium.com/@AstarItalia/agglayer-il-layer-per-trasformare-linterazione-tra-le-blockchain-08ffcad7776f

Live on The Crypto Gateaway https://www.youtube.com/watch?v=jZnp2wiV9W8

**Comment by Gunit2481** [comment]
Good job Vasa!
