### ISSUE TITLE
February 2024 Contribution - Marco Da Rocha (Pitcoin)

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#2405]
Discord Username: pitcoin #3857
ASTR/SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

CM - Manage and Support
Astar Network PT (Telegram) and Astar Network (Discord)
Telegram: https://t.me/astarnetworkPT - 513 members (+16 members) +3%
![Screen Shot 2024-03-02 at 10 27 12](https://github.com/AstarNetwork/growth-program/assets/99457582/ef900861-350c-4ee4-ae28-bcb60becdffb)
![Screen Shot 2024-03-02 at 10 27 35](https://github.com/AstarNetwork/growth-program/assets/99457582/0aeac477-61ab-4ea5-9fed-3a518f9b150b)

GOV - Governance & Project Engagement
https://forum.astar.network/u/pitcoin777
![Screen Shot 2024-03-02 at 19 37 46](https://github.com/AstarNetwork/growth-program/assets/99457582/33fb6eeb-f0bb-47cd-871d-09968b71c1a1)
![Screen Shot 2024-03-02 at 19 37 52](https://github.com/AstarNetwork/growth-program/assets/99457582/f6f6dfeb-d9d9-45a8-b755-47fbe2c279db)
![Screen Shot 2024-03-02 at 19 37 57](https://github.com/AstarNetwork/growth-program/assets/99457582/8bf3cadb-0550-451e-bde6-889e2835a15d)
![Screen Shot 2024-03-02 at 19 38 03](https://github.com/AstarNetwork/growth-program/assets/99457582/387fd9a0-ea24-4c38-9919-86f41b45fc14)
![Screen Shot 2024-03-02 at 19 38 10](https://github.com/AstarNetwork/growth-program/assets/99457582/72921a4c-dcde-4c7e-b975-e51ea52d0d69)
![Screen Shot 2024-03-02 at 19 38 17](https://github.com/AstarNetwork/growth-program/assets/99457582/7b868f33-0dae-4c25-8292-894bc349be8f)
![Screen Shot 2024-03-02 at 19 38 23](https://github.com/AstarNetwork/growth-program/assets/99457582/f9d29ebe-86e8-4d13-a9e5-24e7259564e3)

SM - Social Media Engagement
Twitter @Pitcoin_ – 1875 followers (+82 new followers) - 4%
![Screen Shot 2024-03-02 at 19 42 47](https://github.com/AstarNetwork/growth-program/assets/99457582/8e54b6c8-56bb-4b4f-8ee1-1de0690db5c5)
![Screen Shot 2024-03-02 at 19 43 15](https://github.com/AstarNetwork/growth-program/assets/99457582/d890d9d6-6f69-47bd-8885-9cad43141d98)
![Screen Shot 2024-03-02 at 19 43 32](https://github.com/AstarNetwork/growth-program/assets/99457582/08d303c4-93be-4ce4-a1b2-10c35d86d8ae)
![Screen Shot 2024-03-02 at 19 43 49](https://github.com/AstarNetwork/growth-program/assets/99457582/8cdaa75c-fe92-4a8b-89db-71e15e74fa97)
![Screen Shot 2024-03-02 at 19 44 12](https://github.com/AstarNetwork/growth-program/assets/99457582/eaef4dac-054e-4bb7-a28e-c668428f0764)
![Screen Shot 2024-03-02 at 19 44 31](https://github.com/AstarNetwork/growth-program/assets/99457582/fffd6e68-6288-4f18-a2c9-9946b2de04e2)
![Screen Shot 2024-03-02 at 19 44 40](https://github.com/AstarNetwork/growth-program/assets/99457582/079ba6fd-474e-4301-b952-982a625c3f5d)
![Screen Shot 2024-03-02 at 19 44 59](https://github.com/AstarNetwork/growth-program/assets/99457582/37b85a7c-b029-43e3-9de3-8d2e87222d0d)
![Screen Shot 2024-03-02 at 19 45 06](https://github.com/AstarNetwork/growth-program/assets/99457582/6c3403cf-5eb8-4b2d-b161-5985eeaa6112)
![Screen Shot 2024-03-02 at 19 45 24](https://github.com/AstarNetwork/growth-program/assets/99457582/09aae3e5-8c42-4f6d-afc8-14274182fd7f)

Twitter @AstarNetworkBR – 1333 followers (+2 new followers) +1%
![Screen Shot 2024-03-02 at 19 48 25](https://github.com/AstarNetwork/growth-program/assets/99457582/320bb1bd-7a93-4f71-8bd5-12202d8c681e)
![Screen Shot 2024-03-02 at 19 48 35](https://github.com/AstarNetwork/growth-program/assets/99457582/0416bf74-a676-4e6c-9ec0-1a31b92102e0)
![Screen Shot 2024-03-02 at 19 48 54](https://github.com/AstarNetwork/growth-program/assets/99457582/91f50e7a-0322-410b-b4e0-cd70fb00dd6a)
![Screen Shot 2024-03-02 at 19 49 04](https://github.com/AstarNetwork/growth-program/assets/99457582/a2641d27-fa78-4831-afde-1441ae69bc12)
![Screen Shot 2024-03-02 at 19 49 09](https://github.com/AstarNetwork/growth-program/assets/99457582/8e5676fe-12af-4972-964c-64cd8aa34cb2)

Translations:
https://polkaverse.com/6917/astar-zk-evm-ecosystem-vol-1-o-surgimento-do-de-fi-75925
https://polkaverse.com/6917/community-call-lancamento-do-zk-evm-origens-yoki-and-d-app-64215

CC - The Content Creator
Astar Network: February Dump
https://polkaverse.com/6283/astar-network-february-dump-78492
https://polkaverse.com/6917/astar-network-dump-de-fevereiro-78496 (Portuguese)

Astar Network Updates: 46 days in 2024
https://polkaverse.com/6283/astar-network-updates-46-days-in-2024-65234

Others - Yoki Origin Beta test / Report

**Comment by Gunit2481** [comment]
Great work Pitcoin! 👏
