### ISSUE TITLE
February 2024 Contribution - bao

### ISSUE THREAD

**Issue by 0xbao** [AstarNetwork/growth-program#2406]
Telegram Username: @bao1993jp
Discord Username: bao#bao1993
Twitter User name: @bao1993jp
ASTR Wallet Address: beeZfXVZppLCGtZuE4jRZLD9RperjqbfCYrC148Np1uv4pE

# Contributions:

### -Translation of the official blog about dApp Staking v3
DApp Staking v3 Explained (https://note.com/bao1993/n/nfcedcd1f8801)
DApp Staking v3 User Guide (https://note.com/bao1993/n/na5b42ad10f20)
### -Supporting to inquiries from the community almost every day
Astar Network Discord: JAPAN channel
Astar Network Discord: SUPPORT channel **(support to Japanese QA)**
Astar Network Japan Telegram: https://t.me/AstarJapan

## -GOV
I posted **30 times** on the Forum and actively participated in governance.
https://forum.astar.network/u/bao/activity

I also got the "Nice Share" badge on several topics and successfully attracted more people to the Forum.
<img width="1112" alt="スクリーンショット 2024-03-04 9 31 15" src="https://github.com/AstarNetwork/growth-program/assets/123560716/b125e303-00c4-4397-b00a-dee7d4ee1e2d">

![スクリーンショット 2024-03-03 11 48 30](https://github.com/AstarNetwork/growth-program/assets/123560716/6cb0e62a-e81b-485a-8cca-f4f119433ce8)
![スクリーンショット 2024-03-03 11 48 47](https://github.com/AstarNetwork/growth-program/assets/123560716/77485101-bee2-4376-baf8-ecd9a9372bd8)
![スクリーンショット 2024-03-03 11 48 58](https://github.com/AstarNetwork/growth-program/assets/123560716/75a74d05-6321-4550-87cd-3d36d54462e5)
![スクリーンショット 2024-03-03 11 49 14](https://github.com/AstarNetwork/growth-program/assets/123560716/72fb9018-2f6f-467e-b274-2214ca07432f)

## -CC
[1] Astar Weekly Journal Feb.3
EN ver.
https://theastarbulletin.news/launch-of-dapp-staking-v3-53-astar-weekly-journal-1ac2b8c16d6c
JP ver.
https://astarweeklyjournal.substack.com/p/dapp-staking-v3

[2] Astar Weekly Journal Feb.10
EN ver.
https://theastarbulletin.news/idol-project-astar-54-astar-weekly-journal-1ee5289b4bb0
JP ver.
https://astarweeklyjournal.substack.com/p/astar

[3] Astar Weekly Journal Feb.17
EN ver.
https://theastarbulletin.news/dapp-staking-v3-is-live-55-astar-weekly-journal-727ebafe5af7
JP ver.
https://astarweeklyjournal.substack.com/p/dapp-staking-v3-is-live

[4] Astar Weekly Journal Feb.24
EN ver.
https://theastarbulletin.news/defi-on-astar-zkevm-56-astar-weekly-journal-a3b96c0d7108
JP ver.
https://astarweeklyjournal.substack.com/p/defi-on-astar-zkevm
![スクリーンショット 2024-03-03 11 55 13](https://github.com/AstarNetwork/growth-program/assets/123560716/570da8f7-70d7-40b1-9ce7-ddcca8e5f691)
![スクリーンショット 2024-03-03 11 54 36](https://github.com/AstarNetwork/growth-program/assets/123560716/2f81bd74-3887-4722-8136-bc229df28f4b)
### -Key posts that contributed to social media engagement
The post about **"Explanation of DeFi coming to Astar zkEVM"** has garnered **43k impressions.**(https://x.com/bao1993jp/status/1760158279773327731?s=20)
The post about **"How does Bifrost function on Astar zkEVM?"** has garnered **12k impressions.**(https://twitter.com/bao1993jp/status/1761221590703034482)
The post about **"The relationship between Astar and Polygon's AggLayer"** has garnered **6.7k impressions.**(https://twitter.com/bao1993jp/status/1755068362550591850)
![スクリーンショット 2024-03-03 11 58 30](https://github.com/AstarNetwork/growth-program/assets/123560716/9adb4185-87a0-4d6f-bace-6ecda7d599d6)

**Comment by Gunit2481** [comment]
Great work Bao! 👍
