### ISSUE TITLE
February 2024 contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2410]
Telegram Username: `@actlee`
Discord Username: `pithecus.astr` (previously `pithecus#9288`)
ASTR Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

### Mandatory tasks
**CM**
- Manage the Korean TG community & Discord channel
- Share announcements
- Help/respond the community for various topics in general, especially these days for dApp staking v3 and Yoki Origins campaign, often Sony related questions and/or investment related questions
- Respond to the tickets and discussions on Discord
- Active community (+76.5% message MoM, 280+ active users, and 200+ new users MoM)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/5db65dc7-f0ac-4fbf-94bb-7fa1bb07d8bb)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/152ec7d3-e57c-45dc-83ef-43522b70becd)

**GOV**
https://forum.astar.network/u/pithecus/activity
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b494a122-fd41-4978-8a67-572502e830af)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ac1c4c48-6659-4191-be19-962f32935e19)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/a5020ef0-a5ad-448b-93d7-9a21edfaafb5)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/7adc788c-8878-4d28-ab79-8581381a4f7c)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/447ee47f-0959-443b-83a5-0b399bc3f892)

### Optional tasks
**SM**
- Blue mark
- Followers closed to 1.3k
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/4e44580a-03b6-4bf3-856f-493739a26cdd)

https://twitter.com/spmlaihm/status/1763221471252320590
https://twitter.com/spmlaihm/status/1762382454969557093
https://twitter.com/spmlaihm/status/1762138726593896459
https://twitter.com/spmlaihm/status/1760990199784313074
https://twitter.com/spmlaihm/status/1760988356844916788
https://twitter.com/spmlaihm/status/1760988484859314245
https://twitter.com/spmlaihm/status/1760975655200514307
https://twitter.com/spmlaihm/status/1760893258220081457
https://twitter.com/spmlaihm/status/1760890021869941074
https://twitter.com/spmlaihm/status/1760870704629575927
https://twitter.com/spmlaihm/status/1759947425110794297
https://twitter.com/spmlaihm/status/1757358352659583072
https://twitter.com/spmlaihm/status/1757357349495345447
https://twitter.com/spmlaihm/status/1757260211297948036
https://twitter.com/spmlaihm/status/1757260214993101285
https://twitter.com/spmlaihm/status/1757260218440843347
https://twitter.com/spmlaihm/status/1757260221582287266
https://twitter.com/spmlaihm/status/1757260224660988138
https://twitter.com/spmlaihm/status/1757260227135610939
https://twitter.com/spmlaihm/status/1757260230025445729
https://twitter.com/spmlaihm/status/1757260233284444267
https://twitter.com/spmlaihm/status/1757260235389968642
https://twitter.com/spmlaihm/status/1757260237357092924
https://twitter.com/spmlaihm/status/1757260239336870160
https://twitter.com/spmlaihm/status/1757260241362735113
https://twitter.com/spmlaihm/status/1757171561235140841
https://twitter.com/spmlaihm/status/1757026130362556649
https://twitter.com/spmlaihm/status/1756604183661224381
https://twitter.com/spmlaihm/status/1756604185930236351
https://twitter.com/spmlaihm/status/1755414809711976639
https://twitter.com/spmlaihm/status/1754113864432537792
https://twitter.com/spmlaihm/status/1753446960516718992
https://twitter.com/spmlaihm/status/1753084150557347893
https://twitter.com/spmlaihm/status/1753084152679714834
https://twitter.com/spmlaihm/status/1753084154541957322
https://twitter.com/spmlaihm/status/1753039576388526519
https://twitter.com/spmlaihm/status/1752936162937765897

**CC**
- 아스타 네트워크 디앱 스테이킹 V3 — 설명서 (https://medium.com/astar-korea/af606bcd0396) 
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/4e3554b3-2d1a-49bd-b703-ffae04a3068a)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/70629838-8267-41ca-8498-300f3b650127)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b21d1965-63a4-40ae-9073-b2f80bff4df8)

- Yoki Origins Chapters from 1 to 5 integrating the Korean texts into the speech bubbles
- Yoki Origins Chapters 4 and 5 translated into Korean

Chapter 01 (KR) https://twitter.com/AstarNetwork_KR/status/1761929837290410434
Chapter 02 (KR) https://twitter.com/AstarNetwork_KR/status/1762294770754633819
Chapter 03 (KR) https://twitter.com/AstarNetwork_KR/status/1762688829297946675
Chapter 04 (KR) https://twitter.com/AstarNetwork_KR/status/1765227720504758454
Chapter 05 (KR) https://twitter.com/AstarNetwork_KR/status/1765227723499467121

- UI Tester DAO
https://docs.google.com/spreadsheets/d/1wVtQ5zMVJYgQaXrQE88lm6zfIqZRu-S-e4fRRGWDGws/edit#gid=918008994

- Yoki beta test and feedback shared

**Comment by Gunit2481** [comment]
Good work Pithecus! Thank you for your support of the Korean Astar team.
