### ISSUE TITLE
February 2024 Contribution - marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#2411]
Telegram : Soulstar / [https://t.me/marvelet6](https://t.me/marvelet6) (previously Soul Eater)
Discord : marvelet#8647
Native Address : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

___

### CM
**TELEGRAM**
Astar Indonesia
Link : [https://t.me/astarnetwork_id](https://t.me/astarnetwork_id)
Total Members : 240 members (exclude Rose Bot, increased 12 member)
Combot Link : [https://combot.org/c/-1001288040165/a](https://combot.org/c/-1001288040165/a)
Screenshots: :

![tele_ss](https://github.com/AstarNetwork/growth-program/assets/87793956/20ecfac8-292b-452d-86ba-195ab29656a7)

Comments :
- Another very active discussions mostly regarding tech behind L2 also Eth as gas fee.
- Almost all active members were very excited regarding the event.
- For Discord , kindly check my activity there

___

### GOV
**FORUM**
My activity on Astar Forum
[https://forum.astar.network/u/souleater/activity](https://forum.astar.network/u/souleater/activity)
[https://forum.astar.network/u/souleater/summary](https://forum.astar.network/u/souleater/summary)

Screenshot :

![forum_summary](https://github.com/AstarNetwork/growth-program/assets/87793956/12cd3a3c-b35f-48d7-b341-e6dc156d6483)

For Discord, kindly check my activity there

___

### SM
**TWITTER**
Personal : [https://twitter.com/rudayruday](https://twitter.com/rudayruday)
Analytic Screenshot :

![ss_x_personal](https://github.com/AstarNetwork/growth-program/assets/87793956/7059ab31-c94e-41b6-a17e-1ac03faf2a12)

In-depth twitter activity:

[daily_tweet_activity_metrics_rudayruday_20240201_20240301_en.csv](https://github.com/AstarNetwork/growth-program/files/14477052/daily_tweet_activity_metrics_rudayruday_20240201_20240301_en.csv)

===

Astar Indonesia : [https://twitter.com/AstarNetwork_ID](https://twitter.com/AstarNetwork_ID)
Analytic Screenshot :

![ss_x_astrid_rev](https://github.com/AstarNetwork/growth-program/assets/87793956/8e96f9a5-8a63-48df-b732-1544c4417de9)

In-depth twitter activity:
[daily_tweet_activity_metrics_AstarNetwork_ID_20240201_20240301_en.csv](https://github.com/AstarNetwork/growth-program/files/14477158/daily_tweet_activity_metrics_AstarNetwork_ID_20240201_20240301_en.csv)

___

### CC
**The Astar Bulletin**
Writing a monthly article on Astar Bulletin, introductions about Yoki Origins
Title :
A Tale of The Yokai
[https://theastarbulletin.news/a-tale-of-the-yokai-7cd8de161e42](https://theastarbulletin.news/a-tale-of-the-yokai-7cd8de161e42)

**Binance Squared**
Writing a monthly short article to increase Astar exposure on Binance global.
Title:
Everything Astar - Feb 24
[https://www.binance.com/en/feed/post/4310873746386](https://www.binance.com/en/feed/post/4310873746386)

Comment : 
- I dont know what happened or who reshared my Binance Squared, but it got 1k readers, usually it only 100-200ish.

___

That's all my contribution for February 2024. For the points I leave it up to you.

**Comment by Gunit2481** [comment]
Thank for your contribution Rudy!
