### ISSUE TITLE
February 2024 Contribution - Tech. Ambassador: Carlos Rodríguez

### ISSUE THREAD

**Issue by Juminstock** [AstarNetwork/growth-program#2413]
**Technical ambassador information:**

Telegram Username: @Juminstock
Discord Username: @Juminstock#8856
ASTR Wallet Address: ZJKp9fuuQihYopwLEmxZ55zU5WMpeXi95HAPRPUiGcZgZQz

**Contributions:**

**DS - Support developers on Astar Discord:**

<img width="1131" alt="Screenshot 2024-03-04 at 02 48 23" src="https://github.com/AstarNetwork/growth-program/assets/105810861/85814c89-b857-463d-9ec8-6def83d87d4f">
<img width="1131" alt="Screenshot 2024-03-04 at 02 49 04" src="https://github.com/AstarNetwork/growth-program/assets/105810861/85e92840-fd6f-4c67-8806-ce253dd840cb">
<img width="1131" alt="Screenshot 2024-03-04 at 02 49 42" src="https://github.com/AstarNetwork/growth-program/assets/105810861/e975824a-c3a3-4c47-92e3-e06e2962e274">
<img width="1131" alt="Screenshot 2024-03-04 at 02 50 03" src="https://github.com/AstarNetwork/growth-program/assets/105810861/09f05f22-90b3-42cc-993f-14e0c01376cd">
<img width="1131" alt="Screenshot 2024-03-04 at 02 50 49" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a86c953a-895c-419f-a3d7-d7f05488d160">
<img width="1131" alt="Screenshot 2024-03-04 at 02 51 23" src="https://github.com/AstarNetwork/growth-program/assets/105810861/44bf3cff-bb75-461f-b7fd-3089972ca768">
<img width="1131" alt="Screenshot 2024-03-04 at 02 51 47" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a5e67d09-5d34-4adf-9cb4-84c3a91b2330">
<img width="1131" alt="Screenshot 2024-03-04 at 02 52 18" src="https://github.com/AstarNetwork/growth-program/assets/105810861/595454c3-6a66-49fc-9b7c-d2e0bcb2460c">
<img width="1131" alt="Screenshot 2024-03-04 at 02 52 42" src="https://github.com/AstarNetwork/growth-program/assets/105810861/1ad39a71-9fc9-4fa5-ae19-cea15c9f3ae3">
<img width="1131" alt="Screenshot 2024-03-04 at 02 58 15" src="https://github.com/AstarNetwork/growth-program/assets/105810861/ad95408f-049a-4a50-b390-ba607043ca86">
<img width="1131" alt="Screenshot 2024-03-04 at 02 58 38" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3e2fecdd-c661-4a75-b671-9e444c9bee57">
<img width="1131" alt="Screenshot 2024-03-04 at 02 59 23" src="https://github.com/AstarNetwork/growth-program/assets/105810861/0da72e55-1aa6-4f2e-bc01-59699ab62640">
<img width="1131" alt="Screenshot 2024-03-04 at 03 00 43" src="https://github.com/AstarNetwork/growth-program/assets/105810861/f49f5cab-3ebc-47e4-8f9b-e8f169dfdb89">
<img width="1131" alt="Screenshot 2024-03-04 at 03 01 23" src="https://github.com/AstarNetwork/growth-program/assets/105810861/e0d280ed-d663-456e-89d8-e55437b538af">
<img width="1131" alt="Screenshot 2024-03-04 at 03 01 42" src="https://github.com/AstarNetwork/growth-program/assets/105810861/284e0084-8145-4183-a4a3-f84dcd45da2c">
<img width="1131" alt="Screenshot 2024-03-04 at 03 02 22" src="https://github.com/AstarNetwork/growth-program/assets/105810861/8a509733-4ce3-4ac9-948f-a3189b6e7ed9">
<img width="1131" alt="Screenshot 2024-03-04 at 03 02 44" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3e8bd5f0-7da7-445a-b2d7-eaca7afa5168">
<img width="1131" alt="Screenshot 2024-03-04 at 03 03 10" src="https://github.com/AstarNetwork/growth-program/assets/105810861/17c75906-0fc9-468d-9dbc-6e3296f50e99">
<img width="1131" alt="Screenshot 2024-03-04 at 03 03 39" src="https://github.com/AstarNetwork/growth-program/assets/105810861/e77a1248-d435-453c-802c-6a4d19a0753d">
<img width="1131" alt="Screenshot 2024-03-04 at 03 10 19" src="https://github.com/AstarNetwork/growth-program/assets/105810861/044b141d-e4ad-42e2-a3ee-7cb99ac07b45">
<img width="1131" alt="Screenshot 2024-03-04 at 03 10 49" src="https://github.com/AstarNetwork/growth-program/assets/105810861/2c7c26be-c0b6-45df-b971-2e043ef5f8e1">
<img width="1131" alt="Screenshot 2024-03-04 at 03 11 12" src="https://github.com/AstarNetwork/growth-program/assets/105810861/06569b89-9e51-4ab2-a54a-d81f24b96884">
<img width="1131" alt="Screenshot 2024-03-04 at 03 11 36" src="https://github.com/AstarNetwork/growth-program/assets/105810861/0e6cb033-7345-4130-b909-4e492c4c1aa1">
<img width="1131" alt="Screenshot 2024-03-04 at 03 12 02" src="https://github.com/AstarNetwork/growth-program/assets/105810861/adc2fbc5-d749-4f4d-a05f-9b20b12e9211">

**GOV - Engaged in governance discussion:**

- https://forum.astar.network/u/juminstock/activity

**EM - Events managed:**

- Hackathon of ETH Cinco de Mayo: 
https://twitter.com/Juminstock/status/1753114520040423748
https://twitter.com/2020_alby/status/1753500017766105505
https://twitter.com/Another__Dev/status/1753501626470478250
https://twitter.com/Cryptoyonqui/status/1753500288344805678
https://twitter.com/eliandecrypto/status/1753503215872573766
https://twitter.com/nomeencuentro8/status/1753507944308605409
https://twitter.com/0xfchambi/status/1753508283883634781
https://twitter.com/alexrubeola/status/1753834309557858459

- Technical workshop about dApp staking V3 en ETH Cinco de Mayo:
https://twitter.com/ETHCincoDeMayo/status/1753825293385547843
https://twitter.com/casi_audi/status/1763227607649161259

- Space about Polkadot and Astar Network:
https://twitter.com/Polkadotcol/status/1759750541893157042

- Space about Astar network and its dApp staking V3:
https://twitter.com/pepehori/status/1762612955944718558

**CM - Content management:**

- Article about dApp staking V3: https://twitter.com/Juminstock/status/1757183684396925091
- Article about Lucky dApp and Astar: https://twitter.com/AstarBulletin/status/1762405415046754561
- Article about swanky CLI: https://twitter.com/Juminstock/status/1762101728013648015
- Article about new blog post: https://twitter.com/Juminstock/status/1760714160038359275
- Article about Yoki Origins: https://twitter.com/Juminstock/status/1758221728487023083

**Other contributions:**

- New repository with tools for use Astar: https://twitter.com/Juminstock/status/1755995933781741807
- PR accepted by the Ink!devhub team: https://github.com/inkdevhub/swanky-cli/pull/189
- Translation a part of Astar docs into Spanish language:
<img width="1168" alt="Screenshot 2024-03-04 at 03 38 30" src="https://github.com/AstarNetwork/growth-program/assets/105810861/f25a3f71-1702-4b44-aac0-31329b94ece1">
<img width="1168" alt="Screenshot 2024-03-04 at 03 39 26" src="https://github.com/AstarNetwork/growth-program/assets/105810861/eded4b6d-d303-46a5-a97c-791771b5d876">

**Comment by Gunit2481** [comment]
Congratulations Carlos, your work during the month of February was impressive. 👏

**Comment by Juminstock** [comment]
Really thank you, G! Happy to add value to Astar 🫡
