### ISSUE TITLE
February 2024 Contribution - Matt

### ISSUE THREAD

**Issue by Matt3Web** [AstarNetwork/growth-program#2414]
# **February 2024 Contribution - Matt**

Telegram Username: @Matt_Web3
Discord Username: mattweb5go
Twitter Username: @Matt_Web3_
Medium Username: @matt_web3
ASTAR Native Wallet Address: YMFxavc4wzMncNBKr6NkuPwNkp2C78hYhX6kkF7BD4jrhp2

# CM - Community Management
**Astar Network CZ/SK Telegram**: https://t.me/AstarNetwork_CS
**Combot link -** https://combot.org/c/-1001943903354/a

![Snímek obrazovky (965)](https://github.com/AstarNetwork/growth-program/assets/104125423/9bf6667d-c95e-43c0-8424-6b4ff51cf931)
![Snímek obrazovky (966)](https://github.com/AstarNetwork/growth-program/assets/104125423/9bfdabb3-4b62-431a-999b-8b2c69b9d378)

**Astar Network Official Discord:** https://discord.gg/zARxg4ZR
Responding on daily basis in general channel, guide people to tutorials or directly by myself. Also deleting and banning inappropriate content and spam!

# GOV - Governance & Project Engagement
**Astar Forum Engagement:**
**My profile:** https://forum.astar.network/u/matt/activity

![Snímek obrazovky (968)](https://github.com/AstarNetwork/growth-program/assets/104125423/be82b921-64ee-466e-a103-ed5cf9743200)
![Snímek obrazovky (971)](https://github.com/AstarNetwork/growth-program/assets/104125423/6c752aa2-c55f-4e5f-a67f-0a0521ac4887)
![Snímek obrazovky (970)](https://github.com/AstarNetwork/growth-program/assets/104125423/2dfa8eb9-6ecb-4762-973f-dcfd3dbbfba6)
![Snímek obrazovky (967)](https://github.com/AstarNetwork/growth-program/assets/104125423/5df3b357-2c41-46c3-88db-e5b546c4bb56)
![Snímek obrazovky (969)](https://github.com/AstarNetwork/growth-program/assets/104125423/d38cda51-4551-4a72-b081-a00138a5ce3a)

**Discord Unstoppable Grant discussion:**
Participating in Governance and Projects discussion when new project appear. Raise questions, support or refuse their proposals. Here is my Discord Username: mattweb5go

# SM - Social Media Engagement
**Astar Network CZ/SK Twitter:** https://twitter.com/AstarNetwork_CS

![Snímek obrazovky (973)](https://github.com/AstarNetwork/growth-program/assets/104125423/8db90d0e-101d-4fab-bf72-a0236607db93)
![Snímek obrazovky (972)](https://github.com/AstarNetwork/growth-program/assets/104125423/dbf649eb-9646-453c-acf6-3794446e1058)

#

**Personal Twitter:** https://twitter.com/Matt_Web3_
Trying to promote major things especially Astar Network's announcements and forum proposals on daily basis!

![Snímek obrazovky (975)](https://github.com/AstarNetwork/growth-program/assets/104125423/40ead112-9e13-4c46-8aca-6d234ce116f9)
![Snímek obrazovky (976)](https://github.com/AstarNetwork/growth-program/assets/104125423/0eef7b51-0bdf-41b1-8107-d1148bd4bad5)

#

**Astar Bulletin:** https://twitter.com/AstarBulletin 

![Snímek obrazovky (977)](https://github.com/AstarNetwork/growth-program/assets/104125423/64990843-655d-4b04-87bc-0d46e03c4bd0)
![Snímek obrazovky (978)](https://github.com/AstarNetwork/growth-program/assets/104125423/b5909b1f-e0e2-4710-8314-c3d80e8cea46)

#

# CC - Content Creation

**1) Astar Network dApp Staking v3: What You Need to Know in TAB:** 
https://medium.com/the-astar-bulletin-tab/astar-network-dapp-staking-v3-what-you-need-to-know-27e0781540c7

**2) Introducing L2X: The Next-Gen Decentralized Exchange on Astar ZkEVM In TAB:** 
https://medium.com/the-astar-bulletin-tab/introducing-l2x-the-next-gen-decentralized-exchange-on-astar-zkevm-5d78ad21f450

**3) Astar Community Call CZ translation:**
https://docs.google.com/document/d/19w-TvUr5FhK5EoQI9uZXCgqmrQ_wYMx4/edit

That's all for my February contributions, thank you very much!

**Comment by Gunit2481** [comment]
Good job Matt!
