### ISSUE TITLE
February 2024 Contribution - Technical Ambassador: Takeshi

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/growth-program#2415]
Telegram Username: @tksarah0822
Discord Username: tksarah#tksarah
X(Twitter) Username: @tsarah0822 ( TKLab | tklab.astr )
Astar Wallet Address: aZkj2EgiZkUbnKk6XMp9pf9f9SALXSAaTgz17ZEYUaq2UZy

# Core Tasks (Mandatory)
## 1. DEVELOPER SUPPORT
I advised to build the astar node and helped community members asking dev questions on discord (**peers-program**).

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/898142b0-29bd-482d-b7ba-553e04866e75)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b73b7d2c-decc-42d6-9bc8-5916874e9ffc)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/8c8bfde0-0636-4291-bb5c-422606465963)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/58c52126-2227-4de0-b759-ec7b267fbee3)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/5553d910-94a8-4c72-a62d-628585f1a541)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/e1d84061-f677-4939-94f4-2320f5de750f)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/dcaac496-26f5-4499-9441-cf63759c7a5b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/e5db601e-983e-40f6-a22c-7c50ecaeded9)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3ee988ed-5ecd-42db-978a-ca52959aef2f)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/14b65573-7894-4b1d-93a7-b7475197362a)

## 2. GOVERNANCE & PROJECT ENGAGEMENT
_https://forum.astar.network/u/tksarah/activity_

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/aff40d10-3b22-4d35-b9af-ab68ae3e1591)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/f2d7914a-7b3b-4f6b-8488-a8dbbc1be91e)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/a035e5f2-6f86-4ad5-a33e-377a9427209f)

# Optional Tasks (Choose up to 2 tasks/month)

### [1] Contents
Title: **dApp Staking v3 でステーキング**
Published in No+e Feb 17, 2024
https://note.com/tksarahweb3/n/nd6fcdeb027d0
**View: 900 , Like: 10**
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/4a7c2951-7855-4ac4-87a0-92f06a0c39ec)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/774bf52e-4ec1-4e1a-96b8-4b94ce4f496c)

### [2] Contents
Title: **dApp Staking v3 でステーキング(Build&Earn Subperiod)**
Published in No+e Feb 23, 2024
https://note.com/tksarahweb3/n/na0e54e9f67a7
**View: 120 , Like: 3**
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/e5f57134-e355-451b-92d7-18bb0fba8137)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/f11913a4-cc8a-4bad-b0a8-defd55b0fb10)

### [3] Contents
Title: **dApp Staking v3（報酬と請求）**
Published in No+e Feb 28, 2024
https://note.com/tksarahweb3/n/n30ae2c9e39f9
**View: 109 , Like: 3**
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/fb2728ae-dc36-48cd-9d59-d0280bd73e40)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/2f9abb11-5985-4844-8650-eb75f174fb8d)

### [4] Contents
Title: **Vol.1 The Emergence of DeFi**
Published in Medium Feb 23, 2024
https://medium.com/the-astar-bulletin-tab/the-emergence-of-defi-7a6adbea1d25
This is a Japanese translation of the following article.
(https://astar.network/blog/astar-zkevm-ecosystem-vol.-1:-the-emergence-of-defi-72404)

### [5] Contents
Title: **コミュニティコールサマリー Astar zkEVMローンチ/dApp Staking V3/Yoki Origins**
Published in Medium Feb 12, 2024
https://astar.network/ja/blog/astar-zkevmdapp-staking-v3yoki-origins-59535
I translated at the request of the Japanese team.

### [6] Astar Document Translation for Japanese
Use -> dApp-staking -> **for-stakers**
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/d846b9cf-5863-45a0-89cc-767d480ae55f)
(ref: https://github.com/AstarNetwork/astar-docs/pull/619)

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3067e24d-f9fc-4aa8-890c-e81ed2052890)

### Viewer and tool for dApp Staking
Sample View Page: https://agent.sun-t-sarah.work/ (Original https://tksarah.github.io/bc/)

dApp Staking v3 has been released. However, it is not possible to immediately grasp the overall staking amount and ranking trends of dApps on Astar Portal. With the introduction of Period in v3, analyzing past data becomes important for creating future achievements. I have started building and testing for personal use and for Agents.
As I also possess knowledge of statistics, it may be possible to create simple analysis reports from facts in the future. I will try through trial and error.

The technologies and elements I am using are as follows:
- Repository: https://github.com/tksarah/bc
- Languages: Perl, Shell, JavaScript, HTML
- Data: on-chain

I haven't written the README yet, but I will write it later.

## Other, Feedback for testing of Yogi Beta
https://docs.google.com/document/d/14MwJ7ZOX528rPdfzuAbLb8bzYmnDb9M5xgvuCWquyMM/edit?usp=sharing

**Comment by Gunit2481** [comment]
Wonderful work, Takeshi! Thank you so much for your continued support of Astar. 🎉
