### ISSUE TITLE
February 2024 Contribution - Danchoi

### ISSUE THREAD

**Issue by iamdanchoi** [AstarNetwork/growth-program#2416]
Telegram Username: @dan_choi
Discord Username: danchoi
ASTR Wallet Address: bRuaSxsUKcnB7gXt5pvwyAP49ptARTFVfAq9P1H6GeCxibd

Mandatory tasks
[CM]

Manage the Korean TG ( https://t.me/astar_kr )

Optional Tasks
[SM] & [CC] & [EM]

https://t.me/officialunivercityofcrypto/18028
Startale labs raised $7M
3.2k views/ 13 replies / 18 react

https://t.me/officialunivercityofcrypto/18030
Astar Web3 Enter [YOAKE]
2.8k views/ 2 replies / 18 react

https://t.me/officialunivercityofcrypto/18048
I had lunch with Sota (seoul)
6.2k views/ 64 replies / 87 react

https://t.me/officialunivercityofcrypto/18058
Astar zkEVM 1st Edition NFT 
3.6k views/ 14 replies / 22 react

https://t.me/officialunivercityofcrypto/18060
Astar Network에 dApp Stake v3 official launch
3.6k views/ 12 replies / 25 react

https://t.me/officialunivercityofcrypto/18114
Sota's big things coming (twitt)
4k views/ 24 replies / 25 react

https://t.me/officialunivercityofcrypto/18153
Astar raised 3.5M samsung next, UOB.
4.7k views/ 12 replies / 38 react

= All of above I have made 24.7k views. spreaded Astar news and info to korean crypto people.

**Comment by Gunit2481** [comment]
Thank you Dan for your support of Astar.

All the work you've shared here under the optional tasks [SM] & [CC] & [EM] is part of social media management [SM]. 

Content creation (CC) can be articles, blog content, videos, podcasts, art, etc.
Event management (EM) concerns meet-ups, events, conferences or AMA/live/twitter spaces.
