### ISSUE TITLE
February 2024 Contribution 

### ISSUE THREAD

**Issue by PenguPaPa** [AstarNetwork/growth-program#2417]
Telegram Username: @We_Crypto_Together
Discord Username: wecryptotogether
ASTR Wallet Address: WEFVFma2XwsNf3W2k3Z3KbnZDQ1defrvoXFehNyzdDMDFSw

Mandatory tasks
[CM]

Manage the Korean TG ( https://t.me/astar_kr )

Optional Tasks
[SM] & [CC] & [EM]
![image](https://github.com/AstarNetwork/growth-program/assets/106796987/325854c0-7f1d-4e4a-8cd1-ca2d153b9587)

**☑️Astar's StarTale Labs raises $3.5M from Samsung NEXT + UOB Venture Management**
https://x.com/AstarNetwork_KR/status/1760475611544568075?s=20 (5k view)
![image](https://github.com/AstarNetwork/growth-program/assets/106796987/189b0c4e-c1d5-4f5a-a36e-ecedb9cf70e9)

**☑️ What Astar has been up to: **
https://t.me/WeCryptoTogether/35012(5k view)
https://t.me/ROKvsJPN/126 (5.4k)
![image](https://github.com/AstarNetwork/growth-program/assets/106796987/1b311d36-78da-4c21-8ac9-c860dcb15d72)

**☑️Outperfom of ASTAR - JAPAN NARRATIVE**
https://t.me/WeCryptoTogether/35081 (5k view)
https://t.me/ROKvsJPN/127 (5.1k view)

**☑️Japan moves to allow direct investment in crypto and web3 startups: Flow in Astar!**
https://t.me/WeCryptoTogether/35301 (4.7k)
https://t.me/ROKvsJPN/128 (5.7k)

**☑️ Outperfom of Japan Narrative Astar**
https://t.me/WeCryptoTogether/35450(5k)
https://t.me/ROKvsJPN/131(5.2k)

45k views from ma community

**Comment by Gunit2481** [comment]
Hi @PenguPaPa, well done with supporting Astar in your channel. 💪 

I suggest you work on other tasks and participate in our governance system on the Astar Forum to get more points and a better score.
Content creation (CC) can be articles, blog content, videos, podcasts, art, etc.
Event management (EM) concerns meet-ups, events, conferences or AMA/live/twitter spaces.
