### ISSUE TITLE
February 2024 Contribution - Van 

### ISSUE THREAD

**Issue by eudomar500** [AstarNetwork/growth-program#2418]
**Telegram Username:** @DTK21

**Discord Username: Van9719**

**ASTR Wallet Address: WT1qMP9fKyfNc2TtAbpZF4yPN3YDxTvT9YMXCopAfz1urrY**

# Contributions:

# 1. CM - Community Management

### -Combot Link:** https://combot.org/c/1314210486

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e73e52aa-85f9-4b18-b67d-a5840ba79fc1)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/60f06117-7b52-42e6-b496-ef4edc145871)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/4118365f-115c-486f-922d-4940f9796438)

# 2. GOV - Governance & Project Engagement

### -Profile: https://forum.astar.network/u/vangardem/activity

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/cead8979-a2ab-498e-bca1-c1eeecc193aa)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/d6fb7a2b-9f0a-4575-8d77-69b7b9bc7f7f)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/287dca84-c48f-45cf-abf4-10c94e494166)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/09c4bd5d-634b-4ae0-a7b0-1ff3a8a225d1)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/218337d1-5d88-4b86-83a9-393ced00f269)

# 3. SM - Social Media Engagement

### Impressions and post activity:

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/f5abc981-c1e7-4c70-b567-0b6ad9614f28)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/57413fea-eefd-4a3e-a259-5592a4c8529f)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/a8684c25-bd56-4353-97cd-9dc5493c49a7)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/b12f61c0-a3c8-4adf-9573-cf22fdf163bf)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/99d83ae1-040a-46a9-a9a1-8cea48e68bbd)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/f7604a5e-da4e-4ce2-b894-7429f1131468)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/2de24774-48cd-43f0-a870-c2bc5cc4153d)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/a482c59c-4770-4626-9108-6f169beef527)

# 4. Others:

### Link: https://astarweeklynews.substack.com/

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6e25e2bd-e9d7-42c8-8d16-abda1bd85eb3)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/fe54e892-b772-486e-9a19-4a8c08fdf0e2)

# Total Views - February: 407

# Total Users: 208

https://github.com/AstarNetwork/growth-program/assets/39355497/f6d9bcb3-c9b7-445a-b3d5-e9173cddff72

![_96cca17d-ee25-4f16-97d5-382cb90a3a0b](https://github.com/AstarNetwork/growth-program/assets/39355497/419e93f5-0de4-4884-8265-7ffc784f060a)

**Comment by Gunit2481** [comment]
Mucha gracias Van !

**Comment by eudomar500** [comment]
Gracias a tí!!! Gran trabajo!
