### ISSUE TITLE
February 2024 Contribution - defiguy

### ISSUE THREAD

**Issue by astardefi** [AstarNetwork/growth-program#2419]
February 2024 Contribution - defiguy
Telegram Username: @defiguy2022
Discord Username: defiguy#1725
Twitter User name: defiguy22
ASTR Wallet Address: YJ9ZyKwzX6tLh21eV1YT61EpihraYAdJYbcpyJFDwdyrfi7

# CM
## Astar Network (BR) Telegram
![marco-2024](https://github.com/AstarNetwork/growth-program/assets/104277195/118e74af-9193-4869-8447-6ddff9bd2f1c)
![marco-2024-2](https://github.com/AstarNetwork/growth-program/assets/104277195/d26d3ddd-b373-4abe-8739-ed9a77076c3a)

# GOV
![Screenshot 2024-03-05 at 20 17 04](https://github.com/AstarNetwork/growth-program/assets/104277195/15e78565-d648-42e8-aa52-6bd355e6c11a)
https://forum.astar.network/u/defiguy/activity

# SM 
## Twitter Activity
![Screenshot 2024-03-05 at 21 03 38](https://github.com/AstarNetwork/growth-program/assets/104277195/66cc1837-4bc3-4940-bd4f-9f56707dfe9d)

## defiguy Telegram group - increase of 70% in members (215 members)
Link - https://t.me/+QfslDL_epwZlMmUx
![Screenshot 2024-03-06 at 14 35 55](https://github.com/AstarNetwork/growth-program/assets/104277195/52e7d912-248b-43ad-97a0-aa62061a1374)

# BD
Starting the conversation with Francisco Carvalho (Founder of Blockchain RIO - biggest crypto event in LATAM)
Info Blokchain RIO - https://blockchainfestival.io/
![Screenshot 2024-03-05 at 21 05 13](https://github.com/AstarNetwork/growth-program/assets/104277195/ceb4bd66-6ad1-49aa-9ff5-a9d781161442)

# CC/ART
## 1 MONTH data from 1 FEB - 29FEB 
![Screenshot 2024-03-06 at 14 32 48](https://github.com/AstarNetwork/growth-program/assets/104277195/ae254fab-c3df-456d-a41c-67b745feb2a4)

![Astar updates (54)](https://github.com/AstarNetwork/growth-program/assets/104277195/a3b137bf-0843-4a08-bb68-b28ef421bd17)

Link - https://youtube.com/live/QCApaKH_81s - **OPORTUNIDADE de AIRDROPS? INVESTIDORES chegando FORTE EM DAPPS DA ASTAR!!!** 

![Astar updates (55)](https://github.com/AstarNetwork/growth-program/assets/104277195/becc0d17-bab4-4755-89c7-8bef1d8ed3a6)

Link https://youtube.com/live/DhOSCJsI80U - **ASTAR DAPP STAKING V3 e parceria com DELOITTE e JAPAN AIRLINES**

![Astar updates (56)](https://github.com/AstarNetwork/growth-program/assets/104277195/f944c9fe-8826-4fbd-b9dd-88e05f9b5672)

Link - https://youtube.com/live/zpxl52Hiils 

![Astar updates (57)](https://github.com/AstarNetwork/growth-program/assets/104277195/222ea36a-001d-4a39-97fd-cd36356e2ac9)
 Link - https://youtube.com/live/94wTcXkRgM0 - **ASTAR zkEVM está CHEGANDO! ETHER.FI e vários projetos CONFIRMADOS!!**

**Comment by Gunit2481** [comment]
Bom trabalho gustavo!
