### ISSUE TITLE
February 2024 contribution - Earl

### ISSUE THREAD

**Issue by Earlcho** [AstarNetwork/growth-program#2421]
Telegram Username: @Earl_Senor
Discord Username: Earl_Senor
ASTR Wallet Address: X7zVHUVANKthHfqHuiJnXa7ZZibWRfxKWo361MfTtHD66aF

### Mandatory tasks
**CM**

- Manage the Korean TG ( https://t.me/astar_kr )

- Publish official announcements in Korean across Korean channels (TG, Discord, Twitter)

Telegram Announcement Lists
https://t.me/astar_krann/158													
https://t.me/astar_krann/166													
https://t.me/astar_krann/167													
https://t.me/astar_krann/168													
https://t.me/astar_krann/170													
https://t.me/astar_krann/171													
https://t.me/astar_krann/173													
https://t.me/astar_krann/176													
https://t.me/astar_krann/177													
https://t.me/astar_krann/179													
https://t.me/astar_krann/180													
https://t.me/astar_krann/181													
https://t.me/astar_krann/182													
https://t.me/astar_krann/186													
https://t.me/astar_krann/188													
https://t.me/astar_krann/189													
https://t.me/astar_krann/191													
https://t.me/astar_krann/193													
https://t.me/astar_krann/195													
https://t.me/astar_krann/196													
https://t.me/astar_krann/198													
https://t.me/astar_krann/199													
https://t.me/astar_krann/200													
https://t.me/astar_krann/202													
https://t.me/astar_krann/206													
https://t.me/astar_krann/207													
https://t.me/astar_krann/211													
https://t.me/astar_krann/212													
https://t.me/astar_krann/216		

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/cacd8e95-0e13-4b25-af96-e2a3a8178dac)											

The same content are being also announced on the Discord Korea channel.

Twitter Announcement
https://x.com/AstarNetwork_KR/status/1753028305857720487?s=20
https://x.com/AstarNetwork_KR/status/1753252542736458024?s=20
https://x.com/AstarNetwork_KR/status/1754131403472855136?s=20
https://x.com/AstarNetwork_KR/status/1754328869514146277?s=20
https://x.com/AstarNetwork_KR/status/1754350071993561128?s=20
https://x.com/AstarNetwork_KR/status/1754459473400459732?s=20
https://x.com/AstarNetwork_KR/status/1754853007962022222?s=20
https://x.com/AstarNetwork_KR/status/1755047064273387904?s=20
https://x.com/AstarNetwork_KR/status/1755127398566412755?s=20
https://x.com/AstarNetwork_KR/status/1755805538531897581?s=20
https://x.com/AstarNetwork_KR/status/1756245017159668212?s=20
https://x.com/AstarNetwork_KR/status/1756922293639598397?s=20
https://x.com/AstarNetwork_KR/status/1757008646146585063?s=20
https://x.com/AstarNetwork_KR/status/1757247067846807555?s=20
https://x.com/AstarNetwork_KR/status/1757337542209540230?s=20
https://x.com/AstarNetwork_KR/status/1757393228482117745?s=20
https://x.com/AstarNetwork_KR/status/1757950838268641570?s=20
https://x.com/AstarNetwork_KR/status/1758070272488525852?s=20
https://x.com/AstarNetwork_KR/status/1759774214461284557?s=20
https://x.com/AstarNetwork_KR/status/1760119284460851593?s=20
https://x.com/AstarNetwork_KR/status/1760128494888239165?s=20
https://x.com/AstarNetwork_KR/status/1760475611544568075?s=20
https://x.com/AstarNetwork_KR/status/1760640483670589849?s=20
https://x.com/AstarNetwork_KR/status/1760872973697950014?s=20
https://x.com/AstarNetwork_KR/status/1761929837290410434?s=20
https://x.com/AstarNetwork_KR/status/1761998289514488137?s=20
https://x.com/AstarNetwork_KR/status/1762294770754633819?s=20
https://x.com/AstarNetwork_KR/status/1762688829297946675?s=20
https://x.com/AstarNetwork_KR/status/1763065958279868432?s=20

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/fa27ab43-b409-474a-bba8-10a4b4975e8f)

**GOV**
https://forum.astar.network/u/earl/activity
![image](https://github.com/AstarNetwork/growth-program/assets/108060432/5764014f-2d2c-4c9d-9cdd-b85ac493e946)
![image](https://github.com/AstarNetwork/growth-program/assets/108060432/bc3fe989-efe5-42bf-a26f-256ba4a296f5)

### Optional tasks
**SM**
![image](https://github.com/AstarNetwork/growth-program/assets/108060432/87e8f7e3-b5ad-4732-8dde-2ecb862033ac)

https://x.com/Earl_Senor/status/1753091522516631684?s=20																
https://x.com/Earl_Senor/status/1755190473604686333?s=20																
https://x.com/Earl_Senor/status/1758436808403419320?s=20																
https://x.com/Earl_Senor/status/1763147548548870170?s=20																

**CC**

**Astar 2.0 Summit Summary by Crypto Times**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-2-0-%EC%84%9C%EB%B0%8B-%EB%8F%84%EC%BF%84%EC%97%90%EC%84%9C-%EA%B0%9C%EC%B5%9C-%E6%97%A5-%EB%A7%A4%EC%B2%B4-%ED%81%AC%EB%A6%BD%ED%86%A0%ED%83%80%EC%9E%84%EC%A6%88-%EB%B3%B4%EB%8F%84-97d32eed5e42													
Naver Blog: https://blog.naver.com/astarkr/223341881006

**Yoake**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-zkevm-%EC%A3%BC%EB%8F%84%EC%9D%98-%EC%9B%B93-%EC%97%94%ED%84%B0%ED%85%8C%EC%9D%B8%EB%A8%BC%ED%8A%B8-%EC%82%B0%EC%97%85-yoake-59c0646c30e8
Naver Blog: https://blog.naver.com/astarkr/223347163146

**Deloitte**
Medium Blog: https://medium.com/astar-korea/%EB%94%9C%EB%A1%9C%EC%9D%B4%ED%8A%B8-deloitte-%ED%86%A0%EB%A7%88%EC%B8%A0-%EA%B7%B8%EB%A3%B9-%EC%95%84%EC%8A%A4%ED%83%80-zkevm%EC%9C%BC%EB%A1%9C-%EC%8A%A4%ED%8F%AC%EC%B8%A0-%EC%82%B0%EC%97%85-%EB%B3%80%ED%98%81-18e4ee21a1b9
Naver Blog: https://blog.naver.com/astarkr/223351893700

**Community Call**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-24-02-12-%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0-%EC%BD%9C-%EA%B5%AD%EB%AC%B8-%EC%9A%94%EC%95%BD%EB%B3%B8-8c01c870ac8a
Naver Blog: https://blog.naver.com/astarkr/223352066358

**dApp Staking V3 Guide**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EB%94%94%EC%95%B1-%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%82%B9-v3-%EC%82%AC%EC%9A%A9%EC%9E%90-%EA%B0%80%EC%9D%B4%EB%93%9C-547800a0714ff
Naver Blog: https://blog.naver.com/astarkr/223355715820

**Samsung NEXT & UOB Ventures Extended Seed Round**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%ED%95%B5%EC%8B%AC-%EA%B0%9C%EB%B0%9C%EC%82%AC-%EC%8A%A4%ED%83%80%ED%85%8C%EC%9D%BC-%EB%9E%A9%EC%8A%A4-%EC%82%BC%EC%84%B1%EB%84%A5%EC%8A%A4%ED%8A%B8-uob-%EB%B2%A4%EC%B2%98-%EB%A7%A4%EB%8B%88%EC%A7%80%EB%A8%BC%ED%8A%B8%EB%A1%9C%EB%B6%80%ED%84%B0-350%EB%A7%8C%EB%8B%AC%EB%9F%AC-%ED%88%AC%EC%9E%90-%EC%9C%A0%EC%B9%98-da2d373b8df2
Naver Blog: https://blog.naver.com/astarkr/223362696267

**Packs**
Medium Blog: https://medium.com/astar-korea/packs-%EC%95%84%EC%8A%A4%ED%83%80-zkevm-%EC%9C%84%EC%97%90%EC%84%9C-%ED%8A%B8%EB%A0%88%EC%9D%B4%EB%94%A9-%EC%B9%B4%EB%93%9C-%EA%B2%BD%ED%97%98%EC%97%90-%ED%98%81%EC%8B%A0%EC%9D%84-%EA%B0%80%EC%A0%B8%EC%98%A4%EB%8B%A4-a90bddf134b1
Naver Blog: https://blog.naver.com/astarkr/223362700875

**Astar DeFi**
Medium Blog: https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-zkevm-%EC%83%9D%ED%83%9C%EA%B3%84-%EC%8B%9C%EB%A6%AC%EC%A6%88-vol-1-defi-a2e837cdaf37
Naver Blog: https://blog.naver.com/astarkr/223366705470

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/35b8cdc0-7345-4e66-9305-704dadbddfb3)

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/9f8ac692-a062-4533-aa6f-d36a55f3e700)

The image below shows the total number of views for Astar Korea Naver Blog content in FEB.

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/75a44520-2c82-49f0-aa49-d56759067854)

**Comment by Gunit2481** [comment]
Thank for your great work Earl!
