### ISSUE TITLE
February 2024 contribution - Max.eth

### ISSUE THREAD

**Issue by MaxEthHealthy** [AstarNetwork/growth-program#2422]
Telegram Username: @max_eth_heatlhy
Discord Username: max.eth.healthy
X User name: @max_eth_heatlhy
ASTR Wallet Address: WAgeWZSPzQdJf58kELDGBp2P8VRCNFie9s3j7fgvpJduNMX

-----
**CM**

Telegram: Gaius is very active and more suited to answer the technical questions that are asked than me... But I will try to be more present.

Discord: I will be more present too.

DMs with people to answer their questions and defend Astar:
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/64603ef7-161b-4597-9c36-c3b1824ac1cf)
<img width="404" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/ae31edb8-8903-4fd6-b8c2-aa77c8ce6500">
<img width="500" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/8a83dd94-62a1-4d4b-ba46-5c76de23d581">
<img width="582" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/bce9b3bd-537f-4c1d-9ada-35d1299ef56f">

**GOV**

**Forum**

https://forum.astar.network/u/max.eth/activity
https://forum.astar.network/u/max.eth/summary

<img width="1009" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/61a0dafa-baec-4516-8e62-d9c021e35507">

**Community call**
I actively participated and asked questions.
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/a62cb199-e299-4e55-996e-9ccb045b7ecd)
https://x.com/max_eth_healthy/status/1758132037486264525?s=20

**Yoki campaign**:
I tested the campaign and wrote my feedback with screenshots on the shared G doc.

**SM**

That's where I'm most active.

**Analytics**

<img width="562" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/0e5a99b3-1911-4390-bc83-d8095bca8dc0">
<img width="1213" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/a687aced-0019-4c24-974e-a83802816ecf">

**Sample of tweets:**

https://x.com/max_eth_healthy/status/1759599349560959357?s=20
<img width="867" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/f0806c16-6774-4fc6-ac5c-f05007da1622">
<img width="900" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/a0660b8c-8699-40d6-b2d1-db345b2d07cb">
<img width="886" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/dac03d3f-fc29-45b1-afcc-279fca71bd53">
<img width="869" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/456ad097-cba0-4d4f-8be1-7e58d7787c38">
<img width="906" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/35e37925-6e59-4ca8-8189-0fde392696b5">
<img width="863" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/28b35193-69b0-4b39-be6f-aaddba1a9118">

**CC**

**zkEVM ecosystem map:** I created the zkEVM ecosystem map under the direction of Gaius. I used a trial version of Adobe Creator (I spent a lot of hours on it!)

![telegram-cloud-photo-size-4-5971953129903735276-y](https://github.com/AstarNetwork/growth-program/assets/157904479/56e90bee-2d13-467e-b538-b4b749239b7e)

- **Instagram** where I post stories of my tweet and othe contents: https://www.instagram.com/max_eth_/

- **Blog article**: 

**Dapp staking V3**:
Medium: https://medium.com/@max.eth/astar-easy-guides-dapps-staking-v3-the-app-store-of-web-3-f52b6ae60055
Bonzai: https://www.bonzai.pro/maxeth/posts/vokB_6535/astar-easy-guides-dapps-staking-v3-the-app-store-of-web-3

**Community call**
Bonzai: https://www.bonzai.pro/maxeth/posts/DYbR_6540/astar-february-community-call-main-points
medium https://medium.com/@max.eth/astar-february-community-call-main-points-bee5c8a94862

**Zealy event**
https://x.com/max_eth_healthy/status/1755952942220181729?s=20

**Translation in French of the recap of community call**
https://docs.google.com/document/d/1N1nkqfGbFWr61brZhTG8dQ47qaXGwdu94an_DSX7e_U/edit

**EV**

**NFT Factory event**: I went to events at NFT factory which is an important Web3 center in Paris. I talk about astar and represent it to the speakers and other people.

**NFT Paris**: I represented Astar Network at the biggest Web3 event of Europe.
I introduce myself and Astar to various projects and KOL.
I schedule meetings with 2 Medias where the connection is made for present or future communication. The medias are the Big whale: I met with the CEO. I also met with cointribune and cointelegraph.
Connected with Caspr Network for eventual future partnerships. The director of Dev will come back to me on TG.

![image](https://github.com/AstarNetwork/growth-program/assets/157904479/273123ba-86b7-413a-ac98-962f8e8096bb)

https://x.com/max_eth_healthy/status/1761760463925211435?s=20

**Comment by Gunit2481** [comment]
Hey Max! Great job on your first months as an agent. You should participate more in our forum and share your opinion to help shape the Astar ecosystem. 

For the next report, please add screenshots and statistics for your Telegram and Discord support. You can use this report as an example. 

PS: Thanks for your help with the ecosystem map. 💪

**Comment by MaxEthHealthy** [comment]
Salut Gaius bien reçu !

Merci pour le retour et d'avoir driver l'écosystème map
