### ISSUE TITLE
March 2024 Contribution - GuiGou

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/growth-program#2424]
Telegram Username: @GuiGou12358
Discord Username: GuiGou#1021
Twitter Username: @GuiGou12358
Native Wallet Address: 5DaCixaPPaYrdGdSxP6Mwptn7dPNp3DTeJCQKuCUQe5jp6fL

## DS
Support for builders and developers in Astar Discord
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/86a41de6-897b-4aab-b8d0-d95044b7255e)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/3564faef-e64c-413e-bcfc-10f5ef1508df)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/620e9d82-5b37-42fa-a61b-fbd860541358)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/07d6e876-89c1-440f-8738-6612dabd00e4)

## Community
Support for the community in the local Telegram channel
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/4c37bd22-d3df-4c1f-af02-94b864190669)

## GOV - Governance & Project Engagement
Activity on the forum: https://forum.astar.network/u/guigou/activity

Here is the summary
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/0e51f6af-0b57-4d86-97c6-053d13797419)

Here are the activities
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/fe7390a3-1117-49e5-a860-879d05ed9473)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/1e34fe13-c932-41e5-a939-6bef9650d350)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/f656e435-b438-46b7-9508-7bc7839d83e8)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/acab70c7-abab-476e-9002-b08840689ab6)

## BUILD
Here the proof of work: https://github.com/GuiGou12358 
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/cd6190c7-dd63-46b5-b444-4dcfd4e64e08)

## OTHER - PINK 

- Poposals in the forum:
https://forum.astar.network/t/how-to-share-pink-received-on-astar-network/6167
https://forum.astar.network/t/how-to-share-pink-received-on-astar-network-revised-version/6519

- PR in the Astar Apps to register the asset and manage XCM transfer with non sufficient asset.
https://github.com/AstarNetwork/astar-apps/pull/1127

- Multisig member

- Snapshot preparation  for the airdrop

Have a nice day G'

**Comment by Gunit2481** [comment]
Great work GuiGou and thanks for the help with PINK! 💪
