### ISSUE TITLE
March 2024 Contribution - Tech. Ambassador: Carlos Rodríguez

### ISSUE THREAD

**Issue by Juminstock** [AstarNetwork/growth-program#2426]
_Technical ambassador information:_

Telegram Username: **@Juminstock**
Discord Username: **@Juminstock#8856**
ASTR Wallet Address: **ZJKp9fuuQihYopwLEmxZ55zU5WMpeXi95HAPRPUiGcZgZQz**

**Contributions:**

**DS - Support developers on Astar Discord:**

<img width="1118" alt="Screenshot 2024-04-01 at 07 48 13" src="https://github.com/AstarNetwork/growth-program/assets/105810861/513fceb5-ea8b-4a85-be4b-e8678ce60408">
<img width="1118" alt="Screenshot 2024-04-01 at 07 51 35" src="https://github.com/AstarNetwork/growth-program/assets/105810861/013e60da-e0d6-468a-82d7-c50cfc0fdecf">
<img width="1118" alt="Screenshot 2024-04-01 at 07 52 12" src="https://github.com/AstarNetwork/growth-program/assets/105810861/804bfc13-2308-43a4-988b-0c6781c7dc88">
<img width="1120" alt="Screenshot 2024-04-01 at 07 52 48" src="https://github.com/AstarNetwork/growth-program/assets/105810861/eb79a55d-b323-4409-9632-288059703786">
<img width="1120" alt="Screenshot 2024-04-01 at 07 53 07" src="https://github.com/AstarNetwork/growth-program/assets/105810861/466d7fc1-b8f8-4823-995e-9dbdfbd31b87">
<img width="1120" alt="Screenshot 2024-04-01 at 07 54 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/f4350790-3a7f-4cf5-bba0-7363d3dfed59">
<img width="1120" alt="Screenshot 2024-04-01 at 07 54 27" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a65ae783-f7e7-4379-aed0-329ecaf3f8f3">
<img width="1120" alt="Screenshot 2024-04-01 at 07 54 47" src="https://github.com/AstarNetwork/growth-program/assets/105810861/cb3404b9-5552-4a9c-b840-b0b7099a251f">
<img width="1120" alt="Screenshot 2024-04-01 at 07 55 02" src="https://github.com/AstarNetwork/growth-program/assets/105810861/b9a546d4-0108-496c-b785-cc2908c07f07">
<img width="1120" alt="Screenshot 2024-04-01 at 07 55 32" src="https://github.com/AstarNetwork/growth-program/assets/105810861/1e09d229-3d37-4512-95fb-4a1dcea0968f">
<img width="1120" alt="Screenshot 2024-04-01 at 07 56 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/8cf676e6-ca33-4247-b246-7ca790ee4744">
<img width="1120" alt="Screenshot 2024-04-01 at 07 56 22" src="https://github.com/AstarNetwork/growth-program/assets/105810861/19fff683-cf63-4c85-a4a4-c19585e33962">
<img width="1120" alt="Screenshot 2024-04-01 at 07 56 52" src="https://github.com/AstarNetwork/growth-program/assets/105810861/29d68727-9d7c-435e-8cc7-3fbba8bc26c3">
<img width="1120" alt="Screenshot 2024-04-01 at 07 57 03" src="https://github.com/AstarNetwork/growth-program/assets/105810861/706c07d2-0f50-41fb-9561-835e4829a692">
<img width="1120" alt="Screenshot 2024-04-01 at 07 57 21" src="https://github.com/AstarNetwork/growth-program/assets/105810861/d10c2a58-2399-49d8-8ac7-4c8035768ddd">

**GOV - Engaged in governance discussion:**

- https://forum.astar.network/u/juminstock/activity

**EM - Events managed:**

- Space about ETHDenver and Astar participation with Sota: https://x.com/Bra_CriptoPT/status/1764674195198243134?s=20

**CM - Content management:**

- Article about ecosystem updates on Medium: https://x.com/Juminstock/status/1764621824040513739?s=20
- Support to other members to create content: https://x.com/casi_audi/status/1764695217175715896?s=20
- DApp staking V3 article support by Astar bulletin: https://x.com/AstarBulletin/status/1765074799997436002?s=20
- Astar zkEVM article on Medium support by Astar bulletin: https://theastarbulletin.news/astar-zkevm-is-live-143ad4b3fa09
- Post on Twitter about Astar zkEVM article: https://x.com/Juminstock/status/1765765676164141081?s=20
- Thread about Yoki Origins launch on Twitter: https://x.com/Juminstock/status/1767210226388787362?s=20
- Thread explain how to participate in Yoki Origins campaign: https://x.com/Juminstock/status/1768018900405363076?s=20
- Article about Astar projects and communities: https://x.com/Juminstock/status/1772348237162094988?s=20
- Article support by Astar bulletin: https://x.com/AstarBulletin/status/1772544420761464897?s=20
- Astar testnet incentivized article: https://x.com/Juminstock/status/1773362299815833852?s=20

**Other contributions:**

- Spanish translation of the Astar doc: https://github.com/AstarNetwork/astar-docs/pull/651
- Support to projects built on Astar zkEVM: https://forum.astar.network/t/rollalove-dating-web3-application/6478?u=juminstock
- Support to projects built on Astar zkEVM: https://forum.astar.network/t/swapay-crosschain-transafers-ucg-aplication/6479?u=juminstock
- My monthly contributions to Astar docs:

<img width="1176" alt="Screenshot 2024-04-01 at 08 25 28" src="https://github.com/AstarNetwork/growth-program/assets/105810861/0e30a4dc-559b-41fd-9b1e-b385b5435724">

**Comment by Gunit2481** [comment]
Thank you Carlos!
