### ISSUE TITLE
March 2024 Contribution - Matt

### ISSUE THREAD

**Issue by Matt3Web** [AstarNetwork/growth-program#2429]
# **March2024 Contribution - Matt**

Telegram Username: @Matt_Web3
Discord Username: mattweb5go
Twitter Username: @Matt_Web3_
Medium Username: @matt_web3
ASTAR Native Wallet Address: YMFxavc4wzMncNBKr6NkuPwNkp2C78hYhX6kkF7BD4jrhp2

# CM - Community Management
**Astar Network CZ/SK Telegram**: https://t.me/AstarNetwork_CS
**Combot link -** https://combot.org/c/-1001943903354/a

![Snímek obrazovky (992)](https://github.com/AstarNetwork/growth-program/assets/104125423/1379272e-569d-4f19-a6fd-dbcf6348f9bf)
![Snímek obrazovky (993)](https://github.com/AstarNetwork/growth-program/assets/104125423/2eed1ea1-8ece-42a7-aad8-54cb96ee5a82)

**Astar Network Official Discord:** https://discord.gg/zARxg4ZR
Responding on daily basis in general channel, guide people to tutorials or directly by myself. Also deleting and banning inappropriate content and spam!

# GOV - Governance & Project Engagement
**Astar Forum Engagement:**
**My profile:** https://forum.astar.network/u/matt/activity

![Snímek obrazovky (994)](https://github.com/AstarNetwork/growth-program/assets/104125423/81f93ad4-72bf-461e-83cb-231f5dbb9a50)
![Snímek obrazovky (995)](https://github.com/AstarNetwork/growth-program/assets/104125423/ccf7c47c-ff80-4587-9791-8c436000d796)
![Snímek obrazovky (996)](https://github.com/AstarNetwork/growth-program/assets/104125423/2ab96013-8930-4c50-8378-ade453e47157)

**Discord Unstoppable Grant discussion:**
Participating in Governance and Projects discussion when new project appear. Raise questions, support or refuse their proposals. Here is my Discord Username: mattweb5go

# SM - Social Media Engagement
**Astar Network CZ/SK Twitter:** https://twitter.com/AstarNetwork_CS

![Snímek obrazovky (997)](https://github.com/AstarNetwork/growth-program/assets/104125423/6b591205-5f22-49a4-a9bd-452514afef72)
![Snímek obrazovky (999)](https://github.com/AstarNetwork/growth-program/assets/104125423/c38a7efe-bbc8-4917-899e-6e0cf356a7fd)

#

**Personal Twitter:** https://twitter.com/Matt_Web3_
Trying to promote major things especially Astar Network's announcements and forum proposals on daily basis!

![Snímek obrazovky (1002)](https://github.com/AstarNetwork/growth-program/assets/104125423/1e486f2f-8e31-4d38-8f5d-82680cc23a54)
![Snímek obrazovky (1003)](https://github.com/AstarNetwork/growth-program/assets/104125423/ca2c1675-055b-4094-b167-f9fb724b97e8)

#

**AstarChan:** https://twitter.com/Astar_Chan_

![Snímek obrazovky (1000)](https://github.com/AstarNetwork/growth-program/assets/104125423/717d1066-2b05-4e95-a2f3-a7a3194589f1)
![Snímek obrazovky (1001)](https://github.com/AstarNetwork/growth-program/assets/104125423/af129350-9bdd-4cd0-ac50-e6d9770e6985)

# CC - Content Creation

**1) Astar Network Announces Revised Allocation Plan for $PINK Token Distribution in TAB:** 
https://medium.com/p/1e64ecdc9660
![Snímek obrazovky (1004)](https://github.com/AstarNetwork/growth-program/assets/104125423/534a5c32-97c5-4a64-9847-129a7e767718)

**2) C14 101: Introducing a New Era in Lending on the Astar zkEVM In TAB:** 
https://medium.com/the-astar-bulletin-tab/c14-101-introducing-a-new-era-in-lending-on-the-astar-zkevm-1cef197f64dd
![Snímek obrazovky (1005)](https://github.com/AstarNetwork/growth-program/assets/104125423/b4080091-da7f-46bf-9b99-d270fecc25de)

**3) Astar CZ & SK Community community growth chart:**
https://x.com/AstarNetwork_CS/status/1767102512664846574?s=20
![Astar CZ and SK community growth](https://github.com/AstarNetwork/growth-program/assets/104125423/2c23f093-4fff-4d88-b49c-0eee8027dd96)

That's all for my March contributions, thank you very much!

**Comment by Gunit2481** [comment]
Hello Matt!
Good job on contributing to Astar Growth last month.

As for your content creation, I'm not taking into account **_2) C14 101: Introducing a New Era in Lending on the Astar zkEVM In TAB_** because it's a repost of a C14 article. 

https://medium.com/@c14_wtf/c14-101-introducing-a-new-era-in-lending-on-the-astar-zkevm-6b65f024f036

It's not original content and should be rewarded by C14 and by the ecosystem agent program.

Thank you
