### ISSUE TITLE
March 2024 contribution - marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#2434]
Telegram : Soulstar / https://t.me/marvelet6 (previously Soul Eater)
Discord : marvelet#8647
Native Address : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

_____

### CM
**TELEGRAM**
Astar Indonesia
Link : [https://t.me/astarnetwork_id](https://t.me/astarnetwork_id)
Total Members : 244 members (exclude Rose Bot, increased 4 members)
Combot Link : [https://combot.org/c/-1001288040165/a](https://combot.org/c/-1001288040165/a)
Screenshots: :

![telegram_act](https://github.com/AstarNetwork/growth-program/assets/87793956/49d492c7-c02c-4032-aab2-d3db444439b3)

Comments :
- Less activities compared to last month, but still active discussion regarding how to get Yoki.
- Users wants to see DeFi

For Discord , kindly check my activity there

____

### GOV
**FORUM**
My activity on Astar Forum
[https://forum.astar.network/u/souleater/activity](https://forum.astar.network/u/souleater/activity)
[https://forum.astar.network/u/souleater/summary](https://forum.astar.network/u/souleater/summary)

Screenshot :

![ss_forum](https://github.com/AstarNetwork/growth-program/assets/87793956/adbeabf9-669c-495f-b678-8070fb01e719)

For Discord, kindly check my activity there

_____

### SM
**TWITTER**
Personal : [https://twitter.com/rudayruday](https://twitter.com/rudayruday)
Analytic Screenshot :

![x_personal_1](https://github.com/AstarNetwork/growth-program/assets/87793956/41206f0c-2fb3-4f30-8d12-2afc7ec98087)
![x_personal_2](https://github.com/AstarNetwork/growth-program/assets/87793956/8533fb48-9ab6-450a-b7d6-150269de62cf)

In-depth twitter activity:
[tweet_activity_metrics_rudayruday_20240301_20240401_en.csv](https://github.com/AstarNetwork/growth-program/files/14850664/tweet_activity_metrics_rudayruday_20240301_20240401_en.csv)

===

Astar Indonesia : https://twitter.com/AstarNetwork_ID
Analytic Screenshot :

![x_astrid_1](https://github.com/AstarNetwork/growth-program/assets/87793956/e62db03c-6bbd-4d8d-8e7c-4606f77c5994)
![x_astrid_2](https://github.com/AstarNetwork/growth-program/assets/87793956/9a92c05f-1bd3-4c25-b7ae-491d7fa034b7)

In-depth twitter activity:
[tweet_activity_metrics_AstarNetwork_ID_20240301_20240401_en.csv](https://github.com/AstarNetwork/growth-program/files/14850691/tweet_activity_metrics_AstarNetwork_ID_20240301_20240401_en.csv)

____

### CC
**The Astar Bulletin**
Writing a monthly article on Astar Bulletin, introductions about Yoki Origins
Title :
Astar zkEVM : One Month After
[https://theastarbulletin.news/astar-zkevm-one-month-after-fc4322ea4a6d](https://theastarbulletin.news/astar-zkevm-one-month-after-fc4322ea4a6d)

===

**Binance Squared**
Writing a monthly short article to increase Astar exposure on Binance global.
Title:
Everything Astar - Mar 24
[https://www.binance.com/en/square/post/5423465891793](https://www.binance.com/en/square/post/5423465891793)

That's all my contribution for March 2024.

**Comment by Gunit2481** [comment]
Thank you Rudy! 👏
