### ISSUE TITLE
March 2024 Contribution - Marco Da Rocha (Pitcoin)

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#2435]
Discord Username: pitcoin #3857
ASTR/SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

CM - Manage and Support
Astar Network PT (Telegram) and Astar Network (Discord)
Telegram: https://t.me/astarnetworkPT - 533 members (+20 members) +4%
![Screen Shot 2024-04-03 at 08 16 17](https://github.com/AstarNetwork/growth-program/assets/99457582/e7c71713-5bb5-4150-b654-6b404e3e79be)
![Screen Shot 2024-04-03 at 08 16 30](https://github.com/AstarNetwork/growth-program/assets/99457582/fc886f7c-cfc9-4b90-9388-36dbbb403136)

GOV - Governance & Project Engagement
https://forum.astar.network/u/pitcoin777
![Screen Shot 2024-04-03 at 08 49 34](https://github.com/AstarNetwork/growth-program/assets/99457582/ad48a426-8c1d-4622-81d2-46e41c5b729d)

SM - Social Media Engagement
Twitter @Pitcoin_ – 1896 ollowers (+21 new followers) - 1%
![Screen Shot 2024-04-03 at 08 53 51](https://github.com/AstarNetwork/growth-program/assets/99457582/ea8c0b4d-0950-4750-b92c-5707d69ba694)
![Screen Shot 2024-04-03 at 08 53 42](https://github.com/AstarNetwork/growth-program/assets/99457582/bf38619e-353c-4ce0-8a78-ebf96ebac5b5)
![Screen Shot 2024-04-03 at 08 53 33](https://github.com/AstarNetwork/growth-program/assets/99457582/a3a01f31-9736-452a-9fe0-c667aae15da6)
![Screen Shot 2024-04-03 at 08 53 15](https://github.com/AstarNetwork/growth-program/assets/99457582/81628c32-40a6-4c64-ad00-5f618d143e6b)
![Screen Shot 2024-04-03 at 08 52 47](https://github.com/AstarNetwork/growth-program/assets/99457582/695ed1ae-01ce-4003-b0b8-1a522a1753e2)
![Screen Shot 2024-04-03 at 08 52 33](https://github.com/AstarNetwork/growth-program/assets/99457582/3a7a412a-30ff-4bf6-aa62-e4b03ae359b6)

Twitter @AstarNetworkBR – SUSPENDED again.
![Screen Shot 2024-04-03 at 08 57 19](https://github.com/AstarNetwork/growth-program/assets/99457582/de6588d3-49d4-4524-a8c8-ab06159bb9d7)

CC - The Content Creator
Astar zkEVM updates: https://grillapp.net/6283/astar-zk-evm-updates-104556?ref=7524

Translations
https://grillapp.net/6917/astar-zk-evm-mainnet-foi-lancada-86117?ref=7524

**Comment by Gunit2481** [comment]
Thank you for your report Marco!
