### ISSUE TITLE
March 2024 Contribution - defiguy

### ISSUE THREAD

**Issue by astardefi** [AstarNetwork/growth-program#2436]
march 2024 Contribution - defiguy
Telegram Username: @defiguy2022
Discord Username: defiguy
Twitter User name: defiguy22
ASTR Wallet Address: YJ9ZyKwzX6tLh21eV1YT61EpihraYAdJYbcpyJFDwdyrfi7

# CM
![telegram-march-astar](https://github.com/AstarNetwork/growth-program/assets/104277195/7d63ec53-64f3-498c-9318-0462b998a071)
![telegram-march-astar-2](https://github.com/AstarNetwork/growth-program/assets/104277195/84b0c789-e913-45a8-ad71-499a4a0b7a2f)

# GOV
![Screenshot 2024-04-03 at 15 24 46](https://github.com/AstarNetwork/growth-program/assets/104277195/78391368-308c-462a-abcc-e2226cc9401b)
![Screenshot 2024-04-03 at 15 25 13](https://github.com/AstarNetwork/growth-program/assets/104277195/d3484898-0f2a-446e-8730-5983c49d666f)

# SM
## Astar Telegram group
![Screenshot 2024-04-03 at 15 26 19](https://github.com/AstarNetwork/growth-program/assets/104277195/c60b98a5-2b2e-42fd-8dca-068f79896f48)
![Screenshot 2024-04-03 at 15 26 53](https://github.com/AstarNetwork/growth-program/assets/104277195/11595dda-b94d-4ba4-81d5-251e6bd1245d)

## defiguy telegram (248 members)

**_Around 95 messages related to Astar (questions, links, discussions, events)_**
![Screenshot 2024-04-03 at 15 40 57](https://github.com/AstarNetwork/growth-program/assets/104277195/a2cc03a7-474a-4b4e-b1ce-4183cad498fe)

Link - https://t.me/+QfslDL_epwZlMmUx

# CC
## 51K impressions/ Average of 80 live viewers per stream
![Screenshot 2024-04-03 at 15 28 07](https://github.com/AstarNetwork/growth-program/assets/104277195/09bec44c-3fa0-4735-b73f-fbfe20426664)

![Astar updates (58)](https://github.com/AstarNetwork/growth-program/assets/104277195/f701412f-5710-408a-9d7f-2aa32d5b6c12)

https://www.youtube.com/watch?v=IP6VoVViI54 - **ASTAR zkEVM está em MAINNET!! Mais de 5M de dólares em TVL (1 dia)!!!!**

![Astar updates (59)](https://github.com/AstarNetwork/growth-program/assets/104277195/564c4ea8-cbb3-474e-ab2d-24e21dbfbfd3)
https://www.youtube.com/live/YfPSKhWLSAM - **LayerZero na ASTAR zkEVM!! AIRDROPS e MEMECOINS CRESCENDO!!!**

![Astar updates (60)](https://github.com/AstarNetwork/growth-program/assets/104277195/b154c6cd-6c1e-485c-9767-8d590a9cb083)
https://youtube.com/live/8f8kxgHfPaQ - **POKÉMON na ASTAR?? MEMECOINS e AIRDROPS aparecendo!!!**

![Astar updates (61)](https://github.com/AstarNetwork/growth-program/assets/104277195/a2be26e7-24ba-4d1a-8f78-4f18dd5f5963)
https://youtube.com/live/T-MZXxl4vfM - **NÃO PERCA!!!! AIRDROP DE ASTR e tokens de DAPPS**

# BD
## Approach to Artemis (one of the biggest Data terminals in crypto)
![Screenshot 2024-04-03 at 15 32 21](https://github.com/AstarNetwork/growth-program/assets/104277195/c71488a6-ea7b-4e9b-bad2-d86d580454ff)

**Comment by Gunit2481** [comment]
Great work Gustavo! 💪
