### ISSUE TITLE
March 2024 Contribution - bao

### ISSUE THREAD

**Issue by 0xbao** [AstarNetwork/growth-program#2437]
Telegram Username: @bao1993jp
Discord Username: bao#bao1993
Twitter User name: @bao1993jp
ASTR Wallet Address: beeZfXVZppLCGtZuE4jRZLD9RperjqbfCYrC148Np1uv4pE

# Contributions:

### -Supporting to inquiries from the community almost every day
Astar Network Discord: JAPAN channel
Astar Network Discord: SUPPORT channel **(support to Japanese QA)**
Astar Network Japan Telegram: https://t.me/AstarJapan

## -GOV
I posted **21 times** on the Forum and actively participated in governance.
https://forum.astar.network/u/bao/activity

I also got the "Nice Share" badge on several topics and successfully attracted more people to the Forum.
![スクリーンショット 2024-04-04 14 50 52](https://github.com/AstarNetwork/growth-program/assets/123560716/0a462c3e-ac61-4442-ad8e-8bb0105e90ca)

![スクリーンショット 2024-04-04 14 30 10](https://github.com/AstarNetwork/growth-program/assets/123560716/fb201f68-541e-4a59-9c73-dcdc4559de00)
![スクリーンショット 2024-04-04 14 30 21](https://github.com/AstarNetwork/growth-program/assets/123560716/26c6627c-4d4f-4f60-8a5a-1e2c6afe70fe)
![スクリーンショット 2024-04-04 14 30 32](https://github.com/AstarNetwork/growth-program/assets/123560716/57a0c83c-3f68-4bf1-acc4-5a48286dae4d)

## -CC
[1] Astar Weekly Journal Mar.3
EN ver.
https://theastarbulletin.news/meme-57-astar-weekly-journal-2a6d2774d1f8
JP ver.
https://astarweeklyjournal.substack.com/p/meme

[2] Astar Weekly Journal Mar.9
EN ver.
https://medium.com/@bao.crypto.5515/astar-zkevm-is-live-58-astar-weekly-journal-93abc0390c60
JP ver.
https://astarweeklyjournal.substack.com/p/astar-zkevm-is-live

[3] Astar Weekly Journal Mar.16
EN ver.
https://theastarbulletin.news/layerzero-59-astar-weekly-journal-16c53faab0be
JP ver.
https://astarweeklyjournal.substack.com/p/layerzero

[4] Astar Weekly Journal Mar.23
EN ver.
https://theastarbulletin.news/haha-coin-60-astar-weekly-journal-70ccd923cd70
JP ver.
https://astarweeklyjournal.substack.com/p/haha-coin

[5] Astar Weekly Journal Mar.30
EN ver.
https://theastarbulletin.news/yoki-origins-61-astar-weekly-journal-4c58e013f269
JP ver.
https://astarweeklyjournal.substack.com/p/yoki-origins
![スクリーンショット 2024-04-04 14 35 26](https://github.com/AstarNetwork/growth-program/assets/123560716/68d1e70e-0fad-4025-a3f8-4d7e32afa9e8)
![スクリーンショット 2024-04-04 14 35 44](https://github.com/AstarNetwork/growth-program/assets/123560716/73775f51-6914-4480-83f6-7b0bc12dd313)

### Mar.10：Open Source Conference 2024 Tokyo/Spring
I participated in this event with tksarah to acquire new users for Astar Network.
The Open Source Conference is a famous event in Japan where companies and individuals interested in Open Source come together. We set up a booth on how to operate Astar nodes and gained the attention of many new users.

Event HP：https://event.ospn.jp/osc2024-spring/
![GIRb-bLbsAAyXlv](https://github.com/AstarNetwork/growth-program/assets/123560716/4a88cbfd-6b70-4bf1-9424-bd1cd628718c)

## -Other Bonus
I did the Japanese translation for "LayerZero to Provide Cross-chain Interoperability for Astar zkEVM" at Cody's request.
The blog is here：https://astar.network/ja/blog/layerzeroastar-zkevm-93975

**Comment by Gunit2481** [comment]
Great work Bao! 🙏
