### ISSUE TITLE
March 2024 Contribution 

### ISSUE THREAD

**Issue by RomanShevchenko099** [AstarNetwork/growth-program#2438]
Telegram Username: @Rotraf9 
Discord Username: .romantop
ASTR Wallet Address: ZRDkMxCMKHWKxdQAQc3jr1MWbpGifW6237uUotjLEv7nbYw

CM 
Promoted the Russian community: https://t.me/astar_rus in my telegram channel: https://t.me/DenegnieMillioner

https://t.me/DenegnieMillioner/1999
![IMG_6575](https://github.com/AstarNetwork/growth-program/assets/162012547/38f775b7-a096-47a4-88e0-bfd789a45bca)

https://t.me/DenegnieMillioner/2003
![IMG_6576](https://github.com/AstarNetwork/growth-program/assets/162012547/3c118afa-9b37-49ad-a574-b864ce19df63)

https://t.me/DenegnieMillioner/2008
![IMG_6577](https://github.com/AstarNetwork/growth-program/assets/162012547/1205cf6c-d2a4-481e-976f-e154e580243c)

https://t.me/DenegnieMillioner/2012
![IMG_6578](https://github.com/AstarNetwork/growth-program/assets/162012547/a9e1f301-9b4a-4136-b9ef-682de9bd7107)

[SM] & [CC] 

I created 2 videos for my YouTube channel
https://youtu.be/VnARxsQr7xY?si=fGutt2BdUZd5j0lv over 2000 views and 90+ likes
![IMG_6581](https://github.com/AstarNetwork/growth-program/assets/162012547/04dae093-0b44-4ebd-a70e-c999d4ecdf3f)
https://youtu.be/aLhSjbZEhQM?si=v49eJria7sHuLro7 over 2300 views and 71+ likes
![IMG_6582](https://github.com/AstarNetwork/growth-program/assets/162012547/1e1affad-56ce-4c83-ac95-18bd43d9e3af)

I created 2 articles 
https://kriptozar99.medium.com/astar-parachain-%D0%BE%D0%B1%D0%B7%D0%BE%D1%80-%D1%80%D0%BE%D0%BB%D0%B8-%D0%B8-%D0%BF%D1%80%D0%B5%D0%B8%D0%BC%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2-e81ccbb3fabf
![IMG_6583](https://github.com/AstarNetwork/growth-program/assets/162012547/6b8e7aae-fee2-46e9-b39d-1d6d2039d180)

https://medium.com/@kriptozar99/astar-network-%D0%BE%D0%B1%D0%B7%D0%BE%D1%80-%D0%B5%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-fdf703357b2e
![IMG_6584](https://github.com/AstarNetwork/growth-program/assets/162012547/b1c661ab-f94c-4366-afa2-659269079be2)

Twitter infographics: 
https://twitter.com/Ka69UxyS24CMSx9/status/1772771376400609385
![IMG_6588](https://github.com/AstarNetwork/growth-program/assets/162012547/837a62c2-c09f-40da-8df9-48533d4bda2e)
https://twitter.com/Ka69UxyS24CMSx9/status/1775629908158378121
![IMG_6587](https://github.com/AstarNetwork/growth-program/assets/162012547/02f7fd91-16cd-47bb-81a4-45cb16d7a82d)

Others:
I prepared 2 presentations and uploaded them to Google Drive so you can download them
https://drive.google.com/file/d/1FjvN0EvJJaYO6OSk73pD-CDVZPhnSiBV/view?usp=sharing
https://drive.google.com/file/d/1Mja1KdS9-glzZnnN9YrdBqQFWUy5zbGF/view?usp=sharing

next month I plan to do a lot more work, I have an idea to create a very interesting and useful video, I will also start making animated content and write quality threads on Twitter, I am glad to participate in the development of Astar Network🚀

**Comment by Gunit2481** [comment]
Hello Roman,

It's great to see your contributions and motivation for Astar's growth. 

The program rewards the only official agent of the Astar ecosystem. 

If you'd like to take part in the program, I invite you to join the Astar Space Club: 
https://astarnetwork.notion.site/Astar-Space-Club-2023-5e396c75fcf34d698baf288d9aa9230f

Best of luck !
