### ISSUE TITLE
March 2024 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2440]
Telegram Username: `@actlee`
Discord Username: `pithecus.astr (previously pithecus#9288)`
ASTR Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

### Mandatory tasks
**CM**
- Manage the Korean TG community & Discord channel
- Share announcements
- Help/respond the community for various topics in general, especially these days for Yoki Origins campaign and the dApps onboarded on zkEVM, dApp staking v3, often Sony related questions and/or investment related questions
- Active community (2.4k+ members, 12k+ messages, 500+ active users, and 650+ new net users)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/28d924d8-bd0d-4718-8a35-7b884c813fad)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/605d74b1-2e46-4733-8170-c53c968d71f2)

**GOV**
https://forum.astar.network/u/pithecus/activity
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b5c02c72-8695-4afc-8052-e05c6a7617f5)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/20fd8560-d2f3-488d-b0e7-fd538fb89982)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/2233ad2f-8709-4639-8d85-99110555af90)

### Optional tasks
**SM**
- Blue mark & 1.3k- followers
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b763d083-8265-4fb6-831d-b0f1b0b8a7c1)
https://twitter.com/spmlaihm/status/1774311140182413584
https://twitter.com/spmlaihm/status/1773993740933206118
https://twitter.com/spmlaihm/status/1773310064897528060
https://twitter.com/spmlaihm/status/1772922213756219562
https://twitter.com/spmlaihm/status/1772869891214700621
https://twitter.com/spmlaihm/status/1772869407645073542
https://twitter.com/spmlaihm/status/1772865304508481875
https://twitter.com/spmlaihm/status/1772864206716514796
https://twitter.com/spmlaihm/status/1772389208084132059
https://twitter.com/spmlaihm/status/1772389212332958085
https://twitter.com/spmlaihm/status/1772389215822602745
https://twitter.com/spmlaihm/status/1772389219241021531
https://twitter.com/spmlaihm/status/1772389222680252433
https://twitter.com/spmlaihm/status/1772389225259778173
https://twitter.com/spmlaihm/status/1772389227503755350
https://twitter.com/spmlaihm/status/1772389229642842561
https://twitter.com/spmlaihm/status/1772232730169729344
https://twitter.com/spmlaihm/status/1772157408434909498
https://twitter.com/spmlaihm/status/1772120077128925420
https://twitter.com/spmlaihm/status/1772120079221628949
https://twitter.com/spmlaihm/status/1772119666162344015
https://twitter.com/spmlaihm/status/1771194076445970846
https://twitter.com/spmlaihm/status/1771147541020545089
https://twitter.com/spmlaihm/status/1771147885016457672
https://twitter.com/spmlaihm/status/1771068910177009812
https://twitter.com/spmlaihm/status/1769578704932372563
https://twitter.com/spmlaihm/status/1769578707449000193
https://twitter.com/spmlaihm/status/1769578709571256821
https://twitter.com/spmlaihm/status/1767697335423770994
https://twitter.com/spmlaihm/status/1767689119604297905
https://twitter.com/spmlaihm/status/1767687553623236929
https://twitter.com/spmlaihm/status/1767683369024786538
https://twitter.com/spmlaihm/status/1767682632962162894
https://twitter.com/spmlaihm/status/1765960399461982306
https://twitter.com/spmlaihm/status/1765959903632400822
https://twitter.com/spmlaihm/status/1765855388136612227
https://twitter.com/spmlaihm/status/1765792662261534721
https://twitter.com/spmlaihm/status/1765792314692157524
https://twitter.com/spmlaihm/status/1765643100146348419
https://twitter.com/spmlaihm/status/1765642333805023726
https://twitter.com/spmlaihm/status/1765349743553573225
https://twitter.com/spmlaihm/status/1765219253009998276
https://twitter.com/spmlaihm/status/1765218361552630093
https://twitter.com/spmlaihm/status/1764867992507036116
https://twitter.com/spmlaihm/status/1764589440855396396
https://twitter.com/spmlaihm/status/1764519380816142622

*CC*
- 이더리움의 덴쿤 (Dencun) 업그레이드에 관하여 (https://medium.com/astar-korea/04b8e4de4e71)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/6592f475-dbb1-475b-9335-dc5a6e00bc3d)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/e3131464-983b-43eb-8d53-eaeccf759c54)

**Comment by Gunit2481** [comment]
Great work with our Korean community!
