### ISSUE TITLE
March 2024 Contribution - VasaKing

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2441]
Telegram : @VasaKing

Discord Username: @VasaKing

ASTR Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

----- CM - Community Support & Management -----

Users support on the Italian Astar Community Telegram

----- GOV - Forum partecipation -----

https://forum.astar.network/u/vasaking/activity

----- VSM - Astar Italia Twitter -----

OMAs thread https://x.com/Astar_Italia/status/1763885562186862677

Yoki projects introduction https://x.com/Astar_Italia/status/1764682109824725214

zkMainnet launch https://x.com/Astar_Italia/status/1765316029339652149

NFT Trader on Astar https://x.com/Astar_Italia/status/1765322259164475438

Intract x Astar https://x.com/Astar_Italia/status/1765371780959543481

Sota x YieldLabs https://x.com/Astar_Italia/status/1765422093661765773

Startale Nodes https://x.com/Astar_Italia/status/1765664937966256214

DappRadar x Astar https://x.com/Astar_Italia/status/1765671053164949527

Ordinals on Astar https://x.com/Astar_Italia/status/1765693882241839357

Yoki medium promo https://x.com/Astar_Italia/status/1765714091216175500

Arthswap 10eth campaign https://x.com/Astar_Italia/status/1765731511645413733

Relaybridge x Astar https://x.com/Astar_Italia/status/1765752209797525682

Yoki launch https://x.com/Astar_Italia/status/1765861008583676297

Astar on Dune https://x.com/Astar_Italia/status/1766087469416505727

Astar Japanese NFT creators https://x.com/Astar_Italia/status/1767485775635939454

Graph x Astar thread https://x.com/Astar_Italia/status/1767501543874461868

NTT wallet x Astar https://x.com/Astar_Italia/status/1767506875162271798

TeamZ Hackathon https://x.com/Astar_Italia/status/1767530541958541782

Astarzk on DefiLlama https://x.com/Astar_Italia/status/1767536017559752905

Owlto x Astar https://x.com/Astar_Italia/status/1767552491787321630

Airlyft promo https://x.com/Astar_Italia/status/1767560276713635889

Yoki Notebook https://x.com/Astar_Italia/status/1767822910343757919

Astar space promo https://x.com/Astar_Italia/status/1767852558993821853

Skylabs trailer https://x.com/Astar_Italia/status/1767853105725468764

Astar after Dencun https://x.com/Astar_Italia/status/1767859368467325315

Quickswap on Astar zk https://x.com/Astar_Italia/status/1767878983796867339

Dencun Medium promo https://x.com/Astar_Italia/status/1767933363766038537

Astar x Stargate https://x.com/Astar_Italia/status/1768208092926247043

Astar x Layerswap  https://x.com/Astar_Italia/status/1768212822876405874

HAHA promo https://x.com/Astar_Italia/status/1768216929892700182

Keom x Astar https://x.com/Astar_Italia/status/1768219544173125721

dYdX x Astar https://x.com/Astar_Italia/status/1769013106066264221

L2X on Astar https://x.com/Astar_Italia/status/1770389342843761054

Magic labs x Astar https://x.com/Astar_Italia/status/1770393468197560526

Rarible x Astar https://x.com/Astar_Italia/status/1770402327503016100

HIKI x Astar https://x.com/Astar_Italia/status/1770404334435488020

HAHA on Quickswap https://x.com/Astar_Italia/status/1770406728900784241

Physical Yokis short https://x.com/Astar_Italia/status/1770423003878183221

TeamZ x Astar promo https://x.com/Astar_Italia/status/1770444841723293813

DenDekaDen x Astar https://x.com/Astar_Italia/status/1770764953424683085

Benny Giang twitter space https://x.com/Astar_Italia/status/1770787288512933925

Layerswap on Yoki https://x.com/Astar_Italia/status/1770812753139192258

CityPop x Astar  https://x.com/Astar_Italia/status/1770826921670004851

DOT on Astar zk https://x.com/Astar_Italia/status/1770882506377572519

Crossmint x Astar https://x.com/Astar_Italia/status/1772275141898035345

Dev twitter space https://x.com/Astar_Italia/status/1772589201155862637

Protofire promo https://x.com/Astar_Italia/status/1772596353903767563

Bifrost on Hackathon https://x.com/Astar_Italia/status/1772609732550766772

Gaming twitter space https://x.com/Astar_Italia/status/1772896341783629946

Kitsch cats on Yoki https://x.com/Astar_Italia/status/1772928458324115807

PINK on Astar https://x.com/Astar_Italia/status/1772930437850997155

Build Asia event https://x.com/Astar_Italia/status/1772952788420514102

YoPort 2.0 https://x.com/Astar_Italia/status/1772982324927287474

Yoki game https://x.com/Astar_Italia/status/1773017597467939183

Yoki updates https://x.com/Astar_Italia/status/1773666302747394419

NFT trader YoPort https://x.com/Astar_Italia/status/1773670282302980438

DappRadar YoPort https://x.com/Astar_Italia/status/1773700914504679493

Rabby wallet x Astar zk https://x.com/Astar_Italia/status/1773735035377435027

![Astar March 1](https://github.com/AstarNetwork/growth-program/assets/63927981/4d1f2d96-ad0e-49c5-a474-3131339ede8c)
![Astar March 2](https://github.com/AstarNetwork/growth-program/assets/63927981/a807400d-e15a-47f8-a7ac-9483f59c789a)

----- CC - Medium -----

Yoki deep dive https://medium.com/@AstarItalia/yoki-origins-tutto-quello-che-c%C3%A8-da-sapere-87885f564623

Astar after Dencun upgrade https://medium.com/@AstarItalia/astar-zkevm-cosa-cambia-dopo-laggiornamento-di-ethereum-dencun-bb91671d1146

**Comment by Gunit2481** [comment]
Good work on covering Astar news!
