### ISSUE TITLE
March 2024 Contribution - Technical Ambassador: Takeshi

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/growth-program#2442]
Telegram Username: @tksarah0822
Discord Username: tksarah#tksarah
X(Twitter) Username: @tsarah0822 ( TKLab | tklab.astr )
Astar Wallet Address: aZkj2EgiZkUbnKk6XMp9pf9f9SALXSAaTgz17ZEYUaq2UZy

# Core Tasks (Mandatory)
## 1. DEVELOPER SUPPORT
I advised to build the astar node and helped community members asking dev questions on discord (**builder** and **peers-program**).

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/bb335424-db9f-4db1-ae05-7186f9962e1d)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/6cc27705-f543-4d29-91bc-75e53c8bcac7)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/531c06af-5126-4791-8e99-39ed2ea1024a)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b217038d-e748-4d06-9789-b827f6d279e7)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3b0e25de-35ae-46c9-8b91-65691d73d86b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/46c92ee9-8bc1-481c-adbc-d50ad6aade0b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/956803e5-1526-4660-91e4-afd0413b2c93)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/30432e66-f865-4019-b1b1-864ea9346d68)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/603e70e5-2520-4456-8ed2-f72068b6c7df)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/cdb94700-e36c-420e-8c19-09d155a5f16d)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/08bf7a5f-c76a-415e-96fe-0cf20bd85e69)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3c836a1d-ec9b-4765-a103-8c37bc016178)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/5acada51-f763-4c99-8942-e844eaca1e84)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/310ae87f-5991-4aa6-af1b-7a721599c736)

## 2. GOVERNANCE & PROJECT ENGAGEMENT
_https://forum.astar.network/u/tksarah/activity_

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/8fae12d0-7b35-4eea-9ec5-96765ce51f51)

# Optional Tasks (Choose up to 2 tasks/month)

### [1] Contents
Title: **Astar zkEVM エコシステムアップデート2024/2**
Published in Medium Mar 3, 2024
https://theastarbulletin.news/astar-zkevm-%E3%82%A8%E3%82%B3%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%882024-2-58548c02562c
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/2032bac6-9309-4563-b1aa-264b25288a9e)

### [2] Astar Document Translation for Japanese

**Astar zkEVM**
https://docs.astar.network/ja/docs/use/zkevm-guides/
**Astar zkEVM ネットワークの設定方法**
https://docs.astar.network/ja/docs/use/zkevm-guides/set-up-zkevm
**Ethereum および他の EVM ベースのチェーンから Astar zkEVM へのブリッジ**
https://docs.astar.network/ja/docs/use/zkevm-guides/Bridge-Ethereum
**Astar EVMからAstar zkEVMへの資産のブリッジング**
https://docs.astar.network/ja/docs/use/zkevm-guides/Bridge-Astar-EVM
**Bifrost Finance による ASTR Liquid dApp Staking**
https://docs.astar.network/ja/docs/use/zkevm-guides/ASTR-Liquid-Staking

**_Github:_**
* https://github.com/AstarNetwork/astar-docs/pull/649
* https://github.com/AstarNetwork/astar-docs/pull/648
* https://github.com/AstarNetwork/astar-docs/pull/640

### Viewer and tool for dApp Staking
View Page: https://agent.sun-t-sarah.work/ (Original https://tksarah.github.io/bc/)

dApp Staking v3 has been released. However, it is not possible to immediately grasp the overall staking amount and ranking trends of dApps on Astar Portal. With the introduction of Period in v3, analyzing past data becomes important for creating future achievements. I have started building and testing for personal use and for Agents.
As I also possess knowledge of statistics, it may be possible to create simple analysis reports from facts in the future. I will try through trial and error.

The technologies and elements I am using are as follows:
- Repository: https://github.com/tksarah/bc
- Languages: Perl, Shell, JavaScript, HTML
- Data: on-chain

_**March update:**_

 - Add README.md
 - Change docs directory and add script for price check.
 - Add function to filter table by category 

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/172a435b-3dfe-442c-a2d7-578379593975)

_**Plan:**_
In this month, I plan to create a page that regularly retrieves information and displays the trend with a line graph.

### Open Source Conference 2024 Tokyo/Spring 

**Online Seminar / Mar 1, 2024**
I made a presentation about recent Astar Network updates.

Event Page: https://event.ospn.jp/osc2024-online-spring/
Session Page: https://event.ospn.jp/osc2024-online-spring/session/1392554
Contents: https://speakerdeck.com/tksarah/2024nian-geng-nijin-hua-sita-astar-network-nozi

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/1254f9e6-0ce7-4a3d-a6e9-f907ec56a430)

**Exhibited at Asakusa in Tokyo /  Mar 10, 2024**
I exhibited at the event as Astar Network with Agent Bao.
I brought an archive node built on my **Raspberry Pi** to the venue and introduced it live to the attendees, showing them how the node synchronizes blocks.

Event Page: https://event.ospn.jp/osc2024-spring/
Event Report: https://www.ospn.jp/press/20240322tokyo-spring-2024-report.html
X Post: https://twitter.com/tsarah0822/status/1766638109364785175

![IMG_20240310_140921094](https://github.com/AstarNetwork/growth-program/assets/11060137/448ab8f7-b1b6-4a17-af0e-4906dbabf6ea)
![GIRb-aIbMAADS2E](https://github.com/AstarNetwork/growth-program/assets/11060137/d59f4561-09cf-4781-92a4-ba00dd77d6b6)
![GIRb-bLbsAAyXlv](https://github.com/AstarNetwork/growth-program/assets/11060137/401a0f42-fc41-4198-a5a3-ea295fdc0ad3)

**Comment by Gunit2481** [comment]
Great work Takeshi! 👏
