### ISSUE TITLE
March 2024 Contribution - Leo

### ISSUE THREAD

**Issue by LeoNeurolanche** [AstarNetwork/growth-program#2443]
Hello, I'm Leo. In March, as the Astar Network Turkey team, we were involved in many activities and projects.

First, I will share the content I created from my own account with you, and then I will inform you about the posts we made on the Turkey account. Let's take a look together.

Personal Twitter: https://twitter.com/neurolauncher?s=21&t=ISh07fvjMqpmUg40w5HqBg  Discord: neurolauncher.
 Astar Network Turkey Twitter: https://twitter.com/astarnetworktr_?s=21&t=ISh07fvjMqpmUg40w5HqBg  Astar Network Turkey Telegram: https://t.me/AstarTurkiye  Personal medium: https://medium.com/@enesfaruksahin?source=linkShare-7dc743decc41-1683244333  Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4

My personal Twitter montly views: 221.5k view

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/6af91d3c-1858-4f19-9ced-76c730692e1e)

Cm: Community Support

This month, in addition to actively providing support to the Turkish communityx In addition, I became the active person in the community by sending 134 messages.

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/25fb50e0-2fa9-4e22-9044-3c5e13408270)

**GOV - Governance & Project Engagement**

Gov- https://forum.astar.network/u/leo/activity

I participated in all active forum activities in governance this month. Additionally, I made efforts for the Astar ecosystem to be more decentralized.
![image](https://github.com/AstarNetwork/growth-program/assets/126774982/7e31fcc3-e6ce-4700-8de8-3f9674aa65a5)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/482e11f7-3010-4803-9e9a-47e42bf7f216)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/6be2d820-d576-4b3c-b571-e022da1659af)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/69b28e3b-33e2-41e4-b69d-3d397d09cc25)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/d3c5d77b-1d24-4f27-81da-a8526b48f299)

**SM - SOCIAL MEDIA ENGAGEMENT**

I will share my social media activities on my personal account: 

----------
Do you know that with the new tokenomics adoption by Astar Network, there's a monthly burn of 5,791,320 $ASTR solely due to the dapp staking update? 

(View 21901, Like 154, Rt 57)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/916156a4-a31a-455b-9f6c-c097457f3f6b)

https://x.com/neurolauncher/status/1764987395039003131?s=46

-----------

It has been exactly 1 year since I became an agent for Astar Network. 

I will share with you the experiences I have had over this year and how Astar has evolved in the last year.

(View 6153, Like 103, Rt 27)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/e838caf4-119a-46aa-8acd-9efd90c5a7e7)

https://x.com/neurolauncher/status/1768302672606613507?s=46

-------------

 Is a strong hype waiting for us with Astar Network's ZkEvm?

The Meme and AI token craze in the crypto world are gradually starting to reflect in the Astar Network ecosystem as well. 

(View 14324, 146 Like, 49 Rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/dc19da6b-8528-4045-8a42-7fa1e4b77751)

https://x.com/neurolauncher/status/1770392165761306746?s=46

-------------

Hello Astar Network family, after a great semester in my academic career, I am back with you again. I've really missed writing articles!

Today, we will explore the strong projects in $ASTR ecosystem and discuss the opportunities available.

(View 12424, Like 137, Rt 50)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/79fb5b2f-c83c-451d-9259-8fc3a2d5afc1)

https://x.com/neurolauncher/status/1773655296356880811?s=46
----------

https://x.com/neurolauncher/status/1774500473015328819?s=46

----------

**CC- CONTENT CREATION**

Video 1: https://youtu.be/iLV645uHmBg?si=wozYyPELW1vZ_dsK

(Note: Sorry G sama, at March I have 2 week exam week, I couldnt be online to much)

**Comment by Gunit2481** [comment]
Good job Leo! 👏
