### ISSUE TITLE
March 2024 Contibution - Emre(Mr.Karahanlı) 

### ISSUE THREAD

**Issue by siyaksares** [AstarNetwork/growth-program#2444]
Twitter: https://twitter.com/mr_karahanl
Telegram Username: @Emret16
Discord Username: mr.karahanli_emre_
Medium: https://medium.com/@emretanis4
ASTAR Native Wallet Address: ZkXuTVXB4s6sPgf42gviV2GcTHkvXks72sbVB7rqevzr2xu

Astar Network Turkey Twitter: https://twitter.com/astarnetworktr_?s=21&t=ISh07fvjMqpmUg40w5HqBg
Astar Network Turkey Telegram: [https://t.me/AstarTurkiye  Personal](https://t.me/AstarTurkiye%E2%80%A8%E2%80%A8Personal)

It's been crazy.

Over 1,000 people listened to my Astar Space. Also I've been getting views of 45,000..My viewership was 672 THOUSAND, I'm adding more details.
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/9ff99ed3-d682-41f0-bb32-e51ac31f0b1b)

New 216 follower
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/5b9c321c-851c-4397-aa54-5174ec9212b1)

Cm:COMMUNITY SUPPORT
I have been the top contributor for months. I also moved up to 1st place in CM and became the top contributor to our community in telegrams. My number of messages increased by 25%. This includes our discord server and telegram.
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/00d52671-52ae-4013-87b6-fb8fb4196fa2)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/be97f287-d9f6-40a7-9217-f575397c49c7)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/a346c9b0-804d-48a5-8910-974ec50d5866)

############################################################

GOV - Governance and Project Engagement
Gov-https://forum.astar.network/u/mrkarahanli-emre/activity
I pondered important issues such as $Pink distribution. I participated in active forum activities. I engaged in subjective and creative discussions.
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/32e768a3-9448-434c-8219-feb842bd5a54)

############################################################

SM - SOCIAL MEDIA ENGAGEMENT
This month I organized an ASTARNETWORK Space for 1000+ people.
I've been getting reports of 45,000.
Thousands of people watched my Youtube video!!!
My tweets about Astar have a high number of views.
45.000,20.000.. and more interactions!

45.000
https://x.com/mr_karahanl/status/1771587655769206794?s=46
![WhatsApp Görsel 2024-04-07 saat 23 31 20_0ebddb14](https://github.com/AstarNetwork/growth-program/assets/78142371/d00ef21f-d69e-4c6d-9a95-33c50201830c)

Twitter space with 1000+ people!
https://x.com/mr_karahanl/status/1772699874540040217?s=46
![WhatsApp Görsel 2024-04-07 saat 23 33 47_f2292905](https://github.com/AstarNetwork/growth-program/assets/78142371/433622a3-650a-4751-aa8b-667e53628f06)

15000
https://x.com/mr_karahanl/status/1774057940174987588?s=46
![WhatsApp Görsel 2024-04-07 saat 23 37 22_a8240c32](https://github.com/AstarNetwork/growth-program/assets/78142371/2852b18d-6dc6-4a0d-b9c9-aba7585c5a6a)

9500
https://x.com/mr_karahanl/status/1765700437594845696?s=46
![WhatsApp Görsel 2024-04-07 saat 23 23 27_01682185](https://github.com/AstarNetwork/growth-program/assets/78142371/d16120b9-ee83-4da1-97f8-0e2dae9c953c)

6500
https://x.com/mr_karahanl/status/1766115253627060715?s=46
![WhatsApp Görsel 2024-04-07 saat 23 25 32_7e108f8e](https://github.com/AstarNetwork/growth-program/assets/78142371/aad5796d-5a8e-4f0f-9c8d-279c03bcacf3)

6500
https://x.com/mr_karahanl/status/1772606201114644761?s=46
![WhatsApp Görsel 2024-04-07 saat 23 34 38_f951445b](https://github.com/AstarNetwork/growth-program/assets/78142371/c0334a6d-0df5-4a73-b870-ca8d55676ec9)

5000
https://x.com/mr_karahanl/status/1765421710705102933?s=46
![WhatsApp Görsel 2024-04-07 saat 23 22 18_af9cc694](https://github.com/AstarNetwork/growth-program/assets/78142371/edf2750b-ed12-4c38-acb9-708d35b2e069)

4500+YOKİ VİDEO, 1200 VİDEO VİEW
https://x.com/mr_karahanl/status/1766763330079723639?s=46
![WhatsApp Görsel 2024-04-07 saat 23 27 41_39df9f35](https://github.com/AstarNetwork/growth-program/assets/78142371/a874ada3-4b69-4ed9-aa3b-4ef5ced2dd79)

3500
https://x.com/mr_karahanl/status/1773464771246924009?s=46
![WhatsApp Görsel 2024-04-07 saat 23 36 25_5e38de96](https://github.com/AstarNetwork/growth-program/assets/78142371/1659377c-5ee3-42c7-81ec-d0f6874e04ac)

3200
https://x.com/mr_karahanl/status/1765717354292314269?s=46
![WhatsApp Görsel 2024-04-07 saat 23 24 49_510f2b39](https://github.com/AstarNetwork/growth-program/assets/78142371/8b200ed6-fb87-47b2-aef7-b4ea6a49884f)

3200
https://x.com/mr_karahanl/status/1772926546942054505?s=46
![WhatsApp Görsel 2024-04-07 saat 23 35 39_4940d92b](https://github.com/AstarNetwork/growth-program/assets/78142371/6a1fec9a-2f28-4c8c-975a-30238324a40d)

2800
https://x.com/mr_karahanl/status/1763948553850740795?s=46
![WhatsApp Görsel 2024-04-07 saat 23 20 08_c5eb4e83](https://github.com/AstarNetwork/growth-program/assets/78142371/70112be3-9482-442e-b227-ba989bf8c612)

2300
https://x.com/mr_karahanl/status/1766555873697030608?s=46
![WhatsApp Görsel 2024-04-07 saat 23 26 25_492e19f6](https://github.com/AstarNetwork/growth-program/assets/78142371/15659c13-50f1-40f9-8251-29e39f708144)

1700
https://x.com/mr_karahanl/status/1765051151475429484?s=46
![WhatsApp Görsel 2024-04-07 saat 23 21 06_9957c6fd](https://github.com/AstarNetwork/growth-program/assets/78142371/089c933c-8f2f-4f5d-a681-9b9eedcdeb7a)

############################################################

VIDEO;

YOKI ORIGİN VİDEO #1
1200 ACTIVE VIEWS
4600 TWEET VIEWS
12 minute
https://twitter.com/mr_karahanl/status/1766763330079723639
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/43d30da6-ffc8-4ac4-b363-602890ebb526)

#########

TWITTER SPACE
1.120 MEMBER!!
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/735efc0a-2d25-4479-81c6-7b3f64789126)
https://twitter.com/i/spaces/1yoKMwBbDEeJQ

############################################################

OTHER;
A new proposal for $PINK. It was received very positively by the ambassadors.![image](https://github.com/AstarNetwork/growth-program/assets/78142371/39d8635d-f413-44db-b546-c9ff6e44d04f)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/8dec52a9-7dee-49cd-8d0f-568c6550247c)

#########

BUG or ERROR RAPORTSs;
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/22dccfa7-89aa-4b15-a3af-2936a5275fa1)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/78366ab4-1bbc-46ac-8fac-0e946f38e856)

#########

Handmande Visual
![GID98_fWQAAysD3](https://github.com/AstarNetwork/growth-program/assets/78142371/57aa0c56-1a98-49f6-9367-adecd52fa5e3)

**Comment by Gunit2481** [comment]
Good job Emre!
