### ISSUE TITLE
March 2024 Contribution - Danchoi

### ISSUE THREAD

**Issue by iamdanchoi** [AstarNetwork/growth-program#2445]
Telegram Username: @dan_choi
Discord Username: danchoi
ASTR Wallet Address: bRuaSxsUKcnB7gXt5pvwyAP49ptARTFVfAq9P1H6GeCxibd

Mandatory tasks
[CM]
Manage the Korean TG ( https://t.me/astar_kr )

Optional Tasks
[SM]

https://t.me/officialunivercityofcrypto/18290
Launch of zkEVM
4.3k views/ 8 replies / 22 react

https://t.me/officialunivercityofcrypto/18558
Packs reveal date post
4.5k views/ 7 replies / 24 react

https://t.me/officialunivercityofcrypto/18609
All info about Packs
3.2k views/ 13 replies / 15 react

[CC]

https://t.me/officialunivercityofcrypto/18329
Me struggling to try Yoki Origin
3.1k views/ 11 replies / 21 react

https://t.me/officialunivercityofcrypto/18331
how to bridge l2 -> astar zkevm and how to claim OMA tokens
3.8k views/ 38 replies / 25 react

https://t.me/officialunivercityofcrypto/18417
Giving away 5WL spots on PACKS
4.7k views/ 156 replies / 45 react

https://t.me/officialunivercityofcrypto/18419
Giving away 5WL spots on PACKS
3.7k views/ 18 replies / 43 react

https://t.me/officialunivercityofcrypto/18554
Posted about minting PACKS
8.6k views/ 44 replies / 32 react

https://t.me/officialunivercityofcrypto/18557
I research on the poke-mon price
8.7k views/ 32 replies / 24 react

[EM]

https://t.me/officialunivercityofcrypto/18488
Astar Korea meet up posting
3.5k views/ 8 replies / 18 react

https://t.me/officialunivercityofcrypto/18583
I went to Astar meetup and uploaded video
4k views/ 39 replies / 48 react

= All of above I have made 52.1k views. spreaded Astar news and info to korean crypto people.
Also, as of proudly well known kol , I participated Astar Korea meet-up.

**Comment by Gunit2481** [comment]
Good work Dan! Thank you for your support and participation in Astar Meetup. 👏
