### ISSUE TITLE
March 2024 Contibution - Max.eth

### ISSUE THREAD

**Issue by MaxEthHealthy** [AstarNetwork/growth-program#2446]
Telegram Username: @max_eth_heatlhy
Discord Username: max.eth.healthy
X User name: @max_eth_heatlhy
ASTR Wallet Address: WAgeWZSPzQdJf58kELDGBp2P8VRCNFie9s3j7fgvpJduNMX

---

**CM**:

Telegram: again a lot of technical questions from the French community on telegram. 

<img width="1126" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/9c74990e-ad3e-4b52-9013-acce3dcd4626">

Discord:

<img width="429" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/53c6c6e5-a0e6-4972-95c2-0ef3510753c7">

- support and feedback to aspiring ambassador 

<img width="492" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/9e464e36-96eb-452b-8f13-b7f3778cdd26">

Twitter.

Regular contacts with people of the community to build relation and keep the community engaged.

<img width="559" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/ff557a29-8eb0-4e37-ae23-5926073e729d">

<img width="561" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/b81f1b34-dde3-4253-8b94-63459d90c137">

<img width="597" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/2239d976-bb91-46a5-8248-c05b9004517a">

<img width="561" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/f3c2ac50-9ea9-4494-9d2f-8a9424acd7de">

**GOV**

I was more active this month and enjoyed it. 

https://forum.astar.network/u/max.eth/activity
https://forum.astar.network/u/max.eth/summary

(not screening all:)
<img width="947" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/5b85dd8c-daa4-4705-8af8-aaf5cfef6779">
<img width="932" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/71baf793-5e1c-4b17-8ac0-039532897881">

**SM**

**Analytics**
<img width="1199" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/c3de7d89-f40c-4fb2-9f6b-7d202aa8a154">

**Samples of posts**:
<img width="602" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/0decb742-b633-4811-b528-e2ae6f260a02">

<img width="575" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/9f2348c2-4a07-4e74-88a3-c83a1181aa24">

<img width="583" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/33e99b6c-549d-4e5d-8912-bf7bd054c03f">

**CC**

- launch of the Astar French version of the newsletter and other articles. _Can I share it in the French TG?_
For now I translated the newsletter from the fondation. I will also translate other things like my most important article.

https://www.bonzai.pro/astar_newsletter_fr/lp/1124/astar-newsletter-fr

- articles from the French newsletter:

Campagne Yoki
https://www.bonzai.pro/astar_newsletter_fr/posts/60v2_7086/yoki-orgins-participez-maintenant-pour-obtenir-denormes-recompenses

Update ecosystème Astar
https://www.bonzai.pro/astar_newsletter_fr/posts/mVrj_7085/astar-ecosystem-updates

Plus de 700 000 holders ASTR, plus de 1 million de portefeuilles, et bien plus encore 🤩
https://www.bonzai.pro/astar_newsletter_fr/posts/9Mma_6537/plus-de-700-000-holders-astr-plus-de-1-million-de-portefeuilles-et-bien-plus-encore

Guide Facile d'Astar: dApp Staking v3. "L'App Store du Web 3".
https://www.bonzai.pro/astar_newsletter_fr/posts/ZQbx_6539/guide-facile-dastar-dapp-staking-v3-lapp-store-du-web-3

- Blog Articles

- All you need to know about new Astar Zkevm
https://medium.com/@max.eth/all-you-need-to-know-about-new-astar-zkevm-ae81f9084f53
https://www.bonzai.pro/maxeth/posts/zOrY_7090/all-you-need-to-know-about-new-astar-zkevm

- Talking about Astar to every event I go, every person I meet.
This month, I went to events like Solana first Paris event with the foundation or Bitcoin maxi event in Paris.

**Comment by Gunit2481** [comment]
Good work Max! You could progress in community management and governance by getting more involved. 👍
