### ISSUE TITLE
April 2024 Contribution - Tech. Ambassador: Carlos Rodríguez

### ISSUE THREAD

**Issue by Juminstock** [AstarNetwork/growth-program#2447]
_Technical ambassador information:_

Telegram Username: **@Juminstock**
Discord Username: **@Juminstock#8856**
ASTR Wallet Address: **ZJKp9fuuQihYopwLEmxZ55zU5WMpeXi95HAPRPUiGcZgZQz**

**Contributions:**

**DS - Support developers on Astar Discord:**

<img width="1109" alt="Screenshot 2024-05-01 at 00 20 31" src="https://github.com/AstarNetwork/growth-program/assets/105810861/82324a33-7fd9-492c-be76-6129ba076986">
<img width="1109" alt="Screenshot 2024-05-01 at 00 20 53" src="https://github.com/AstarNetwork/growth-program/assets/105810861/6416ae79-8042-43fd-8c04-e627564613ba">
<img width="1109" alt="Screenshot 2024-05-01 at 00 21 07" src="https://github.com/AstarNetwork/growth-program/assets/105810861/4238afc9-63b6-4c0f-b6d1-0b99af40e730">
<img width="1109" alt="Screenshot 2024-05-01 at 00 21 24" src="https://github.com/AstarNetwork/growth-program/assets/105810861/cedfa47b-c601-48ef-b967-a0339a5ca79e">
<img width="1109" alt="Screenshot 2024-05-01 at 00 21 42" src="https://github.com/AstarNetwork/growth-program/assets/105810861/df653f73-29bf-4097-b6f7-4f725eea9164">
<img width="1109" alt="Screenshot 2024-05-01 at 00 21 55" src="https://github.com/AstarNetwork/growth-program/assets/105810861/f2a9a890-aa7c-4d20-817c-d9849ba65fdb">
<img width="1109" alt="Screenshot 2024-05-01 at 00 22 08" src="https://github.com/AstarNetwork/growth-program/assets/105810861/9ae30683-c5fa-414d-94a6-30f4b538d548">
<img width="1109" alt="Screenshot 2024-05-01 at 00 22 21" src="https://github.com/AstarNetwork/growth-program/assets/105810861/21953e85-9ee8-4d65-9486-c1648a2436dc">
<img width="1109" alt="Screenshot 2024-05-01 at 00 22 59" src="https://github.com/AstarNetwork/growth-program/assets/105810861/bdf2ee5b-0841-4ce5-a8e8-0e629435ef27">
<img width="1109" alt="Screenshot 2024-05-01 at 00 23 12" src="https://github.com/AstarNetwork/growth-program/assets/105810861/b51ec025-80c8-4b44-bf19-195f341adcbe">
<img width="1109" alt="Screenshot 2024-05-01 at 00 23 22" src="https://github.com/AstarNetwork/growth-program/assets/105810861/34f1722b-ce40-47e0-8519-248ad21c7fdb">
<img width="1109" alt="Screenshot 2024-05-01 at 00 23 33" src="https://github.com/AstarNetwork/growth-program/assets/105810861/dabb98d6-3282-48bd-80e2-bdbd91c58962">
<img width="1109" alt="Screenshot 2024-05-01 at 00 23 44" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a5a88597-becc-4895-8c01-92fc61b3e4b9">
<img width="1109" alt="Screenshot 2024-05-01 at 00 23 59" src="https://github.com/AstarNetwork/growth-program/assets/105810861/4e86e79c-e8f6-47fa-a36f-a575987678cc">
<img width="1109" alt="Screenshot 2024-05-01 at 00 24 13" src="https://github.com/AstarNetwork/growth-program/assets/105810861/d4af8900-ad87-49a4-a106-cb3c9480b1e6">
<img width="1109" alt="Screenshot 2024-05-01 at 00 24 27" src="https://github.com/AstarNetwork/growth-program/assets/105810861/baa0dc8c-99b2-4459-80b5-5eb07d4e9877">
<img width="1109" alt="Screenshot 2024-05-01 at 00 24 51" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3fb56102-da9a-49b3-b311-d48954dfe0f3">
<img width="1109" alt="Screenshot 2024-05-01 at 00 25 07" src="https://github.com/AstarNetwork/growth-program/assets/105810861/46443a4f-f6f5-4873-8171-41b6575dc51d">
<img width="1109" alt="Screenshot 2024-05-01 at 00 25 17" src="https://github.com/AstarNetwork/growth-program/assets/105810861/8259d940-6f88-405c-9532-f7d98dc59e1f">
<img width="1109" alt="Screenshot 2024-05-01 at 00 25 23" src="https://github.com/AstarNetwork/growth-program/assets/105810861/f7280b21-b1b4-4545-acb5-cbcc9ff316ce">
<img width="1109" alt="Screenshot 2024-05-01 at 00 25 37" src="https://github.com/AstarNetwork/growth-program/assets/105810861/cbc19cfa-b523-42bb-b17c-5c028065082a">
<img width="1109" alt="Screenshot 2024-05-01 at 00 25 47" src="https://github.com/AstarNetwork/growth-program/assets/105810861/d728cd24-d083-40c0-bd5f-487179605b5c">
<img width="1109" alt="Screenshot 2024-05-01 at 00 26 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3fae993b-f545-42cd-ba76-1d861e71c743">
<img width="1109" alt="Screenshot 2024-05-01 at 00 26 22" src="https://github.com/AstarNetwork/growth-program/assets/105810861/136c6012-bac8-4657-a223-55da1fcd7a65">
<img width="1109" alt="Screenshot 2024-05-01 at 00 26 33" src="https://github.com/AstarNetwork/growth-program/assets/105810861/891ba2a5-1c15-4235-9d2a-40fb6f86b9d8">
<img width="1109" alt="Screenshot 2024-05-01 at 00 26 46" src="https://github.com/AstarNetwork/growth-program/assets/105810861/63e0aff2-8fb8-41ae-8658-91f8528ffc2a">
<img width="1109" alt="Screenshot 2024-05-01 at 00 26 58" src="https://github.com/AstarNetwork/growth-program/assets/105810861/65c2f9e9-6703-4e14-954b-fe29a98937ff">
<img width="1109" alt="Screenshot 2024-05-01 at 00 27 09" src="https://github.com/AstarNetwork/growth-program/assets/105810861/b800ae1d-7e47-4dff-8e58-abb786f3db89">
<img width="1109" alt="Screenshot 2024-05-01 at 00 27 21" src="https://github.com/AstarNetwork/growth-program/assets/105810861/87953362-4e6c-4088-9555-bed961e6b421">
<img width="1109" alt="Screenshot 2024-05-01 at 00 27 31" src="https://github.com/AstarNetwork/growth-program/assets/105810861/aebe6191-be43-49de-90ea-d9dd4fa0a0be">
<img width="1109" alt="Screenshot 2024-05-01 at 00 27 42" src="https://github.com/AstarNetwork/growth-program/assets/105810861/8879249e-ee58-462b-b9ce-3e8f98384434">

**DS - Support users on Astar Discord:**

<img width="1112" alt="Screenshot 2024-05-01 at 21 38 49" src="https://github.com/AstarNetwork/growth-program/assets/105810861/952230bb-b075-4489-a41a-7cfcf08f5b76">
<img width="1112" alt="Screenshot 2024-05-01 at 21 39 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/fde08298-612f-4e08-b023-487b8f633745">
<img width="1112" alt="Screenshot 2024-05-01 at 21 39 14" src="https://github.com/AstarNetwork/growth-program/assets/105810861/df3b25f8-326f-4bde-8bf1-f64004117481">

**GOV - Engaged in governance discussion:**

- https://forum.astar.network/u/juminstock/activity

**EM - Events managed:**

- Planning and organize two Astar Network events in Venezuela: https://forum.astar.network/t/astar-meetups-in-venezuela/6671?u=juminstock

**CM - Content management:**

- Twitter post about Astar testnet incentivized: https://x.com/Juminstock/status/1773362299815833852
- Twitter post about new Astar website UX: https://x.com/Juminstock/status/1774783420473729092
- Twitter post about Astar docs translation: https://x.com/Juminstock/status/1777737946608615748
- Twitter thread about ETH Seoul hackathon: https://x.com/Juminstock/status/1778393288623403300
- Astar bulletin post: https://x.com/AstarBulletin/status/1782666989757939936
- Twitter post about Astar events in Venezuela: https://x.com/Juminstock/status/1783165610282623091
- Twitter space about Astar dApp staking program: https://x.com/LuckyDapp/status/1778337385564221562
- Twitter space about Astar network events in Venezuela: https://x.com/Juminstock/status/1785508927477588455
- Medium article about Astar developer report: https://medium.com/the-astar-bulletin-tab/developer-newsletter-april-2024-spanish-version-d5c88f9f7b36

**Other contributions:**

- 10 new sections of the documentation translated: 

<img width="1173" alt="Screenshot 2024-05-01 at 00 48 43" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3d5a23d4-93fe-4563-b77e-88f924d636f7">
<img width="1173" alt="Screenshot 2024-05-01 at 00 50 10" src="https://github.com/AstarNetwork/growth-program/assets/105810861/afea85fa-362b-4efd-af88-e98a07c8bbd6">

**Comment by Gunit2481** [comment]
Good work Carlos! Thank you for initiating and supporting these events. 💯

**Comment by Juminstock** [comment]
Thank you for your words, G! 🙏🏼⚡️
