### ISSUE TITLE
April 2024 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2452]
Telegram Username: `@actlee`
Discord Username: `pithecus.astr`
ASTR Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

### Mandatory tasks
**CM**
- Manage the Korean TG community & Discord channel
- Share announcements
- Help/respond the community for various topics in general, especially these days for Yoki Origins campaign and the reorg incident, dApp staking v3 and/or investment related questions
- Less active MoM but still very active community (2.3k+ members, 7.5k+ messages, and 200- active users)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/802e4930-d881-43c3-b00a-230c1b25542a)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b7ede7e7-030e-4538-8a20-75c2dcb8b135)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/d2f427ab-aae3-4003-8425-74d4f3ac6e59)

**GOV**
https://forum.astar.network/u/pithecus/activity
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/1a6d5a60-1fcb-45df-a194-5a54498a34a3)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/a2b599f4-023b-400d-93c8-5b8c62bcaaee)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/d25da1bf-7c68-4173-ae22-5513e50c7a4e)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/c1ef8c9f-68b3-4915-8fc9-f8adc37e0009)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/26351e8d-efb0-4540-8fe1-85259e23a7a0)

### Optional tasks
**SM**
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/5c1b7513-c4c7-4a74-bc13-2ac2c971083e)
https://twitter.com/spmlaihm/status/1783509999831875599
https://twitter.com/spmlaihm/status/1782771675043353051
https://twitter.com/spmlaihm/status/1782764391709933742
https://twitter.com/spmlaihm/status/1782747950046761409
https://twitter.com/spmlaihm/status/1782747597704135092
https://twitter.com/spmlaihm/status/1781557667720269940
https://twitter.com/spmlaihm/status/1781557670698205648
https://twitter.com/spmlaihm/status/1781557673827213384
https://twitter.com/spmlaihm/status/1781557676809326598
https://twitter.com/spmlaihm/status/1781557678742925419
https://twitter.com/spmlaihm/status/1781554044609147083
https://twitter.com/spmlaihm/status/1781554047243243818
https://twitter.com/spmlaihm/status/1781554050397347888
https://twitter.com/spmlaihm/status/1781554053035479156
https://twitter.com/spmlaihm/status/1781554055791120613
https://twitter.com/spmlaihm/status/1781554057615741016
https://twitter.com/spmlaihm/status/1780453353782218813
https://twitter.com/spmlaihm/status/1780449803605778494
https://twitter.com/spmlaihm/status/1779728153239236913
https://twitter.com/spmlaihm/status/1779728155588112484
https://twitter.com/spmlaihm/status/1779728157194486040
https://twitter.com/spmlaihm/status/1779724742221565973
https://twitter.com/spmlaihm/status/1776153562801651933
https://twitter.com/spmlaihm/status/1776152184423399635
https://twitter.com/spmlaihm/status/1775646021827035516

**CC**
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/49a79820-f6f9-4793-9d61-41b76fe2b2e1)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ee129ace-7fab-4ef5-bf35-577a8250b077)

- 아스타 네트워크의 The Graph 활용 방안 (https://medium.com/astar-korea/cbf708490d06)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/309c3cad-53a9-4ae6-b9d1-bd2f9bda4490)

- 아스타 네트워크 —『 크로스체인』 튜토리얼 (https://medium.com/astar-korea/318aaa58bb92)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/e685fcde-8809-4bdf-afd1-db98d4b19cb4)

**Comment by Gunit2481** [comment]
Good work in supporting the Korean community. 🙌
