### ISSUE TITLE
April 2024 Contribution - marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#2453]
Telegram : Soulstar / https://t.me/marvelet6 (previously Soul Eater)
Discord : marvelet#8647
Native Address : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

___

### CM
**TELEGRAM**
Astar Indonesia
Link : https://t.me/astarnetwork_id
Total Members : 251 members (exclude Rose Bot, increased 11 member)
Combot Link : https://combot.org/c/-1001288040165/a
Screenshots: :

![TELE_SS](https://github.com/AstarNetwork/growth-program/assets/87793956/64a2b956-7efa-444b-89bc-a0ff4b88676c)

Comments :
- Less active compare last months, there are 2 possible reasons : Many Indonesians celebrated Eid Mubarak and there was a long public holiday for like 7 days + Because our chain was trouble because ETH Reorg.
- Demands for playing Yoki a bit dropped outside Astar community because of ETH Reorg issue, eventhough slightly rising up again after the release YoPort 3 and 4.
-  Many communities in and outside Astar community were asking is there any DeFi campaign

For Discord , kindly check my activity there

___

### GOV
**FORUM**
My activity on Astar Forum
[https://forum.astar.network/u/souleater/activity](https://forum.astar.network/u/souleater/activity)
[https://forum.astar.network/u/souleater/summary](https://forum.astar.network/u/souleater/summary)

Screenshot :

![FORUM_SS](https://github.com/AstarNetwork/growth-program/assets/87793956/f565775f-fd3c-4c5e-b986-d8ada98b29b1)

For Discord, kindly check my activity there

___

### SM
**TWITTER**
Personal : https://twitter.com/rudayruday
Analytic Screenshot :

![XPERSONAL_SS](https://github.com/AstarNetwork/growth-program/assets/87793956/ae2a974a-0ccb-4c80-a637-80ba0359f64c)
![XPERSONAL_SS_2](https://github.com/AstarNetwork/growth-program/assets/87793956/df8a61e5-adc1-4cd2-b6bb-53cc624be44e)

In-depth twitter activity:

[daily_tweet_activity_metrics_rudayruday_20240401_20240501_en.csv](https://github.com/AstarNetwork/growth-program/files/15197602/daily_tweet_activity_metrics_rudayruday_20240401_20240501_en.csv)

===
Astar Indonesia : https://twitter.com/AstarNetwork_ID
Analytic Screenshot :

![XASTRID_SS](https://github.com/AstarNetwork/growth-program/assets/87793956/39322426-6bed-43f7-b95a-71198223a412)

In-depth twitter activity:

[tweet_activity_metrics_AstarNetwork_ID_20240401_20240501_en.csv](https://github.com/AstarNetwork/growth-program/files/15197591/tweet_activity_metrics_AstarNetwork_ID_20240401_20240501_en.csv)

___

### CC
**The Astar Bulletin**
Writing a monthly article on Astar Bulletin, teasing about Astar roadmap in 2024 regarding offline meetup Astar <> Startale
Title :
Building The Road
[https://theastarbulletin.news/building-the-road-a694d7313880](https://theastarbulletin.news/building-the-road-a694d7313880)

___

### EVENT
Notes : I didn't hosted this event, I was invited as a panelist representing Astar Network
When : May 27th, 2024
Where : Ganara Art Space , Plaza Indonesia
Event Title : zkSync Indonesia Community Meetup - L2 Battle
Attendants : 150-200
Proofs : 
![event meetup 2](https://github.com/AstarNetwork/growth-program/assets/87793956/641ac7cd-545c-45cc-908b-c7382be7e1e4)
![event meetup 3](https://github.com/AstarNetwork/growth-program/assets/87793956/35ea127d-3483-4a5e-8a9c-ea1d8a435447)
![event meetup 1](https://github.com/AstarNetwork/growth-program/assets/87793956/28241daa-ec5e-4898-a783-77ef54aceb55)

___

That's all my contributions for April 2024

**Comment by Gunit2481** [comment]
Nice to see you as a panelist at this event! 📸
