### ISSUE TITLE
April 2024 Contribution - VasaKing

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2454]
Telegram : @VasaKing

Discord Username: @VasaKing

ASTR Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

----- CM - Community Support & Management -----

Yoki Origins users support on the Italian Astar Community Telegram and Astar Discord 

----- GOV - Forum partecipation -----

https://forum.astar.network/u/vasaking/activity

----- VSM - Astar Italia Twitter -----

Dwelli x Astar zkEVM https://x.com/Astar_Italia/status/1774733830278045920

C14 on Astar zkEVM https://x.com/Astar_Italia/status/1774735277803688182

Astar in ETHSeoul https://x.com/Astar_Italia/status/1774765380474450349

NINJA airdrop https://x.com/Astar_Italia/status/1775829918464573938

zKyoto x Dwellir https://x.com/Astar_Italia/status/1775831732274487349

Quickswap YoPort https://x.com/Astar_Italia/status/1775840674522280136

VLS YoPort https://x.com/Astar_Italia/status/1775873956710371402

HIS YoPort https://x.com/Astar_Italia/status/1777254027350122961

Astar Upgrade https://x.com/Astar_Italia/status/1777260601921638704

Astar zk Gaming Space https://x.com/Astar_Italia/status/1777279198081564908

HyperNative x Astar https://x.com/Astar_Italia/status/1777284483617571044

HIKIzone https://x.com/Astar_Italia/status/1777292671951757610

Golden Fox Boost https://x.com/Astar_Italia/status/1777299384830468531

Mazda x Astar zkEVM https://x.com/Astar_Italia/status/1777303581554520309

D'CENT on Astar zkEVM https://x.com/Astar_Italia/status/1777329792251007389

L2X YoPort https://x.com/Astar_Italia/status/1777338049489166473

VLS Promo https://x.com/Astar_Italia/status/1777342133919215885

Closepa YoPort https://x.com/Astar_Italia/status/1777632002675548519

Fireblocks event in Japan with Sota https://x.com/Astar_Italia/status/1777688795183280354

SkyLab promo https://x.com/Astar_Italia/status/1777693355054375142

The Wonderist NFTs on Astar https://x.com/Astar_Italia/status/1777700891673477228

Astar Upgrade report https://x.com/Astar_Italia/status/1778341513153425639

Sony Gold Sponsor on TeamZ promo https://x.com/Astar_Italia/status/1778399857968861586

Astar Upgrade report 2 https://x.com/Astar_Italia/status/1779461996741587438

Sota on TeamZ https://x.com/Astar_Italia/status/1779467458346143840

Arthswap YoPort https://x.com/Astar_Italia/status/1779807558393311449

Quickswap part 2 https://x.com/Astar_Italia/status/1779870523578565014

Astar Community Call https://x.com/Astar_Italia/status/1782331675134865722

Sota x ZeLo event https://x.com/Astar_Italia/status/1782346192220774505

0n1Force x Astar Meetup https://x.com/Astar_Italia/status/1782349029550051521

Sota x Yasushi Akimoto https://x.com/Astar_Italia/status/1782366898526507170

Reorg update https://x.com/Astar_Italia/status/1782746603394150508

YoPort #3 https://x.com/Astar_Italia/status/1782751265698586663

Polkadot North America x Astar hackathon https://x.com/Astar_Italia/status/1782763580405821887

NFTs2Me x Astar https://x.com/Astar_Italia/status/1782770817643708818

BattleFly YoPort https://x.com/Astar_Italia/status/1782775862313541878

NEET YoPort https://x.com/Astar_Italia/status/1782816708308193293

DFG Japan Promo https://x.com/Astar_Italia/status/1783079495068455001

Yoki You425 docs promo https://x.com/Astar_Italia/status/1783091987106639962

Cryptact x Astar zkEVM  https://x.com/Astar_Italia/status/1783099974516969737

YoPort #4 https://x.com/Astar_Italia/status/1783111826294661369

Astar stats https://x.com/Astar_Italia/status/1783164004149674242

Umbrella x Astar https://x.com/Astar_Italia/status/1784859997618225282

YooldoYoPort https://x.com/Astar_Italia/status/1784873826372743549

VLS Simple Staking promo https://x.com/Astar_Italia/status/1785264515078103166

Astar x Supra Labs https://x.com/Astar_Italia/status/1785262361932161423

Mazda AD https://x.com/Astar_Italia/status/1785309982377869643

Yuliverse YoPort https://x.com/Astar_Italia/status/1785365321001349425

![Astar April ](https://github.com/AstarNetwork/growth-program/assets/63927981/653db070-fedb-43d6-80be-d407a1799116)
![Astar April 2](https://github.com/AstarNetwork/growth-program/assets/63927981/e65aefde-7d2f-4962-a49b-6f4e6c645c90)

----- CC - Medium -----

Astar Upgrade report https://medium.com/@AstarItalia/astar-zkevm-rapporto-sullaggiornamento-del-network-ae5caf0f5718

Astar Downtime report https://medium.com/@AstarItalia/dettagli-sul-downtime-di-astar-zkevm-e74186b995e3

**Comment by Gunit2481** [comment]
Good Job Vasa! 💪
