### ISSUE TITLE
March 2024 Contribution - Van

### ISSUE THREAD

**Issue by eudomar500** [AstarNetwork/growth-program#2455]
**Telegram Username:** @DTK21

**Discord Username: Van9719**

**ASTR Wallet Address: YAVPSp5GTZePeR74c9qvmojFcFPtxcJZnyEh1mHu5UVqqat**

# Contributions:

# 1. CM - Community Management

### -Combot Link: https://combot.org/c/1314210486

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/b2a11e53-e46b-45f3-afde-323b745b75eb)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/ff4485cd-6638-4ca1-8732-8ca56bd56875)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/be7b6173-d418-4e99-87d7-0bb072a5d92c)

# 2. GOV - Governance & Project Engagement

### -Profile: https://forum.astar.network/u/vangardem/activity

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/7b98ca29-e5b2-4109-ae22-d20765f99e06)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6430f358-9a87-4fa3-ba11-a7fa20f35a87)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/fa5acd4d-2835-46ef-8e4f-42e2f481cb7b)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/afd5ca63-41d8-4709-8812-5a394fbb0ef0)

# 3. SM - Social Media Engagement

### Impressions and post activity:

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6d257e2a-d044-4131-9a07-dc8ee950d1dc)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/ba5dc40f-6964-4c58-a859-4c277ccd5f05)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/8871a30d-d73a-4cc4-940e-b049457ce123)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/9769caec-efc8-4705-b033-04c86549ac6a)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/05656666-0cc3-4f28-bebf-25e7afb2e08e)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e8810d49-41e5-45f9-9dfd-8f613dce6418)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/dc987d7a-8dcd-4972-816e-0de1750a074c)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/838d0c0d-9337-43a3-8f27-7571ac36e9cd)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6dd6b112-3c52-469c-aba0-56662b3c02ca)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/b8a47ff8-14a0-4ece-a8d6-d0df5841d257)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/7196d801-f017-4302-92d7-c186bd9cc304)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/f42c2feb-60d1-44a5-9dea-d6be7c9d6465)

# 4. Others:

### Link: https://astarweeklynews.substack.com/

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/8acc4f86-c367-4c8b-ae7c-02f6e3c9023b)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/053dd349-82ac-49b2-858d-c207b0a6afae)

# Total Views - April: 355

# Total Users: 194

https://github.com/AstarNetwork/growth-program/assets/39355497/67fe48ae-5b65-400c-90f1-0c6bc5fb35a9

![Elevate Your Tech Game with Thynk Unlimited!](https://github.com/AstarNetwork/growth-program/assets/39355497/82da2aa8-a59c-4b20-8597-6aa76d9e7609)

![Elevate Your Tech Game with Thynk Unlimited! (1)](https://github.com/AstarNetwork/growth-program/assets/39355497/ceef2f82-6249-41e9-a104-2a74953d3af9)

# Thank You!

**Comment by Gunit2481** [comment]
Good work! 👏
