### ISSUE TITLE
April 2024 Contribution - defiguy

### ISSUE THREAD

**Issue by astardefi** [AstarNetwork/growth-program#2456]
April 2024 Contribution - defiguy
Telegram Username: @defiguy2022
Discord Username: defiguy
Twitter User name: defiguy22
ASTR Wallet Address: YJ9ZyKwzX6tLh21eV1YT61EpihraYAdJYbcpyJFDwdyrfi7

# CM
## defiguy telegram (248 members)

![Screenshot 2024-05-05 at 18 39 32](https://github.com/AstarNetwork/growth-program/assets/104277195/5d369c06-9bc1-4b2f-b4ba-598de478f364)
Link - https://t.me/+QfslDL_epwZlMmUx

![MAIO-2024-TELEGRAM](https://github.com/AstarNetwork/growth-program/assets/104277195/7cb3e619-0c9b-4476-bf11-b3199a9e8fe3)
![MAIO-TELEGRAM-2](https://github.com/AstarNetwork/growth-program/assets/104277195/037eb83a-e1fe-494d-afee-b3adb5665049)

# GOV
![Screenshot 2024-05-05 at 18 36 34](https://github.com/AstarNetwork/growth-program/assets/104277195/5ed5b2ef-ff5e-4f74-b7dd-0a87161ddf21)

https://forum.astar.network/u/defiguy/activity

# SM
## Twitter - defiguy
![Screenshot 2024-05-05 at 20 37 01](https://github.com/AstarNetwork/growth-program/assets/104277195/8a11e744-216b-49aa-92f4-daa18af23db3)

# CC
33K impressions/ Average of 80 live viewers per stream
![Screenshot 2024-05-05 at 18 50 10](https://github.com/AstarNetwork/growth-program/assets/104277195/7804caae-d644-463f-8ca2-d11e0cbcee03)
**SNAPSHOT do AIRDROP chegando na ASTAR!!!** 
![Astar updates (62)](https://github.com/AstarNetwork/growth-program/assets/104277195/bafc3f11-8136-409a-ba3f-a4b814b4b0a8)
https://youtube.com/live/NjZLOSthD8o
**GAMES na ASTAR!! YOKI voltou!!!**
![Astar updates (63)](https://github.com/AstarNetwork/growth-program/assets/104277195/7123fafb-a0ff-4ec7-b764-c1393a65c2f9)
https://youtube.com/live/vFCZW1KpAQE

**Updates ASTAR - VERBODOTSAMA**
https://www.youtube.com/watch?v=cX10QOte724

# BD
## MotoDEX
![Screenshot 2024-05-05 at 18 42 58](https://github.com/AstarNetwork/growth-program/assets/104277195/c84ac9dd-a9a5-4517-934d-197efa608c22)
**Website -** https://motodex.dexstudios.games/
**Dappradar** - https://dappradar.com/dapp/motodex

## Afloat Platform
![Screenshot 2024-05-05 at 18 45 22](https://github.com/AstarNetwork/growth-program/assets/104277195/73678aef-b2ac-4bf1-9306-a2a25488e995)
**Website** - https://afloat.app/

**Comment by Gunit2481** [comment]
Thanks for your work Gustavo!
