### ISSUE TITLE
April 2024 Contribution - bao

### ISSUE THREAD

**Issue by 0xbao** [AstarNetwork/growth-program#2459]
Telegram Username: @bao1993jp
Discord Username: bao#bao1993
Twitter User name: @bao1993jp
ASTR Wallet Address: beeZfXVZppLCGtZuE4jRZLD9RperjqbfCYrC148Np1uv4pE

# Contributions:

### -Supporting to inquiries from the community almost every day
Astar Network Discord: JAPAN channel
Astar Network Discord: SUPPORT channel **(support to Japanese QA)**
Astar Network Japan Telegram: https://t.me/AstarJapan

## -GOV
I posted **22 times** on the Forum and actively participated in governance.
https://forum.astar.network/u/bao/activity

I also got the "Nice Share" badge on several topics and successfully attracted more people to the Forum.
![スクリーンショット 2024-05-05 19 44 16](https://github.com/AstarNetwork/growth-program/assets/123560716/565c0eb5-a4fd-4ca6-89cf-83344f454292)

![スクリーンショット 2024-05-05 19 44 56](https://github.com/AstarNetwork/growth-program/assets/123560716/e0de9892-1954-4ef9-88f6-99a45ff074b1)
![スクリーンショット 2024-05-05 19 45 10](https://github.com/AstarNetwork/growth-program/assets/123560716/e93ea24e-fd27-4a9f-ac24-bbd11e9b5e48)
![スクリーンショット 2024-05-05 19 45 21](https://github.com/AstarNetwork/growth-program/assets/123560716/96b37a5c-a32a-4678-971c-721c0136778b)

### [1] Astar Weekly Journal Apr.7
EN ver.
https://theastarbulletin.news/yoki-lore-62-astar-weekly-journal-3253f79ee774
JP ver.
https://astarweeklyjournal.substack.com/p/yoki-lore

### [2] Astar Weekly Journal Apr.13
EN ver.
https://theastarbulletin.news/summary-of-the-astar-zkevm-incident-63-astar-weekly-journal-9d81e87963f9
JP ver.
https://astarweeklyjournal.substack.com/p/astar-zkevm-dd6

### [3] Astar Weekly Journal Apr.21
EN ver.
https://theastarbulletin.news/summary-of-the-astar-zkevm-incident-part2-64-astar-weekly-journal-4be4b696b56c
JP ver.
https://astarweeklyjournal.substack.com/p/astar-zkevm-b1d

### [4] Astar Weekly Journal Apr.28
EN ver.
https://theastarbulletin.news/astar-zkevm-restart-65-astar-weekly-journal-32f70eb89aab
JP ver.
https://astarweeklyjournal.substack.com/p/astar-zkevm-restart
![スクリーンショット 2024-05-05 19 50 07](https://github.com/AstarNetwork/growth-program/assets/123560716/0bf5c313-743a-414f-a662-bfd64bfb7801)
![スクリーンショット 2024-05-05 19 50 23](https://github.com/AstarNetwork/growth-program/assets/123560716/b4de731e-581d-4b6d-ac27-0b3a4a53a70a)

### -Key posts that contributed to social media engagement
-The post about **"Introduction to the meme coin "$NINJA""** has garnered **26.4k impressions.**(https://twitter.com/bao1993jp/status/1784401405954203715)

-The post about **"Explanation of the Astar zkEVM incident"** has garnered **20.1k impressions.**(https://twitter.com/bao1993jp/status/1777861712936677714)

-The post about **"Explanation of VeryLongSwap"** has garnered **15.9k impressions.**(https://twitter.com/bao1993jp/status/1784794090602889290)

![スクリーンショット 2024-05-05 19 53 23](https://github.com/AstarNetwork/growth-program/assets/123560716/9317bf87-18f8-4ddc-92df-b4d19f52d833)

**Comment by Gunit2481** [comment]
Good job on supporting JP community 💪
