### ISSUE TITLE
April 2024 Contribution - Technical Ambassador: Takeshi 

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/growth-program#2461]
Telegram Username: @tksarah0822
Discord Username: tksarah#tksarah
X(Twitter) Username: @tsarah0822 ( TKLab | tklab.astr )
Astar Wallet Address: aZkj2EgiZkUbnKk6XMp9pf9f9SALXSAaTgz17ZEYUaq2UZy

# Core Tasks (Mandatory)
## 1. DEVELOPER SUPPORT
I advised to build the astar node and helped community members asking dev questions on discord (**builder** and **peers-program**).

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/9c25b1b9-15a5-453a-bd95-1ef3b39cd3d9)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b452e63f-3d92-4ac5-ab6b-c00c8bc9bb06)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/f2253fcd-3a01-4450-8ce9-b0e88ce40d36)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3c098eb1-eadd-4b34-b03c-8d1e4c3750ed)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b19db24c-356e-4134-a074-6a0be7cfb65b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/51909770-f2f1-4f47-bb7a-e1d1cdf290e5)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/72a71ca1-0a42-431a-aa65-1811475f5257)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/a6ba3eb8-5942-4066-b293-e30a07c11325)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/8c5f1835-1a18-4cfa-b7a9-a51e01a4cbcb)

## 2. GOVERNANCE & PROJECT ENGAGEMENT
_https://forum.astar.network/u/tksarah/activity_

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/fc0b63fa-f1aa-4bc2-868c-b2a0e5044f3b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/11728708-9fe9-4df7-a477-ea61bdf769a3)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/6c59fe4e-1ac5-4907-a17e-858f9cd1328f)

# Optional Tasks (Choose up to 2 tasks/month)

### [1] Articles
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/a82ddb78-60fd-44e1-be87-fd1522f66bb6)

Title: **Validium ノードで見るL1とL2の世界**
Published in Note April 27, 2024
https://note.com/tksarahweb3/n/n196c8c5e5ac3
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/782901e4-2ed9-4a27-9016-05a9888687e5)

Title: **The world of L1 and L2 seen with Validium nodes**
Published in Note April 27, 2024
https://theastarbulletin.news/the-world-of-l1-and-l2-seen-with-validium-nodes-c75fa069e9f6
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/00bc93af-3925-4e89-8856-99d7c9c29dcc)

### [2] Astar Document Translation for Japanese

**ローカル Validium ノードのセットアップ**
https://docs.astar.network/ja/docs/build/zkEVM/zk-node/setup-local-validium-node/

**_Github:_**
* https://github.com/AstarNetwork/astar-docs/pull/661

### Viewer and Analytics tool for dApp Staking
View Page: https://agent.sun-t-sarah.work/ (Original https://tksarah.github.io/bc/)

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/e5f84b42-bd64-4107-be8b-58a0a9b44568)

The technologies and elements I am using are as follows:
- Repository: https://github.com/tksarah/bc
- Languages: Perl, Shell, JavaScript, HTML, **R**
- Data: on-chain

### April Update
I have created an R script that generates line charts using CSV data collected via scripts. This allows us to gain insights from historical statistical information from various angles whenever needed.

 - Add R_script.R

![Rplot](https://github.com/AstarNetwork/growth-program/assets/11060137/fda4662a-6866-4a26-928a-fdcdd2dd24c3)
![326743700-8fa7cee2-d6b5-406f-ae22-69a5faee8b49](https://github.com/AstarNetwork/growth-program/assets/11060137/6f57c7cc-fbd7-4e6e-9702-47a4ee6a8831)

I am using the X post for the simplified report of dAppStaking.
* https://twitter.com/tsarah0822/status/1784803747534914022

### TEAMZ SUMMIT 2024
Date: April 13-14
Event Page: https://en.web3.teamz.co.jp/

I participated in this event as part of the management team along with everyone from Astar Japan. I also helped at the Astar Network booth and introduced Astar Network to various people.

X-Post:
* https://twitter.com/tsarah0822/status/1779053313482432733
* https://twitter.com/tsarah0822/status/1779352297186988152
* https://twitter.com/tsarah0822/status/1779421484823515345

![GLB3dh6a0AAM_Ie](https://github.com/AstarNetwork/growth-program/assets/11060137/e114e1b0-99eb-4f36-875d-e794847b03f7)
![GLAfoZCaoAA2w4F](https://github.com/AstarNetwork/growth-program/assets/11060137/4d4f935e-de73-4634-88a0-e72312e90b6f)

**Comment by Gunit2481** [comment]
Amazing contributions Takeshi! Thank you so much.
