### ISSUE TITLE
April 2024 Contribution - Matt

### ISSUE THREAD

**Issue by Matt3Web** [AstarNetwork/growth-program#2462]
# **April 2024 Contribution - Matt**

Telegram Username: @Matt_Web3
Discord Username: mattweb5go
Twitter Username: @Matt_Web3_
Medium Username: @matt_web3
ASTAR Native Wallet Address: YMFxavc4wzMncNBKr6NkuPwNkp2C78hYhX6kkF7BD4jrhp2

# CM - Community Management
**Astar Network CZ/SK Telegram**: https://t.me/AstarNetwork_CS
**Combot link -** https://combot.org/c/-1001943903354/a

![Snímek obrazovky (1025)](https://github.com/AstarNetwork/growth-program/assets/104125423/68bced59-2e4c-4327-aa13-37cb0b9115e6)
![Snímek obrazovky (1026)](https://github.com/AstarNetwork/growth-program/assets/104125423/b10d1702-d9f8-4f26-aab1-00a065d45c8a)

**Astar Network Official Discord:** https://discord.gg/zARxg4ZR
Responding on daily basis in general channel, guide people to tutorials or directly by myself. Also deleting and banning inappropriate content and spam!

# GOV - Governance & Project Engagement
**Astar Forum Engagement:**
**My profile:** https://forum.astar.network/u/matt/activity

![Snímek obrazovky (1030)](https://github.com/AstarNetwork/growth-program/assets/104125423/3b9cbd14-dd13-4101-921b-1c4417da88a8)
![Snímek obrazovky (1029)](https://github.com/AstarNetwork/growth-program/assets/104125423/2705bd23-32a6-4900-820a-31889552edd8)
![Snímek obrazovky (1028)](https://github.com/AstarNetwork/growth-program/assets/104125423/ccadc043-d082-47ad-b71d-d5d1c14421c1)
![Snímek obrazovky (1027)](https://github.com/AstarNetwork/growth-program/assets/104125423/91c65fb9-a370-48ea-a1d1-9b3297e2af0a)

**Discord Unstoppable Grant discussion:**
Participating in Governance and Projects discussion when new project appear. Raise questions, support or refuse their proposals. Here is my Discord Username: mattweb5go

# SM - Social Media Engagement
**Astar Network CZ/SK Twitter:** https://twitter.com/AstarNetwork_CS

![Snímek obrazovky (1032)](https://github.com/AstarNetwork/growth-program/assets/104125423/b5214176-320d-4b25-a5c7-d06956b09f29)
![Snímek obrazovky (1031)](https://github.com/AstarNetwork/growth-program/assets/104125423/456a8a65-8f14-4fe1-bab0-c64927a65ec3)

#

**Personal Twitter:** https://twitter.com/Matt_Web3_
Trying to promote major things especially Astar Network's announcements and forum proposals on daily basis!

![Snímek obrazovky (1033)](https://github.com/AstarNetwork/growth-program/assets/104125423/86b4c70b-b5b2-4754-92a6-33f51cf0baae)
![Snímek obrazovky (1034)](https://github.com/AstarNetwork/growth-program/assets/104125423/e191e6f0-773b-40ed-9b82-5d9f51999b48)

#

**AstarChan:** https://twitter.com/Astar_Chan_

Can't fetch the data from analytics: https://analytics.twitter.com/user/Astar_Chan_/home

# CC - Content Creation

**1) Simplified Insight into Astar Governance Proposal in TAB:** 
(https://medium.com/the-astar-bulletin-tab/simplified-insight-into-astar-governance-proposal-315aff5ce3d4)

**2) Simplified Guide: Astar Community’s Liquidity Injection into HydraDX Omnipool In TAB:** 
(https://medium.com/the-astar-bulletin-tab/simplified-guide-astar-communitys-liquidity-injection-into-hydradx-omnipool-af28d5e850c7)

**3) LayerZero poskytuje Cross-Chain Bridge pro Astar zkEVM translation to Czech:**
(https://medium.com/@matt_web3/layerzero-poskytuje-cross-chain-bridge-pro-astar-zkevm-070e37d2d6d6)

That's all for my April contributions, thank you very much!

**Comment by Gunit2481** [comment]
Good job Matt! 💪
