### ISSUE TITLE
April 2024 Contribution - Marco Da Rocha (Pitcoin)

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#2463]
Discord Username: pitcoin #3857
ASTR/SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

CM - Manage and Support
Astar Network PT (Telegram) and Astar Network (Discord)
Telegram: https://t.me/astarnetworkPT - 534 members (+1 member) 
![Screen Shot 2024-05-06 at 17 55 51](https://github.com/AstarNetwork/growth-program/assets/99457582/7e842972-51a3-439a-b654-5dba7d760b67)
![Screen Shot 2024-05-06 at 17 56 06](https://github.com/AstarNetwork/growth-program/assets/99457582/de45d68a-40d7-405a-932a-ba81b2cd3e9a)

GOV - Governance & Project Engagement
https://forum.astar.network/u/pitcoin777
![Screen Shot 2024-05-07 at 20 54 29](https://github.com/AstarNetwork/growth-program/assets/99457582/78a283e9-75ae-4c69-91b8-e09f7d58cbba)
![Screen Shot 2024-05-07 at 20 54 39](https://github.com/AstarNetwork/growth-program/assets/99457582/48d77afb-c709-470d-ae91-65e004d39366)
![Screen Shot 2024-05-07 at 20 54 46](https://github.com/AstarNetwork/growth-program/assets/99457582/50d6c6b4-316c-4c20-9a5c-749ec13caac9)
![Screen Shot 2024-05-07 at 20 54 53](https://github.com/AstarNetwork/growth-program/assets/99457582/491b2eaf-694b-44e6-8e66-e426e5cc24fc)

SM - Social Media Engagement
Twitter @Pitcoin_ – 1902 followers (+6 new followers) 
![Screen Shot 2024-05-07 at 20 57 06](https://github.com/AstarNetwork/growth-program/assets/99457582/ad09dec0-ce11-4a9c-989c-c6d29f1920f5)
![Screen Shot 2024-05-07 at 20 57 18](https://github.com/AstarNetwork/growth-program/assets/99457582/08a1aea7-f172-4623-bf98-525aa370094a)
![Screen Shot 2024-05-07 at 20 57 41](https://github.com/AstarNetwork/growth-program/assets/99457582/0e8ba565-8d3a-4314-941f-ab4d2448b0bd)
![Screen Shot 2024-05-07 at 20 57 48](https://github.com/AstarNetwork/growth-program/assets/99457582/1dca1c31-3e0c-46a5-910d-50abcabee42b)
![Screen Shot 2024-05-07 at 20 57 54](https://github.com/AstarNetwork/growth-program/assets/99457582/ee62d1ea-79c8-4bc4-9e97-b62bd1614462)
![Screen Shot 2024-05-07 at 20 58 05](https://github.com/AstarNetwork/growth-program/assets/99457582/b38f9b8b-6856-42dd-84a4-dfd1dc946a2d)
![Screen Shot 2024-05-07 at 20 58 26](https://github.com/AstarNetwork/growth-program/assets/99457582/88a6f8a1-748d-4879-b358-bd76d30b805a)
![Screen Shot 2024-05-07 at 20 58 36](https://github.com/AstarNetwork/growth-program/assets/99457582/76e0d736-ae14-49b6-8e4b-8e032150f05d)
![Screen Shot 2024-05-07 at 20 59 01](https://github.com/AstarNetwork/growth-program/assets/99457582/7c0c804a-b862-4125-9740-2a83db2785bc)

CC - The Content Creator
Astar Network News - April season III
https://grillapp.net/6283/astar-network-news-april-season-iii-142738

The Astar Network News - April Season 2
https://grillapp.net/6283/the-astar-network-news-april-season-2-135505

Astar Network at the @teamz_inc Summit - Highlights!
https://grillapp.net/6283/astar-network-at-the-teamz-inc-summit-highlights-129098

Astar Network News - APRIL
https://grillapp.net/6283/astar-network-news-april-114079

**Comment by Gunit2481** [comment]
Great work Pitcoin! 👏
