### ISSUE TITLE
April 2024 Contribution - Earl

### ISSUE THREAD

**Issue by Earlcho** [AstarNetwork/growth-program#2464]
Telegram Username: @Earl_Senor
Discord Username: Earl_Senor
ASTR Wallet Address: X7zVHUVANKthHfqHuiJnXa7ZZibWRfxKWo361MfTtHD66aF

### Mandatory tasks
**CM**

Manage the Korean TG ( https://t.me/astar_kr )

Publish official announcements in Korean across Korean channels (TG, Discord, Twitter)

**Telegram Announcement Lists**
https://t.me/astar_krann/297													
https://t.me/astar_krann/298													
https://t.me/astar_krann/300													
https://t.me/astar_krann/302													
https://t.me/astar_krann/305													
https://t.me/astar_krann/306													
https://t.me/astar_krann/307													
https://t.me/astar_krann/309													
https://t.me/astar_krann/310													
https://t.me/astar_krann/311													
https://t.me/astar_krann/312													
https://t.me/astar_krann/316													
https://t.me/astar_krann/317													
https://t.me/astar_krann/319													
https://t.me/astar_krann/320													
https://t.me/astar_krann/322													
https://t.me/astar_krann/323													
https://t.me/astar_krann/325													
https://t.me/astar_krann/327													
https://t.me/astar_krann/328													
https://t.me/astar_krann/332													
https://t.me/astar_krann/333													
https://t.me/astar_krann/334													
https://t.me/astar_krann/336													
https://t.me/astar_krann/337													
https://t.me/astar_krann/338													
https://t.me/astar_krann/340													
https://t.me/astar_krann/341													
https://t.me/astar_krann/342													
https://t.me/astar_krann/344													
https://t.me/astar_krann/348													
https://t.me/astar_krann/349													

The same content are being also announced on the Discord Korea channel.

**Twitter Announcement**
https://x.com/AstarNetwork_KR/status/1774708037565272453
https://x.com/AstarNetwork_KR/status/1775119072868634712
https://x.com/AstarNetwork_KR/status/1775459290385637405
https://x.com/AstarNetwork_KR/status/1775738303440142599
https://x.com/AstarNetwork_KR/status/1775819191540723791
https://x.com/AstarNetwork_KR/status/1776052924592132578
https://x.com/AstarNetwork_KR/status/1776111071360938166
https://x.com/AstarNetwork_KR/status/1776166075622883335
https://x.com/AstarNetwork_KR/status/1776427086162624639
https://x.com/AstarNetwork_KR/status/1777220608482505179
https://x.com/AstarNetwork_KR/status/1777302380595577163
https://x.com/AstarNetwork_KR/status/1777522079254138930
https://x.com/AstarNetwork_KR/status/1778607790908690712
https://x.com/AstarNetwork_KR/status/1778724863408271371
https://x.com/AstarNetwork_KR/status/1779360679662952530
https://x.com/AstarNetwork_KR/status/1781141413599830038
https://x.com/AstarNetwork_KR/status/1781214468284014801
https://x.com/AstarNetwork_KR/status/1781951857667215800
https://x.com/AstarNetwork_KR/status/1782226737784565844
https://x.com/AstarNetwork_KR/status/1782336914861048146
https://x.com/AstarNetwork_KR/status/1782624334491877503
https://x.com/AstarNetwork_KR/status/1782671201649004765
https://x.com/AstarNetwork_KR/status/1782764981731168635
https://x.com/AstarNetwork_KR/status/1782959849074237785
https://x.com/AstarNetwork_KR/status/1782978378242609345
https://x.com/AstarNetwork_KR/status/1784878806857134417
https://x.com/AstarNetwork_KR/status/1785129494224965657
https://x.com/AstarNetwork_KR/status/1785214380445204758

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/3204f847-9120-4e31-9792-73a396ef463e)

### GOV
https://forum.astar.network/u/earl/activity

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/42359ef9-01fc-46ff-8d68-0d0ba6698d05)

### Optional tasks
**SM**
![image](https://github.com/AstarNetwork/growth-program/assets/108060432/6baea5ea-7e19-4535-b7c4-6f278c6879b5)

https://x.com/Earl_Senor/status/1774753299482484767																
https://x.com/Earl_Senor/status/1780083643723198681																

**CC**

1. ERC-6551
https://medium.com/astar-korea/%EC%B0%A8%EC%84%B8%EB%8C%80-%EC%9B%B93-%EC%95%84%ED%8A%B8-%EA%B8%B0%EC%88%A0-%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0-%EC%95%84%EC%8A%A4%ED%83%80%EA%B0%80-%EC%9D%B4%EB%81%84%EB%8A%94-nft-%ED%91%9C%EC%A4%80-erc-6551-%ED%83%90%EA%B5%AC-5003df90168d
														
https://blog.naver.com/astarkr/223401925640

2. zkEVM Upgrade									
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-zkevm-%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%93%9C-%EB%B0%8F-%EC%9C%A0%EC%A7%80%EB%B3%B4%EC%88%98-%EC%95%88%EB%82%B4-2024%EB%85%84-4%EC%9B%94-10%EC%9D%BC-dd7993d5c7c5	
													
https://blog.naver.com/astarkr/223423590279			
		
3. Astar Governance Proposal									
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0-%EB%B0%8F-%EA%B1%B0%EB%B2%84%EB%84%8C%EC%8A%A4-%EB%AC%B8%ED%99%94%EB%A5%BC-%EC%A1%B0%EC%84%B1%ED%95%98%EB%8B%A4-%EC%95%84%EC%8A%A4%ED%83%80-%ED%8F%AC%EB%9F%BC%EC%9D%98-%EC%A0%9C%EC%95%88%EC%84%9C-27545d7d1fd2	
													
https://blog.naver.com/astarkr/223423597789			
			
4. Astar Tokenomics 2.0 / dApp Staking 3.0 Quant								
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%ED%86%A0%ED%81%AC%EB%85%B8%EB%AF%B9%EC%8A%A4-2-0-%EB%94%94%EC%95%B1-%EC%8A%A4%ED%85%8C%EC%9D%B4%ED%82%B9-v3-%EC%A0%95%EB%9F%89%EC%A0%81-%EB%B6%84%EC%84%9D-dbfd8ed45ffb	
													
https://blog.naver.com/astarkr/223434125650														

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/bd7fe2aa-a9ec-4f90-b583-0a0d3bc4f702)

The image below shows the total number of views for Astar Korea Naver Blog content in April.

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/7d30b7b7-911a-4886-899e-0d051f18d3f2)

**Comment by Gunit2481** [comment]
Great job supporting the Korean community! 👍
