### ISSUE TITLE
April 2024 Contibution - Max.eth

### ISSUE THREAD

**Issue by MaxEthHealthy** [AstarNetwork/growth-program#2465]
Telegram Username: @max_eth_heatlhy
Discord Username: max.eth.healthy
X User name: @max_eth_heatlhy
ASTR Wallet Address: WAgeWZSPzQdJf58kELDGBp2P8VRCNFie9s3j7fgvpJduNMX

---
**CM**:

-Telegram
https://combot.org/c/-1001138925620
<img width="1132" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/ee07d8ba-7f2f-4a78-9afd-8b05e5c87bfe">

- Discord
support while the team was busy in Japan and taking care of the polygon problem

![image](https://github.com/AstarNetwork/growth-program/assets/157904479/70781cbb-448c-4507-928c-7582c22a4fe6)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/4177f00e-0aad-4205-b215-2e041c54c6f4)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/ee4256ca-211e-449f-9a46-c620267b7bb8)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/fae5f6b1-6fdd-49fa-9e37-aff1ea8aed0d)

- connection with the community by DMs
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/73077794-b016-46cb-bf20-92e7b5a313ab)

**GOV**

https://forum.astar.network/u/max.eth/activity
https://forum.astar.network/u/max.eth/summary

<img width="942" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/e0e564e3-34b3-4911-b786-7e0c97b609c4">

**SM**

Analytics:

I had a very good month with some of my posts reaching above my average impressions. 
I got my best performing post ever with Sony x Astar thread
I announced the French newsletter
Sample of posts below

<img width="915" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/979e9cb1-195d-4b67-bbfe-e0b996490e88">

![image](https://github.com/AstarNetwork/growth-program/assets/157904479/99c2e5b9-536c-4c28-afc3-d507def3db6b)

<img width="584" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/06e29d38-321b-434b-bb58-9f1fa661f14e">
<img width="585" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/e6213fb8-6d5b-465a-af8c-c4c26c6d2c61">
<img width="597" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/c6857c18-d046-4644-8ec2-572a36f42ca1">
<img width="577" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/1f8d365b-30c4-4792-a332-2cf924620a65">

**CC**

- I talked about my path in Web 3 and about getting interested in Astar in a French podcast.

<img width="582" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/86e505c8-2675-44cf-8085-b095200d832e">

- Articles

https://medium.com/@max.eth/astar-network-next-few-months-with-sony-are-pivotal-sota-watanabe-6a0f23a155ce
https://www.bonzai.pro/maxeth/posts/bnPB_8128/astar-network-next-few-months-with-sony-are-pivotal-sota-watanabe

https://www.bonzai.pro/maxeth/posts/Rp6V_8129/astar-easily-explained-astar-zkevm

**Comment by Gunit2481** [comment]
Thanks Max!
