### ISSUE TITLE
April 2024 Contibution - Emre(Mr.Karahanlı)

### ISSUE THREAD

**Issue by siyaksares** [AstarNetwork/growth-program#2466]
Twitter: https://twitter.com/mr_karahanl
Telegram Username: @Emret16
Discord Username: mr.karahanli_emre_
Medium: https://medium.com/@emretanis4
ASTAR Native Wallet Address: ZkXuTVXB4s6sPgf42gviV2GcTHkvXks72sbVB7rqevzr2xu

This month I focused on the Yoki Campaign and the Yoki Video got 37K views.

Astar Network Turkey Twitter: https://twitter.com/astarnetworktr_?s=21&t=ISh07fvjMqpmUg40w5HqBg
Astar Network Turkey Telegram: [https://t.me/AstarTurkiye  Personal](https://t.me/AstarTurkiye%E2%80%A8%E2%80%A8Personal)

![image](https://github.com/AstarNetwork/growth-program/assets/78142371/e76cba0a-8bae-478e-bd3f-c0d0308fec08)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/7caa3b25-d67e-4e3b-9f21-bd746a2c707c)

Cm: COMMUNITY SUPPORT
I've been the top contributor for months. I've also been ranked #1 on CM and the top contributor to our community on telegrams.

By request, I also focused on Discord this month and helped new Turkish members coming in.
My main goal here was to direct people to our telegram group after solving problems on Discord.

![WhatsApp Görsel 2024-05-09 saat 23 56 51_6ea5e3dc](https://github.com/AstarNetwork/growth-program/assets/78142371/a08e2df1-53b5-437d-af1f-ce4c29be1ce4)

![image](https://github.com/AstarNetwork/growth-program/assets/78142371/3b5ece04-fff3-4317-b136-45c7dce02fb4)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/599b3a2d-d279-4599-a0db-b0be7802d265)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/123a8c56-4fc8-4b64-af87-a4105815f543)

GOV - Governance and Project Engagement
Gov-https://forum.astar.network/u/mrkarahanli-emre/activity
I participated in active forum activities. I engaged in subjective and creative discussions.

![image](https://github.com/AstarNetwork/growth-program/assets/78142371/04720493-70aa-43e4-be57-15e5c44d0b84)

My 22-minute Yoki video got 37,500 views!
https://twitter.com/mr_karahanl/status/1776276730811982272
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/2a6b4d8a-6403-4bf9-9a1b-45858ffea38b)

$PIKK dApp staking Airdrop distribution
https://twitter.com/mr_karahanl/status/1778436574272696368
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/1a6a3a55-b009-4c7c-ac05-2b664b835120)

Yoki Origins point system
https://twitter.com/mr_karahanl/status/1775144082039243233
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/c9b1c87c-00f8-4752-9585-b9da3f291b82)

Yoki Origins leaderboard.
https://twitter.com/mr_karahanl/status/1777006268093223289
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/3d9fd7c8-1178-44c0-9dde-5f19aaffbe99)

MAZDA X ASTAR
https://twitter.com/mr_karahanl/status/1776200224836391253
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/807644fa-caf3-43d3-8c81-596d8428fa96)

Nerox&Astr
https://twitter.com/mr_karahanl/status/1777396249399869549
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/58ab482f-fede-431a-82d8-bf9410045076)

https://twitter.com/mr_karahanl/status/1774845434726343097
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/cd276c0b-72ed-418d-9eb9-b4f19988f9c4)

Sonybank x Astar
https://twitter.com/mr_karahanl/status/1776194378211508613
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/e0ee31b9-2554-4404-a5a3-afeac31f90f2)

Quickswap Space with neurolanche
https://twitter.com/mr_karahanl/status/1776212649191109082
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/49a2aa38-a718-4089-81e6-6e88b9c5415d)

Astar MEME
https://twitter.com/mr_karahanl/status/1776646576456262113
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/7a4817ef-0548-4e9f-a811-fbd14a8422a0)

OTHER:

Handmade IMAGE:
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/aff4e5d8-aaed-45ed-8408-a029a56ef902)

Handmade VIDEO:
The video size is too big and won't load.
I'm leaving a screenshot.
22-minute YOKI Origins Video
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/a1f7aebc-6335-4dbe-b227-d9eada14fcc9)

Handmade MEME:
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/f2b62593-b93c-4c92-86fa-3a68db60c98d)

**Comment by Gunit2481** [comment]
Thanks Emre!
