### ISSUE TITLE
May 2024 Contribution

### ISSUE THREAD

**Issue by cryptosats** [AstarNetwork/growth-program#2472]
Telegram Username: @christopedia

Discord Username: @cmalize 

ASTR Wallet Address: Y5iCr5tyia5UwQnjVjSE9nDWJoFtowywG3BSfmsqLzNgy6W

**Contributions:**

**1. CM - Managed and supported both Local and Main community chat.**
[
![photo_2024-06-01_22-23-11](https://github.com/AstarNetwork/growth-program/assets/69989414/26ceff29-7c31-4ff8-b52e-3771a9aa854a)
![photo_2024-06-01_22-23-12](https://github.com/AstarNetwork/growth-program/assets/69989414/1114102d-8a3e-45d4-afdf-1ebb2e65cda7)
![photo_2024-06-01_22-23-13](https://github.com/AstarNetwork/growth-program/assets/69989414/41f1010e-cbbb-493e-bbe5-6abb17ed937c)
]

**2. GOV - Engaged in governance discussion.**
[https://forum.astar.network/u/cmalize/activity]

**3. VSM - Twitted about Astar**
[https://twitter.com/ChrisMalize3/status/1786101306173665728?t=0V3idmYmHhp1kASopkxpzg&s=19
https://twitter.com/ChrisMalize3/status/1787799944755118281?t=djKZvxmppOUHWU8v4Inaig&s=19
https://twitter.com/ChrisMalize3/status/1788057892077089036?t=0tg2yD_rU-ETQFvmXbGaFw&s=19
https://twitter.com/ChrisMalize3/status/1788835901537210571?t=lNJeZyvbL82MqFxGhjc-0A&s=19
https://twitter.com/ChrisMalize3/status/1790270757639000070?t=NJtZ4xogrwY2xRGaJzscug&s=19
https://twitter.com/ChrisMalize3/status/1791746094923202875?t=JbR6vnIJgq1kEO1IhU4u7w&s=19
https://twitter.com/ChrisMalize3/status/1792907951176384592?t=8S3szfWsDzQdWIL2NJoUnA&s=19
https://twitter.com/ChrisMalize3/status/1793611619882467773?t=MSTWZcI2EsxSHxfljFo-6w&s=19
https://twitter.com/ChrisMalize3/status/1795368995782316170?t=FO8aE6esYWawOkzQu1AHaQ&s=19
https://twitter.com/ChrisMalize3/status/1795166550082638015?t=mj7dKpFMELDObn3N81xEpw&s=19
![photo_2024-06-01_22-33-28](https://github.com/AstarNetwork/growth-program/assets/69989414/921e352f-7ad1-4936-92e5-fd54d17443ea)
![photo_2024-06-01_22-33-30](https://github.com/AstarNetwork/growth-program/assets/69989414/f88d9557-1dd6-40a9-bb9f-b480ec027306)
![photo_2024-06-01_22-33-31](https://github.com/AstarNetwork/growth-program/assets/69989414/7b40d24e-1c1b-4623-ae41-2c21c6b5417e)
![photo_2024-06-01_22-33-32](https://github.com/AstarNetwork/growth-program/assets/69989414/da2750bc-0e6b-4126-b2b5-070cee77dd19)
![photo_2024-06-01_22-33-33](https://github.com/AstarNetwork/growth-program/assets/69989414/aa57fc73-c577-4d73-83c6-4bc970862089)
![photo_2024-06-01_22-33-34](https://github.com/AstarNetwork/growth-program/assets/69989414/8065eda6-8d85-4925-b23e-7443f413df8c)
![photo_2024-06-01_22-33-35](https://github.com/AstarNetwork/growth-program/assets/69989414/9fc0402b-9503-4d25-aad8-2abc3f64e72e)
![photo_2024-06-01_22-33-36](https://github.com/AstarNetwork/growth-program/assets/69989414/429f704c-75e5-4791-a746-b519a19e58af)
![photo_2024-06-01_22-33-37](https://github.com/AstarNetwork/growth-program/assets/69989414/37a2f80f-669e-4a85-957f-96027357530c)
![photo_2024-06-01_22-33-38](https://github.com/AstarNetwork/growth-program/assets/69989414/41c5ef34-f2cc-4711-a381-cb8444181995)
![photo_2024-06-01_22-33-40](https://github.com/AstarNetwork/growth-program/assets/69989414/301c7da7-4ecc-4513-8586-66f4e998cba3)
]

**Comment by Gunit2481** [comment]
Thank you.
