### ISSUE TITLE
May 2024 Contribution - Matt

### ISSUE THREAD

**Issue by Matt3Web** [AstarNetwork/growth-program#2475]
# **May 2024 Contribution - Matt**

Telegram Username: @Matt_Web3
Discord Username: mattweb5go
Twitter Username: @Matt_Web3_
Medium Username: @matt_web3
ASTAR Native Wallet Address: YMFxavc4wzMncNBKr6NkuPwNkp2C78hYhX6kkF7BD4jrhp2

# CM - Community Management
**Astar Network CZ/SK Telegram**: https://t.me/AstarNetwork_CS
**Combot link -** https://combot.org/c/-1001943903354/a

![Snímek obrazovky (1063)](https://github.com/AstarNetwork/growth-program/assets/104125423/ea72711f-085d-44ce-b365-8f78a58a54c1)
![Snímek obrazovky (1064)](https://github.com/AstarNetwork/growth-program/assets/104125423/d26ee56b-49b4-4403-8a62-511362d8d37a)

**Astar Network Official Discord:** https://discord.gg/zARxg4ZR
Responding on daily basis in general channel, guide people to tutorials or directly by myself. Also deleting and banning inappropriate content and spam!

# GOV - Governance & Project Engagement
**Astar Forum Engagement:**
**My profile:** https://forum.astar.network/u/matt/activity

![Snímek obrazovky (1068)](https://github.com/AstarNetwork/growth-program/assets/104125423/cede7aad-2025-4a08-9523-654fe4d6f99b)
![Snímek obrazovky (1067)](https://github.com/AstarNetwork/growth-program/assets/104125423/8af7184a-cda3-490a-bab1-9b43a69e5f22)
![Snímek obrazovky (1066)](https://github.com/AstarNetwork/growth-program/assets/104125423/25285f36-4fc5-44e1-b9e0-1728ad17ad2a)
![Snímek obrazovky (1065)](https://github.com/AstarNetwork/growth-program/assets/104125423/80f561ef-62b8-4a76-807f-71acc5469113)

**Discord Unstoppable Grant discussion:**
Participating in Governance and Projects discussion when new project appear. Raise questions, support or refuse their proposals. Here is my Discord Username: mattweb5go

# SM - Social Media Engagement
**Astar Network CZ/SK Twitter:** https://twitter.com/AstarNetwork_CS

![Snímek obrazovky (1070)](https://github.com/AstarNetwork/growth-program/assets/104125423/1a566133-e565-4863-9c00-b81db4436042)
![Snímek obrazovky (1069)](https://github.com/AstarNetwork/growth-program/assets/104125423/9a26dcf7-ba83-4dff-a0ee-de784ef18c0d)

#

**Personal Twitter:** https://twitter.com/Matt_Web3_
Trying to promote major things especially Astar Network's announcements and forum proposals on daily basis!

![Snímek obrazovky (1071)](https://github.com/AstarNetwork/growth-program/assets/104125423/49314458-64ef-40f1-a545-d6e515512d8a)
![Snímek obrazovky (1072)](https://github.com/AstarNetwork/growth-program/assets/104125423/9770cd04-7e31-4d91-a110-5570e129a03f)

#

**AstarChan:** https://twitter.com/Astar_Chan_

Can't fetch the data from analytics: https://analytics.twitter.com/user/Astar_Chan_/home

# CC - Content Creation

**1) Registering Bifrost Liquid Staking Tokens (LSTs) vGLMR, vFIL, and vMANTA on Astar Network in TAB:** 
(https://medium.com/the-astar-bulletin-tab/registering-bifrost-liquid-staking-tokens-lsts-vglmr-vfil-and-vmanta-on-astar-network-679633376328)

**2) Youdles NFT Collection Set to Launch on Astar Network in TAB:** 
(https://medium.com/the-astar-bulletin-tab/youdles-nft-collection-set-to-launch-on-astar-network-31092ef03985)

**3) Astar Studio — co to je? Astar studio article translation to Czech:**
(https://medium.com/the-astar-bulletin-tab/astar-studio-co-to-je-2cfd0fc789d3)

**4) Astar & Startale: Zářící světlo na masovém přijetí Web in TAB:**
(https://medium.com/the-astar-bulletin-tab/astar-startale-z%C3%A1%C5%99%C3%ADc%C3%AD-sv%C4%9Btlo-na-masov%C3%A9m-p%C5%99ijet%C3%AD-web3-e54a77f12acd)

That's all for my May contributions, thank you very much!

**Comment by Gunit2481** [comment]
Good work Matt! 👍
