### ISSUE TITLE
May 2024 Contribution - marveLet

### ISSUE THREAD

**Issue by marvelet** [AstarNetwork/growth-program#2479]
Telegram : Soulstar / https://t.me/marvelet6 (previously Soul Eater)
Discord : marvelet#8647
Native Address : YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

___

### CM
**TELEGRAM**
Astar Indonesia
Link : [https://t.me/astarnetwork_id](https://t.me/astarnetwork_id)
Total Members : 245 members (exclude Rose Bot, decreased 6 member)
Combot Link : [https://combot.org/c/-1001288040165/a](https://combot.org/c/-1001288040165/a)
Screenshots: :

![tele_rep](https://github.com/AstarNetwork/growth-program/assets/87793956/515713ef-07f2-4ef5-8ffb-b74f23197dac)

Comments :
- In last week of the month, activity dropped since Yoki entering its last week. But had a spike before it because On1 NFT

For Discord , kindly check my activity there

___

### GOV
**FORUM**
My activity on Astar Forum
[https://forum.astar.network/u/souleater/activity](https://forum.astar.network/u/souleater/activity)
[https://forum.astar.network/u/souleater/summary](https://forum.astar.network/u/souleater/summary)

Screenshot :

![forum_rep](https://github.com/AstarNetwork/growth-program/assets/87793956/79d1fdd1-f8ca-4ecd-b791-bcd625f3396f)

For Discord, kindly check my activity there

___

### SM
**TWITTER**
Personal : https://twitter.com/rudayruday
Analytic Screenshot :

![x_rep1](https://github.com/AstarNetwork/growth-program/assets/87793956/66c35e18-81c6-4306-9515-519e159deec3)
![x_rep2](https://github.com/AstarNetwork/growth-program/assets/87793956/843a7983-69f1-47bd-81d6-c0a7dffc255c)

In-depth twitter activity:
[tweet_activity_metrics_rudayruday_20240501_20240601_en.csv](https://github.com/user-attachments/files/15545936/tweet_activity_metrics_rudayruday_20240501_20240601_en.csv)

===
Astar Indonesia : https://twitter.com/AstarNetwork_ID
Analytic Screenshot :

Currently suspended, waiting feedback from X support to resolve this issue. :(

___

### CC
**The Astar Bulletin**
Writing a monthly article on Astar Bulletin, teasing about Astar roadmap in 2024 regarding offline meetup Astar <> Startale
Title :
The Townhall
[https://theastarbulletin.news/the-townhall-3b3085b60390](https://theastarbulletin.news/the-townhall-3b3085b60390)

**Binance Square**
Everything Astar May 2024
[https://www.binance.com/en/square/post/8339412978361](https://www.binance.com/en/square/post/8339412978361)

___

### EVENT
ONLINE AMA on IG
When : May 14th, 2024. 12PM UTC
Where : Digital Exchange (CEX in Indonesia), Live IG : [https://www.instagram.com/p/C60Cl8WvyvB/](https://www.instagram.com/p/C60Cl8WvyvB/)  
Event Title : Menggali Potensi Industri Web3 dan Crypto di Indonesia (trans : Exploring the Potential of the Web3 and Crypto Industry in Indonesia)
Attendants : less than 100 
Proof : 
![proof](https://github.com/AstarNetwork/growth-program/assets/87793956/faacd71d-610b-4f97-b389-d100a7a88308)
(I'm not the one who made the graphics :( )
___

That's all my contributions for May 2024

**Comment by Gunit2481** [comment]
Good work, thanks Rudy!
