### ISSUE TITLE
May 2024 Contribution - Marco Da Rocha (Pitcoin)

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#2480]
Discord Username: pitcoin #3857
ASTR/SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

CM - Manage and Support
Astar Network PT (Telegram) and Astar Network (Discord)
Telegram: https://t.me/astarnetworkPT - 526 members (-8 members)
![Screen Shot 2024-06-03 at 23 08 55](https://github.com/AstarNetwork/growth-program/assets/99457582/156b7b24-004d-4a86-96b2-39324a428a84)
![Screen Shot 2024-06-03 at 23 09 06](https://github.com/AstarNetwork/growth-program/assets/99457582/a99ab069-e162-4490-81d0-6bbf65b96c6a)

GOV - Governance & Project Engagement
https://forum.astar.network/u/pitcoin777
![Screen Shot 2024-06-04 at 20 08 01](https://github.com/AstarNetwork/growth-program/assets/99457582/93289822-12dc-4716-b206-4df0d99e206e)
![Screen Shot 2024-06-04 at 20 08 09](https://github.com/AstarNetwork/growth-program/assets/99457582/b12cff50-99c4-407f-8ef5-51876ecbadaa)
![Screen Shot 2024-06-04 at 20 08 19](https://github.com/AstarNetwork/growth-program/assets/99457582/7b6f6147-e8e5-42b1-b941-e08f3d78ee2b)
![Screen Shot 2024-06-04 at 20 08 27](https://github.com/AstarNetwork/growth-program/assets/99457582/126c6acc-4f3a-49c9-82a7-d93f79eee47f)
![Screen Shot 2024-06-04 at 20 08 35](https://github.com/AstarNetwork/growth-program/assets/99457582/b22fc6a8-cf4e-478d-a3b6-a5825560f65e)
![Screen Shot 2024-06-04 at 20 08 42](https://github.com/AstarNetwork/growth-program/assets/99457582/f0f07bf9-21e3-4d84-b0ff-a93b093b10b8)

SM - Social Media Engagement
Twitter @Pitcoin_ – 1902 followers (+6 new followers)
![Screen Shot 2024-06-04 at 20 13 00](https://github.com/AstarNetwork/growth-program/assets/99457582/79671bee-c876-488f-be5d-1d46829a53f0)
![Screen Shot 2024-06-04 at 20 12 50](https://github.com/AstarNetwork/growth-program/assets/99457582/389f44d3-d810-4a5b-873c-35c57d959b4f)
![Screen Shot 2024-06-04 at 20 12 44](https://github.com/AstarNetwork/growth-program/assets/99457582/31b324ff-18e3-4aa0-b59e-0e9e32fe35e5)
![Screen Shot 2024-06-04 at 20 12 35](https://github.com/AstarNetwork/growth-program/assets/99457582/ea5a3c66-2336-4fdc-9c3a-b99408abfa3d)
![Screen Shot 2024-06-04 at 20 12 23](https://github.com/AstarNetwork/growth-program/assets/99457582/89636dbd-67a4-4223-8dfb-a9caa02a8cae)
![Screen Shot 2024-06-04 at 20 12 07](https://github.com/AstarNetwork/growth-program/assets/99457582/5a2e88c0-56a6-4b8f-ad94-aaf40275b992)
![Screen Shot 2024-06-04 at 20 11 16](https://github.com/AstarNetwork/growth-program/assets/99457582/7a3c12f3-dda5-47a9-b762-aa9105306117)
![Screen Shot 2024-06-04 at 20 10 58](https://github.com/AstarNetwork/growth-program/assets/99457582/8eb08de9-9408-4f5e-858d-4ddf6166e3c1)

CC - The Content Creator
Sota Watanabe on Sony chain
https://grillapp.net/6283/167353

Astar NEWS!
https://grillapp.net/6917/164634

Others - Town hall testing report
![Screen Shot 2024-06-04 at 20 21 38](https://github.com/AstarNetwork/growth-program/assets/99457582/f3b326bb-d708-4675-97f2-9859d6b98a6f)

**Comment by Gunit2481** [comment]
Good job, thank you! 👍
