### ISSUE TITLE
May 2024 Contribution - Earl

### ISSUE THREAD

**Issue by Earlcho** [AstarNetwork/growth-program#2481]
Telegram Username: @Earl_Senor
Discord Username: Earl_Senor
ASTR Wallet Address: X7zVHUVANKthHfqHuiJnXa7ZZibWRfxKWo361MfTtHD66aF

### Mandatory tasks
**CM**

Manage the Korean TG ( https://t.me/astar_kr )

Publish official announcements in Korean across Korean channels (TG, Discord, Twitter)

**Telegram Announcement Lists**
https://t.me/astar_krann/350													
https://t.me/astar_krann/351													
https://t.me/astar_krann/352	
https://t.me/astar_krann/353												
https://t.me/astar_krann/359												
https://t.me/astar_krann/360	
https://t.me/astar_krann/361												
https://t.me/astar_krann/362												
https://t.me/astar_krann/363												
https://t.me/astar_krann/364												
https://t.me/astar_krann/365												
https://t.me/astar_krann/366												
https://t.me/astar_krann/367												
https://t.me/astar_krann/368												
https://t.me/astar_krann/369												
https://t.me/astar_krann/370												
https://t.me/astar_krann/371												
https://t.me/astar_krann/372												
https://t.me/astar_krann/373												
https://t.me/astar_krann/374												
https://t.me/astar_krann/375												
https://t.me/astar_krann/376												
https://t.me/astar_krann/377												
https://t.me/astar_krann/378

The same content are being also announced on the Discord Korea channel.

**Twitter Announcement**
https://x.com/AstarNetwork_KR/status/1785604057090146803
https://x.com/AstarNetwork_KR/status/1785849700723351634
https://x.com/AstarNetwork_KR/status/1785998104871002328
https://x.com/AstarNetwork_KR/status/1786284904189415591
https://x.com/AstarNetwork_KR/status/1788025746595930236
https://x.com/AstarNetwork_KR/status/1788173351309218299
https://x.com/AstarNetwork_KR/status/1788385871164768559
https://x.com/AstarNetwork_KR/status/1788387908535386355
https://x.com/AstarNetwork_KR/status/1788388051124982204
https://x.com/AstarNetwork_KR/status/1788802499899707602
https://x.com/AstarNetwork_KR/status/1789862616627876218
https://x.com/AstarNetwork_KR/status/1790274503316234664
https://x.com/AstarNetwork_KR/status/1790933531511951817
https://x.com/AstarNetwork_KR/status/1791050053005816041
https://x.com/AstarNetwork_KR/status/1791314779556249985
https://x.com/AstarNetwork_KR/status/1792745792190787819
https://x.com/AstarNetwork_KR/status/1792762835715650033
https://x.com/AstarNetwork_KR/status/1792775102406549580
https://x.com/AstarNetwork_KR/status/1792863344363471205
https://x.com/AstarNetwork_KR/status/1793119023003283943
https://x.com/AstarNetwork_KR/status/1793529422374715539
https://x.com/AstarNetwork_KR/status/1793578036174127146
https://x.com/AstarNetwork_KR/status/1794995960407609371
https://x.com/AstarNetwork_KR/status/1795268212294340978
https://x.com/AstarNetwork_KR/status/1796382795792797930

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/786a7936-0fa0-4515-a4a2-272f1bf1632d)

### Optional tasks
**SM**
https://x.com/Earl_Senor/status/1788163048148201682																
https://x.com/Earl_Senor/status/1791327648905564473																
https://x.com/Earl_Senor/status/1795405322347286648		

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/1e0959f6-d98c-46b3-a3da-d0bd8912ffb6)

**CC**

1. Yoki Origins Finale
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%9A%94%ED%82%A4-%EC%98%A4%EB%A6%AC%EC%A7%84%EC%8A%A4-%EC%97%AC%EC%A0%95%EC%9D%84-%EB%A7%88%EC%B9%98%EB%A9%B0-27d63d88038c	
													
https://blog.naver.com/astarkr/223444950834	

2. TGE Grants
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-zkevm-%EC%83%9D%ED%83%9C%EA%B3%84-%ED%99%95%EC%9E%A5%EC%9D%84-%EC%9C%84%ED%95%9C-%EC%8B%A0%EA%B7%9C-%EA%B7%B8%EB%9E%9C%ED%8A%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B3%B5%EA%B0%9C-fd6a5b10d6ea	
													
https://blog.naver.com/astarkr/223444955559		

3. Interview with CASIO
https://medium.com/astar-korea/%EC%B9%B4%EC%8B%9C%EC%98%A4-%EC%8B%9C%EA%B3%84%EC%99%80%EC%9D%98-%EC%9D%B8%ED%84%B0%EB%B7%B0-%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EB%A5%BC-%ED%86%B5%ED%95%9C-nft-%EC%84%B8%EA%B3%84%EB%A1%9C-%EC%A7%84%EC%B6%9C-82ad4b88a9c5														

https://blog.naver.com/astarkr/223445069272			

4. Astar Studio
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4-20%EB%A7%8C-%EB%8B%AC%EB%9F%AC-%EA%B7%B8%EB%9E%9C%ED%8A%B8-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8%EA%B3%BC-%ED%95%A8%EA%BB%98-%EC%B6%9C%EC%8B%9C%EB%90%98%EB%8A%94-%EA%B0%9C%EB%B0%9C%EC%9E%90-%EC%BD%98%EC%86%94-4a234b854ff9		
												
https://blog.naver.com/astarkr/223453843404		

5. Astar & Startale
https://medium.com/astar-korea/%EC%95%84%EC%8A%A4%ED%83%80-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%8A%A4%ED%83%80%ED%85%8C%EC%9D%BC%EB%9E%A9%EC%8A%A4-%EC%9B%B93%EC%9D%98-%EB%8C%80%EC%A4%91-%EC%88%98%EC%9A%A9%EC%9D%84-%EC%8B%A4%ED%98%84%ED%95%98%EB%8B%A4-f7a307030a2c		
												
https://blog.naver.com/astarkr/223461149926		

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/96be1722-603a-4a6d-ad33-c11c60bc4773)

![image](https://github.com/AstarNetwork/growth-program/assets/108060432/41b78220-46af-47c9-930b-a2352173295c)

**Comment by Gunit2481** [comment]
Thank you Earl
