### ISSUE TITLE
May 2024 Contribution - MSPY

### ISSUE THREAD

**Issue by thanhmycm** [AstarNetwork/growth-program#2483]
Telegram : MS-PY (Never PM you first)/ @ThanhCayMoney
Discord : lethanhmy
SDN/ASTR Address : ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

CM :
Telegram Vietnamese : https://t.me/PlasmOfficialVietnam - https://t.me/astarshidenvietnam

![1](https://github.com/AstarNetwork/growth-program/assets/89438593/c741deba-8081-49c9-8d63-232a4cd2dcd6)
![2](https://github.com/AstarNetwork/growth-program/assets/89438593/830f7317-e66e-47e5-ae25-41f245250ebe)

Discord Support :

![3](https://github.com/AstarNetwork/growth-program/assets/89438593/f48be678-671d-4fbc-a7d9-5d44992c7f8b)
![4](https://github.com/AstarNetwork/growth-program/assets/89438593/d763199e-f129-4e50-bffe-0c864444ac06)
![5](https://github.com/AstarNetwork/growth-program/assets/89438593/36a6d53c-f3f5-46cf-8cd7-9c879bbf05fa)
![6](https://github.com/AstarNetwork/growth-program/assets/89438593/f72a7634-08ad-4e16-a2de-2462f3be6696)
![7](https://github.com/AstarNetwork/growth-program/assets/89438593/58b5f27f-5130-4f79-8a75-38b8619f4b3e)
![8](https://github.com/AstarNetwork/growth-program/assets/89438593/b7d288a1-46c3-4df2-8a9f-a1b009f9af98)

SM : https://twitter.com/ThanhMy67 | https://twitter.com/AstarNetworkVN is waiting to open the suspension
![t1](https://github.com/AstarNetwork/growth-program/assets/89438593/ee245767-3972-4b0d-bc21-53bcb6bd82bd)
![t2](https://github.com/AstarNetwork/growth-program/assets/89438593/3f71315e-12bc-40bb-b821-7c7904b7bc58)
![t3](https://github.com/AstarNetwork/growth-program/assets/89438593/8ba90fe2-73bd-4dc7-b072-5688873809e6)
![t4](https://github.com/AstarNetwork/growth-program/assets/89438593/2f881af4-3e68-4354-aa03-7121d7c8c682)
![t5](https://github.com/AstarNetwork/growth-program/assets/89438593/d762b36f-07dd-4294-904f-4a379f5adaf4)

**Comment by Gunit2481** [comment]
Good support on Discord, I appreciate 🙏
