### ISSUE TITLE
May 2024 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2484]
Telegram Username: `@actlee`
Discord Username: `pithecus.astr`
ASTR Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

### Mandatory tasks
**CM**
- Manage the Korean TG community & Discord channel
- Share announcements
- Help and mingle with the community for various topics, especially these days for Yoki Origins, zkEVM, dApp staking v3 and/or investment/roadmap related questions
- Active community, having various discussions (2.2k+ members, 4.2k+ messages, and 150+ active users), some of the KR community members participated in the forum
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ff221b19-f6af-4b24-b7a7-dabb8a13af2a)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/0e25a4d6-f179-4122-8cfd-c2464c07625e)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/c6f2a73e-6daf-4f9a-a0de-dac87dd3a88b)

**GOV**
https://forum.astar.network/u/pithecus/activity
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/2bd3932a-da58-4a1c-9371-085e3d99fcf5)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/f3239092-8aaa-4a99-b19c-022d93ab0290)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/f6b0ce51-a76f-4876-86cd-8f5eb7526380)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ae037d56-f521-408f-b87a-c7674fbd8538)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/b5327245-78cf-4ea3-82aa-5c4809904319)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/71fdd462-10c8-40d7-a05e-36febde8ceaf)

### Optional tasks
**SM**
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/6eaa6ad4-4512-4fdf-ae15-7eb32cb4aff1)
https://x.com/spmlaihm/status/1796518120104075738
https://x.com/spmlaihm/status/1796518123018846629
https://x.com/spmlaihm/status/1796518125044691151
https://x.com/spmlaihm/status/1796518127267979526
https://x.com/spmlaihm/status/1796518129528664169
https://x.com/spmlaihm/status/1796518131885875481
https://x.com/spmlaihm/status/1796518134368887158
https://x.com/spmlaihm/status/1796208870030762413
https://x.com/spmlaihm/status/1796199088666391035
https://x.com/spmlaihm/status/1795833074045088107
https://x.com/spmlaihm/status/1795829854375686235
https://x.com/spmlaihm/status/1795679682630656395
https://x.com/spmlaihm/status/1795679684791074876
https://x.com/spmlaihm/status/1795679687856763275
https://x.com/spmlaihm/status/1795679689945571473
https://x.com/spmlaihm/status/1795679692072333782
https://x.com/spmlaihm/status/1795679694764818835
https://x.com/spmlaihm/status/1795679696782246196
https://x.com/spmlaihm/status/1795679698472837480
https://x.com/spmlaihm/status/1795679700330950981
https://x.com/spmlaihm/status/1795679702809723176
https://x.com/spmlaihm/status/1795679704906887544
https://x.com/spmlaihm/status/1795679706898891111
https://x.com/spmlaihm/status/1795798673936240827
https://x.com/spmlaihm/status/1795665142820335647
https://x.com/spmlaihm/status/1795479007741252046
https://x.com/spmlaihm/status/1795478596162589009
https://x.com/spmlaihm/status/1794293392115110355
https://x.com/spmlaihm/status/1793668829886955674
https://x.com/spmlaihm/status/1789526628776689883
https://x.com/spmlaihm/status/1789230832395145515
https://x.com/spmlaihm/status/1788520835541524640
https://x.com/spmlaihm/status/1788426989365232018
https://x.com/spmlaihm/status/1788278359689978226
https://x.com/spmlaihm/status/1785576985894257006

**CC**
아스타 네트워크 — 『콜드월렛』 튜토리얼
https://medium.com/astar-korea/baab53373e5a
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ddb5927d-f33b-4be4-87fc-7ad4adb8454d)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/32e77128-ec5d-4a0a-a2da-b7aa32f2085b)

**EM**
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/69760d32-8613-4357-94b8-d2d88b42d8ac)
A quick and unofficial community call in the Korean telegram group

**Comment by Gunit2481** [comment]
Good work Pithecus! 👏
