### ISSUE TITLE
May 2024 Contribution - Leo

### ISSUE THREAD

**Issue by LeoNeurolanche** [AstarNetwork/growth-program#2485]
Hello, I'm Leo. In May, as the Astar Network Turkey team, we were involved in many activities.

First, I will share the content I created from my own account with you. Let's take a look together.

Personal Twitter: https://twitter.com/neurolauncher?s=21&t=ISh07fvjMqpmUg40w5HqBg  Discord: neurolauncher.
 Astar Network Turkey Telegram: https://t.me/AstarTurkiye  Personal medium: https://medium.com/@enesfaruksahin?source=linkShare-7dc743decc41-1683244333  Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4

My personal Twitter montly views: 135k view

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/2fb2b25d-d9f0-4a04-9e51-739620801e3a)

**Cm: Community Support**
This month, in addition to actively providing support to the Turkish communityx In addition, I became the active person in the community. Mostly They are texting me from dm. 

We get new 67 member

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/ecb820cd-a6a0-48aa-b800-d6864ccd1c58)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/4617cd2a-90b3-4f8c-afa8-9c9712fb2c36)

**GOV - Governance & Project Engagement**
Gov- https://forum.astar.network/u/leo/activity
I participated in all active forum activities in governance this month. Additionally, I made efforts for the Astar ecosystem to be more decentralized.

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/39d13fa0-7eba-48b3-bd62-9a4400e0492f)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/c71e8dd8-eaef-4016-8f8a-2312ed394824)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/cc9ae1a5-99ee-44c7-ab91-c0387b687714)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/9af53a7d-f1ab-400f-9001-b01e28df7338)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/b7ded848-36f6-4b97-a674-02ab25a9ecca)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/679dd589-afe2-4bfd-9d15-45738e74c8e9)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/9d4872ec-6b4f-47c2-8833-cb0ef39ff031)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/b9bc933d-da2c-41eb-bcb6-5feeebbbb35e)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/0137d2b6-58df-42b7-95c7-a34dc2fb67de)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/4ed53af8-8826-4ef0-a3bf-b7e5c41c10dc)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/38749290-801e-49b6-8f01-7f725ba9f876)

**SM - SOCIAL MEDIA ENGAGEMENT**

I will share my social media activities on my personal account:

----------

**Tweet 1: **

Hybrid chain: Will Astar Network be the most successful project?

Astar Network; By accessing a hybrid chain with EVM, WASM and ZkEvm, it creates an innovative technological space for us users and developers.

Despite all these developments, how can $ASTR become successful?

(view 8823, like 102, Rt 33)

Link: https://x.com/neurolauncher/status/1786309037635592247?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/f0247391-0cd7-49da-9167-b6fb36065613)

-------------

**Tweet 2: **

Building successful project: Astar Network

If you are ASTR holder or active member of our ecosystem, it is essential for you to read this article.

The most important rule for the success of a blockchain project is to establish an active community and manage this process.

(View 10.090, 91 Like, 41 Rt)

Link: https://x.com/neurolauncher/status/1786704224249630889?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/e3c4aa2e-b83c-490b-bb14-6277db785afa)

-------------

**Tweet 3: Part 1 (Long tweet)**

Entering Decentralized World: Astar Network

In the world of #Web3, the governance model is emerging as important structure. Decentralization is the biggest factor in the success of projects. 

Today, we will talk about how dApp staking model can affect to Astar Governance.

Link: https://x.com/neurolauncher/status/1788253955941716046?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/77d92280-0c05-4fa7-ace5-00e13a39bcf5)

--------

**Tweet 4: Part 2 (Long Tweet)**

Step 2.2 Influence of Projects on Governance

On the @AstarNetwork, there is a dApp staking model that brings together projects and communities. 

Users stake their $ASTR in projects they support and trust, allowing these projects to earn rewards.

Link: https://x.com/neurolauncher/status/1788253967593382338?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/b558b629-92a7-438d-bfe4-c214920ad53d)

-------------

**Tweet 5:**

Creating a Hybrid Network: $ASTR

To succeed on blockchain, we must have a robust infrastructure. The underlying technology is the factor that sustains the entire ecosystem. 

As an academic person, would you like to understand why I chose to build on Astar Network?

(View 10612, Like 97, Rt 44)

Link: https://x.com/neurolauncher/status/1790767923591520364?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/4d74e37c-3478-4dee-bcfc-1042cbf9c680)

---------

Tweet 6: 
The last leaf of Sakura; Astar Network!

In 20th century, Japan made a great leap in the world economy and became one of the leading countries in technology.  

In 21st century, Watanabe Sota want to be pioneers of the web3 world. Do you think this hero could be successful?

(View 7597, Like 82, Rt 30)

Link: https://x.com/neurolauncher/status/1796149143833895349?s=46

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/165f322f-93e3-4283-b357-ad92ad5445de)

----------

**CC- CONTENT CREATION**

Creating a Successful Project on Astar Network

Link: https://theastarbulletin.news/creating-a-successful-project-on-astar-network-30ebaa05768e

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/1b8a1a8c-9a9b-41bc-9aab-1a26871e3efc)

---------

How did Astar Network become the most successful project of Polkadot? What set it apart from other parachains?

Link: https://medium.com/@enesfaruksahin/the-unstoppable-rise-dot-is-astr-94bd2c75c8d8

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/80cae6f6-7319-4708-a481-e353f467a7d8)

**Comment by Gunit2481** [comment]
Review, thank you Leo. 👍
