### ISSUE TITLE
May 2024 Contribution - VasaKing

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2486]
Telegram : @VasaKing

Discord Username: @VasaKing

ASTR Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

----- CM - Community Support & Management -----

Yoki Origins users support on the Italian Astar Community Telegram and Astar Discord

----- GOV - Forum partecipation -----

https://forum.astar.network/u/vasaking/activity

----- VSM - Astar Italia Twitter -----

Astar Guardians https://x.com/Astar_Italia/status/1785617134191514108

Skylab on Yoki https://x.com/Astar_Italia/status/1785623675221205222

D'Cent x Astar https://x.com/Astar_Italia/status/1786034943308578851

AggLayer space https://x.com/Astar_Italia/status/1786058046344507542

Yoki Updates community call https://x.com/Astar_Italia/status/1786476526143201560

Casio on Yoki https://x.com/Astar_Italia/status/1787061807984619957

Trekki on Yoki https://x.com/Astar_Italia/status/1787076957173358928

Neko Alliance with Ramz https://x.com/Astar_Italia/status/1787135161475506346

Galxe OG interns https://x.com/Astar_Italia/status/1787393881337733273

Mazda x Astar promo https://x.com/Astar_Italia/status/1787834461662417045

Yoki stats https://x.com/Astar_Italia/status/1787834458399277419

Astar zkEVM TGE https://x.com/Astar_Italia/status/1787862264231371064

Singular on Yoki https://x.com/Astar_Italia/status/1787873612185149499

Ramz discord event https://x.com/Astar_Italia/status/1788583017159561644

OG interns 2 https://x.com/Astar_Italia/status/1788899182037631324

AMA Casio https://x.com/Astar_Italia/status/1788901165117128726

Bitget on Yoki https://x.com/Astar_Italia/status/1788911338435015105

Sequence x Astar https://x.com/Astar_Italia/status/1789006188811620723

Tokyo Hackathon winners thread https://x.com/Astar_Italia/status/1790318319179878897

Astar space : Dynamic Community https://x.com/Astar_Italia/status/1790322562582368465

Doge Pound on Yoki https://x.com/Astar_Italia/status/1791091345945194660

Doll Mint on Yoki https://x.com/Astar_Italia/status/1791093359357886972

VeryLongSwap simple staking https://x.com/Astar_Italia/status/1791098644956954846

NEET labz dApp promo https://x.com/Astar_Italia/status/1791103039144624446

TGE with Bitget https://x.com/Astar_Italia/status/1791116320785698955

Ramz x The Graph https://x.com/Astar_Italia/status/1792466783816855993

Astar governance discord event https://x.com/Astar_Italia/status/1792492246652133402

Walkmon 1 https://x.com/Astar_Italia/status/1792495486433214800

Lugano event https://x.com/Astar_Italia/status/1792555889750356001

Gate wallet x Astar https://x.com/Astar_Italia/status/1792834041319993648

Walkmon 2 https://x.com/Astar_Italia/status/1792851933507596559

0n1Force Mint https://x.com/Astar_Italia/status/1792912857975214423

The Wonder World on Yoki https://x.com/Astar_Italia/status/1792916037375053858

PBADAO on Yoki https://x.com/Astar_Italia/status/1792919070582481243

Algem testing campaign https://x.com/Astar_Italia/status/1792948469201822090

TGE with Gate.io https://x.com/Astar_Italia/status/1793174963131924765

Walkmon 3 https://x.com/Astar_Italia/status/1793294636875673918

Hydra(now Hydration) Proposal https://x.com/Astar_Italia/status/1793302475161653696

Walkmon 4 https://x.com/Astar_Italia/status/1793970352961597749

Walkmon intro https://x.com/Astar_Italia/status/1793974880934998471

Rabby wallet free gas x Astar https://x.com/Astar_Italia/status/1793980168228475041

Airdrop Snapshot  https://x.com/Astar_Italia/status/1794997601605222764

Walkmon x HAHA https://x.com/Astar_Italia/status/1795077502689583123

Walkmon x Moonveil https://x.com/Astar_Italia/status/1795122795548168336

YoudleDAO x Astar https://x.com/Astar_Italia/status/1795202664071917661

Walkmon x SNPIT https://x.com/Astar_Italia/status/1795334191829110912

![May 1 ](https://github.com/AstarNetwork/growth-program/assets/63927981/0b3ed060-eda5-4aa3-8753-c260aa0d4515)

![May 2](https://github.com/AstarNetwork/growth-program/assets/63927981/57834abb-2d50-45b9-9390-1e074890aca7)

----- CC - Medium -----

Astar Studio introduction
https://medium.com/@AstarItalia/astar-studio-la-piattaforma-per-sviluppatori-con-un-programma-di-sovvenzioni-da-200-000-dollari-09c3fdcab746

----- Extra -----
Astar Portal UI tester

**Comment by Gunit2481** [comment]
Great work, thank you! 💪
