### ISSUE TITLE
May 2024 Contibution - Max.eth

### ISSUE THREAD

**Issue by MaxEthHealthy** [AstarNetwork/growth-program#2488]
Telegram Username: @max_eth_heatlhy
Discord Username: max.eth.healthy
X User name: @max_eth_heatlhy
ASTR Wallet Address: WAgeWZSPzQdJf58kELDGBp2P8VRCNFie9s3j7fgvpJduNMX

----
**CM**:

- Telegram
https://combot.org/c/-1001138925620
<img width="1121" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/4c6bf185-4c78-4ae2-b799-05bd1bbc6c37">

- Discord

![image](https://github.com/AstarNetwork/growth-program/assets/157904479/92189aee-8fe7-4ca3-988e-debfedef4be8)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/726f6ddc-51fe-41fa-b0da-84769f2e06a5)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/8387c7db-13b3-44df-a9b6-885c0c279bac)
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/acb9eb25-8358-4152-b331-a3ed6a6c8c93)

**GOV**

https://forum.astar.network/u/max.eth/activity
https://forum.astar.network/u/max.eth/summary

- voted on each proposal or almost 
- forum
<img width="925" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/2bb01b50-5369-45c8-a2d9-efe9738f43e2">

**SM**

I grow my account to 3000 followers this month.

- Analytics

<img width="1228" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/c24f95fd-31c2-4ba5-bbc0-1cff2ab12af6">

- sample of posts

<img width="587" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/77addfaa-72bf-41d2-bfb6-638b96c5c79a">
<img width="597" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/4e18cb58-3bc9-491d-a406-5f9fdc1c88fb">
<img width="582" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/3da68de4-bf99-45e5-8fcf-320e7809833b">
<img width="593" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/7939dc1e-1089-4e14-9680-e25067f6fdb7">
<img width="603" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/1edeed19-472c-4e71-833f-89828d8299ac">
<img width="562" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/03921f1d-a632-4861-b388-c04a00b785e1">

**CC**

- French translation of the newsletter 

https://www.bonzai.pro/astar_newsletter_fr/posts/rmX9_8534/astar-zkevm-depasse-les-100-000-transactions-quotidiennes-et-plus-encore
<img width="739" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/6d05290d-dddd-400c-841b-92d4be919062">

Articles

- Sota becoming director of Sony
https://www.bonzai.pro/maxeth/posts/8yRo_9011/sota-to-be-nominated-as-one-of-the-directors-of-sony
https://medium.com/@max.eth/sota-to-be-nominated-as-one-of-the-directors-of-sony-4a225c2ebc6b

**Event**
I went to an event with founders and KOLs happening during NFC Lisbon and I introduce Astar to each person I talk with.

**Comment by Gunit2481** [comment]
Good job Max! 👏
