### ISSUE TITLE
June 2024 Contibution - Max.eth

### ISSUE THREAD

**Issue by MaxEthHealthy** [AstarNetwork/growth-program#2489]
Telegram Username: @max_eth_heatlhy
Discord Username: max.eth.healthy
X User name: @max_eth_heatlhy
ASTR Wallet Address: WAgeWZSPzQdJf58kELDGBp2P8VRCNFie9s3j7fgvpJduNMX
----

**CM**

- Telegram
https://combot.org/c/-1001138925620

Managing my community to participate to the governance with the important forum discussion
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/66d7b18a-d824-484d-9c0b-656fcd600c1c)

Community management via X, replies and DMs:
![image](https://github.com/AstarNetwork/growth-program/assets/157904479/0e8f017f-96a9-4811-8557-b60c9ab77c99)

**GOV**

https://forum.astar.network/u/max.eth/activity
https://forum.astar.network/u/max.eth/summary

<img width="923" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/89cfa218-e714-4e7b-82b7-10aaef6c16ac">

**SM**

- June analytics:
<img width="981" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/97210209-7f25-4061-808f-c184cee33ceb">

- Sample of posts

<img width="579" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/ab4a5249-74a9-4a12-98da-17e9a6bf97f8">

<img width="610" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/341fbc16-3895-4424-8076-8b160aee33b1">

<img width="581" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/35513bf2-46c5-45e3-b577-0d83b9605c99">

<img width="590" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/31c97ea5-30d9-4d3b-9229-78cc15609862">

<img width="591" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/f36096e1-704e-45bb-bf7f-40f449e0a706">

<img width="583" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/9a25945c-353d-4fd2-8ef1-5eeee2b088fa">

**CC**

French translation of the newsletter

- Un mois de croissance massive pour l'Astar zkEVM:  https://www.bonzai.pro/astar_newsletter_fr/posts/ojea_9015/astar
- La prochaine période de vote a commencé pour le dApp Staking:
- https://www.bonzai.pro/astar_newsletter_fr/posts/q9Y0_9844/la-prochaine-periode-de-vote-a-commence-pour-le-dapp-staking

Articles:
https://medium.com/@max.eth/founder-of-astarnetwork-watanabesota-recently-talked-about-the-astar-x-sony-collaboration-in-an-bc14df03907e
https://www.bonzai.pro/maxeth/posts/7B6K_9832/sota-talk-about-sony-x-astar-in-an-blockbeats-interview
<img width="716" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/c0a0a6be-c141-420a-ac22-d252ba072ac1">

https://medium.com/@max.eth/making-the-most-of-the-new-astar-dapp-staking-e00feda70cd5
https://www.bonzai.pro/maxeth/posts/pNYW_9833/making-the-most-of-the-new-astar-dapp-staking
<img width="642" alt="image" src="https://github.com/AstarNetwork/growth-program/assets/157904479/c395a4a8-59c2-4bc4-8f23-24ef1491666d">

**Comment by Gunit2481** [comment]
Thank you Max!

For next time, please add a screenshot of Telegram's combot data. Twitter is not part of community management, as it is already included in social management (SM). Community management covers Astar Discord, Telegram and local communities.
