### ISSUE TITLE
June 2024 Contribution - Tech. Ambassador: Carlos Rodríguez 

### ISSUE THREAD

**Issue by Juminstock** [AstarNetwork/growth-program#2493]
_Technical ambassador information:_

Telegram Username: **@Juminstock**
Discord Username: **@Juminstock#8856**
ASTR Wallet Address: **ZJKp9fuuQihYopwLEmxZ55zU5WMpeXi95HAPRPUiGcZgZQz**

**Contributions:**

**DS - Support developers on Astar Discord:**

<img width="1131" alt="Screenshot 2024-07-01 at 10 15 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/2197183f-36a9-4f5b-a429-6041cbddc196">
<img width="1131" alt="Screenshot 2024-07-01 at 10 18 09" src="https://github.com/AstarNetwork/growth-program/assets/105810861/0c621ad7-9965-40da-8d8a-f8a38e239aa1">
<img width="1131" alt="Screenshot 2024-07-01 at 10 18 51" src="https://github.com/AstarNetwork/growth-program/assets/105810861/50b125cd-1470-401b-839d-6a6cbcf79ce0">
<img width="1131" alt="Screenshot 2024-07-01 at 10 15 51" src="https://github.com/AstarNetwork/growth-program/assets/105810861/8ea12f98-389f-4786-ab5b-434c32957232">
<img width="1131" alt="Screenshot 2024-07-01 at 10 16 17" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3044b32f-36aa-4d20-b053-e742f34b7c26">
<img width="1131" alt="Screenshot 2024-07-01 at 10 16 50" src="https://github.com/AstarNetwork/growth-program/assets/105810861/baf7bd84-0d88-450c-8582-d002b7601d1a">
<img width="1131" alt="Screenshot 2024-07-01 at 10 17 11" src="https://github.com/AstarNetwork/growth-program/assets/105810861/4d0ef546-6e18-465f-805b-e61edf299227">
<img width="1131" alt="Screenshot 2024-07-01 at 10 17 43" src="https://github.com/AstarNetwork/growth-program/assets/105810861/815c1aac-0057-4635-b8a0-30a327d86842">
<img width="1131" alt="Screenshot 2024-07-01 at 10 18 01" src="https://github.com/AstarNetwork/growth-program/assets/105810861/ba49904b-1b1d-4397-b180-5b66bdbb527b">
<img width="1131" alt="Screenshot 2024-07-01 at 10 13 52" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a4b36209-2d4f-4a71-9099-4be9ad4c3850">
<img width="1131" alt="Screenshot 2024-07-01 at 10 14 13" src="https://github.com/AstarNetwork/growth-program/assets/105810861/1e1c7c16-dd9b-4087-aebe-89b52debaf1b">
<img width="1131" alt="Screenshot 2024-07-01 at 10 14 53" src="https://github.com/AstarNetwork/growth-program/assets/105810861/a5e0fec4-dc1b-4576-920a-26fa8313bcd4">

----------------------------------------------------------------------------------------------------------------

**GOV - Engaged in governance discussion:**

- https://forum.astar.network/u/juminstock/activity
- https://astargov.com/user/5FRjNrhq8B5bKyo6qwKqXQviP2oErRpy7sn29iBcqucc6hTk?activityType=votes

----------------------------------------------------------------------------------------------------------------

**EM - Events managed:**

- Astar Maracay Meetup: https://forum.astar.network/t/astar-network-in-maracay-venezuela/6839?u=juminstock
- Astar Network workshop IRL 1: https://x.com/Juminstock/status/1806849350103974094 
- Astar Network workshop IRL 2: https://x.com/Luis96xd/status/1806836357743968458
- Astar Network workshop IRL 3: https://x.com/autobanco/status/1806860086939185181
- Astar Network workshop IRL 4: https://x.com/ch1nux/status/1807109714330669470

----------------------------------------------------------------------------------------------------------------

**CC - Content management:**

- Astar Maracay meetup post: https://x.com/Juminstock/status/1797662482057646406
- Astar ecosystem update in spanish: https://x.com/Juminstock/status/1798075151667654736
- Astar bulletin post mention: https://x.com/AstarBulletin/status/1798308792884416801
- Technical article and post about client side: https://x.com/Juminstock/status/1801259459332743509
- Technical article about smart contracts on Astar: https://x.com/Juminstock/status/1802705521759113401
- Article about smart contract stack on Astar: https://x.com/Juminstock/status/1803779370521149778
- Repost an important announcement: https://x.com/StartaleHQ/status/1805490046914674834
- Astar news twitter space: https://x.com/Juminstock/status/1805662990265442547
- Second link: https://x.com/Juminstock/status/1806026881617064382

----------------------------------------------------------------------------------------------------------------

**CC - Community management: **

- Creation and maintenance of a local community of developers interested in Polkadot and **Astar Network**: 

<img width="925" alt="Screenshot 2024-07-01 at 10 29 26" src="https://github.com/AstarNetwork/growth-program/assets/105810861/da3979b1-1bf6-4d28-a705-02ea2c8d9a86">
<img width="925" alt="Screenshot 2024-07-01 at 10 30 00" src="https://github.com/AstarNetwork/growth-program/assets/105810861/3910d01b-cda0-4565-8122-67a0dc96298b">
<img width="925" alt="Screenshot 2024-07-01 at 10 30 18" src="https://github.com/AstarNetwork/growth-program/assets/105810861/dc9a10e8-6372-436f-b5e1-145abda4ed6c">

**Comment by Gunit2481** [comment]
Great work Carlos! 💪

**Comment by Juminstock** [comment]
I appreciate it, G!
