### ISSUE TITLE
June 2024 Contribution - pithecus

### ISSUE THREAD

**Issue by crypto-pithecus** [AstarNetwork/growth-program#2494]
Telegram Username: `@actlee`
Discord Username: `pithecus.astr`
ASTR Wallet Address: `b1gtBwnLUzcxMfXBPAd8j5m9Xxj9W77cBUcnHcijw1CqiUM`

### Mandatory Tasks
**CM**
- Managed the Korean TG and Discord community
- Shared announcement and updated on TG, Discord, and X
For example,
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/f7ec9a28-111b-4d2d-99a6-e94f964f5b1e)
https://t.me/astar_kr/126971
https://t.me/astar_kr/126972
https://t.me/astar_kr/127176
https://t.me/astar_kr/127275
https://t.me/astar_kr/128112
https://t.me/astar_kr/128287
https://t.me/astar_kr/128968
https://t.me/astar_kr/129087
https://t.me/astar_kr/129115
https://t.me/astar_kr/129157
https://t.me/astar_kr/129314

- Helped the community members in regard to the current development, milestones, news, dApp staking, latest updates on forum, vote, etc.,
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/37f06002-0cb1-46d9-b52b-3ec1e6aabffb)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/87c05e57-9c15-487f-b089-bc35466878e4)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/d4ecdf20-f274-4773-a84c-8526e593dac9)

**GOV**
https://forum.astar.network/u/pithecus/activity
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/6ab3543f-ab2f-45bc-af6f-a51b364a6e85)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/e4e26a30-120a-45f0-aefd-8fedfd7744f4)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/866bcfcb-a002-4873-9c2d-4162a40daea4)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/acf78364-435c-43d5-a10d-c3e8ca28659b)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/1e49a3d8-4552-48e4-9d99-f894b025a156)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/1db77e83-b4ef-49b9-85d6-ee5c6058add4)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/c6eb276a-adb3-426a-b995-fa8c3e1067df)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/9b3ac2c5-5db7-421b-853d-3d96f562dbb7)

### Optional Tasks
**SM**
Personal account
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/eef7ab2c-b11c-49d0-94d1-9a5b1d0ab089)

https://x.com/spmlaihm/status/1807411778403418209
https://x.com/spmlaihm/status/1807400454357147895
https://x.com/spmlaihm/status/1807400456928305631
https://x.com/spmlaihm/status/1807400461047128448
https://x.com/spmlaihm/status/1807400464624833021
https://x.com/spmlaihm/status/1807400468496220318
https://x.com/spmlaihm/status/1807400471658635302
https://x.com/spmlaihm/status/1807400475374854372
https://x.com/spmlaihm/status/1807400479237833055
https://x.com/spmlaihm/status/1806599624439775279
https://x.com/spmlaihm/status/1806596929058419030
https://x.com/spmlaihm/status/1805880301630943394
https://x.com/spmlaihm/status/1805244635654013319
https://x.com/spmlaihm/status/1805239983092957184
https://x.com/spmlaihm/status/1805122151365718025
https://x.com/spmlaihm/status/1805121897559941215
https://x.com/spmlaihm/status/1804693417873559843
https://x.com/spmlaihm/status/1804692380311781471
https://x.com/spmlaihm/status/1804691528515723539
https://x.com/spmlaihm/status/1804691530763956535
https://x.com/spmlaihm/status/1804691532588482590
https://x.com/spmlaihm/status/1804691534454894776
https://x.com/spmlaihm/status/1804691536208073181
https://x.com/spmlaihm/status/1804691537806143557
https://x.com/spmlaihm/status/1804691540020810154
https://x.com/spmlaihm/status/1804687347071479905
https://x.com/spmlaihm/status/1804687349722341510
https://x.com/spmlaihm/status/1804687352008155479
https://x.com/spmlaihm/status/1804687354453742070
https://x.com/spmlaihm/status/1804687356504547705
https://x.com/spmlaihm/status/1804687358261866893
https://x.com/spmlaihm/status/1804687360304554183
https://x.com/spmlaihm/status/1804449697928495588
https://x.com/spmlaihm/status/1803652912461058325
https://x.com/spmlaihm/status/1803652914251956321
https://x.com/spmlaihm/status/1803035643716440455
https://x.com/spmlaihm/status/1797513534638805097

Astar Korea account
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/7678d408-8a47-467b-8b2b-a4e7c7385812)
for example,
https://x.com/AstarNetwork_KR/status/1805461567695208636
https://x.com/AstarNetwork_KR/status/1805461570320814167
https://x.com/AstarNetwork_KR/status/1801363976023953513
https://x.com/AstarNetwork_KR/status/1801363978326507906
https://x.com/AstarNetwork_KR/status/1801363980352721209
https://x.com/AstarNetwork_KR/status/1803035164945399872
https://x.com/AstarNetwork_KR/status/1803651122734801403

**CC**
- 아스타 네트워크 디앱 스테이킹 V3 — 사용자 가이드 (업데이트편)
https://medium.com/astar-korea/f301ce7bd71a
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/77945c0b-3ef9-4d5b-94f6-12ebc15b3430)

- 아스타 에볼루션 Astar Evolution
- https://medium.com/astar-korea/88aa153ec125
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/a6a2220e-9f36-48b7-9de2-2dd94f68ac7a)

![image](https://github.com/AstarNetwork/growth-program/assets/90181025/ccf3195f-bb37-46a9-9553-4527486b52cf)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/6bf06fd7-7202-4962-829f-ae416fc7f41b)

**EM**
- [KR] Community call (Jun/18th): Yoki Origins summary and what's coming up next?
https://x.com/i/broadcasts/1OwxWYYoMYkGQ
https://x.com/AstarNetwork_KR/status/1803035164945399872

- Campaign for the Korean community: WL 30 spots for The WALKMON NFT collection by Team So Noisy
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/dbe3542d-ccc5-46d2-9f0b-db69152e3efb)
![image](https://github.com/AstarNetwork/growth-program/assets/90181025/10277ed0-87be-44e3-b85f-a665537b3710)

**Comment by Gunit2481** [comment]
Thank you Pithecus!
