### ISSUE TITLE
June 2024 Contribution - bao

### ISSUE THREAD

**Issue by 0xbao** [AstarNetwork/growth-program#2495]
Telegram Username: @bao1993jp
Discord Username: bao#bao1993
Twitter User name: @bao1993jp
ASTR Wallet Address: beeZfXVZppLCGtZuE4jRZLD9RperjqbfCYrC148Np1uv4pE

# Contributions:

### -Supporting to inquiries from the community almost every day
Astar Network Discord: JAPAN channel
Astar Network Discord: SUPPORT channel **(support to Japanese QA)**
Astar Network Japan Telegram: https://t.me/AstarJapan
### -During the voting period, I created articles introducing recommended dApps to support the community.
https://note.com/bao1993/n/nd4d7b94ec203

## -GOV
I posted **27 times** on the Forum and actively participated in governance.
https://forum.astar.network/u/bao/activity

![スクリーンショット 2024-07-02 10 36 04](https://github.com/AstarNetwork/growth-program/assets/123560716/ae03c4b3-718f-42b0-a5e4-3fd8eb125b63)
![スクリーンショット 2024-07-02 10 36 30](https://github.com/AstarNetwork/growth-program/assets/123560716/b910fa9e-178d-4a5d-8414-b8ce04b3d282)
![スクリーンショット 2024-07-02 10 36 42](https://github.com/AstarNetwork/growth-program/assets/123560716/5f7d7853-1f11-46a6-92ed-9f01bb16137f)
![スクリーンショット 2024-07-02 10 36 52](https://github.com/AstarNetwork/growth-program/assets/123560716/29e08690-7f03-42dc-ad89-3f312636f5df)

### [1] Astar Weekly Journal June.8
EN ver.
https://theastarbulletin.news/token-burn-70-astar-weekly-journal-0f6547194290
JP ver.
https://astarweeklyjournal.substack.com/p/token-burn

### [2] Astar Weekly Journal June.16
EN ver.
https://theastarbulletin.news/2nd-voting-period-71-astar-weekly-journal-19a1f639c06b
JP ver.
https://astarweeklyjournal.substack.com/p/2nd-voting-period

### [3] Astar Weekly Journal June.22
EN ver.
https://theastarbulletin.news/yoki-origins-reward-72-astar-weekly-journal-89d23219215e
JP ver.
https://astarweeklyjournal.substack.com/p/yoki-origins-reward

### [4] Astar Weekly Journal June.29
EN ver.
https://theastarbulletin.news/astar-evolution-73-astar-weekly-journal-91a140748e18
JP ver.
https://astarweeklyjournal.substack.com/p/astar-evolution
![スクリーンショット 2024-07-02 10 40 33](https://github.com/AstarNetwork/growth-program/assets/123560716/5dddaf2a-e6f4-4f7a-a0aa-750320fb98be)
![スクリーンショット 2024-07-02 10 39 59](https://github.com/AstarNetwork/growth-program/assets/123560716/f071f4ee-c2ee-494c-bee9-c572d33bd447)

### -Key posts that contributed to social media engagement
-The post about **"Introduction of dApp Staking"** has garnered **3.9k impressions.**(https://x.com/bao1993jp/status/1801796062799401183)

-The post about **"Explanation of token burn proposal"** has garnered **3.4k impressions.**(https://x.com/bao1993jp/status/1799981610995249433)

-The post about **"Explanation of Astar Evolution"** has garnered **2.6k impressions.**(https://x.com/bao1993jp/status/1805410529076527219)

![スクリーンショット 2024-07-02 10 47 36](https://github.com/AstarNetwork/growth-program/assets/123560716/9c48589a-0776-4c11-a9e4-42a7e7657646)

**Comment by Gunit2481** [comment]
Good work Bao!
