### ISSUE TITLE
June 2024 Contribution - GuiGou

### ISSUE THREAD

**Issue by GuiGou12358** [AstarNetwork/growth-program#2497]
Telegram Username: @GuiGou12358
Discord Username: GuiGou#1021
Twitter Username: @GuiGou12358
Native Wallet Address: 5DaCixaPPaYrdGdSxP6Mwptn7dPNp3DTeJCQKuCUQe5jp6fL

### DS
Support for builders and developers in Astar Discord
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/01090c39-f765-488c-8499-ef29897516f6)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/5c28989d-d629-4888-9bbc-e257615f70df)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/7d5ec9ca-a845-411d-b296-1ddc2d61295b)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/72289346-14ff-4c97-95c0-d0c0eb8e1a30)

### Community
Moderator (delete scams) and support for the community in the local Telegram channel
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/913135c2-5e2e-4e80-a800-68545ac369aa)

### GOV - Governance & Project Engagement
Activity on the forum: https://forum.astar.network/u/guigou/activity

Here is the summary:
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/fbb3c907-e13b-418f-ac6d-d58610705c5d)

Here are the activities:
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/28b68b4b-0ab5-4ec5-ad10-3ed8cd24ffb2)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/f4830245-d539-467d-b747-c8fb0730c0f7)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/87d481b1-c484-4963-b376-4bc2af7ba1f4)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/893cd901-ef99-48d4-bf04-96f83503496e)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/f6f60cdd-857d-418f-abd3-c38a293639df)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/184ea4cd-66cd-43d5-b67b-989646af3cd0)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/0ae6b1f6-4653-4c05-93bb-6ff405059f09)

### BUILD
Here the proof of work: https://github.com/GuiGou12358
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/6c6f8adb-3e7a-43ab-8fa5-b9fe7897430b)

Check the updates and add a comment for PR  https://github.com/AstarNetwork/Astar/pull/1240

Spot an issue with Astar Portal
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/2a553b3e-60b4-44ae-8cab-21f71a98a0cd)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/779300ed-d6e3-4141-85e1-3358a489d966)
![image](https://github.com/AstarNetwork/growth-program/assets/92046056/fc4cad60-4d43-449b-ba81-5a940108be4e)

### OTHER - PINK

Snapshotting and extract all addresses and amounts staked during the voting sub-period for period 2.

**Comment by Gunit2481** [comment]
Thanks GuiGou! 💪
