### ISSUE TITLE
June 2024 Contribution - Marco Da Rocha (Pitcoin)

### ISSUE THREAD

**Issue by pitcoin777** [AstarNetwork/growth-program#2498]
Discord Username: pitcoin #3857
ASTR/SDN Wallet: ae4jogSftsjxjLr3RCzifMSmU9wcAuUaXw4PYrqrRVXtiQM

CM - Manage and Support
Astar Network PT (Telegram) and Astar Network (Discord)
Telegram: https://t.me/astarnetworkPT - 517 members (-9 members)
![Screen Shot 2024-07-02 at 08 46 28](https://github.com/AstarNetwork/growth-program/assets/99457582/c8bcf0d4-f22b-4967-969a-e49c98728204)
![Screen Shot 2024-07-02 at 08 46 41](https://github.com/AstarNetwork/growth-program/assets/99457582/6fa5940b-37e2-4b73-99d0-befbd8ac1713)

GOV - Governance & Project Engagement
https://forum.astar.network/u/pitcoin777
![Screen Shot 2024-07-03 at 10 04 41](https://github.com/AstarNetwork/growth-program/assets/99457582/8be07ca7-eae7-472d-b74b-119b92bc4167)
![Screen Shot 2024-07-03 at 10 04 47](https://github.com/AstarNetwork/growth-program/assets/99457582/5132f958-184d-47e1-b5f1-1a35b7f45d77)
![Screen Shot 2024-07-03 at 10 04 53](https://github.com/AstarNetwork/growth-program/assets/99457582/c1269129-f647-45ba-ad4a-1fe3bd73de84)
![Screen Shot 2024-07-03 at 10 05 03](https://github.com/AstarNetwork/growth-program/assets/99457582/9b10a480-c3ab-4648-82d6-198a767dff1d)

SM - Social Media Engagement
Twitter @Pitcoin_ – 1925 followers (+23 new followers)
![Screen Shot 2024-07-03 at 10 07 47](https://github.com/AstarNetwork/growth-program/assets/99457582/179b82cc-610d-4221-8c05-574314c801f2)
![Screen Shot 2024-07-03 at 10 07 56](https://github.com/AstarNetwork/growth-program/assets/99457582/4553a9a3-62d1-48a1-9752-46c29f7a9e68)

CC - The Content Creator

Astar June News
https://grillapp.net/6283/181289?ref=7524

Web3 no Japão e Atualização da Sony Chain (translation)
https://grillapp.net/6917/182317?ref=7524

**Comment by Gunit2481** [comment]
Good work 👏
