### ISSUE TITLE
June 2024 Contribution - defiguy 

### ISSUE THREAD

**Issue by astardefi** [AstarNetwork/growth-program#2499]
June 2024 Contribution - defiguy
Telegram Username: @defiguy2022
Discord Username: defiguy
Twitter User name: defiguy22
ASTR Wallet Address: YJ9ZyKwzX6tLh21eV1YT61EpihraYAdJYbcpyJFDwdyrfi7

# CM
## Astar Telegram (BR)
![june-telegram-2024-2](https://github.com/AstarNetwork/growth-program/assets/104277195/b1e08357-a7a0-427c-bb25-9397aaa2e5f6)
![june-telegram-2024](https://github.com/AstarNetwork/growth-program/assets/104277195/fe68fabd-7277-4ab0-b548-9dfcfc82b3e3)

## defiguy group
https://t.me/+QfslDL_epwZlMmUx
### Around 60 messages talking about Astar and taking questions around the ecosystem
![Screenshot 2024-07-03 at 22 28 57](https://github.com/AstarNetwork/growth-program/assets/104277195/3f3d0ce0-25ab-4651-9845-aafe1b776828)

# GOV
![Screenshot 2024-07-03 at 19 38 46](https://github.com/AstarNetwork/growth-program/assets/104277195/6f13433e-0db7-4d6f-a99e-08f02454671b)
![Screenshot 2024-07-03 at 19 39 17](https://github.com/AstarNetwork/growth-program/assets/104277195/fe726528-802d-42b3-aa86-56a0ae8de71c)
## defiguy telegram (248 members)

# SM
## twitter defiguy
![Screenshot 2024-07-03 at 19 43 05](https://github.com/AstarNetwork/growth-program/assets/104277195/341f7131-66d1-46db-bad1-956e35d59c8f)

# CC
## BURN de 5% do SUPPLY de ASTR!!! DAPP STAKING season 2 chegando!!!
https://youtube.com/live/V2Fs0xErgcs
![Astar updates (67)](https://github.com/AstarNetwork/growth-program/assets/104277195/836fbbe4-0106-4b6b-9f9a-756b2a4ec0cd)

## AIRDROP da YOKI CHEGANDO!!! Dapp staking nativo com a LEDGER!!!
https://youtube.com/live/7VW2jJEkIJg
![Astar updates (68)](https://github.com/AstarNetwork/growth-program/assets/104277195/1055d55d-7ebd-40c2-9156-e533dddfacae)

## CRITERIOS do AIRDROP da YOKI DIVULGADOS!!! ASTAR 3.0 CHEGANDO??
https://youtube.com/live/V2Fs0xErgcs
![Astar updates (69)](https://github.com/AstarNetwork/growth-program/assets/104277195/d88ec356-c158-4810-b5b3-11800d69e73d)

# BD

## Showing the features of Astar for 0xLabs (BD company connects with different teams)
![Corentin-astar](https://github.com/AstarNetwork/growth-program/assets/104277195/681a0733-86b7-40d7-b7d8-704aaef54eef)

## Conversation with Aztec well know influencer and businnes founder in Polygon ecosystem, to understand more about Astar and make partnerships with Astar projects
![aztec-astar](https://github.com/AstarNetwork/growth-program/assets/104277195/ff6cb204-b5f1-49e0-a45f-412924e07149)

**Comment by Gunit2481** [comment]
Good work Defiguy! 👏
