### ISSUE TITLE
June 2024 Contribution - Van 

### ISSUE THREAD

**Issue by eudomar500** [AstarNetwork/growth-program#2500]
Telegram Username: **@DTK21**

Discord Username: **Van9719**

ASTR Wallet Address: **YAVPSp5GTZePeR74c9qvmojFcFPtxcJZnyEh1mHu5UVqqat**

# Contributions:

# 1. CM - Community Management

### -Combot Link: https://combot.org/c/1314210486

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/91a66cac-0ee0-45fd-9351-45c59d78a0eb)
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/0705ed86-51f7-472c-8292-81938809245d)
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/84ddd1be-6034-4327-97fa-e8d69c7ee827)

# 2. GOV - Governance & Project Engagement
 
### -Profile: https://forum.astar.network/u/vangardem/activity

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e16c8129-d4e8-4c59-bf41-cfc08970631b)
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/3c8bb5a8-6dcc-490a-94a3-e2386fc3ed46)
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/a8d78400-af23-4d0b-8df2-b59de88a1613)

# 3. SM - Social Media Engagement

### Impressions and post activity:

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e4cfe6a7-552f-48f5-b4ce-7d0535a91cb4)

1. https://x.com/Eu1583/status/1797968203269943522
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/5de27b4d-e8da-44a6-bf40-e8445436cb03)

2. https://x.com/Eu1583/status/1799446168360903068
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/b87e88ba-83c6-4ac4-a34e-226beb126331)

3. https://x.com/Eu1583/status/1800887632655761538
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6c5452fb-fa14-49a7-b40d-6601fd49577a)

4. https://x.com/Eu1583/status/1800906293160640846
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/521743c4-a92a-4577-acad-610a90716f41)

5. https://x.com/Eu1583/status/1800911303860727869
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/5e5206c7-8d57-4488-be79-40ab0425d26f)

6. https://x.com/Eu1583/status/1800998562534174849
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/9ffa2231-9c3d-46dd-9158-929f5c304637)

7. https://x.com/Eu1583/status/1801040603414663443
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/05727ad5-2302-4495-b678-b927401ed3a1)

8. https://x.com/Eu1583/status/1801983731529404539
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/b885968b-927f-41bd-b844-0b527f45a7f0)

9. https://x.com/Eu1583/status/1802707574678077655
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/7aceb4e1-56fc-4bb9-9942-ab41ec08b33a)

10. https://x.com/Eu1583/status/1803045995883672020
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/9533f7b3-8065-42c4-8934-ad80d60b72e8)

11. https://x.com/Eu1583/status/1803111465194279158
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/3cf1b32a-15f7-4e01-9799-8006c24a87fc)

12. https://x.com/Eu1583/status/1803398031691132981
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e022afbb-9199-401a-9e76-22704371e0f1)

13. https://x.com/Eu1583/status/1803539358814969915
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/a662320f-deac-4078-9fdc-cb46ae001e79)

14. https://x.com/Eu1583/status/1803604119229194294
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/e15edf82-9759-40c2-b064-8b35af28846f)

15. https://x.com/Eu1583/status/1805261528867766331
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/04932063-e98c-4f5e-a2c7-c7b24ecbb28c)

16. https://x.com/Eu1583/status/1805850337946845584
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/2d078e1f-9493-4791-a21a-b05de37773ba)

17. https://x.com/Eu1583/status/1806709365644165429
![image](https://github.com/AstarNetwork/growth-program/assets/39355497/f53f980d-89e8-44a6-b32a-3f25dc227cb5)

# 4. Others:

### - Link: https://astarweeklynews.substack.com/

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/f3c57432-0495-4922-922d-c9c368eff235)

![image](https://github.com/AstarNetwork/growth-program/assets/39355497/6d7fd3a7-4223-4d1d-ac89-dc2d791fef3b)

# Total Views - June: 410

# Total Users: 202

# 5. Content Creation:

https://medium.com/@eudomar500/dapp-staking-v3-second-voting-period-is-open-062f32585835

![Elevate Your Tech Game with Thynk Unlimited! (4)](https://github.com/AstarNetwork/growth-program/assets/39355497/247e12ee-fc94-497d-816e-84919769c1ca)

# Thank You!

**Comment by Gunit2481** [comment]
Good work ! Thanks 🙌
