### ISSUE TITLE
June 2024 Contribution - VasaKing

### ISSUE THREAD

**Issue by VasaKing** [AstarNetwork/growth-program#2501]
Telegram : @VasaKing

Discord Username: @VasaKing

ASTR Wallet Address: Wma5KpbBszEHmTQpAt2HzhT5mPG4iUeZiuqPkmqZVhJz4a2

----- CM - Community Support & Management -----

Users support on the Italian Astar Community Telegram and Astar Discord support (still cannot show data cause I'm not the owner )

----- GOV - Forum partecipation -----

https://forum.astar.network/u/vasaking/activity

----- VSM - Astar Italia Twitter -----

Astar Demo Days x Crossmint  https://x.com/Astar_Italia/status/1796849376838472166

Walkmon x Genso Meta https://x.com/Astar_Italia/status/1796882555922174325

Yoki Origins end https://x.com/Astar_Italia/status/1796895118437625947

Dune Analytics https://x.com/Astar_Italia/status/1796919641287328250

Walkmon x Mindblowon https://x.com/Astar_Italia/status/1796964937014882310

Dwellir on Astar 1 year celebration https://x.com/Astar_Italia/status/1796980031954010538

Astar Townhall https://x.com/Astar_Italia/status/1799387288864276727

Band protocol on zKyoto https://x.com/Astar_Italia/status/1799390611763577194

Sota x Japan https://x.com/Astar_Italia/status/1799399060501307772

Astar x Blockchain for good https://x.com/Astar_Italia/status/1799408698739351927

Astar x Crossmint https://x.com/Astar_Italia/status/1799444520217825571

Astar x Youdle https://x.com/Astar_Italia/status/1799456348767137907

Astar japanese AMA https://x.com/Astar_Italia/status/1799836434939146388

Heal on TGE Catalyst Grant https://x.com/Astar_Italia/status/1799869960803516722

Walkmon x TNC Alpha https://x.com/Astar_Italia/status/1800179550925808113

Sonova introduction https://x.com/Astar_Italia/status/1800209647871431139

Walkmon x TokyoBeast https://x.com/Astar_Italia/status/1800211322694676719

Walkmon mint https://x.com/Astar_Italia/status/1800422718111883649

Sota on WebX Asia https://x.com/Astar_Italia/status/1801251018589581354

Astar x boarding bridge https://x.com/Astar_Italia/status/1801259935545610271

Astar Community Call https://x.com/Astar_Italia/status/1801279687336882260

Band Protocol on zKyoto part2  https://x.com/Astar_Italia/status/1801298487276884259

Astar x Youdle part2 https://x.com/Astar_Italia/status/1801574497956323422

Lucky dApp promo https://x.com/Astar_Italia/status/1801579534724030849

Burning proposal https://x.com/Astar_Italia/status/1801592040033067383

Voting Period https://x.com/Astar_Italia/status/1802328123368751340

VLS promo https://x.com/Astar_Italia/status/1802335162182557701

VLS promo2 https://x.com/Astar_Italia/status/1802340914200826023

HAHA promo https://x.com/Astar_Italia/status/1802358598422475056

Sky Labs promo https://x.com/Astar_Italia/status/1802368334962286630

Heal III promo https://x.com/Astar_Italia/status/1802711708210806999

Astar x Quickswap Twitter space https://x.com/Astar_Italia/status/1803689928640897091

Airdrop info https://x.com/Astar_Italia/status/1803708534384685435

Sota x PANews https://x.com/Astar_Italia/status/1804891040811221298

Astar x The Graph Demo Day https://x.com/Astar_Italia/status/1804897548072554967

Walkmon promo   https://x.com/Astar_Italia/status/1804899817048391909

Astar x Layer0 airdrop https://x.com/Astar_Italia/status/1804952565823701404

Astar tools https://x.com/Astar_Italia/status/1805191680628293825

Astar x Stake Stone https://x.com/Astar_Italia/status/1805202396378714589

Stake Stone tutorial https://x.com/Astar_Italia/status/1805284752293085192

Astar Evolution Twitter space https://x.com/Astar_Italia/status/1805864315632623724

Astar maintenance  https://x.com/Astar_Italia/status/1806259607150444679

Sonova Twitter space https://x.com/Astar_Italia/status/1806263518821281983

Trekki promo https://x.com/Astar_Italia/status/1806299910695739860

Walmon Mint promo https://x.com/Astar_Italia/status/1806303725255839821

Astar Evolution https://x.com/Astar_Italia/status/1806313495098474598

Yoki rewards https://x.com/Astar_Italia/status/1806785428420522403

----- CC - Medium -----
Astar Dynamic Staking
https://medium.com/@AstarItalia/dynamic-staking-linnovazione-di-astar-network-che-si-adatta-alle-condizioni-del-mercato-c3db905e0b87

Astar x Band Protocol 
https://medium.com/@AstarItalia/band-protocol-x-astar-zkyoto-linteroperabilit%C3%A0-zk-rollup-su-astar-zkevm-b573b4558a36

Astar Governance V1 
https://medium.com/@AstarItalia/astar-governance-v1-i-primi-passi-verso-la-decentralizzazione-3743f80cf73f

Yoki Rewards 
https://medium.com/@AstarItalia/premi-e-ricompense-della-campagna-di-yoki-origins-eadcce220013

**Comment by Gunit2481** [comment]
Good work Vasa! 🤌

**Comment by VasaKing** [comment]
どうもありがとうございます！ 🙇‍♂️
