### ISSUE TITLE
June 2024 Contribution - Dr CAO

### ISSUE THREAD

**Issue by ahjxcrz** [AstarNetwork/growth-program#2502]
June. 2024

Telegram Username:
@ahjxcrz

Discord Username:
DrCAO#1508

SDN Wallet Address:
akBsuDRUzk9hRxiLRdQTcFsgsHoa5PvWQuPVjrEK6zkLU3X

Contributions:
CM - Manage and support both Local and Main community chat. Being active in the Astar official discord like:
<img width="656" alt="Screen Shot 2024-07-03 at 3 09 35 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/3eb906cd-2bde-4a61-9566-05ef39199e28">
<img width="697" alt="Screen Shot 2024-07-03 at 3 09 57 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/9f1546f1-5857-4bc0-885d-a673d2a97a2e">

<img width="775" alt="Screen Shot 2024-07-03 at 3 10 25 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/6132a71c-dc4a-45ef-abab-38c84a3e8178">
<img width="616" alt="Screen Shot 2024-07-03 at 3 10 56 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/3f8ff4f7-e057-496c-935c-a41c97aec263">
<img width="602" alt="Screen Shot 2024-07-03 at 3 11 08 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/6dfc7f47-1e5c-463c-a4b9-4a00f45a7938">
<img width="682" alt="Screen Shot 2024-07-03 at 3 11 23 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/971b014f-ca7a-4236-b67c-e79e77208566">
<img width="680" alt="Screen Shot 2024-07-03 at 3 11 38 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/1fd97abd-3764-4202-a17d-77e4b5981243">

<img width="730" alt="Screen Shot 2024-07-03 at 3 12 09 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/95c69849-ba4f-411f-bf30-7747641118eb">
<img width="686" alt="Screen Shot 2024-07-03 at 3 13 11 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/0e7bd246-567e-498d-986b-db90ae9119b6">
<img width="639" alt="Screen Shot 2024-07-03 at 3 13 36 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/06f53210-42cd-42eb-8919-5af9dbc8a72c">

<img width="710" alt="Screen Shot 2024-07-03 at 3 13 51 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/c2ff42a3-13d2-46fe-a6da-5274f4169698">

**Gov participation:**
I have been voted for all the gov proposal, and also participated in discussions. For example, 

<img width="849" alt="Screen Shot 2024-07-03 at 3 17 00 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/8aaf9ccf-7ef1-46a0-a755-e7a95f8e24e4">

<img width="1127" alt="Screen Shot 2024-07-03 at 3 18 32 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/87b1652b-7dae-4948-9612-c56193ec6583">

<img width="1082" alt="Screen Shot 2024-07-03 at 3 18 51 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/009214b2-e044-4069-aef2-d5e9b4f7c5ba">

**VSM**

Tweet analytics:
Tweet impressions: 33K

<img width="1070" alt="Screen Shot 2024-07-03 at 3 19 46 PM" src="https://github.com/AstarNetwork/growth-program/assets/6592082/0fc4180e-ce63-4e53-a243-3f53eb6076c8">

Representative tweet and videos:
https://x.com/cao_lab/status/1808617383877300486
https://x.com/cao_lab/status/1807807699641589835
https://x.com/cao_lab/status/1807808056715289017
https://x.com/cao_lab/status/1806716357213561022
https://x.com/cao_lab/status/1805390580064891203
https://x.com/cao_lab/status/1803860787829837958
https://x.com/cao_lab/status/1803661434150130096
https://x.com/cao_lab/status/1803661120567386191
https://x.com/aiweb3dao/status/1802087356671168581
https://x.com/cao_lab/status/1801981190288879767
https://x.com/cao_lab/status/1801304803471200299
https://x.com/cao_lab/status/1801296986836242455
https://x.com/cao_lab/status/1799878400837882180
https://x.com/cao_lab/status/1798777428376166763
https://x.com/cao_lab/status/1798004261219131436
https://x.com/cao_lab/status/1798003725770059893
https://x.com/cao_lab/status/1797399520286003437
https://x.com/cao_lab/status/1797398998774677714

Twitter space and share about the Astar eco:
https://x.com/aiweb3dao/status/1798729198036754758    , with DeStore, 19.4K tuned in 

**CC:**

Chinese video:
https://www.youtube.com/watch?v=n2zqwtFGba8
https://www.youtube.com/watch?v=1NGTl5_6Mvk
https://www.youtube.com/watch?v=OYXMRXN17rM
https://www.youtube.com/watch?v=L4cRTzqys1s
https://www.youtube.com/watch?v=LUh9MFmliGY

Tutorial:
https://www.youtube.com/watch?v=gvgzjnTnYf8

BD and building:

Organized the big event in chinese community for the new Astar dApp staking: https://x.com/aiweb3dao/status/1802087356671168581 
 More than 100 ppl joined the event in discord. I will provide more than 300 Astar for the community and more importantly, encourage more ppl to join the new dApp staking! 

The discord dragon card game with Neurolanche dragon card. Right now, users can use the point to buy the Neurolanche card and also burn the card to get Astar tokens, double reward from May 5, so there might be more ppl participating, and each of them will get the notification about the whitelist inform, already sent few hundreds Astar tokens to the community and request the community to stake it on Neurolanche dApp.

**Comment by Gunit2481** [comment]
Good work! You can be more active on the forum to get more points in governance. 👍

**Comment by ahjxcrz** [comment]
Thank you! I thought I had participated in all governance voting, but sure,
I will try to be more active in the forum this month!
