### ISSUE TITLE
June 2024 Contribution - MSPY

### ISSUE THREAD

**Issue by thanhmycm** [AstarNetwork/growth-program#2503]
Telegram : MS-PY (Never PM you first)/ @ThanhCayMoney
Discord : lethanhmy
SDN/ASTR Address : ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

CM :
Telegram Vietnamese : https://t.me/PlasmOfficialVietnam - https://t.me/astarshidenvietnam
![Screenshot 2024-07-05 144245](https://github.com/AstarNetwork/growth-program/assets/89438593/e01d00ed-99a7-4b1b-af86-aae38c3d8caf)
![Screenshot 2024-07-05 144307](https://github.com/AstarNetwork/growth-program/assets/89438593/1733f300-0287-403b-8b74-2d22c0a9f999)

Discord Support :

![Screenshot 2024-07-05 144410](https://github.com/AstarNetwork/growth-program/assets/89438593/0dcb5a76-9c24-45b7-bf30-07db56e90f7a)
![Screenshot 2024-07-05 144425](https://github.com/AstarNetwork/growth-program/assets/89438593/1d9cd591-c218-48e7-a9a5-448dbec9d273)
![Screenshot 2024-07-05 144432](https://github.com/AstarNetwork/growth-program/assets/89438593/9c025ff0-dd1b-41e5-b7c4-a1afd2fbe0e9)
![Screenshot 2024-07-05 144446](https://github.com/AstarNetwork/growth-program/assets/89438593/7ee92f25-39b1-4da4-a43e-aa1ed91a8932)
![Screenshot 2024-07-05 144455](https://github.com/AstarNetwork/growth-program/assets/89438593/a780158a-6151-4cb8-9c5b-55657f382d0d)
![Screenshot 2024-07-05 144507](https://github.com/AstarNetwork/growth-program/assets/89438593/8f662c9c-526e-49b9-838e-9599c4234e1a)
![Screenshot 2024-07-05 144523](https://github.com/AstarNetwork/growth-program/assets/89438593/38712890-e630-468f-bbc5-b88cbd0de44f)

SM : https://twitter.com/ThanhMy67 | https://twitter.com/AstarNetworkVN is waiting to open the suspension

1. https://x.com/ThanhMy67/status/1797513418335023348
2. https://x.com/ThanhMy67/status/1798245105348047311
3. https://x.com/ThanhMy67/status/1798600432174129310
4. https://x.com/ThanhMy67/status/1801545849346097393
5. https://x.com/ThanhMy67/status/1802232294683648159
6. https://x.com/ThanhMy67/status/1803318446111052112
7. https://x.com/ThanhMy67/status/1803672198462447765
8. https://x.com/ThanhMy67/status/1805858436628070757
![Screenshot 2024-07-05 144952](https://github.com/AstarNetwork/growth-program/assets/89438593/d0f60109-28e3-4795-a420-4001411f475e)
![Screenshot 2024-07-05 145007](https://github.com/AstarNetwork/growth-program/assets/89438593/ebc9adf9-2407-468f-bbec-f2675e5c222f)
![Screenshot 2024-07-05 145015](https://github.com/AstarNetwork/growth-program/assets/89438593/a72bb1fb-ce1c-42be-8cbe-a817dd9acbae)
![Screenshot 2024-07-05 145023](https://github.com/AstarNetwork/growth-program/assets/89438593/05a8cadb-7ddf-4fcb-8a50-333f06ce8d01)
![Screenshot 2024-07-05 145038](https://github.com/AstarNetwork/growth-program/assets/89438593/5a784b8f-76b9-47fe-ae8c-792d27162de3)
![Screenshot 2024-07-05 145047](https://github.com/AstarNetwork/growth-program/assets/89438593/76572f2e-212b-4644-adb5-c8a620a5f2ae)
![Screenshot 2024-07-05 145132](https://github.com/AstarNetwork/growth-program/assets/89438593/8d8e2d53-56e2-424d-a2af-396816e48410)

**Comment by Gunit2481** [comment]
Thanks for your support MSPY! 💪
