### ISSUE TITLE
June 2024 Contribution - Technical Ambassador: Takeshi

### ISSUE THREAD

**Issue by tksarah** [AstarNetwork/growth-program#2504]
Telegram Username: @tksarah0822
Discord Username: tksarah#tksarah
X(Twitter) Username: @tsarah0822 ( TKLab | tklab.astr )
Astar Wallet Address: aZkj2EgiZkUbnKk6XMp9pf9f9SALXSAaTgz17ZEYUaq2UZy

# Core Tasks (Mandatory)
## 1. DEVELOPER SUPPORT
I advised to build the astar node and helped community members asking dev questions on discord (**builder** and **peers-program**).

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/2d93483f-c2c0-43df-b2f0-011aec567529)

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/a8d2c7a5-7be5-45a0-b9c8-7be6729bba0d)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/9ed8b7c5-0c56-4a7c-803a-ac79a2ede248)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/38ada050-2d3d-4e62-b7da-4e17eb117ba1)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/0e467bda-74d6-4048-9da4-aeaf4fb2df73)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/1b1c6550-d73f-4637-af5a-d88bd42b5e1f)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/d06d98ac-0232-477d-b517-7e8d60b5a298)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/1b84f56b-48eb-4787-9c73-6791df344090)

## 2. GOVERNANCE & PROJECT ENGAGEMENT
_https://forum.astar.network/u/tksarah/activity_

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/3188b5cf-82bf-4959-997b-808ccab89ce1)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/a4ab7773-e174-4b6f-a0a5-cf2b00bbbec9)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/9a285747-56d9-4b48-aa6a-a9eb2f24fdb6)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/da4474c2-5304-46e0-9160-28dcc2b9d59b)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b204de3f-35b3-4cc8-973e-dec3ce58b60e)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/5cbb96b6-0cb2-42f7-a9cb-5a285c8e0c51)

# Optional Tasks (Choose up to 2 tasks/month)

### [1] Articles

※The cover illustration for the article was created using **Copilot Designer** and **PowerPoint**.

Title: **dApp Staking v3 First Period Ends**
Published in Note June 14, 2024
https://medium.com/the-astar-bulletin-tab/dapp-staking-v3-first-period-ends-8ec50e61b85b
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/2a5c8dc3-74b6-49ec-a7a3-30e348d38197)

Title: **dApp Staking v3 最初の Period 終了**
Published in Note June 14, 2024
https://note.com/tksarahweb3/n/n5364423c1005
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/d94bf719-b4a4-491e-a376-eccb7e1dad23)

## 4. BUILD

The technologies and elements I am using are as follows:

* Repository: https://github.com/tksarah/bc
* Languages: Perl, Shell, JavaScript, HTML, R
* Data: on-chain

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/1d51ce69-8d3c-4d12-8145-5d56524c1257)

### === June Update ===

I have added features and provided regular reports, especially during the Voting Subperiod, for the purpose of facilitating promotional activities for the project and as a reference for stakers when they stake.

### Integrated UI

The main UI feature additions:
* For **Staking Amount by dApp Staker**, I have enabled the export of results in CSV format.
* I have simplified the information in **dApp Ranking During Build&Earn Subperiod**.
* **dApp Ranking During Voting Subperiod** has been newly created. Since there was a second Voting Subperiod in June, I used this to report regularly on a daily basis throughout the period.

[Related Forum](https://forum.astar.network/t/summary-data-information-for-dapp-staking-projects/7010)

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/b5165c91-3571-485b-95b7-764f0843b473)

https://agent.sun-t-sarah.work

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/5f12c291-5b8a-4a97-ac04-f18c4620d81a)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/691cbeb2-e299-40a7-ba87-6a7f91bd5162)
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/eda88ccc-acd3-4d3c-a3a2-b2abb4de7964)

### CM: Community Management
I have established a Facebook group called ‘Astar Network Japan Community.’ The goal is to spread awareness of the Astar Network among Japanese enterprises. Many serious and veteran businesspeople in Japan, especially those in IT-related companies, tend to use Facebook, where the network is quite extensive. Since I am connected with numerous industry professionals through my ‘Friends,’ I launched this group as an entry point and have started to manage it, initiating the spread of Astar. The Japan Team is also aware of this. Primarily, I repost official announcements related to the Astar Network/Startale.

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/dea1c5ad-97a8-45ab-b91b-aa7010a10c10)

![image](https://github.com/AstarNetwork/growth-program/assets/11060137/94eaa37d-3c52-4ec5-a6df-f6b395d3f127)

### X Analytics
![image](https://github.com/AstarNetwork/growth-program/assets/11060137/9e208916-005b-4158-a1b4-f486a9ee3186)

**Comment by Gunit2481** [comment]
Great work Takeshi-san! 💪
