### ISSUE TITLE
June 2024 Contribution - Leo

### ISSUE THREAD

**Issue by LeoNeurolanche** [AstarNetwork/growth-program#2505]
Hello, I'm Leo. In May, as the Astar Network Turkey team, we were involved in many activities.
First, I will share the content I created from my own account with you. Let's take a look together.
Personal Twitter: https://twitter.com/neurolauncher?s=21&t=ISh07fvjMqpmUg40w5HqBg  Discord: neurolauncher.  Astar Network Turkey Telegram: https://t.me/AstarTurkiye  Personal medium: https://medium.com/@enesfaruksahin?source=linkShare-7dc743decc41-1683244333  Wallet: bc2Stpr8BUfbxcpb9VCLiYUfduNQM5jbg7vJPUukZbEBxU4
My personal Twitter montly views: 185k view

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/974604e4-7eaf-4481-b149-e6ef052d07e4)

**Cm: Community Support**
This month, in addition to actively providing support to the Turkish communityx In addition, I became the active person in the community.

We get new 74 member

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/42ac4dc5-0ca5-449b-af57-d8cd13664f8f)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/86c30842-9b09-48ea-b8f8-a924cfedf6a1)

**GOV - Governance & Project Engagement**

Gov- https://forum.astar.network/u/leo/activity
I participated in all active forum activities in governance this month. Additionally, I made efforts for the Astar ecosystem to be more decentralized. And I am voting each governance townhall with 3 Million astr. 

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/73397888-f2f9-4357-8687-694b6ad6a716)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/03bf09e0-0425-4d83-be21-8cd3695b0546)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/cf8abad9-e550-4cc0-ac51-53d08e2d8efa)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/cb1d2971-9756-49c2-95e2-85a8422c6d8c)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/aa0ef021-656d-4387-b7c8-cd0a67569c98)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/80e87072-cb52-4506-a889-ab0f2efed7fd)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/3d352356-5fd7-4543-9b68-5545f2dda6bd)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/55c5f5de-f35f-4ed1-8009-6a6a320ab371)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/8e4d9154-f8d2-499a-b32e-08a3ac1f8e70)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/c11c318e-7f72-4e79-8821-317493d43d79)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/795fc9d6-acde-4cad-b0f8-56ed7e6d6c59)

**SM - SOCIAL MEDIA ENGAGEMENT**

I will share my social media activities on my personal account:

----

Tweet 1: As a long-time blockchain researcher and developer, I will share my thoughts with you on the paths Astar Network should follow to become a successful web3 project. 

Link; https://x.com/neurolauncher/status/1797692031810121946?s=46

(17,440 view, 140 like, 55 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/154d86a0-5085-4608-8c2f-9e386fcb3673)

----

Tweet 2: The biggest burn: $38 million of $ASTR

Astar Network, which collaborates with major companies like Sony, has put up for vote the burning of $38 million worth of ASTR supply.

Let's take a look at the details of this burning news together.

Link: https://x.com/neurolauncher/status/1798686548998709694?s=46

(8514 view, 163 like, 56 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/36e71f29-cd0d-4550-bbeb-bdf3396e535d)

----

Tweet 3: Building to Earn: dApp Staking Season 2

Today, we will discuss how to participate dApp staking, which is the most important structure of Astar Network

We will cover many topics together:

- How you will earn bonus.
- How can you stake $ASTR

Link: https://x.com/neurolauncher/status/1800438293533720578?s=46

(10,160 view, 84 like, 46 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/aeab1c53-b2fb-47c4-9897-220aba051448)

----

Tweet 4: GM @AstarNetwork family:

🌐 Decentralization of the governance model,
🔗 Hybrid network support with Astar ZkEvm, WASM and EVM,
💪 Supporting developers with dApp staking,
🤝 Strong connections with major companies through StartaleHQ!

Link: https://x.com/neurolauncher/status/1803028873669456382?s=46

(3588 view, 73 like, 20 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/a3e0c6ad-f303-419a-be22-a78644f9b45b)

---

Tweet 5: ⚒️ The Development of the Polkadot ~ Innovation - Astar Network

Link: https://x.com/neurolauncher/status/1805286390009065882?s=46

(7713 view, 139 like, 44 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/a88c305a-fc96-4013-a0fd-ef2057d57f3d)

---

Tweet 6: Astar and Web3 evolution: Startale

Adaptation of web2 companies in the blockchain world is critical factor:

- AstarNetwork is preparing for a revolutionary period by reaching major companies like Sony

⚙️Astar provides significant infrastructure with WASM, EVM and ZkEvm.

Link: https://x.com/neurolauncher/status/1805922549265555627?s=46

(3360 view, 82 like, 24 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/72a99c6f-294b-4e6a-97f7-86696420b763)

---

Tweet 7: 🪂 $630,000 AirDrop: 9 Million $ASTR

- A significant AirDrop is coming for users who participated in the Yoki during the Astar Network ZkEvm campaign.

Link: https://x.com/neurolauncher/status/1807422553184489504?s=46

(7607 view, 125 like, 39 rt)

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/c7dd64c4-b63f-4625-805a-231c1ab90100)

----

**CC- CONTENT CREATION**

YouTube video: question from community

https://youtu.be/s0rPpqr4jFs?si=sf33bfa0l6_AkYm5

![image](https://github.com/AstarNetwork/growth-program/assets/126774982/6c76d050-ae05-4b09-94ca-23570f276410)

Article 1: Astar Evolution:

https://medium.com/@enesfaruksahin/astar-and-web3-evolution-startale-8bb1ef873d89

Article 2: Astar Network ZkEvm

https://medium.com/@enesfaruksahin/astar-network-zkevm-with-millions-of-web3-users-571324e867fb

**Comment by Gunit2481** [comment]
Good work, thanks Leo!
