### ISSUE TITLE
JUNE 2024 Contribution - Emre(Mr.Karahanlı)

### ISSUE THREAD

**Issue by siyaksares** [AstarNetwork/growth-program#2506]
Twitter: https://twitter.com/mr_karahanl
Telegram Username: @Emret16
Discord Username: mr.karahanli_emre_
Medium: https://medium.com/@emretanis4
ASTAR Native Wallet Address: ZkXuTVXB4s6sPgf42gviV2GcTHkvXks72sbVB7rqevzr2xu

Astar Network Turkey Twitter: https://twitter.com/astarnetworktr_?s=21&t=ISh07fvjMqpmUg40w5HqBg
Astar Network Turkey Telegram: [https://t.me/AstarTurkiye  Personal](https://t.me/AstarTurkiye%E2%80%A8%E2%80%A8Personal)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/2674006a-6e43-4dfc-a981-722f582c2a41)

CM: COMMUNITY SUPPORT

I have been the top contributor for months. I was also ranked https://github.com/AstarNetwork/growth-program/pull/1 on CM and was the top contributor to our community on telegrams.

I was the most active person in the Discord TR group.

For TG:

As you can see from this, I am the most active member of the community.
We get new 74 member
I sent 122 messages and I have 22% of all conversations. There are also dozens of minutes of voice responses.

![image](https://github.com/AstarNetwork/growth-program/assets/78142371/75bf3a45-3fb9-4043-bced-725bc0dcde02)

For Discord:
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/b8634666-2a4a-4a52-9424-84599945f285)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/d31b6b85-ec98-4868-9f97-6e9e4dff1433)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/cd13cc6e-ef50-48a7-86c6-47aedffff089)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/b00b92f4-ba84-4aa6-8fff-2f9975e956c6)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/f0b18633-9f8a-4470-a51a-91025a9784bb)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/22f99b11-2a7e-4353-92b2-7386c498e8ac)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/b2db3ab9-e2e2-4907-b435-ee0d64aa27a6)

GOV - Governance and Project Engagement

Gov-https://forum.astar.network/u/mrkarahanli-emre/activity
I started a discussion for an event budget and answered people's questions. I also participated in other active forum discussions

![image](https://github.com/AstarNetwork/growth-program/assets/78142371/22131f63-bcc7-4efb-8801-436f30cca28b)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/bbf41d08-7894-43f2-8beb-b988550bb8f6)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/ee6a086e-5143-4dbf-b365-8306e52e96af)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/f1a44a68-c438-4a81-9f56-04b32a5bc1cb)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/0007674d-3f6e-40b6-9e23-879d2d8e2687)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/db304d89-3468-4245-ab88-36c105399d71)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/546371b3-dc73-4fe0-a865-fc77f3431e68)

GOV-2-AstarTownHall
I participated in the voting with my active Substrate and EVM/zkEVM wallets.
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/bc7930fd-9d88-4e33-a5f9-2ebf1b298cd5)
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/a597a05f-8845-4461-ac91-be8fd7115e06)

SM:

https://twitter.com/mr_karahanl/status/1803571409551065370
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/acaa546c-2749-4fd5-9699-af78ffe69847)

https://twitter.com/mr_karahanl/status/1805697587179405761
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/03db26f0-8e0a-47b6-8692-a87b355b2ff0)

https://twitter.com/mr_karahanl/status/1806737830216950034
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/71c8e02f-2860-4121-99e0-ba426c921c33)

https://twitter.com/mr_karahanl/status/1804512915719966894
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/89f1f849-b052-4d94-b603-50d843d22390)

https://twitter.com/mr_karahanl/status/1802100793081786400
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/de8c6101-4577-4143-8030-569028d4436f)

https://twitter.com/mr_karahanl/status/1801964667494896104
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/35d2f3e6-c7b7-41c8-8334-2c38ca83087d)

https://twitter.com/mr_karahanl/status/1801226527289291185
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/1229a804-dea5-4905-8c45-f9c8d41d9de9)

https://twitter.com/mr_karahanl/status/1807365605982433634
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/22054b5f-586f-479a-ae0a-9013f942fc04)

https://twitter.com/mr_karahanl/status/1806305764304212169
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/b1b16407-4755-455f-a8f2-33c17093b7ee)

https://twitter.com/mr_karahanl/status/1797960597948231688
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/f76e8a8e-acdc-40e9-a5e0-f4138b3098be)

https://twitter.com/mr_karahanl/status/1806030114347512222
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/7cc40d7f-a11d-418f-ad81-7d0f651c7cf8)

https://twitter.com/mr_karahanl/status/1799769831840874558
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/30a1aea7-bcd7-448a-b383-de57da44381a)

https://twitter.com/mr_karahanl/status/1797579461950353830
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/b1c7a6e4-f1b2-4450-b3dc-ccd242eba287)

CC:

dAppStaking-Sezon2-Voting Period VIDEO:

(9 Minute-1280 VIEW)

https://twitter.com/mr_karahanl/status/1805697587179405761
![image](https://github.com/AstarNetwork/growth-program/assets/78142371/e0f5d4d4-f8be-4e2f-a81b-79ec98dcdc3b)

Youtube Video:

(16 minute-23 view)

https://www.youtube.com/watch?v=s0rPpqr4jFs

**Comment by Gunit2481** [comment]
Good work, thank you!
