### ISSUE TITLE
June 2024 Contribution - Matt

### ISSUE THREAD

**Issue by Matt3Web** [AstarNetwork/growth-program#2507]
# **June 2024 Contribution - Matt**

Telegram Username: @Matt_Web3
Discord Username: mattweb5go
Twitter Username: @Matt_Web3_
Medium Username: @matt_web3
ASTAR Native Wallet Address: YMFxavc4wzMncNBKr6NkuPwNkp2C78hYhX6kkF7BD4jrhp2

# CM - Community Management
**Astar Network CZ/SK Telegram**: https://t.me/AstarNetwork_CS
**Combot link -** https://combot.org/c/-1001943903354/a

![Snímek obrazovky (1092)](https://github.com/AstarNetwork/growth-program/assets/104125423/332c07bc-74ff-426d-b98e-873f0caf2cd7)
![Snímek obrazovky (1093)](https://github.com/AstarNetwork/growth-program/assets/104125423/a0f42ec0-29dd-452d-add9-55a021898eaa)

**Astar Network Official Discord:** https://discord.gg/zARxg4ZR
Responding on daily basis in general channel, guide people to tutorials or directly by myself. Also deleting and banning inappropriate content and spam!

# GOV - Governance & Project Engagement
**Astar Forum Engagement:**
**My profile:** https://forum.astar.network/u/matt/activity

![Snímek obrazovky (1099)](https://github.com/AstarNetwork/growth-program/assets/104125423/4e6b7c8e-57ef-4577-ace7-e994055b6c9e)
![Snímek obrazovky (1098)](https://github.com/AstarNetwork/growth-program/assets/104125423/3b1f8c1c-13d8-430c-938b-f7954a6df32e)
![Snímek obrazovky (1097)](https://github.com/AstarNetwork/growth-program/assets/104125423/4b2626ef-549e-491e-ad09-21dad058f95c)
![Snímek obrazovky (1096)](https://github.com/AstarNetwork/growth-program/assets/104125423/6834864a-4ce2-4b7e-8257-2a5b29a8b561)
![Snímek obrazovky (1095)](https://github.com/AstarNetwork/growth-program/assets/104125423/fbba015f-34c2-40ee-a798-790dc9dddfdb)
![Snímek obrazovky (1094)](https://github.com/AstarNetwork/growth-program/assets/104125423/512d2f7e-fc10-48e7-912f-2b52d15897ba)

**Discord Unstoppable Grant discussion:**
Participating in Governance and Projects discussion when new project appear. Raise questions, support or refuse their proposals. Here is my Discord Username: mattweb5go

# SM - Social Media Engagement
**Astar Network CZ/SK Twitter:** https://twitter.com/AstarNetwork_CS
Sorry no analytics for this account G!

1) RT C14 proposal: https://x.com/c14_wtf/status/1797558640892662051
2) Astar x Crossmint: https://x.com/AstarNetwork_CS/status/1797567454723412042
3) Astar burning proposal: https://x.com/AstarNetwork_CS/status/1798268954382647713
4) Astar Dev Updates: https://x.com/AstarNetwork_CS/status/1799002005266219014
5) Youdles Mint RT: https://x.com/YoudleDAO/status/1798047770206749116'
6) First Townhall vote: https://x.com/AstarNetwork_CS/status/1800124987560628462
7) QRT Band Protocol: https://x.com/AstarNetwork_CS/status/1800473258015535510
8) Summary of burn proposal: https://x.com/AstarNetwork/status/1800132089033199755
9) Astar Community call: https://x.com/AstarNetwork_CS/status/1800841560684400918
10) 3days left till new voting period starts + ledger security: https://x.com/AstarNetwork_CS/status/1801157053940957263
11) Burn-ing summer: https://x.com/AstarNetwork_CS/status/1801540295231701157
12) New voting period: https://x.com/AstarNetwork_CS/status/1802631371103346969
13) 1 left of burn proposal discussion: https://x.com/AstarNetwork_CS/status/1803016977566363885
14) Getnoisier: https://x.com/AstarNetwork_CS/status/1803371361743646886
15) TAB article Astar go v1 RT: https://x.com/AstarBulletin/status/1804069245229125950
16) Astar Netwrok x Startale merging: https://x.com/AstarNetwork_CS/status/1805324131077849095
17) Burn proposal active in townhall: https://x.com/AstarNetwork_CS/status/1805873576186196383
18) Sequence demoday: https://x.com/AstarNetwork_CS/status/1808112999745380601

#

**Personal Twitter:** https://twitter.com/Matt_Web3_
Trying to promote major things especially Astar Network's announcements and forum proposals on daily basis!

![Snímek obrazovky (1091)](https://github.com/AstarNetwork/growth-program/assets/104125423/9f8c56f7-bd28-4cfa-b72f-43bc36d91788)
![Snímek obrazovky (1100)](https://github.com/AstarNetwork/growth-program/assets/104125423/ca87a34f-5856-4676-a6a0-cd6f936602e7)
![Snímek obrazovky (1101)](https://github.com/AstarNetwork/growth-program/assets/104125423/d9413c8c-d6e7-40c2-bc68-fa370f37ced0)
![Snímek obrazovky (1102)](https://github.com/AstarNetwork/growth-program/assets/104125423/1c62c492-d3db-4a5f-b9a8-f65b8d7fa276)
![Snímek obrazovky (1103)](https://github.com/AstarNetwork/growth-program/assets/104125423/ee0241aa-fa8d-41cf-8a44-6a358005812a)

#

**AstarChan:** https://twitter.com/Astar_Chan_

# CC - Content Creation

**1) Astar Foundation Plans to Ignite Tokenomics with Major Burn Proposal in TAB:** 
https://medium.com/the-astar-bulletin-tab/astar-foundation-plans-to-ignite-tokenomics-with-major-burn-proposal-cd47e67bb687

**2) Astar Governance V1: Decentralizing the Future of Astar in TAB:** 
https://medium.com/the-astar-bulletin-tab/astar-governance-v1-decentralizing-the-future-of-astar-d20cdd2ca661

**3) Dynamic Staking: Inovace Astaru, který se přizpůsobuje tržním podmínkám! Astar article translation to Czech:**
https://medium.com/the-astar-bulletin-tab/dynamic-staking-inovace-astaru-kter%C3%BD-se-p%C5%99izp%C5%AFsobuje-tr%C5%BEn%C3%ADm-podm%C3%ADnk%C3%A1m-466c06e75f85

**4) Astar Evolution: Druhá fáze strategie se Startale! Astar article translation to Czech:**
https://medium.com/the-astar-bulletin-tab/astar-evolution-druh%C3%A1-f%C3%A1ze-strategie-se-startale-4e9cc940b491

That's all for my June contributions, thank you very much!

**Comment by Gunit2481** [comment]
Good work Matt 👏
