### ISSUE TITLE
creating memes for shiden exchange and social engagement

### ISSUE THREAD

**Issue by pawan900000** [AstarNetwork/growth-program#597]
telegram - @onlineearninking 
discord - pawan#4571
twitter - https://twitter.com/Airdrop39561881
wallet - ZZnfK94ZUJBvBWpJDLjCnFHakCBwHqULmhAMDk9kB2C26f4

meme post link - https://twitter.com/Airdrop39561881/status/1447987916555182080?s=20
activity share - https://twitter.com/Airdrop39561881/status/1447626785080758276?s=20

**Comment by fiexer** [comment]
Memes made after October 11 arent accepted.
